import { RED, RED_DARK, GOLD, redAlpha, goldAlpha } from "@/lib/tokens";

const commentsStyles = {
  commentsModal: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1000,
    display: "flex",
    alignItems: "flex-end",
  },
  commentsOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: "rgba(0,0,0,0.62)",
    backdropFilter: "blur(4px)",
    WebkitBackdropFilter: "blur(4px)",
  },
  commentsContent: {
    background: "linear-gradient(180deg, #0f0f0f 0%, #0a0a0a 100%)",
    borderRadius: "22px 22px 0 0",
    width: "100%",
    maxHeight: "78vh",
    display: "flex",
    flexDirection: "column",
    position: "relative",
    zIndex: 1001,
    borderTop: "1px solid rgba(255,255,255,0.07)",
    boxShadow: "0 -24px 70px rgba(0,0,0,0.65)",
  },
  commentsHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    background: "rgba(255,255,255,0.18)",
    alignSelf: "center",
    margin: "10px auto 0",
    flexShrink: 0,
  },
  commentsHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: 14,
    paddingBottom: 14,
    paddingLeft: 20,
    paddingRight: 20,
    borderBottom: "1px solid rgba(255,255,255,0.055)",
  },
  commentsTitle: {
    color: "rgba(255,255,255,0.85)",
    fontSize: 14,
    fontWeight: 800,
    margin: 0,
    letterSpacing: 0.3,
    textTransform: "uppercase",
  },
  commentsClose: {
    background: "rgba(255,255,255,0.07)",
    border: "1px solid rgba(255,255,255,0.1)",
    borderRadius: "50%",
    width: 30,
    height: 30,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "rgba(255,255,255,0.65)",
    cursor: "pointer",
    padding: 0,
  },
  commentsList: {
    flex: 1,
    overflowY: "auto",
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 20,
    paddingRight: 20,
    maxHeight: "min(460px, 54vh)",
  },
  noComments: {
    textAlign: "center",
    color: "#AAAAAA",
    paddingTop: 40,
    paddingBottom: 40,
    paddingLeft: 20,
    paddingRight: 20,
    fontSize: 14,
    lineHeight: 1.5,
  },
  commentItem: {
    display: "flex",
    gap: 12,
    paddingTop: 16,
    paddingBottom: 16,
    paddingLeft: 0,
    paddingRight: 0,
    borderBottom: "1px solid rgba(255,255,255,0.07)",
  },
  commentAvatar: {
    width: 38,
    height: 38,
    borderRadius: "50%",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: `${goldAlpha(0.32)}`,
    background: "linear-gradient(145deg, #FF3B30, ${RED_DARK})",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "var(--text-primary)",
    fontSize: 14,
    fontWeight: 950,
    flexShrink: 0,
    overflow: "hidden",
    cursor: "pointer",
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
  },
  commentAvatarImage: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    display: "block",
  },
  commentContent: {
    flex: 1,
  },
  commentUsername: {
    border: "none",
    background: "transparent",
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    color: "var(--text-primary)",
    fontSize: 14,
    fontWeight: 900,
    marginBottom: 4,
    cursor: "pointer",
    textAlign: "left",
  },
  commentText: {
    color: "#ccc",
    fontSize: 14,
    lineHeight: 1.4,
  },
  replyItem: {
    display: "flex",
    gap: 10,
    paddingTop: 8,
    paddingBottom: 8,
    paddingLeft: 16,
    paddingRight: 0,
    borderLeft: `2px solid ${goldAlpha(0.18)}`,
    marginLeft: 12,
  },
  replyAvatar: {
    width: 28,
    height: 28,
    borderRadius: "50%",
    border: "1px solid rgba(255,255,255,0.15)",
    background: "rgba(255,255,255,0.08)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#fff",
    fontSize: 11,
    fontWeight: 900,
    flexShrink: 0,
    overflow: "hidden",
    cursor: "pointer",
    padding: 0,
  },
  replyBtn: {
    marginTop: 4,
    background: "none",
    border: "none",
    color: "rgba(255,255,255,0.45)",
    fontSize: 11,
    fontWeight: 700,
    cursor: "pointer",
    padding: 0,
  },
  repliesSection: {
    marginLeft: 50,
    marginBottom: 4,
  },
  toggleReplies: {
    background: "none",
    border: "none",
    color: GOLD,
    fontSize: 11,
    fontWeight: 700,
    cursor: "pointer",
    padding: "4px 0 8px",
    display: "block",
  },
  commentInput: {
    display: "flex",
    flexDirection: "column",
    paddingTop: 12,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    borderTop: `1px solid ${goldAlpha(0.16)}`,
    gap: 8,
  },
  commentInputRow: {
    display: "flex",
    gap: 10,
    alignItems: "center",
  },
  replyPill: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "5px 10px",
    borderRadius: 999,
    background: `${goldAlpha(0.1)}`,
    border: `1px solid ${goldAlpha(0.25)}`,
    alignSelf: "flex-start",
  },
  replyPillText: {
    fontSize: 12,
    color: GOLD,
    fontWeight: 700,
  },
  replyPillClose: {
    background: "none",
    border: "none",
    color: GOLD,
    fontSize: 11,
    cursor: "pointer",
    padding: 0,
    lineHeight: 1,
  },
  commentInputField: {
    flex: 1,
    paddingTop: 11,
    paddingBottom: 11,
    paddingLeft: 14,
    paddingRight: 14,
    borderRadius: 999,
    border: "1px solid rgba(255,255,255,0.09)",
    background: "rgba(255,255,255,0.06)",
    color: "var(--text-primary)",
    fontSize: 14,
    outline: "none",
  },
  commentSendBtn: {
    paddingTop: 11,
    paddingBottom: 11,
    paddingLeft: 18,
    paddingRight: 18,
    borderRadius: 999,
    border: "none",
    background: `linear-gradient(145deg, ${RED}, ${RED_DARK})`,
    color: "#fff",
    fontSize: 13,
    fontWeight: 800,
    cursor: "pointer",
    boxShadow: `0 4px 14px ${redAlpha(0.35)}, inset 0 1px 0 rgba(255,255,255,0.1)`,
  },
  commentSendBtnDisabled: {
    background: "#333",
    cursor: "not-allowed",
  },

};

export default commentsStyles;
