import { RED, GOLD, PURPLE, BORDER, BORDER_2, RADIUS, MOTION, redAlpha, goldAlpha, whiteAlpha, blackAlpha } from "@/lib/tokens";

const feedbackStyles = {
  // ── feedbackSheetStyles ──────────────────────────────────────────────────
  feedbackModal: {
    position: "fixed",
    inset: 0,
    zIndex: 1200,
    display: "flex",
    alignItems: "flex-end",
  },
  feedbackOverlay: {
    position: "absolute",
    inset: 0,
    background: blackAlpha(0.62),
    backdropFilter: "blur(4px)",
    WebkitBackdropFilter: "blur(4px)",
  },
  feedbackSheet: {
    position: "relative",
    zIndex: 1201,
    width: "100%",
    maxHeight: "76vh",
    overflow: "hidden",
    borderRadius: "26px 26px 0 0",
    borderTop: `1px solid ${BORDER_2}`,
    background: `linear-gradient(145deg, ${redAlpha(0.14)}, rgba(11,11,11,0.98) 36%, ${goldAlpha(0.07)})`,
    boxShadow: `0 -24px 80px ${blackAlpha(0.58)}`,
    color: "#fff",
  },
  feedbackHandle: {
    width: 42,
    height: 4,
    borderRadius: RADIUS.full,
    background: whiteAlpha(0.24),
    margin: "10px auto 2px",
  },
  feedbackHeader: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 16,
    paddingTop: 18,
    paddingRight: 20,
    paddingBottom: 14,
    paddingLeft: 20,
    borderBottom: `1px solid ${BORDER}`,
  },
  feedbackKicker: {
    margin: 0,
    color: GOLD,
    fontSize: 11,
    fontWeight: 900,
    letterSpacing: 3,
    textTransform: "uppercase",
    fontFamily: "var(--font-condensed)",
  },
  feedbackTitle: {
    margin: "5px 0 0",
    color: "#fff",
    fontSize: 24,
    lineHeight: 1,
    fontWeight: 1000,
    letterSpacing: 0,
  },
  feedbackSubtitle: {
    margin: "8px 0 0",
    color: whiteAlpha(0.55),
    fontSize: 13,
    fontWeight: 750,
  },
  feedbackClose: {
    width: 34,
    height: 34,
    borderRadius: "50%",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: BORDER_2,
    background: whiteAlpha(0.08),
    color: "#fff",
    fontSize: 18,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    lineHeight: 1,
  },
  feedbackBody: {
    maxHeight: "calc(76vh - 112px)",
    overflowY: "auto",
    paddingTop: 18,
    paddingRight: 20,
    paddingBottom: "calc(24px + env(safe-area-inset-bottom))",
    paddingLeft: 20,
  },
  feedbackLoading: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    color: whiteAlpha(0.55),
    fontSize: 14,
    fontWeight: 750,
  },
  feedbackSpinner: {
    width: 22,
    height: 22,
    borderRadius: "50%",
    borderTop: `2px solid ${RED}`,
    borderRight: `2px solid ${whiteAlpha(0.18)}`,
    borderBottom: `2px solid ${whiteAlpha(0.18)}`,
    borderLeft: `2px solid ${whiteAlpha(0.18)}`,
    animation: "spin 1s linear infinite",
  },
  feedbackError: {
    color: "#F87171",
    background: redAlpha(0.12),
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: redAlpha(0.26),
    borderRadius: RADIUS.sm,
    paddingTop: 14,
    paddingBottom: 14,
    paddingLeft: 14,
    paddingRight: 14,
    fontSize: 14,
    lineHeight: 1.5,
  },
  feedbackSaved: {
    marginBottom: 14,
    color: GOLD,
    background: goldAlpha(0.1),
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: goldAlpha(0.22),
    borderRadius: RADIUS.sm,
    paddingTop: 11,
    paddingBottom: 11,
    paddingLeft: 13,
    paddingRight: 13,
    fontSize: 13,
    fontWeight: 900,
  },
  feedbackResult: {
    margin: 0,
    whiteSpace: "pre-wrap",
    color: "#fff",
    fontFamily: "inherit",
    fontSize: 14,
    lineHeight: 1.62,
  },

  // ── feedbackXpStyles ─────────────────────────────────────────────────────
  xpCard: {
    marginBottom: 16,
    padding: "14px 15px",
    borderRadius: RADIUS.md,
    background: goldAlpha(0.07),
    border: `1px solid ${goldAlpha(0.2)}`,
    animation: "fadeUp 280ms ease forwards",
  },
  xpCardTitle: {
    margin: "0 0 10px",
    fontSize: 9,
    fontWeight: 900,
    color: GOLD,
    letterSpacing: 2.5,
    textTransform: "uppercase",
  },
  xpCardRows: {
    display: "grid",
    gap: 5,
    marginBottom: 12,
  },
  xpCardRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  xpCardRowTotal: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    borderTop: `1px solid ${BORDER}`,
    marginTop: 5,
    paddingTop: 7,
  },
  xpCardLabel: {
    fontSize: 12,
    color: whiteAlpha(0.45),
    fontWeight: 600,
  },
  xpCardVal: {
    fontSize: 13,
    fontWeight: 900,
    color: whiteAlpha(0.78),
  },
  xpCardTotalLabel: {
    fontSize: 12,
    fontWeight: 900,
    color: "#fff",
  },
  xpCardTotalVal: {
    fontSize: 18,
    fontWeight: 1000,
    color: GOLD,
  },
  xpCapNotice: {
    margin: "5px 0 0",
    fontSize: 10,
    color: "#FB923C",
    fontWeight: 700,
  },
  xpRankWrap: {
    borderTop: `1px solid ${BORDER}`,
    paddingTop: 11,
  },
  xpRankRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
  },
  xpTotalLabel: {
    fontSize: 11,
    color: whiteAlpha(0.45),
    fontWeight: 700,
  },
  xpRankTrack: {
    height: 5,
    borderRadius: RADIUS.full,
    background: whiteAlpha(0.08),
    overflow: "hidden",
    marginBottom: 5,
  },
  xpRankFill: {
    height: "100%",
    borderRadius: RADIUS.full,
    transition: "width 700ms ease",
  },
  xpNextLabel: {
    margin: 0,
    fontSize: 10,
    color: whiteAlpha(0.45),
    textAlign: "right",
  },

  // ── feedbackMetricsStyles ────────────────────────────────────────────────
  metricsOverlay: {
    position: "absolute",
    top: "calc(124px + env(safe-area-inset-top))",
    left: "max(18px, env(safe-area-inset-left))",
    right: "calc(96px + env(safe-area-inset-right))",
    zIndex: 4,
    animation: "fadeUp 420ms ease both",
    pointerEvents: "none",
  },
  metricsRow: {
    width: "fit-content",
    maxWidth: "min(300px, calc(100vw - 132px))",
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: 8,
    padding: 10,
    borderRadius: RADIUS.md,
    background: `linear-gradient(145deg, ${blackAlpha(0.62)}, rgba(22,18,16,0.42))`,
    border: `1px solid ${BORDER_2}`,
    backdropFilter: "blur(18px) saturate(150%)",
    WebkitBackdropFilter: "blur(18px) saturate(150%)",
    boxShadow: `0 18px 46px ${blackAlpha(0.35)}, inset 0 1px 0 ${BORDER_2}`,
  },
  metricItem: {
    minWidth: 0,
    display: "grid",
    gap: 5,
    minHeight: 48,
    padding: "8px 10px",
    borderRadius: RADIUS.sm,
    background: whiteAlpha(0.075),
    border: `1px solid ${BORDER}`,
  },
  metricLabel: {
    fontSize: 10,
    fontWeight: 900,
    color: whiteAlpha(0.62),
    letterSpacing: 0,
    textShadow: "0 1px 4px rgba(0,0,0,0.8)",
    textTransform: "uppercase",
    whiteSpace: "nowrap",
  },
  metricValue: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: 15,
    lineHeight: 1.05,
    fontWeight: 1000,
    color: "#fff",
    textShadow: "0 2px 8px rgba(0,0,0,0.9)",
  },
  creatorInfo: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  creatorStats: {
    fontSize: 12,
    lineHeight: 1.25,
    fontWeight: 800,
    color: whiteAlpha(0.74),
    textShadow: "0 2px 8px rgba(0,0,0,0.9)",
  },
  metricsChips: {
    display: "flex",
    flexWrap: "wrap",
    gap: 5,
    marginBottom: 8,
  },
  metricChip: {
    display: "inline-flex",
    alignItems: "center",
    height: 20,
    paddingLeft: 8,
    paddingRight: 8,
    borderRadius: RADIUS.full,
    background: blackAlpha(0.55),
    border: `1px solid ${BORDER_2}`,
    backdropFilter: "blur(10px)",
    WebkitBackdropFilter: "blur(10px)",
    color: whiteAlpha(0.88),
    fontSize: 11,
    fontWeight: 800,
    letterSpacing: 0,
    whiteSpace: "nowrap",
    textShadow: "0 1px 4px rgba(0,0,0,0.8)",
  },
  reelBadgeRow: {
    display: "flex",
    gap: 6,
    flexWrap: "wrap",
    marginTop: 6,
  },
  reelBadge: {
    fontSize: 10,
    fontWeight: 900,
    borderRadius: RADIUS.full,
    border: "1px solid",
    padding: "3px 8px",
    letterSpacing: 0.4,
  },
  reelCategoryBadge: {
    fontSize: 10,
    fontWeight: 900,
    borderRadius: RADIUS.full,
    border: `1px solid ${BORDER_2}`,
    padding: "3px 8px",
    color: whiteAlpha(0.6),
    background: whiteAlpha(0.07),
    letterSpacing: 0.4,
  },
  trainButtonRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 8,
  },
  tryThisButton: {
    width: "fit-content",
    maxWidth: "100%",
    minHeight: 26,
    marginTop: 0,
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 10,
    paddingRight: 10,
    borderRadius: RADIUS.full,
    border: "none",
    background: RED,
    color: "#fff",
    fontFamily: "inherit",
    fontSize: 10,
    lineHeight: 1,
    fontWeight: 900,
    letterSpacing: 0.5,
    cursor: "pointer",
    boxShadow: `0 2px 10px ${redAlpha(0.4)}`,
    textShadow: "none",
    transition: "transform 180ms ease, background 180ms ease",
    WebkitTapHighlightColor: "transparent",
  },
  beatScoreButton: {
    width: "fit-content",
    maxWidth: "100%",
    minHeight: 34,
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 14,
    paddingRight: 14,
    borderRadius: RADIUS.full,
    border: "1px solid rgba(96,165,250,0.45)",
    background: "rgba(96,165,250,0.12)",
    color: "#93C5FD",
    fontFamily: "inherit",
    fontSize: 13,
    lineHeight: 1,
    fontWeight: 950,
    letterSpacing: 0,
    cursor: "pointer",
    WebkitTapHighlightColor: "transparent",
  },
  learnButton: {
    width: "fit-content",
    maxWidth: "100%",
    minHeight: 34,
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 14,
    paddingRight: 14,
    borderRadius: RADIUS.full,
    border: `1px solid ${goldAlpha(0.42)}`,
    background: goldAlpha(0.12),
    color: GOLD,
    fontFamily: "inherit",
    fontSize: 13,
    lineHeight: 1,
    fontWeight: 950,
    letterSpacing: 0,
    cursor: "pointer",
    WebkitTapHighlightColor: "transparent",
  },
  remixBanner: { fontSize: 11, color: PURPLE, marginTop: 4, opacity: 0.85 },
  gymTagBanner: { fontSize: 11, color: GOLD, marginTop: 4, opacity: 0.9 },
  pvpSourceBanner: {
    position: "absolute",
    top: "calc(68px + env(safe-area-inset-top))",
    left: "max(12px, env(safe-area-inset-left))",
    zIndex: 6,
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "6px 12px",
    borderRadius: RADIUS.full,
    background: "rgba(96,165,250,0.18)",
    border: "1px solid rgba(96,165,250,0.4)",
    backdropFilter: "blur(12px)",
    WebkitBackdropFilter: "blur(12px)",
  },
  pvpSourceIcon: { fontSize: 14, lineHeight: 1 },
  pvpSourceText: {
    color: "#93C5FD",
    fontSize: 11,
    fontWeight: 900,
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  profileProgressCard: {
    position: "absolute",
    top: "calc(68px + env(safe-area-inset-top))",
    left: "max(12px, env(safe-area-inset-left))",
    zIndex: 6,
    borderRadius: RADIUS.sm,
    background: blackAlpha(0.58),
    border: `1px solid ${BORDER_2}`,
    backdropFilter: "blur(14px) saturate(140%)",
    WebkitBackdropFilter: "blur(14px) saturate(140%)",
    padding: "8px 12px",
    display: "grid",
    gap: 6,
    minWidth: 160,
    maxWidth: 210,
    pointerEvents: "none",
  },
  profileProgressTitle: {
    color: GOLD,
    fontSize: 9,
    fontWeight: 900,
    letterSpacing: 1.4,
    textTransform: "uppercase",
  },
  profileProgressEmpty: {
    color: whiteAlpha(0.55),
    fontSize: 11,
    fontWeight: 700,
    lineHeight: 1.3,
  },
  profileProgressStats: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  profileProgressStat: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 1,
  },
  profileProgressStatVal: { color: "#fff", fontSize: 17, fontWeight: 1000, lineHeight: 1 },
  profileProgressStatLbl: {
    color: whiteAlpha(0.55),
    fontSize: 8,
    fontWeight: 700,
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  profileProgressDivider: {
    width: 1,
    height: 24,
    background: BORDER_2,
    flexShrink: 0,
  },
};

export default feedbackStyles;
