import { GOLD, PURPLE, redAlpha, goldAlpha } from "@/lib/tokens";

export const feedbackMetricsStyles = {
  // AI Metrics Overlay
  metricsOverlay: {
    position: "absolute",
    top: "calc(124px + env(safe-area-inset-top))",
    left: "max(18px, env(safe-area-inset-left))",
    right: "calc(96px + env(safe-area-inset-right))",
    zIndex: 4,
    animation: "fadeUp 420ms ease both",
    pointerEvents: "none",
  },
  metricsRow: {
    width: "fit-content",
    maxWidth: "min(300px, calc(100vw - 132px))",
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: 8,
    padding: 10,
    borderRadius: 18,
    background: "linear-gradient(145deg, rgba(8,8,8,0.62), rgba(22,18,16,0.42))",
    border: "1px solid rgba(255,255,255,0.14)",
    backdropFilter: "blur(18px) saturate(150%)",
    WebkitBackdropFilter: "blur(18px) saturate(150%)",
    boxShadow: "0 18px 46px rgba(0,0,0,0.35), inset 0 1px 0 rgba(255,255,255,0.12)",
  },
  metricItem: {
    minWidth: 0,
    display: "grid",
    gap: 5,
    minHeight: 48,
    padding: "8px 10px",
    borderRadius: 13,
    background: "rgba(255,255,255,0.075)",
    border: "1px solid rgba(255,255,255,0.08)",
  },
  metricLabel: {
    fontSize: 10,
    fontWeight: 900,
    color: "rgba(255,255,255,0.62)",
    letterSpacing: 0,
    textShadow: "0 1px 4px rgba(0,0,0,0.8)",
    textTransform: "uppercase",
    whiteSpace: "nowrap",
  },
  metricValue: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: 15,
    lineHeight: 1.05,
    fontWeight: 1000,
    color: "var(--text-primary)",
    textShadow: "0 2px 8px rgba(0,0,0,0.9)",
  },
  // Creator Info and Stats
  creatorInfo: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  creatorStats: {
    fontSize: 12,
    lineHeight: 1.25,
    fontWeight: 800,
    color: "rgba(255,255,255,0.74)",
    textShadow: "0 2px 8px rgba(0,0,0,0.9)",
  },
  metricsChips: {
    display: "flex",
    flexWrap: "wrap",
    gap: 5,
    marginBottom: 8,
  },
  metricChip: {
    display: "inline-flex",
    alignItems: "center",
    height: 20,
    paddingLeft: 8,
    paddingRight: 8,
    borderRadius: 999,
    background: "rgba(0,0,0,0.55)",
    border: "1px solid rgba(255,255,255,0.18)",
    backdropFilter: "blur(10px)",
    WebkitBackdropFilter: "blur(10px)",
    color: "rgba(255,255,255,0.88)",
    fontSize: 11,
    fontWeight: 800,
    letterSpacing: 0,
    whiteSpace: "nowrap",
    textShadow: "0 1px 4px rgba(0,0,0,0.8)",
  },
  reelBadgeRow: {
    display: "flex",
    gap: 6,
    flexWrap: "wrap",
    marginTop: 6,
  },
  reelBadge: {
    fontSize: 10,
    fontWeight: 900,
    borderRadius: 999,
    border: "1px solid",
    padding: "3px 8px",
    letterSpacing: 0.4,
  },
  reelCategoryBadge: {
    fontSize: 10,
    fontWeight: 900,
    borderRadius: 999,
    border: "1px solid rgba(255,255,255,0.18)",
    padding: "3px 8px",
    color: "rgba(255,255,255,0.6)",
    background: "rgba(255,255,255,0.07)",
    letterSpacing: 0.4,
  },
  trainButtonRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 8,
  },
  tryThisButton: {
    width: "fit-content",
    maxWidth: "100%",
    minHeight: 26,
    marginTop: 0,
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 10,
    paddingRight: 10,
    borderRadius: 999,
    border: `1px solid ${redAlpha(0.4)}`,
    background: "rgba(0,0,0,0.38)",
    color: "rgba(255,100,100,0.88)",
    fontFamily: "inherit",
    fontSize: 10,
    lineHeight: 1,
    fontWeight: 900,
    letterSpacing: 0.5,
    cursor: "pointer",
    backdropFilter: "blur(10px)",
    WebkitBackdropFilter: "blur(10px)",
    boxShadow: "none",
    textShadow: "none",
    transition: "transform 180ms ease, background 180ms ease",
    WebkitTapHighlightColor: "transparent",
  },
  beatScoreButton: {
    width: "fit-content",
    maxWidth: "100%",
    minHeight: 34,
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 14,
    paddingRight: 14,
    borderRadius: 999,
    border: "1px solid rgba(96,165,250,0.45)",
    background: "rgba(96,165,250,0.12)",
    color: "#93C5FD",
    fontFamily: "inherit",
    fontSize: 13,
    lineHeight: 1,
    fontWeight: 950,
    letterSpacing: 0,
    cursor: "pointer",
    WebkitTapHighlightColor: "transparent",
  },
  learnButton: {
    width: "fit-content",
    maxWidth: "100%",
    minHeight: 34,
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 14,
    paddingRight: 14,
    borderRadius: 999,
    border: `1px solid ${goldAlpha(0.42)}`,
    background: `${goldAlpha(0.12)}`,
    color: GOLD,
    fontFamily: "inherit",
    fontSize: 13,
    lineHeight: 1,
    fontWeight: 950,
    letterSpacing: 0,
    cursor: "pointer",
    WebkitTapHighlightColor: "transparent",
  },
  remixBanner: {
    fontSize: 11,
    color: PURPLE,
    marginTop: 4,
    opacity: 0.85,
  },
  gymTagBanner: {
    fontSize: 11,
    color: GOLD,
    marginTop: 4,
    opacity: 0.9,
  },
  pvpSourceBanner: {
    position: "absolute",
    top: "calc(68px + env(safe-area-inset-top))",
    left: "max(12px, env(safe-area-inset-left))",
    zIndex: 6,
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "6px 12px",
    borderRadius: 999,
    background: "rgba(96,165,250,0.18)",
    border: "1px solid rgba(96,165,250,0.4)",
    backdropFilter: "blur(12px)",
    WebkitBackdropFilter: "blur(12px)",
  },
  pvpSourceIcon: {
    fontSize: 14,
    lineHeight: 1,
  },
  pvpSourceText: {
    color: "#93C5FD",
    fontSize: 11,
    fontWeight: 900,
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  profileProgressCard: {
    position: "absolute",
    top: "calc(68px + env(safe-area-inset-top))",
    left: "max(12px, env(safe-area-inset-left))",
    zIndex: 6,
    borderRadius: 14,
    background: "rgba(0,0,0,0.58)",
    border: "1px solid rgba(255,255,255,0.12)",
    backdropFilter: "blur(14px) saturate(140%)",
    WebkitBackdropFilter: "blur(14px) saturate(140%)",
    padding: "8px 12px",
    display: "grid",
    gap: 6,
    minWidth: 160,
    maxWidth: 210,
    pointerEvents: "none",
  },
  profileProgressTitle: {
    color: GOLD,
    fontSize: 9,
    fontWeight: 900,
    letterSpacing: 1.4,
    textTransform: "uppercase",
  },
  profileProgressEmpty: {
    color: "rgba(255,255,255,0.55)",
    fontSize: 11,
    fontWeight: 700,
    lineHeight: 1.3,
  },
  profileProgressStats: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  profileProgressStat: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 1,
  },
  profileProgressStatVal: {
    color: "#fff",
    fontSize: 17,
    fontWeight: 1000,
    lineHeight: 1,
  },
  profileProgressStatLbl: {
    color: "rgba(255,255,255,0.55)",
    fontSize: 8,
    fontWeight: 700,
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  profileProgressDivider: {
    width: 1,
    height: 24,
    background: "rgba(255,255,255,0.14)",
    flexShrink: 0,
  },
};
