import { RED, GOLD, BORDER, BORDER_2, RADIUS, MOTION, redAlpha, goldAlpha, whiteAlpha, blackAlpha } from "@/lib/tokens";

export const feedbackSheetStyles = {
  feedbackModal: {
    position: "fixed",
    inset: 0,
    zIndex: 1200,
    display: "flex",
    alignItems: "flex-end",
  },
  feedbackOverlay: {
    position: "absolute",
    inset: 0,
    background: blackAlpha(0.62),
    backdropFilter: "blur(4px)",
    WebkitBackdropFilter: "blur(4px)",
  },
  feedbackSheet: {
    position: "relative",
    zIndex: 1201,
    width: "100%",
    maxHeight: "76vh",
    overflow: "hidden",
    borderRadius: "26px 26px 0 0",
    borderTop: `1px solid ${BORDER_2}`,
    background: `linear-gradient(145deg, ${redAlpha(0.14)}, rgba(11,11,11,0.98) 36%, ${goldAlpha(0.07)})`,
    boxShadow: `0 -24px 80px ${blackAlpha(0.58)}`,
    color: "#fff",
  },
  feedbackHandle: {
    width: 42,
    height: 4,
    borderRadius: RADIUS.full,
    background: whiteAlpha(0.24),
    margin: "10px auto 2px",
  },
  feedbackHeader: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 16,
    paddingTop: 18,
    paddingRight: 20,
    paddingBottom: 14,
    paddingLeft: 20,
    borderBottom: `1px solid ${BORDER}`,
  },
  feedbackKicker: {
    margin: 0,
    color: GOLD,
    fontSize: 11,
    fontWeight: 900,
    letterSpacing: 3,
    textTransform: "uppercase",
    fontFamily: "var(--font-condensed)",
  },
  feedbackTitle: {
    margin: "5px 0 0",
    color: "#fff",
    fontSize: 24,
    lineHeight: 1,
    fontWeight: 1000,
    letterSpacing: 0,
  },
  feedbackSubtitle: {
    margin: "8px 0 0",
    color: whiteAlpha(0.55),
    fontSize: 13,
    fontWeight: 750,
  },
  feedbackClose: {
    width: 34,
    height: 34,
    borderRadius: "50%",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: BORDER_2,
    background: whiteAlpha(0.08),
    color: "#fff",
    fontSize: 18,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    lineHeight: 1,
  },
  feedbackBody: {
    maxHeight: "calc(76vh - 112px)",
    overflowY: "auto",
    paddingTop: 18,
    paddingRight: 20,
    paddingBottom: "calc(24px + env(safe-area-inset-bottom))",
    paddingLeft: 20,
  },
  feedbackLoading: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    color: whiteAlpha(0.55),
    fontSize: 14,
    fontWeight: 750,
  },
  feedbackSpinner: {
    width: 22,
    height: 22,
    borderRadius: "50%",
    borderTop: `2px solid ${RED}`,
    borderRight: `2px solid ${whiteAlpha(0.18)}`,
    borderBottom: `2px solid ${whiteAlpha(0.18)}`,
    borderLeft: `2px solid ${whiteAlpha(0.18)}`,
    animation: "spin 1s linear infinite",
  },
  feedbackError: {
    color: "#F87171",
    background: redAlpha(0.12),
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: redAlpha(0.26),
    borderRadius: RADIUS.sm,
    paddingTop: 14,
    paddingBottom: 14,
    paddingLeft: 14,
    paddingRight: 14,
    fontSize: 14,
    lineHeight: 1.5,
  },
  feedbackSaved: {
    marginBottom: 14,
    color: GOLD,
    background: goldAlpha(0.1),
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: goldAlpha(0.22),
    borderRadius: RADIUS.sm,
    paddingTop: 11,
    paddingBottom: 11,
    paddingLeft: 13,
    paddingRight: 13,
    fontSize: 13,
    fontWeight: 900,
  },
  feedbackResult: {
    margin: 0,
    whiteSpace: "pre-wrap",
    color: "#fff",
    fontFamily: "inherit",
    fontSize: 14,
    lineHeight: 1.62,
  },
};
