import { redAlpha, goldAlpha } from "@/lib/tokens";

export const reelActionsStyles = {
  actions: {
    position: "absolute",
    right: "max(10px, env(safe-area-inset-right))",
    bottom: "calc(90px + env(safe-area-inset-bottom))",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 4,
    paddingTop: 7,
    paddingBottom: 7,
    paddingLeft: 4,
    paddingRight: 4,
    borderRadius: 999,
    background: "var(--glass)",
    border: "1px solid var(--line)",
    boxShadow: "var(--shadow-soft), inset 0 1px 0 rgba(255,255,255,0.08)",
    backdropFilter: "blur(22px) saturate(155%)",
    WebkitBackdropFilter: "blur(22px) saturate(155%)",
    animation: "fadeScale 220ms ease both",
    zIndex: 5,
  },
  actionItem: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 2,
    cursor: "pointer",
    WebkitTapHighlightColor: "transparent",
    userSelect: "none",
    opacity: 0.88,
    transition: "transform var(--motion-fast), opacity var(--motion-fast), filter var(--motion-fast)",
  },
  actionItemLiked: {
    animation: "likePop 340ms ease",
    opacity: 1,
  },
  actionItemSaved: {
    animation: "likePop 340ms ease",
    opacity: 1,
  },
  actionCircle: {
    width: 32,
    height: 32,
    borderRadius: "50%",
    background: "transparent",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "transparent",
    backdropFilter: "none",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 0,
    boxShadow: "none",
    transition: "transform var(--motion-fast), background var(--motion-fast), border-color var(--motion-fast), box-shadow var(--motion-fast)",
  },
  actionCircleLiked: {
    background: "rgba(193, 18, 31, 0.12)",
    borderColor: `${redAlpha(0.32)}`,
    boxShadow: "var(--shadow-glow-red)",
  },
  actionCircleSaved: {
    background: `${goldAlpha(0.12)}`,
    borderColor: `${goldAlpha(0.34)}`,
    boxShadow: `0 0 24px ${goldAlpha(0.22)}`,
  },
  actionIcon: {
    color: "var(--text-primary)",
    fontSize: 0,
    fontWeight: 300,
    lineHeight: 1,
    textShadow: "0 2px 8px rgba(0,0,0,0.9)",
  },
  actionIconLiked: {
    color: "var(--primary-red)",
    transform: "scale(1.08)",
    textShadow: `0 0 22px ${redAlpha(0.75)}, 0 2px 8px rgba(0,0,0,0.9)`,
  },
  actionIconSaved: {
    color: "var(--accent-gold)",
    transform: "scale(1.08)",
    textShadow: `0 0 20px ${goldAlpha(0.45)}, 0 2px 8px rgba(0,0,0,0.9)`,
  },
  actionSvg: {
    width: 20,
    height: 20,
    display: "block",
    color: "currentColor",
    filter: "drop-shadow(0 2px 6px rgba(0,0,0,0.85))",
  },
  backArrowSvg: {
    width: 18,
    height: 18,
    display: "block",
  },
  soundToggleButton: {
    position: "fixed",
    top: "calc(62px + env(safe-area-inset-top))",
    right: "max(14px, env(safe-area-inset-right))",
    zIndex: 92,
    width: 36,
    height: 36,
    borderRadius: "50%",
    border: "1px solid rgba(255,255,255,0.14)",
    background: "rgba(0,0,0,0.5)",
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    backdropFilter: "blur(12px)",
    WebkitBackdropFilter: "blur(12px)",
    transition: "transform var(--motion-fast), background var(--motion-fast)",
    WebkitTapHighlightColor: "transparent",
  },
  soundSvg: {
    width: 20,
    height: 20,
    display: "block",
  },
  actionText: {
    color: "var(--text-primary)",
    fontSize: 10,
    fontWeight: 700,
    textShadow: "0 2px 8px rgba(0,0,0,0.95)",
  },
  muteBtn: {
    position: "absolute",
    top: "calc(64px + env(safe-area-inset-top))",
    right: "max(14px, env(safe-area-inset-right))",
    background: "rgba(0,0,0,0.42)",
    border: "1px solid rgba(255,255,255,0.18)",
    borderRadius: 999,
    minWidth: 52,
    height: 30,
    color: "var(--text-primary)",
    fontSize: 11,
    fontWeight: 900,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backdropFilter: "blur(8px)",
    WebkitBackdropFilter: "blur(8px)",
  },
  playIndicator: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    zIndex: 10,
    pointerEvents: "none",
    animation: "fadeScale 220ms ease both",
  },
};
