import { RED, GOLD, MOTION, RADIUS, redAlpha, goldAlpha, whiteAlpha, blackAlpha } from "@/lib/tokens";

export const reelActionsStyles = {
  actions: {
    position: "absolute",
    right: "max(12px, env(safe-area-inset-right))",
    bottom: "calc(96px + env(safe-area-inset-bottom))",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 6,
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 7,
    paddingRight: 7,
    borderRadius: RADIUS.full,
    background: blackAlpha(0.42),
    border: `1px solid ${whiteAlpha(0.1)}`,
    boxShadow: `0 8px 40px ${blackAlpha(0.6)}, inset 0 1px 0 ${whiteAlpha(0.08)}`,
    backdropFilter: "blur(36px) saturate(180%)",
    WebkitBackdropFilter: "blur(36px) saturate(180%)",
    animation: "fadeScale 220ms ease both",
    zIndex: 5,
  },
  actionItem: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 2,
    cursor: "pointer",
    WebkitTapHighlightColor: "transparent",
    userSelect: "none",
    opacity: 0.88,
    transition: `transform ${MOTION.fast}, opacity ${MOTION.fast}, filter ${MOTION.fast}`,
  },
  actionItemLiked: {
    animation: "likePop 340ms ease",
    opacity: 1,
  },
  actionItemSaved: {
    animation: "likePop 340ms ease",
    opacity: 1,
  },
  actionCircle: {
    width: 40,
    height: 40,
    borderRadius: "50%",
    background: whiteAlpha(0.07),
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: whiteAlpha(0.12),
    backdropFilter: "none",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 0,
    boxShadow: `0 2px 12px ${blackAlpha(0.5)}`,
    transition: `transform ${MOTION.fast}, background ${MOTION.fast}, border-color ${MOTION.fast}, box-shadow ${MOTION.fast}`,
  },
  actionCircleLiked: {
    background: redAlpha(0.12),
    borderColor: redAlpha(0.32),
    boxShadow: `0 0 20px ${redAlpha(0.5)}, 0 4px 16px ${redAlpha(0.3)}`,
  },
  actionCircleSaved: {
    background: goldAlpha(0.12),
    borderColor: goldAlpha(0.34),
    boxShadow: `0 0 24px ${goldAlpha(0.22)}`,
  },
  actionIcon: {
    color: "#fff",
    fontSize: 0,
    fontWeight: 300,
    lineHeight: 1,
    textShadow: "0 2px 8px rgba(0,0,0,0.9)",
  },
  actionIconLiked: {
    color: RED,
    transform: "scale(1.08)",
    textShadow: `0 0 22px ${redAlpha(0.75)}, 0 2px 8px rgba(0,0,0,0.9)`,
  },
  actionIconSaved: {
    color: GOLD,
    transform: "scale(1.08)",
    textShadow: `0 0 20px ${goldAlpha(0.45)}, 0 2px 8px rgba(0,0,0,0.9)`,
  },
  actionSvg: {
    width: 20,
    height: 20,
    display: "block",
    color: "currentColor",
    filter: "drop-shadow(0 2px 6px rgba(0,0,0,0.85))",
  },
  backArrowSvg: {
    width: 18,
    height: 18,
    display: "block",
  },
  soundToggleButton: {
    position: "fixed",
    top: "calc(62px + env(safe-area-inset-top))",
    right: "max(14px, env(safe-area-inset-right))",
    zIndex: 92,
    width: 36,
    height: 36,
    borderRadius: "50%",
    border: `1px solid ${whiteAlpha(0.14)}`,
    background: blackAlpha(0.5),
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    backdropFilter: "blur(12px)",
    WebkitBackdropFilter: "blur(12px)",
    transition: `transform ${MOTION.fast}, background ${MOTION.fast}`,
    WebkitTapHighlightColor: "transparent",
  },
  soundSvg: {
    width: 20,
    height: 20,
    display: "block",
  },
  actionText: {
    color: whiteAlpha(0.85),
    fontSize: 10,
    fontWeight: 800,
    textShadow: "0 2px 8px rgba(0,0,0,0.95)",
    letterSpacing: 0.3,
  },
  actionItemAI: {
    opacity: 1,
    marginTop: 6,
  },
  actionCircleAI: {
    width: 40,
    height: 40,
    background: "rgba(34,211,238,0.1)",
    borderColor: "rgba(34,211,238,0.32)",
    boxShadow: "0 0 18px rgba(34,211,238,0.18), inset 0 1px 0 rgba(34,211,238,0.15)",
  },
  actionTextAI: {
    color: "rgba(34,211,238,0.85)",
    fontSize: 9,
    fontWeight: 900,
    letterSpacing: 0.8,
    textShadow: "0 0 12px rgba(34,211,238,0.6), 0 2px 8px rgba(0,0,0,0.9)",
  },
  muteBtn: {
    position: "absolute",
    top: "calc(64px + env(safe-area-inset-top))",
    right: "max(14px, env(safe-area-inset-right))",
    background: blackAlpha(0.42),
    border: `1px solid ${whiteAlpha(0.18)}`,
    borderRadius: RADIUS.full,
    minWidth: 52,
    height: 30,
    color: "#fff",
    fontSize: 11,
    fontWeight: 900,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backdropFilter: "blur(8px)",
    WebkitBackdropFilter: "blur(8px)",
  },
  playIndicator: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    zIndex: 10,
    pointerEvents: "none",
    animation: "fadeScale 220ms ease both",
  },
};
