import { RED, BORDER, BORDER_2, RADIUS, MOTION, redAlpha, whiteAlpha, blackAlpha } from "@/lib/tokens";

export const reelNavStyles = {
  bottomNav: {
    position: "fixed",
    bottom: "calc(6px + env(safe-area-inset-bottom))",
    left: "50%",
    width: "min(calc(100vw - 28px), 440px)",
    minHeight: 58,
    transform: "translateX(-50%)",
    background: blackAlpha(0.55),
    border: `1px solid ${BORDER}`,
    borderRadius: RADIUS.xl,
    boxShadow: `0 8px 40px ${blackAlpha(0.6)}, inset 0 1px 0 ${whiteAlpha(0.11)}`,
    backdropFilter: "blur(30px) saturate(165%)",
    WebkitBackdropFilter: "blur(30px) saturate(165%)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    zIndex: 100,
    paddingTop: 6,
    paddingBottom: 6,
    paddingLeft: 8,
    paddingRight: 8,
  },
  navItem: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 3,
    cursor: "pointer",
    paddingTop: 6,
    paddingBottom: 6,
    paddingLeft: 6,
    paddingRight: 6,
    minWidth: 43,
    minHeight: 44,
    borderRadius: 16,
    color: whiteAlpha(0.62),
    WebkitTapHighlightColor: "transparent",
    transition: `color ${MOTION.fast}, transform ${MOTION.fast}, background ${MOTION.fast}, opacity ${MOTION.fast}`,
  },
  navItemActive: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 3,
    cursor: "pointer",
    paddingTop: 6,
    paddingBottom: 6,
    paddingLeft: 8,
    paddingRight: 8,
    minWidth: 48,
    minHeight: 44,
    borderRadius: 16,
    color: "#fff",
    background: redAlpha(0.14),
    boxShadow: `0 0 20px ${redAlpha(0.24)}, inset 0 0 0 1px ${redAlpha(0.2)}`,
    WebkitTapHighlightColor: "transparent",
    transition: `color ${MOTION.fast}, transform ${MOTION.fast}, background ${MOTION.fast}, box-shadow ${MOTION.fast}`,
  },
  navIcon: { fontSize: 20 },
  navSvg: {
    width: 20,
    height: 20,
    display: "block",
    fill: "none",
    stroke: "currentColor",
    strokeWidth: 1.9,
    strokeLinecap: "round",
    strokeLinejoin: "round",
  },
  navSvgActive: {
    width: 20,
    height: 20,
    display: "block",
    fill: "none",
    stroke: "#fff",
    strokeWidth: 2,
    strokeLinecap: "round",
    strokeLinejoin: "round",
    filter: `drop-shadow(0 0 8px ${redAlpha(0.72)})`,
  },
  navIconWrap: {
    position: "relative",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minWidth: 24,
    minHeight: 24,
    color: "currentColor",
  },
  navBadge: {
    position: "absolute",
    top: -7,
    right: -9,
    minWidth: 16,
    height: 16,
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 4,
    paddingRight: 4,
    borderRadius: 8,
    background: RED,
    color: "#fff",
    border: `1px solid ${blackAlpha(0.9)}`,
    fontSize: 10,
    fontWeight: 700,
    lineHeight: "14px",
    textAlign: "center",
  },
  navIconActive: { fontSize: 21 },
  navLabel: {
    color: "currentColor",
    fontSize: 8,
    fontWeight: 700,
    letterSpacing: 0,
  },
  navLabelActive: {
    color: "#fff",
    fontSize: 8,
    fontWeight: 800,
    letterSpacing: 0,
    textShadow: `0 0 12px ${redAlpha(0.65)}`,
  },
  navUpload: {
    width: 42,
    height: 42,
    background: redAlpha(0.82),
    border: `1px solid ${BORDER_2}`,
    borderRadius: 16,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    boxShadow: `0 8px 22px ${redAlpha(0.24)}`,
    WebkitTapHighlightColor: "transparent",
    transition: `transform ${MOTION.press}, box-shadow ${MOTION.press}, background ${MOTION.press}`,
  },
  navUploadIcon: {
    color: "#fff",
    fontSize: 22,
    fontWeight: 300,
  },
  navUploadSvg: {
    width: 21,
    height: 21,
    display: "block",
    fill: "none",
    stroke: "#fff",
    strokeWidth: 2,
    strokeLinecap: "round",
    strokeLinejoin: "round",
    filter: `drop-shadow(0 2px 8px ${blackAlpha(0.35)})`,
  },
};
