import { RED, BG, GOLD, redAlpha, goldAlpha } from "@/lib/tokens";

export const reelVideoStyles = {
  container: {
    position: "relative",
    width: "100vw",
    height: "100dvh",
    minHeight: "100dvh",
    background: "#000",
    overflow: "hidden",
  },
  loading: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
    height: "100dvh",
    color: "var(--text-primary)",
    fontSize: 16,
  },
  // Cinematic skeleton loading layout
  loadingCinematic: {
    position: "relative",
    width: "100vw",
    height: "100dvh",
    background: `radial-gradient(ellipse 70% 50% at 50% 20%, ${redAlpha(0.15)} 0%, transparent 60%), linear-gradient(180deg, #060608 0%, #09090B 100%)`,
    overflow: "hidden",
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "center",
    paddingBottom: 120,
  },
  loadingOrb: {
    position: "absolute",
    width: 500,
    height: 500,
    top: "-100px",
    left: "50%",
    transform: "translateX(-50%)",
    background: redAlpha(0.10),
    borderRadius: "50%",
    filter: "blur(80px)",
    pointerEvents: "none",
    animation: "ambient-pulse 5s ease-in-out infinite",
  },
  skeletonBack: {
    position: "absolute",
    top: 0,
    left: "50%",
    transform: "translateX(-50%) scale(0.88) translateY(10px)",
    width: "min(100vw, 440px)",
    height: "100dvh",
    borderRadius: 24,
    background: "rgba(255,255,255,0.025)",
    transformOrigin: "top center",
  },
  skeletonMid: {
    position: "absolute",
    top: 0,
    left: "50%",
    transform: "translateX(-50%) scale(0.94) translateY(5px)",
    width: "min(100vw, 440px)",
    height: "100dvh",
    borderRadius: 20,
    background: "rgba(255,255,255,0.04)",
    transformOrigin: "top center",
  },
  skeletonFront: {
    position: "absolute",
    top: 0,
    left: "50%",
    transform: "translateX(-50%)",
    width: "min(100vw, 440px)",
    height: "100dvh",
    borderRadius: 16,
    background: "rgba(255,255,255,0.055)",
    transformOrigin: "top center",
  },
  loadingStatus: {
    position: "relative",
    zIndex: 2,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 10,
  },
  loadingTitle: {
    color: "var(--text-primary)",
    fontSize: 15,
    fontWeight: 900,
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  loadingMeta: {
    color: "var(--text-secondary)",
    fontSize: 12,
    fontWeight: 650,
    marginTop: -4,
    letterSpacing: 0.5,
  },
  spinner: {
    width: 36,
    height: 36,
    borderTop: `3px solid ${RED}`,
    borderRight: "3px solid rgba(255,255,255,0.15)",
    borderBottom: "3px solid rgba(255,255,255,0.15)",
    borderLeft: "3px solid rgba(255,255,255,0.15)",
    borderRadius: "50%",
    animation: "spin 1s linear infinite",
    boxShadow: `0 0 16px ${redAlpha(0.4)}`,
  },
  empty: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    height: "100dvh",
    color: "var(--text-primary)",
    gap: 16,
  },
  uploadBtn: {
    background: "var(--primary-red)",
    color: "var(--text-primary)",
    border: "none",
    borderRadius: 10,
    paddingTop: 12,
    paddingBottom: 12,
    paddingLeft: "var(--space-6)",
    paddingRight: "var(--space-6)",
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
  },
  header: {
    display: "none",
  },
  headerTabs: {
    display: "flex",
    gap: 24,
  },
  headerTab: {
    color: "rgba(255,255,255,0.6)",
    fontSize: 17,
    fontWeight: 600,
    cursor: "pointer",
  },
  headerTabActive: {
    color: "var(--text-primary)",
    fontSize: 17,
    fontWeight: 700,
    borderBottom: `2px solid ${RED}`,
    paddingBottom: 4,
  },
  profileBackButton: {
    position: "fixed",
    top: "calc(16px + env(safe-area-inset-top))",
    left: "max(14px, env(safe-area-inset-left))",
    zIndex: 90,
    height: 38,
    paddingTop: 0,
    paddingRight: 13,
    paddingBottom: 0,
    paddingLeft: 10,
    borderRadius: 999,
    border: "1px solid rgba(255,255,255,0.16)",
    background: "rgba(0,0,0,0.5)",
    color: "#fff",
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12,
    fontWeight: 900,
    letterSpacing: 0.4,
    cursor: "pointer",
    backdropFilter: "blur(16px)",
    WebkitBackdropFilter: "blur(16px)",
  },
  feedTabs: {
    position: "fixed",
    top: "calc(14px + env(safe-area-inset-top))",
    left: "50%",
    transform: "translateX(-50%)",
    zIndex: 110,
    display: "flex",
    alignItems: "center",
    gap: 6,
    paddingTop: 4,
    paddingBottom: 4,
    paddingLeft: 4,
    paddingRight: 4,
    borderRadius: 999,
    background: "var(--glass)",
    border: "1px solid var(--line)",
    backdropFilter: "blur(18px) saturate(150%)",
    WebkitBackdropFilter: "blur(18px) saturate(150%)",
    boxShadow: "var(--shadow-soft)",
    maxWidth: "calc(100vw - 24px)",
    overflowX: "auto",
    scrollbarWidth: "none",
  },
  feedTab: {
    border: "none",
    borderRadius: 999,
    background: "transparent",
    color: "#888",
    minHeight: 34,
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 11,
    paddingRight: 11,
    fontSize: 12,
    fontWeight: 850,
    cursor: "pointer",
    WebkitTapHighlightColor: "transparent",
    flexShrink: 0,
    whiteSpace: "nowrap",
  },
  feedTabActive: {
    background: RED,
    color: "#FFFFFF",
    boxShadow: "none",
  },
  feed: {
    height: "100dvh",
    overflowY: "scroll",
    scrollSnapType: "y mandatory",
    scrollBehavior: "smooth",
    overscrollBehaviorY: "contain",
    WebkitOverflowScrolling: "touch",
  },
  videoContainer: {
    position: "relative",
    width: "100vw",
    height: "100dvh",
    flexShrink: 0,
    overflow: "hidden",
    scrollSnapAlign: "start",
    scrollSnapStop: "always",
    animation: "reelEnter 220ms ease both",
  },
  activeVideo: {
    zIndex: 1,
  },
  followingEmpty: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 14,
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: "var(--space-6)",
    paddingRight: "var(--space-6)",
    textAlign: "center",
    background: "var(--background)",
  },
  followingEmptyTitle: {
    color: "var(--text-primary)",
    fontSize: 24,
    fontWeight: 950,
  },
  followingEmptyText: {
    color: "var(--text-secondary)",
    fontSize: 14,
    lineHeight: 1.45,
    maxWidth: 320,
  },
  videoLoadingOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    display: "flex",
    flexDirection: "column",
    gap: 12,
    alignItems: "center",
    justifyContent: "center",
    background: `radial-gradient(circle at 50% 42%, ${redAlpha(0.16)}, transparent 34%), linear-gradient(180deg, rgba(11,11,12,0.82), rgba(11,11,12,0.94))`,
    zIndex: 10,
  },
  videoLoadingText: {
    color: "rgba(255,255,255,0.82)",
    fontSize: 13,
    fontWeight: 850,
    textShadow: "0 3px 14px rgba(0,0,0,0.85)",
  },
  video: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    background: "var(--background)",
    filter: "contrast(1.08) saturate(1.04)",
    transformOrigin: "center center",
  },
  vignette: {
    position: "absolute",
    inset: 0,
    pointerEvents: "none",
    background: "radial-gradient(ellipse at center, transparent 42%, rgba(0,0,0,0.22) 72%, rgba(0,0,0,0.56) 100%)",
    zIndex: 2,
  },
  demoReel: {
    position: "absolute",
    inset: 0,
    overflow: "hidden",
    background: `radial-gradient(circle at 52% 34%, ${goldAlpha(0.16)}, transparent 28%), radial-gradient(circle at 46% 62%, ${redAlpha(0.2)}, transparent 30%), #0B0B0C`,
  },
  demoVignette: {
    position: "absolute",
    inset: 0,
    background: "radial-gradient(circle at 50% 38%, rgba(255,255,255,0.08), transparent 34%), linear-gradient(to bottom, rgba(0,0,0,0.15), #000)",
  },
  reelFallback: {
    position: "absolute",
    inset: 0,
    overflow: "hidden",
    background: `radial-gradient(circle at 50% 38%, ${redAlpha(0.22)}, transparent 32%), radial-gradient(circle at 58% 56%, ${goldAlpha(0.12)}, transparent 30%), #0B0B0C`,
  },
  reelFallbackLight: {
    position: "absolute",
    inset: 0,
    background: "linear-gradient(135deg, transparent 0%, rgba(255,255,255,0.08) 42%, transparent 66%)",
    opacity: 0.5,
  },
  reelFallbackContent: {
    position: "absolute",
    left: "max(24px, env(safe-area-inset-left))",
    right: 96,
    bottom: "calc(170px + env(safe-area-inset-bottom))",
    display: "grid",
    gap: 10,
    zIndex: 1,
  },
  reelFallbackKicker: {
    color: "var(--accent-gold)",
    fontSize: 11,
    fontWeight: 950,
    letterSpacing: 1.8,
  },
  reelFallbackTitle: {
    color: "var(--text-primary)",
    fontSize: 28,
    lineHeight: 1.05,
    fontWeight: 1000,
    textShadow: "0 8px 28px rgba(0,0,0,0.9)",
  },
  reelFallbackText: {
    color: "rgba(255,255,255,0.68)",
    fontSize: 14,
    lineHeight: 1.45,
    maxWidth: 360,
  },
  demoGrid: { display: "none" },
  demoSpotlight: { display: "none" },
  demoBag: { display: "none" },
  demoFighter: { display: "none" },
  demoHead: {
    position: "absolute",
    left: 76,
    top: 0,
    width: 54,
    height: 54,
    borderRadius: "50%",
    background: GOLD,
  },
  demoTorso: {
    position: "absolute",
    left: 58,
    top: 60,
    width: 92,
    height: 148,
    borderRadius: "42px 42px 24px 24px",
    background: "linear-gradient(160deg, #1c1c1c, #530916)",
    border: "1px solid rgba(255,255,255,0.08)",
  },
  demoGloveLead: {
    position: "absolute",
    right: 0,
    top: 76,
    width: 86,
    height: 58,
    borderRadius: "34px 30px 28px 28px",
    background: RED,
    boxShadow: "0 20px 48px rgba(0,0,0,0.36)",
  },
  demoGloveRear: {
    position: "absolute",
    left: 8,
    top: 86,
    width: 66,
    height: 54,
    borderRadius: "30px",
    background: GOLD,
  },
  demoHook: {
    position: "absolute",
    left: 18,
    right: 92,
    bottom: 132,
    display: "grid",
    gap: 8,
  },
  demoHookKicker: {
    color: "var(--accent-gold)",
    fontSize: 11,
    fontWeight: 900,
    letterSpacing: 1.8,
    textTransform: "uppercase",
  },
  demoHookTitle: {
    color: "var(--text-primary)",
    fontSize: 34,
    lineHeight: 1,
    fontWeight: 950,
    letterSpacing: 0,
  },
  demoHookText: {
    color: "rgba(255,255,255,0.72)",
    fontSize: 14,
    lineHeight: 1.45,
  },
  demoUploadMessage: {
    marginTop: 8,
    color: "var(--text-primary)",
    fontSize: 15,
    fontWeight: 900,
    textShadow: "0 2px 10px rgba(0,0,0,0.9)",
  },
  demoUploadButton: {
    width: 128,
    minHeight: 42,
    marginTop: 4,
    border: "none",
    borderRadius: 8,
    background: "var(--primary-red)",
    color: "var(--text-primary)",
    fontSize: 15,
    fontWeight: 900,
    cursor: "pointer",
    boxShadow: "0 14px 32px rgba(0,0,0,0.34)",
  },
  overlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    paddingTop: 20,
    paddingRight: 18,
    paddingBottom: "calc(86px + env(safe-area-inset-bottom))",
    paddingLeft: 18,
    background: "linear-gradient(to top, rgba(0,0,0,0.88) 0%, rgba(0,0,0,0.38) 46%, transparent 78%)",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-end",
  },
  bottomGradient: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: "64vh",
    pointerEvents: "none",
    background: "linear-gradient(to top, rgba(0,0,0,0.97) 0%, rgba(0,0,0,0.68) 38%, rgba(0,0,0,0.32) 68%, transparent 100%)",
    zIndex: 2,
  },
  videoProgressBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 2,
    background: "rgba(255,255,255,0.15)",
    zIndex: 20,
    overflow: "hidden",
  },
  videoProgressFill: {
    height: "100%",
    background: "rgba(255,255,255,0.65)",
    transition: "width 0.25s linear",
    borderRadius: "0 1px 1px 0",
  },
};
