import { RED, GOLD, PURPLE, redAlpha, goldAlpha } from "@/lib/tokens";

const styles = {
  container: {
    position: "relative",
    width: "100vw",
    height: "100vh",
    minHeight: "100dvh",
    background: "#000",
    overflow: "hidden",
    fontFamily: "-apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif",
  },
  loading: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
    height: "100vh",
    color: "var(--text-primary)",
    fontSize: 16,
  },
  loadingTitle: {
    color: "var(--text-primary)",
    fontSize: 18,
    fontWeight: 900,
    letterSpacing: 0,
  },
  loadingMeta: {
    color: "var(--text-secondary)",
    fontSize: 13,
    fontWeight: 650,
    marginTop: -8,
  },
  spinner: {
    width: 40,
    height: 40,
    borderTop: "3px solid var(--primary-red)",
    borderRight: "3px solid rgba(255,255,255,0.3)",
    borderBottom: "3px solid rgba(255,255,255,0.3)",
    borderLeft: "3px solid rgba(255,255,255,0.3)",
    borderRadius: "50%",
    animation: "spin 1s linear infinite",
  },
  empty: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    height: "100vh",
    color: "var(--text-primary)",
    gap: 16,
  },
  uploadBtn: {
    background: "var(--primary-red)",
    color: "var(--text-primary)",
    border: "none",
    borderRadius: 10,
    paddingTop: 12,
    paddingBottom: 12,
    paddingLeft: "var(--space-6)",
    paddingRight: "var(--space-6)",
    fontSize: 14,
    fontWeight: 600,
    cursor: "pointer",
  },
  header: {
    display: "none",
  },
  headerTabs: {
    display: "flex",
    gap: 24,
  },
  headerTab: {
    color: "rgba(255,255,255,0.6)",
    fontSize: 17,
    fontWeight: 600,
    cursor: "pointer",
  },
  headerTabActive: {
    color: "var(--text-primary)",
    fontSize: 17,
    fontWeight: 700,
    borderBottom: "2px solid #C1121F",
    paddingBottom: 4,
  },
  profileBackButton: {
    position: "fixed",
    top: "calc(16px + env(safe-area-inset-top))",
    left: "max(14px, env(safe-area-inset-left))",
    zIndex: 90,
    height: 38,
    paddingTop: 0,
    paddingRight: 13,
    paddingBottom: 0,
    paddingLeft: 10,
    borderRadius: 999,
    border: "1px solid rgba(255,255,255,0.16)",
    background: "rgba(0,0,0,0.5)",
    color: "#fff",
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12,
    fontWeight: 900,
    letterSpacing: 0.4,
    cursor: "pointer",
    backdropFilter: "blur(16px)",
    WebkitBackdropFilter: "blur(16px)",
  },
  feedTabs: {
    position: "fixed",
    top: "calc(14px + env(safe-area-inset-top))",
    left: "50%",
    transform: "translateX(-50%)",
    zIndex: 110,
    display: "flex",
    alignItems: "center",
    gap: 6,
    paddingTop: 4,
    paddingBottom: 4,
    paddingLeft: 4,
    paddingRight: 4,
    borderRadius: 999,
    background: "var(--glass)",
    border: "1px solid var(--line)",
    backdropFilter: "blur(18px) saturate(150%)",
    WebkitBackdropFilter: "blur(18px) saturate(150%)",
    boxShadow: "var(--shadow-soft)",
    maxWidth: "calc(100vw - 24px)",
    overflowX: "auto",
    scrollbarWidth: "none",
  },
  feedTab: {
    border: "none",
    borderRadius: 999,
    background: "transparent",
    color: "#888",
    minHeight: 34,
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 11,
    paddingRight: 11,
    fontSize: 12,
    fontWeight: 850,
    cursor: "pointer",
    WebkitTapHighlightColor: "transparent",
    flexShrink: 0,
    whiteSpace: "nowrap",
  },
  feedTabActive: {
    background: RED,
    color: "#FFFFFF",
    boxShadow: "none",
  },
  feed: {
    height: "100dvh",
    overflowY: "scroll",
    scrollSnapType: "y mandatory",
    scrollBehavior: "smooth",
    overscrollBehaviorY: "contain",
    WebkitOverflowScrolling: "touch",
  },
  videoContainer: {
    position: "relative",
    width: "100vw",
    height: "100dvh",
    flexShrink: 0,
    overflow: "hidden",
    scrollSnapAlign: "start",
    scrollSnapStop: "always",
    animation: "reelEnter 220ms ease both",
  },
  activeVideo: {
    zIndex: 1,
  },
  followingEmpty: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 14,
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: "var(--space-6)",
    paddingRight: "var(--space-6)",
    textAlign: "center",
    background: "var(--background)",
  },
  followingEmptyTitle: {
    color: "var(--text-primary)",
    fontSize: 24,
    fontWeight: 950,
  },
  followingEmptyText: {
    color: "var(--text-secondary)",
    fontSize: 14,
    lineHeight: 1.45,
    maxWidth: 320,
  },
  videoLoadingOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    display: "flex",
    flexDirection: "column",
    gap: 12,
    alignItems: "center",
    justifyContent: "center",
    background: `radial-gradient(circle at 50% 42%, ${redAlpha(0.16)}, transparent 34%), linear-gradient(180deg, rgba(7,7,7,0.82), rgba(7,7,7,0.94))`,
    zIndex: 10,
  },
  videoLoadingText: {
    color: "rgba(255,255,255,0.82)",
    fontSize: 13,
    fontWeight: 850,
    textShadow: "0 3px 14px rgba(0,0,0,0.85)",
  },
  video: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    background: "var(--background)",
    filter: "contrast(1.08) saturate(1.04)",
    transformOrigin: "center center",
  },
  vignette: {
    position: "absolute",
    inset: 0,
    pointerEvents: "none",
    background: "radial-gradient(ellipse at center, transparent 42%, rgba(0,0,0,0.22) 72%, rgba(0,0,0,0.56) 100%)",
    zIndex: 2,
  },
  demoReel: {
    position: "absolute",
    inset: 0,
    overflow: "hidden",
    background: `radial-gradient(circle at 52% 34%, ${goldAlpha(0.16)}, transparent 28%), radial-gradient(circle at 46% 62%, ${redAlpha(0.2)}, transparent 30%), linear-gradient(145deg, #070707 0%, #171010 48%, #050505 100%)`,
  },
  demoVignette: {
    position: "absolute",
    inset: 0,
    background: "radial-gradient(circle at 50% 38%, rgba(255,255,255,0.08), transparent 34%), linear-gradient(to bottom, rgba(0,0,0,0.15), #000)",
  },
  reelFallback: {
    position: "absolute",
    inset: 0,
    overflow: "hidden",
    background: `radial-gradient(circle at 50% 38%, ${redAlpha(0.22)}, transparent 32%), radial-gradient(circle at 58% 56%, ${goldAlpha(0.12)}, transparent 30%), linear-gradient(145deg, #070707, #13090b 48%, #050505)`,
  },
  reelFallbackLight: {
    position: "absolute",
    inset: 0,
    background: "linear-gradient(135deg, transparent 0%, rgba(255,255,255,0.08) 42%, transparent 66%)",
    opacity: 0.5,
  },
  reelFallbackContent: {
    position: "absolute",
    left: "max(24px, env(safe-area-inset-left))",
    right: 96,
    bottom: "calc(170px + env(safe-area-inset-bottom))",
    display: "grid",
    gap: 10,
    zIndex: 1,
  },
  reelFallbackKicker: {
    color: "var(--accent-gold)",
    fontSize: 11,
    fontWeight: 950,
    letterSpacing: 1.8,
  },
  reelFallbackTitle: {
    color: "var(--text-primary)",
    fontSize: 28,
    lineHeight: 1.05,
    fontWeight: 1000,
    textShadow: "0 8px 28px rgba(0,0,0,0.9)",
  },
  reelFallbackText: {
    color: "rgba(255,255,255,0.68)",
    fontSize: 14,
    lineHeight: 1.45,
    maxWidth: 360,
  },
  demoGrid: {
    display: "none",
  },
  demoSpotlight: {
    display: "none",
  },
  demoBag: {
    display: "none",
  },
  demoFighter: {
    display: "none",
  },
  demoHead: {
    position: "absolute",
    left: 76,
    top: 0,
    width: 54,
    height: 54,
    borderRadius: "50%",
    background: "linear-gradient(145deg, #D4AF37, #70501a)",
  },
  demoTorso: {
    position: "absolute",
    left: 58,
    top: 60,
    width: 92,
    height: 148,
    borderRadius: "42px 42px 24px 24px",
    background: "linear-gradient(160deg, #1c1c1c, #530916)",
    border: "1px solid rgba(255,255,255,0.08)",
  },
  demoGloveLead: {
    position: "absolute",
    right: 0,
    top: 76,
    width: 86,
    height: 58,
    borderRadius: "34px 30px 28px 28px",
    background: "linear-gradient(145deg, #C1121F, #770111)",
    boxShadow: "0 20px 48px rgba(0,0,0,0.36)",
  },
  demoGloveRear: {
    position: "absolute",
    left: 8,
    top: 86,
    width: 66,
    height: 54,
    borderRadius: "30px",
    background: "linear-gradient(145deg, #D4AF37, #70501a)",
  },
  demoHook: {
    position: "absolute",
    left: 18,
    right: 92,
    bottom: 132,
    display: "grid",
    gap: 8,
  },
  demoHookKicker: {
    color: "var(--accent-gold)",
    fontSize: 11,
    fontWeight: 900,
    letterSpacing: 1.8,
    textTransform: "uppercase",
  },
  demoHookTitle: {
    color: "var(--text-primary)",
    fontSize: 34,
    lineHeight: 1,
    fontWeight: 950,
    letterSpacing: 0,
  },
  demoHookText: {
    color: "rgba(255,255,255,0.72)",
    fontSize: 14,
    lineHeight: 1.45,
  },
  demoUploadMessage: {
    marginTop: 8,
    color: "var(--text-primary)",
    fontSize: 15,
    fontWeight: 900,
    textShadow: "0 2px 10px rgba(0,0,0,0.9)",
  },
  demoUploadButton: {
    width: 128,
    minHeight: 42,
    marginTop: 4,
    border: "none",
    borderRadius: 8,
    background: "var(--primary-red)",
    color: "var(--text-primary)",
    fontSize: 15,
    fontWeight: 900,
    cursor: "pointer",
    boxShadow: "0 14px 32px rgba(0,0,0,0.34)",
  },
  overlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    paddingTop: 20,
    paddingRight: 18,
    paddingBottom: "calc(86px + env(safe-area-inset-bottom))",
    paddingLeft: 18,
    background: "linear-gradient(to top, rgba(0,0,0,0.88) 0%, rgba(0,0,0,0.38) 46%, transparent 78%)",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-end",
  },
  bottomGradient: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: "64vh",
    pointerEvents: "none",
    background: "linear-gradient(to top, rgba(0,0,0,0.97) 0%, rgba(0,0,0,0.68) 38%, rgba(0,0,0,0.32) 68%, transparent 100%)",
    zIndex: 2,
  },
  videoProgressBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 2,
    background: "rgba(255,255,255,0.15)",
    zIndex: 20,
    overflow: "hidden",
  },
  videoProgressFill: {
    height: "100%",
    background: "rgba(255,255,255,0.65)",
    transition: "width 0.25s linear",
    borderRadius: "0 1px 1px 0",
  },
  info: {
    position: "absolute",
    left: "max(14px, env(safe-area-inset-left))",
    right: 76,
    bottom: "calc(92px + env(safe-area-inset-bottom))",
    maxWidth: 520,
    animation: "pageEnter 380ms cubic-bezier(0.16, 1, 0.3, 1) both",
    zIndex: 4,
  },
  creatorRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginBottom: 10,
  },
  creatorAvatarButton: {
    width: 44,
    height: 44,
    flex: "0 0 44px",
    borderRadius: "50%",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: `${goldAlpha(0.64)}`,
    background: `linear-gradient(145deg, ${redAlpha(0.9)}, rgba(7,7,7,0.78))`,
    boxShadow: `0 0 0 3px ${redAlpha(0.2)}, 0 10px 26px rgba(0,0,0,0.55)`,
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    overflow: "hidden",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    WebkitTapHighlightColor: "transparent",
  },
  creatorAvatarImage: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    display: "block",
  },
  creatorAvatarFallback: {
    color: "var(--text-primary)",
    fontSize: 17,
    fontWeight: 1000,
    textShadow: "0 2px 10px rgba(0,0,0,0.72)",
  },
  username: {
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    border: "none",
    background: "transparent",
    color: "var(--text-primary)",
    fontFamily: "inherit",
    fontSize: 15,
    fontWeight: 900,
    margin: 0,
    letterSpacing: 0,
    lineHeight: 1.1,
    textAlign: "left",
    textShadow: "0 5px 28px rgba(0,0,0,0.98), 0 1px 2px rgba(0,0,0,1)",
    WebkitTapHighlightColor: "transparent",
    display: "flex",
    alignItems: "center",
    gap: 6,
  },
  onFireBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: 3,
    fontSize: 11,
    fontWeight: 900,
    letterSpacing: 0.6,
    color: "#FB923C",
    lineHeight: 1,
    flexShrink: 0,
  },
  viewProof: {
    color: "rgba(255,255,255,0.82)",
    fontSize: 13,
    fontWeight: 800,
    marginBottom: 10,
    textShadow: "0 2px 8px rgba(0,0,0,0.95)",
  },
  descriptionLine: {
    display: "block",
    marginBottom: 8,
    padding: 0,
    border: "none",
    background: "transparent",
    textAlign: "left",
    cursor: "pointer",
    color: "var(--text-primary)",
    fontSize: 13,
    lineHeight: 1.35,
    fontWeight: 500,
    maxWidth: 500,
    width: "100%",
    textShadow: "0 4px 22px rgba(0,0,0,0.96), 0 1px 2px rgba(0,0,0,1)",
    letterSpacing: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  filterSheetOverlay: {
    position: "fixed",
    inset: 0,
    zIndex: 9999,
    background: "rgba(0,0,0,0.55)",
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "center",
  },
  filterSheet: {
    width: "100%",
    maxWidth: 600,
    background: "linear-gradient(180deg, #161212, #0a0a0a)",
    borderRadius: "20px 20px 0 0",
    padding: "10px 20px calc(32px + env(safe-area-inset-bottom))",
    border: `1px solid ${goldAlpha(0.12)}`,
    boxShadow: "0 -16px 48px rgba(0,0,0,0.7)",
    display: "flex",
    flexDirection: "column",
  },
  filterSheetHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    background: "rgba(255,255,255,0.18)",
    alignSelf: "center",
    marginBottom: 16,
    flexShrink: 0,
  },
  filterSheetHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  filterSheetTitle: {
    fontSize: 10,
    fontWeight: 900,
    color: "rgba(255,255,255,0.4)",
    letterSpacing: 2,
  },
  filterSheetClose: {
    background: "rgba(255,255,255,0.08)",
    border: "none",
    borderRadius: "50%",
    width: 28,
    height: 28,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "rgba(255,255,255,0.6)",
    fontSize: 12,
    cursor: "pointer",
    padding: 0,
  },
  filterSheetBody: {
    display: "flex",
    flexDirection: "column",
  },
  filterSheetLabel: {
    margin: "0 0 10px",
    fontSize: 10,
    fontWeight: 900,
    color: GOLD,
    letterSpacing: 1.5,
  },
  filterSheetRow: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
  },
  filterChip: {
    padding: "7px 14px",
    borderRadius: 999,
    border: "1px solid rgba(255,255,255,0.14)",
    background: "rgba(255,255,255,0.06)",
    color: "rgba(255,255,255,0.65)",
    fontSize: 12,
    fontWeight: 800,
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  filterChipActive: {
    border: `1px solid ${redAlpha(0.6)}`,
    background: `${redAlpha(0.2)}`,
    color: "#F87171",
  },
  filterClearBtn: {
    marginTop: 20,
    padding: "10px 20px",
    borderRadius: 999,
    border: "1px solid rgba(255,255,255,0.12)",
    background: "rgba(255,255,255,0.05)",
    color: "rgba(255,255,255,0.5)",
    fontSize: 12,
    fontWeight: 800,
    cursor: "pointer",
    alignSelf: "flex-start",
  },
  captionSheetOverlay: {
    position: "fixed",
    inset: 0,
    zIndex: 9999,
    background: "rgba(0,0,0,0.55)",
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "center",
  },
  captionSheet: {
    width: "100%",
    maxWidth: 600,
    maxHeight: "50vh",
    background: "#111",
    borderRadius: "18px 18px 0 0",
    padding: "12px 20px 32px",
    display: "flex",
    flexDirection: "column",
    boxShadow: "0 -4px 32px rgba(0,0,0,0.7)",
  },
  captionSheetHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    background: "rgba(255,255,255,0.22)",
    alignSelf: "center",
    marginBottom: 14,
    flexShrink: 0,
  },
  captionSheetHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
    flexShrink: 0,
  },
  captionSheetTitle: {
    color: "rgba(255,255,255,0.55)",
    fontSize: 12,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  captionSheetClose: {
    background: "rgba(255,255,255,0.1)",
    border: "none",
    borderRadius: "50%",
    width: 28,
    height: 28,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "rgba(255,255,255,0.7)",
    fontSize: 14,
    cursor: "pointer",
    padding: 0,
  },
  captionSheetBody: {
    overflowY: "auto",
    flex: 1,
  },
  captionSheetText: {
    margin: 0,
    color: "var(--text-primary)",
    fontSize: 15,
    lineHeight: 1.6,
    fontWeight: 400,
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  },
  captionMetaChip: {
    display: "inline-flex",
    alignItems: "center",
    padding: "5px 11px",
    borderRadius: 999,
    background: "rgba(255,255,255,0.06)",
    border: "1px solid rgba(255,255,255,0.1)",
    color: "rgba(255,255,255,0.6)",
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: 0.3,
  },
  metaLine: {
    display: "flex",
    gap: 14,
    flexWrap: "wrap",
    color: "rgba(170,170,170,0.9)",
    fontSize: 13,
    fontWeight: 800,
    textShadow: "0 4px 18px rgba(0,0,0,0.98)",
  },
  feedbackButton: {
    marginTop: 16,
    width: "fit-content",
    minHeight: 38,
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 16,
    paddingRight: 16,
    borderRadius: 999,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(255,255,255,0.16)",
    background: `${redAlpha(0.82)}`,
    color: "var(--text-primary)",
    fontSize: 13,
    fontWeight: 900,
    letterSpacing: 0,
    cursor: "pointer",
    boxShadow: `0 14px 34px ${redAlpha(0.24)}, inset 0 1px 0 rgba(255,255,255,0.12)`,
    backdropFilter: "blur(16px)",
    WebkitBackdropFilter: "blur(16px)",
    transition: "transform var(--motion-fast), background var(--motion-fast), box-shadow var(--motion-fast)",
    WebkitTapHighlightColor: "transparent",
  },
  actions: {
    position: "absolute",
    right: "max(10px, env(safe-area-inset-right))",
    bottom: "calc(90px + env(safe-area-inset-bottom))",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 4,
    paddingTop: 7,
    paddingBottom: 7,
    paddingLeft: 4,
    paddingRight: 4,
    borderRadius: 999,
    background: "var(--glass)",
    border: "1px solid var(--line)",
    boxShadow: "var(--shadow-soft), inset 0 1px 0 rgba(255,255,255,0.08)",
    backdropFilter: "blur(22px) saturate(155%)",
    WebkitBackdropFilter: "blur(22px) saturate(155%)",
    animation: "fadeScale 220ms ease both",
    zIndex: 5,
  },
  actionItem: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 2,
    cursor: "pointer",
    WebkitTapHighlightColor: "transparent",
    userSelect: "none",
    opacity: 0.88,
    transition: "transform var(--motion-fast), opacity var(--motion-fast), filter var(--motion-fast)",
  },
  actionItemLiked: {
    animation: "likePop 340ms ease",
    opacity: 1,
  },
  actionItemSaved: {
    animation: "likePop 340ms ease",
    opacity: 1,
  },
  actionCircle: {
    width: 32,
    height: 32,
    borderRadius: "50%",
    background: "transparent",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "transparent",
    backdropFilter: "none",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 0,
    boxShadow: "none",
    transition: "transform var(--motion-fast), background var(--motion-fast), border-color var(--motion-fast), box-shadow var(--motion-fast)",
  },
  actionCircleLiked: {
    background: "rgba(193, 18, 31, 0.12)",
    borderColor: `${redAlpha(0.32)}`,
    boxShadow: "var(--shadow-glow-red)",
  },
  actionCircleSaved: {
    background: `${goldAlpha(0.12)}`,
    borderColor: `${goldAlpha(0.34)}`,
    boxShadow: `0 0 24px ${goldAlpha(0.22)}`,
  },
  actionIcon: {
    color: "var(--text-primary)",
    fontSize: 0,
    fontWeight: 300,
    lineHeight: 1,
    textShadow: "0 2px 8px rgba(0,0,0,0.9)",
  },
  actionIconLiked: {
    color: "var(--primary-red)",
    transform: "scale(1.08)",
    textShadow: `0 0 22px ${redAlpha(0.75)}, 0 2px 8px rgba(0,0,0,0.9)`,
  },
  actionIconSaved: {
    color: "var(--accent-gold)",
    transform: "scale(1.08)",
    textShadow: `0 0 20px ${goldAlpha(0.45)}, 0 2px 8px rgba(0,0,0,0.9)`,
  },
  actionSvg: {
    width: 20,
    height: 20,
    display: "block",
    color: "currentColor",
    filter: "drop-shadow(0 2px 6px rgba(0,0,0,0.85))",
  },
  backArrowSvg: {
    width: 18,
    height: 18,
    display: "block",
  },
  soundToggleButton: {
    position: "fixed",
    top: "calc(62px + env(safe-area-inset-top))",
    right: "max(14px, env(safe-area-inset-right))",
    zIndex: 92,
    width: 36,
    height: 36,
    borderRadius: "50%",
    border: "1px solid rgba(255,255,255,0.14)",
    background: "rgba(0,0,0,0.5)",
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    backdropFilter: "blur(12px)",
    WebkitBackdropFilter: "blur(12px)",
    transition: "transform var(--motion-fast), background var(--motion-fast)",
    WebkitTapHighlightColor: "transparent",
  },
  soundSvg: {
    width: 20,
    height: 20,
    display: "block",
  },
  actionText: {
    color: "var(--text-primary)",
    fontSize: 10,
    fontWeight: 700,
    textShadow: "0 2px 8px rgba(0,0,0,0.95)",
  },
  muteBtn: {
    position: "absolute",
    top: "calc(64px + env(safe-area-inset-top))",
    right: "max(14px, env(safe-area-inset-right))",
    background: "rgba(0,0,0,0.42)",
    border: "1px solid rgba(255,255,255,0.18)",
    borderRadius: 999,
    minWidth: 52,
    height: 30,
    color: "var(--text-primary)",
    fontSize: 11,
    fontWeight: 900,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    backdropFilter: "blur(8px)",
    WebkitBackdropFilter: "blur(8px)",
  },
  playIndicator: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    zIndex: 10,
    pointerEvents: "none",
    animation: "fadeScale 220ms ease both",
  },
  bottomNav: {
    position: "fixed",
    bottom: "calc(6px + env(safe-area-inset-bottom))",
    left: "50%",
    width: "min(calc(100vw - 28px), 440px)",
    minHeight: 58,
    transform: "translateX(-50%)",
    background: "var(--glass)",
    border: "1px solid var(--line)",
    borderRadius: 24,
    boxShadow: "var(--shadow-soft), inset 0 1px 0 rgba(255,255,255,0.11)",
    backdropFilter: "blur(30px) saturate(165%)",
    WebkitBackdropFilter: "blur(30px) saturate(165%)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 7,
    zIndex: 100,
    paddingTop: 6,
    paddingBottom: 6,
    paddingLeft: 8,
    paddingRight: 8,
  },
  navItem: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 3,
    cursor: "pointer",
    paddingTop: 6,
    paddingBottom: 6,
    paddingLeft: 6,
    paddingRight: 6,
    minWidth: 43,
    minHeight: 44,
    borderRadius: 16,
    color: "rgba(255,255,255,0.62)",
    WebkitTapHighlightColor: "transparent",
    transition: "color var(--motion-fast), transform var(--motion-fast), background var(--motion-fast), opacity var(--motion-fast)",
  },
  navItemActive: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 3,
    cursor: "pointer",
    paddingTop: 6,
    paddingBottom: 6,
    paddingLeft: 8,
    paddingRight: 8,
    minWidth: 48,
    minHeight: 44,
    borderRadius: 16,
    color: "var(--text-primary)",
    background: `${redAlpha(0.14)}`,
    boxShadow: `0 0 20px ${redAlpha(0.24)}, inset 0 0 0 1px ${redAlpha(0.2)}`,
    WebkitTapHighlightColor: "transparent",
    transition: "color var(--motion-fast), transform var(--motion-fast), background var(--motion-fast), box-shadow var(--motion-fast)",
  },
  navIcon: {
    fontSize: 20,
  },
  navSvg: {
    width: 20,
    height: 20,
    display: "block",
    fill: "none",
    stroke: "currentColor",
    strokeWidth: 1.9,
    strokeLinecap: "round",
    strokeLinejoin: "round",
  },
  navSvgActive: {
    width: 20,
    height: 20,
    display: "block",
    fill: "none",
    stroke: "#fff",
    strokeWidth: 2,
    strokeLinecap: "round",
    strokeLinejoin: "round",
    filter: `drop-shadow(0 0 8px ${redAlpha(0.72)})`,
  },
  navIconWrap: {
    position: "relative",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    minWidth: 24,
    minHeight: 24,
    color: "currentColor",
  },
  navBadge: {
    position: "absolute",
    top: -7,
    right: -9,
    minWidth: 16,
    height: 16,
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 4,
    paddingRight: 4,
    borderRadius: 8,
    background: "var(--primary-red)",
    color: "var(--text-primary)",
    border: "1px solid rgba(0,0,0,0.9)",
    fontSize: 10,
    fontWeight: 700,
    lineHeight: "14px",
    textAlign: "center",
  },
  navIconActive: {
    fontSize: 21,
  },
  navLabel: {
    color: "currentColor",
    fontSize: 8,
    fontWeight: 700,
    letterSpacing: 0,
  },
  navLabelActive: {
    color: "var(--text-primary)",
    fontSize: 8,
    fontWeight: 800,
    letterSpacing: 0,
    textShadow: `0 0 12px ${redAlpha(0.65)}`,
  },
  navUpload: {
    width: 42,
    height: 42,
    background: `${redAlpha(0.82)}`,
    border: "1px solid rgba(255,255,255,0.14)",
    borderRadius: 16,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    boxShadow: `0 8px 22px ${redAlpha(0.24)}`,
    WebkitTapHighlightColor: "transparent",
    transition: "transform 180ms ease, box-shadow 180ms ease, background 180ms ease",
  },
  navUploadIcon: {
    color: "var(--text-primary)",
    fontSize: 22,
    fontWeight: 300,
  },
  navUploadSvg: {
    width: 21,
    height: 21,
    display: "block",
    fill: "none",
    stroke: "#fff",
    strokeWidth: 2,
    strokeLinecap: "round",
    strokeLinejoin: "round",
    filter: "drop-shadow(0 2px 8px rgba(0,0,0,0.35))",
  },
  // Comments Modal Styles
  commentsModal: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1000,
    display: "flex",
    alignItems: "flex-end",
  },
  commentsOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: "rgba(0,0,0,0.62)",
    backdropFilter: "blur(4px)",
    WebkitBackdropFilter: "blur(4px)",
  },
  commentsContent: {
    background: "linear-gradient(180deg, #0f0f0f 0%, #0a0a0a 100%)",
    borderRadius: "22px 22px 0 0",
    width: "100%",
    maxHeight: "78vh",
    display: "flex",
    flexDirection: "column",
    position: "relative",
    zIndex: 1001,
    borderTop: "1px solid rgba(255,255,255,0.07)",
    boxShadow: "0 -24px 70px rgba(0,0,0,0.65)",
  },
  commentsHandle: {
    width: 36,
    height: 4,
    borderRadius: 2,
    background: "rgba(255,255,255,0.18)",
    alignSelf: "center",
    margin: "10px auto 0",
    flexShrink: 0,
  },
  commentsHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    paddingTop: 14,
    paddingBottom: 14,
    paddingLeft: 20,
    paddingRight: 20,
    borderBottom: "1px solid rgba(255,255,255,0.055)",
  },
  commentsTitle: {
    color: "rgba(255,255,255,0.85)",
    fontSize: 14,
    fontWeight: 800,
    margin: 0,
    letterSpacing: 0.3,
    textTransform: "uppercase",
  },
  commentsClose: {
    background: "rgba(255,255,255,0.07)",
    border: "1px solid rgba(255,255,255,0.1)",
    borderRadius: "50%",
    width: 30,
    height: 30,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "rgba(255,255,255,0.65)",
    cursor: "pointer",
    padding: 0,
  },
  commentsList: {
    flex: 1,
    overflowY: "auto",
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 20,
    paddingRight: 20,
    maxHeight: "min(460px, 54vh)",
  },
  noComments: {
    textAlign: "center",
    color: "#AAAAAA",
    paddingTop: 40,
    paddingBottom: 40,
    paddingLeft: 20,
    paddingRight: 20,
    fontSize: 14,
    lineHeight: 1.5,
  },
  commentItem: {
    display: "flex",
    gap: 12,
    paddingTop: 16,
    paddingBottom: 16,
    paddingLeft: 0,
    paddingRight: 0,
    borderBottom: "1px solid rgba(255,255,255,0.07)",
  },
  commentAvatar: {
    width: 38,
    height: 38,
    borderRadius: "50%",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: `${goldAlpha(0.32)}`,
    background: "linear-gradient(145deg, #C1121F, #520711)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "var(--text-primary)",
    fontSize: 14,
    fontWeight: 950,
    flexShrink: 0,
    overflow: "hidden",
    cursor: "pointer",
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
  },
  commentAvatarImage: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    display: "block",
  },
  commentContent: {
    flex: 1,
  },
  commentUsername: {
    border: "none",
    background: "transparent",
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    color: "var(--text-primary)",
    fontSize: 14,
    fontWeight: 900,
    marginBottom: 4,
    cursor: "pointer",
    textAlign: "left",
  },
  commentText: {
    color: "#ccc",
    fontSize: 14,
    lineHeight: 1.4,
  },
  replyItem: {
    display: "flex",
    gap: 10,
    paddingTop: 8,
    paddingBottom: 8,
    paddingLeft: 16,
    paddingRight: 0,
    borderLeft: `2px solid ${goldAlpha(0.18)}`,
    marginLeft: 12,
  },
  replyAvatar: {
    width: 28,
    height: 28,
    borderRadius: "50%",
    border: "1px solid rgba(255,255,255,0.15)",
    background: "rgba(255,255,255,0.08)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "#fff",
    fontSize: 11,
    fontWeight: 900,
    flexShrink: 0,
    overflow: "hidden",
    cursor: "pointer",
    padding: 0,
  },
  replyBtn: {
    marginTop: 4,
    background: "none",
    border: "none",
    color: "rgba(255,255,255,0.45)",
    fontSize: 11,
    fontWeight: 700,
    cursor: "pointer",
    padding: 0,
  },
  repliesSection: {
    marginLeft: 50,
    marginBottom: 4,
  },
  toggleReplies: {
    background: "none",
    border: "none",
    color: GOLD,
    fontSize: 11,
    fontWeight: 700,
    cursor: "pointer",
    padding: "4px 0 8px",
    display: "block",
  },
  commentInput: {
    display: "flex",
    flexDirection: "column",
    paddingTop: 12,
    paddingBottom: 20,
    paddingLeft: 20,
    paddingRight: 20,
    borderTop: `1px solid ${goldAlpha(0.16)}`,
    gap: 8,
  },
  commentInputRow: {
    display: "flex",
    gap: 10,
    alignItems: "center",
  },
  replyPill: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "5px 10px",
    borderRadius: 999,
    background: `${goldAlpha(0.1)}`,
    border: `1px solid ${goldAlpha(0.25)}`,
    alignSelf: "flex-start",
  },
  replyPillText: {
    fontSize: 12,
    color: GOLD,
    fontWeight: 700,
  },
  replyPillClose: {
    background: "none",
    border: "none",
    color: GOLD,
    fontSize: 11,
    cursor: "pointer",
    padding: 0,
    lineHeight: 1,
  },
  commentInputField: {
    flex: 1,
    paddingTop: 11,
    paddingBottom: 11,
    paddingLeft: 14,
    paddingRight: 14,
    borderRadius: 999,
    border: "1px solid rgba(255,255,255,0.09)",
    background: "rgba(255,255,255,0.06)",
    color: "var(--text-primary)",
    fontSize: 14,
    outline: "none",
  },
  commentSendBtn: {
    paddingTop: 11,
    paddingBottom: 11,
    paddingLeft: 18,
    paddingRight: 18,
    borderRadius: 999,
    border: "none",
    background: RED,
    color: "#fff",
    fontSize: 13,
    fontWeight: 800,
    cursor: "pointer",
    boxShadow: `0 4px 14px ${redAlpha(0.35)}`,
  },
  commentSendBtnDisabled: {
    background: "#333",
    cursor: "not-allowed",
  },
  feedbackModal: {
    position: "fixed",
    inset: 0,
    zIndex: 1200,
    display: "flex",
    alignItems: "flex-end",
  },
  feedbackOverlay: {
    position: "absolute",
    inset: 0,
    background: "rgba(0,0,0,0.62)",
    backdropFilter: "blur(4px)",
    WebkitBackdropFilter: "blur(4px)",
  },
  feedbackSheet: {
    position: "relative",
    zIndex: 1201,
    width: "100%",
    maxHeight: "76vh",
    overflow: "hidden",
    borderRadius: "26px 26px 0 0",
    borderTop: "1px solid rgba(255,255,255,0.12)",
    background: `linear-gradient(145deg, ${redAlpha(0.14)}, rgba(11,11,11,0.98) 36%, ${goldAlpha(0.07)})`,
    boxShadow: "0 -24px 80px rgba(0,0,0,0.58)",
    color: "var(--text-primary)",
  },
  feedbackHandle: {
    width: 42,
    height: 4,
    borderRadius: 999,
    background: "rgba(255,255,255,0.24)",
    margin: "10px auto 2px",
  },
  feedbackHeader: {
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "space-between",
    gap: 16,
    paddingTop: 18,
    paddingRight: 20,
    paddingBottom: 14,
    paddingLeft: 20,
    borderBottom: "1px solid rgba(255,255,255,0.08)",
  },
  feedbackKicker: {
    margin: 0,
    color: "var(--accent-gold)",
    fontSize: 11,
    fontWeight: 950,
    letterSpacing: 1.8,
    textTransform: "uppercase",
  },
  feedbackTitle: {
    margin: "5px 0 0",
    color: "var(--text-primary)",
    fontSize: 24,
    lineHeight: 1,
    fontWeight: 1000,
    letterSpacing: 0,
  },
  feedbackSubtitle: {
    margin: "8px 0 0",
    color: "var(--text-secondary)",
    fontSize: 13,
    fontWeight: 750,
  },
  feedbackClose: {
    width: 34,
    height: 34,
    borderRadius: "50%",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(255,255,255,0.2)",
    background: "rgba(255,255,255,0.08)",
    color: "#fff",
    fontSize: 18,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    lineHeight: 1,
  },
  feedbackBody: {
    maxHeight: "calc(76vh - 112px)",
    overflowY: "auto",
    paddingTop: 18,
    paddingRight: 20,
    paddingBottom: "calc(24px + env(safe-area-inset-bottom))",
    paddingLeft: 20,
  },
  feedbackLoading: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    color: "var(--text-secondary)",
    fontSize: 14,
    fontWeight: 750,
  },
  feedbackSpinner: {
    width: 22,
    height: 22,
    borderRadius: "50%",
    borderTop: "2px solid var(--primary-red)",
    borderRight: "2px solid rgba(255,255,255,0.18)",
    borderBottom: "2px solid rgba(255,255,255,0.18)",
    borderLeft: "2px solid rgba(255,255,255,0.18)",
    animation: "spin 1s linear infinite",
  },
  feedbackError: {
    color: "#ff8b8b",
    background: `${redAlpha(0.12)}`,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: `${redAlpha(0.26)}`,
    borderRadius: 14,
    paddingTop: 14,
    paddingBottom: 14,
    paddingLeft: 14,
    paddingRight: 14,
    fontSize: 14,
    lineHeight: 1.5,
  },
  feedbackSaved: {
    marginBottom: 14,
    color: "var(--accent-gold)",
    background: `${goldAlpha(0.1)}`,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: `${goldAlpha(0.22)}`,
    borderRadius: 14,
    paddingTop: 11,
    paddingBottom: 11,
    paddingLeft: 13,
    paddingRight: 13,
    fontSize: 13,
    fontWeight: 900,
  },
  feedbackResult: {
    margin: 0,
    whiteSpace: "pre-wrap",
    color: "var(--text-primary)",
    fontFamily: "inherit",
    fontSize: 14,
    lineHeight: 1.62,
  },
  xpCard: {
    marginBottom: 16,
    padding: "14px 15px",
    borderRadius: 16,
    background: `${goldAlpha(0.07)}`,
    border: `1px solid ${goldAlpha(0.2)}`,
    animation: "fadeUp 280ms ease forwards",
  },
  xpCardTitle: {
    margin: "0 0 10px",
    fontSize: 9,
    fontWeight: 900,
    color: GOLD,
    letterSpacing: 2.5,
    textTransform: "uppercase",
  },
  xpCardRows: {
    display: "grid",
    gap: 5,
    marginBottom: 12,
  },
  xpCardRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  xpCardRowTotal: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    borderTop: "1px solid rgba(255,255,255,0.08)",
    marginTop: 5,
    paddingTop: 7,
  },
  xpCardLabel: {
    fontSize: 12,
    color: "#888",
    fontWeight: 600,
  },
  xpCardVal: {
    fontSize: 13,
    fontWeight: 900,
    color: "#ccc",
  },
  xpCardTotalLabel: {
    fontSize: 12,
    fontWeight: 900,
    color: "#fff",
  },
  xpCardTotalVal: {
    fontSize: 18,
    fontWeight: 1000,
    color: GOLD,
  },
  xpCapNotice: {
    margin: "5px 0 0",
    fontSize: 10,
    color: "#FB923C",
    fontWeight: 700,
  },
  xpRankWrap: {
    borderTop: "1px solid rgba(255,255,255,0.08)",
    paddingTop: 11,
  },
  xpRankRow: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 6,
  },
  xpTotalLabel: {
    fontSize: 11,
    color: "#888",
    fontWeight: 700,
  },
  xpRankTrack: {
    height: 5,
    borderRadius: 999,
    background: "rgba(255,255,255,0.08)",
    overflow: "hidden",
    marginBottom: 5,
  },
  xpRankFill: {
    height: "100%",
    borderRadius: 999,
    transition: "width 700ms ease",
  },
  xpNextLabel: {
    margin: 0,
    fontSize: 10,
    color: "#888",
    textAlign: "right",
  },
  // AI Metrics Overlay
  metricsOverlay: {
    position: "absolute",
    top: "calc(124px + env(safe-area-inset-top))",
    left: "max(18px, env(safe-area-inset-left))",
    right: "calc(96px + env(safe-area-inset-right))",
    zIndex: 4,
    animation: "fadeUp 420ms ease both",
    pointerEvents: "none",
  },
  metricsRow: {
    width: "fit-content",
    maxWidth: "min(300px, calc(100vw - 132px))",
    display: "grid",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
    gap: 8,
    padding: 10,
    borderRadius: 18,
    background: "linear-gradient(145deg, rgba(8,8,8,0.62), rgba(22,18,16,0.42))",
    border: "1px solid rgba(255,255,255,0.14)",
    backdropFilter: "blur(18px) saturate(150%)",
    WebkitBackdropFilter: "blur(18px) saturate(150%)",
    boxShadow: "0 18px 46px rgba(0,0,0,0.35), inset 0 1px 0 rgba(255,255,255,0.12)",
  },
  metricItem: {
    minWidth: 0,
    display: "grid",
    gap: 5,
    minHeight: 48,
    padding: "8px 10px",
    borderRadius: 13,
    background: "rgba(255,255,255,0.075)",
    border: "1px solid rgba(255,255,255,0.08)",
  },
  metricLabel: {
    fontSize: 10,
    fontWeight: 900,
    color: "rgba(255,255,255,0.62)",
    letterSpacing: 0,
    textShadow: "0 1px 4px rgba(0,0,0,0.8)",
    textTransform: "uppercase",
    whiteSpace: "nowrap",
  },
  metricValue: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontSize: 15,
    lineHeight: 1.05,
    fontWeight: 1000,
    color: "var(--text-primary)",
    textShadow: "0 2px 8px rgba(0,0,0,0.9)",
  },
  // Creator Info and Stats
  creatorInfo: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  creatorStats: {
    fontSize: 12,
    lineHeight: 1.25,
    fontWeight: 800,
    color: "rgba(255,255,255,0.74)",
    textShadow: "0 2px 8px rgba(0,0,0,0.9)",
  },
  metricsChips: {
    display: "flex",
    flexWrap: "wrap",
    gap: 5,
    marginBottom: 8,
  },
  metricChip: {
    display: "inline-flex",
    alignItems: "center",
    height: 20,
    paddingLeft: 8,
    paddingRight: 8,
    borderRadius: 999,
    background: "rgba(0,0,0,0.55)",
    border: "1px solid rgba(255,255,255,0.18)",
    backdropFilter: "blur(10px)",
    WebkitBackdropFilter: "blur(10px)",
    color: "rgba(255,255,255,0.88)",
    fontSize: 11,
    fontWeight: 800,
    letterSpacing: 0,
    whiteSpace: "nowrap",
    textShadow: "0 1px 4px rgba(0,0,0,0.8)",
  },
  reelBadgeRow: {
    display: "flex",
    gap: 6,
    flexWrap: "wrap",
    marginTop: 6,
  },
  reelBadge: {
    fontSize: 10,
    fontWeight: 900,
    borderRadius: 999,
    border: "1px solid",
    padding: "3px 8px",
    letterSpacing: 0.4,
  },
  reelCategoryBadge: {
    fontSize: 10,
    fontWeight: 900,
    borderRadius: 999,
    border: "1px solid rgba(255,255,255,0.18)",
    padding: "3px 8px",
    color: "rgba(255,255,255,0.6)",
    background: "rgba(255,255,255,0.07)",
    letterSpacing: 0.4,
  },
  trainButtonRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 8,
  },
  tryThisButton: {
    width: "fit-content",
    maxWidth: "100%",
    minHeight: 26,
    marginTop: 0,
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 10,
    paddingRight: 10,
    borderRadius: 999,
    border: `1px solid ${redAlpha(0.4)}`,
    background: "rgba(0,0,0,0.38)",
    color: "rgba(255,100,100,0.88)",
    fontFamily: "inherit",
    fontSize: 10,
    lineHeight: 1,
    fontWeight: 900,
    letterSpacing: 0.5,
    cursor: "pointer",
    backdropFilter: "blur(10px)",
    WebkitBackdropFilter: "blur(10px)",
    boxShadow: "none",
    textShadow: "none",
    transition: "transform 180ms ease, background 180ms ease",
    WebkitTapHighlightColor: "transparent",
  },
  beatScoreButton: {
    width: "fit-content",
    maxWidth: "100%",
    minHeight: 34,
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 14,
    paddingRight: 14,
    borderRadius: 999,
    border: "1px solid rgba(96,165,250,0.45)",
    background: "rgba(96,165,250,0.12)",
    color: "#93C5FD",
    fontFamily: "inherit",
    fontSize: 13,
    lineHeight: 1,
    fontWeight: 950,
    letterSpacing: 0,
    cursor: "pointer",
    WebkitTapHighlightColor: "transparent",
  },
  learnButton: {
    width: "fit-content",
    maxWidth: "100%",
    minHeight: 34,
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 14,
    paddingRight: 14,
    borderRadius: 999,
    border: `1px solid ${goldAlpha(0.42)}`,
    background: `${goldAlpha(0.12)}`,
    color: GOLD,
    fontFamily: "inherit",
    fontSize: 13,
    lineHeight: 1,
    fontWeight: 950,
    letterSpacing: 0,
    cursor: "pointer",
    WebkitTapHighlightColor: "transparent",
  },
  remixBanner: {
    fontSize: 11,
    color: PURPLE,
    marginTop: 4,
    opacity: 0.85,
  },
  gymTagBanner: {
    fontSize: 11,
    color: GOLD,
    marginTop: 4,
    opacity: 0.9,
  },
  pvpSourceBanner: {
    position: "absolute",
    top: "calc(68px + env(safe-area-inset-top))",
    left: "max(12px, env(safe-area-inset-left))",
    zIndex: 6,
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    padding: "6px 12px",
    borderRadius: 999,
    background: "rgba(96,165,250,0.18)",
    border: "1px solid rgba(96,165,250,0.4)",
    backdropFilter: "blur(12px)",
    WebkitBackdropFilter: "blur(12px)",
  },
  pvpSourceIcon: {
    fontSize: 14,
    lineHeight: 1,
  },
  pvpSourceText: {
    color: "#93C5FD",
    fontSize: 11,
    fontWeight: 900,
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  profileProgressCard: {
    position: "absolute",
    top: "calc(68px + env(safe-area-inset-top))",
    left: "max(12px, env(safe-area-inset-left))",
    zIndex: 6,
    borderRadius: 14,
    background: "rgba(0,0,0,0.58)",
    border: "1px solid rgba(255,255,255,0.12)",
    backdropFilter: "blur(14px) saturate(140%)",
    WebkitBackdropFilter: "blur(14px) saturate(140%)",
    padding: "8px 12px",
    display: "grid",
    gap: 6,
    minWidth: 160,
    maxWidth: 210,
    pointerEvents: "none",
  },
  profileProgressTitle: {
    color: GOLD,
    fontSize: 9,
    fontWeight: 900,
    letterSpacing: 1.4,
    textTransform: "uppercase",
  },
  profileProgressEmpty: {
    color: "rgba(255,255,255,0.55)",
    fontSize: 11,
    fontWeight: 700,
    lineHeight: 1.3,
  },
  profileProgressStats: {
    display: "flex",
    alignItems: "center",
    gap: 8,
  },
  profileProgressStat: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 1,
  },
  profileProgressStatVal: {
    color: "#fff",
    fontSize: 17,
    fontWeight: 1000,
    lineHeight: 1,
  },
  profileProgressStatLbl: {
    color: "rgba(255,255,255,0.55)",
    fontSize: 8,
    fontWeight: 700,
    letterSpacing: 0.6,
    textTransform: "uppercase",
  },
  profileProgressDivider: {
    width: 1,
    height: 24,
    background: "rgba(255,255,255,0.14)",
    flexShrink: 0,
  },
};

export default styles;
