import { RED, RED_DARK, BG, GOLD, SURFACE_1, BORDER, BORDER_2, RADIUS, MOTION, redAlpha, goldAlpha, whiteAlpha, blackAlpha } from "@/lib/tokens";

export const reelVideoStyles = {
  container: {
    position: "relative",
    width: "100vw",
    height: "100dvh",
    minHeight: "100dvh",
    background: "#000",
    overflow: "hidden",
  },
  loading: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 16,
    height: "100dvh",
    color: "#fff",
    fontSize: 16,
  },
  loadingCinematic: {
    position: "relative",
    width: "100vw",
    height: "100dvh",
    background: `radial-gradient(ellipse 70% 50% at 50% 20%, ${redAlpha(0.15)} 0%, transparent 60%), linear-gradient(180deg, #060608 0%, #09090B 100%)`,
    overflow: "hidden",
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "center",
    paddingBottom: 120,
  },
  loadingOrb: {
    position: "absolute",
    width: 500,
    height: 500,
    top: "-100px",
    left: "50%",
    transform: "translateX(-50%)",
    background: redAlpha(0.10),
    borderRadius: "50%",
    filter: "blur(80px)",
    pointerEvents: "none",
    animation: "ambient-pulse 5s ease-in-out infinite",
  },
  skeletonBack: {
    position: "absolute",
    top: 0,
    left: "50%",
    transform: "translateX(-50%) scale(0.88) translateY(10px)",
    width: "min(100vw, 440px)",
    height: "100dvh",
    borderRadius: 24,
    background: whiteAlpha(0.025),
    transformOrigin: "top center",
  },
  skeletonMid: {
    position: "absolute",
    top: 0,
    left: "50%",
    transform: "translateX(-50%) scale(0.94) translateY(5px)",
    width: "min(100vw, 440px)",
    height: "100dvh",
    borderRadius: 20,
    background: whiteAlpha(0.04),
    transformOrigin: "top center",
  },
  skeletonFront: {
    position: "absolute",
    top: 0,
    left: "50%",
    transform: "translateX(-50%)",
    width: "min(100vw, 440px)",
    height: "100dvh",
    borderRadius: 16,
    background: whiteAlpha(0.055),
    transformOrigin: "top center",
  },
  loadingStatus: {
    position: "relative",
    zIndex: 2,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 10,
  },
  loadingTitle: {
    color: "#fff",
    fontSize: 15,
    fontWeight: 900,
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  loadingMeta: {
    color: whiteAlpha(0.55),
    fontSize: 12,
    fontWeight: 650,
    marginTop: -4,
    letterSpacing: 0.5,
  },
  spinner: {
    width: 36,
    height: 36,
    borderTop: `3px solid ${RED}`,
    borderRight: `3px solid ${whiteAlpha(0.15)}`,
    borderBottom: `3px solid ${whiteAlpha(0.15)}`,
    borderLeft: `3px solid ${whiteAlpha(0.15)}`,
    borderRadius: "50%",
    animation: "spin 1s linear infinite",
    boxShadow: `0 0 16px ${redAlpha(0.4)}`,
  },
  empty: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    height: "100dvh",
    color: "#fff",
    gap: 16,
  },
  uploadBtn: {
    background: `linear-gradient(145deg, ${RED}, ${RED_DARK})`,
    color: "#fff",
    border: "none",
    borderRadius: RADIUS.sm,
    paddingTop: 13,
    paddingBottom: 13,
    paddingLeft: 28,
    paddingRight: 28,
    fontSize: 13,
    fontWeight: 900,
    letterSpacing: 0.8,
    cursor: "pointer",
    boxShadow: `0 8px 24px ${redAlpha(0.32)}, inset 0 1px 0 ${whiteAlpha(0.1)}`,
  },

  // ── Arena empty state ────────────────────────────────────────────────────
  arenaEmpty: {
    position: "relative",
    width: "100vw",
    height: "100dvh",
    background: `radial-gradient(ellipse 65% 45% at 50% 16%, ${redAlpha(0.22)} 0%, transparent 68%), #000`,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "flex-end",
    paddingBottom: "calc(120px + env(safe-area-inset-bottom))",
    overflow: "hidden",
  },
  arenaOrb: {
    position: "absolute",
    width: 360,
    height: 360,
    top: "2%",
    left: "50%",
    transform: "translateX(-50%)",
    borderRadius: "50%",
    background: redAlpha(0.09),
    filter: "blur(90px)",
    animation: "ambient-pulse 6s ease-in-out infinite",
    pointerEvents: "none",
  },
  arenaFigure: {
    position: "absolute",
    top: "7%",
    left: "50%",
    transform: "translateX(-50%)",
    width: 200,
    height: 260,
  },
  arenaFigHead: {
    position: "absolute",
    top: 0,
    left: "50%",
    transform: "translateX(-50%)",
    width: 52,
    height: 52,
    borderRadius: "50%",
    background: whiteAlpha(0.04),
    border: `1px solid ${BORDER}`,
  },
  arenaFigTorso: {
    position: "absolute",
    top: 60,
    left: "50%",
    transform: "translateX(-50%)",
    width: 80,
    height: 132,
    borderRadius: "36px 36px 18px 18px",
    background: `linear-gradient(160deg, ${redAlpha(0.1)}, transparent 70%)`,
    border: `1px solid ${whiteAlpha(0.045)}`,
  },
  arenaFigGloveL: {
    position: "absolute",
    top: 80,
    left: 12,
    width: 58,
    height: 44,
    borderRadius: "24px 28px 22px 22px",
    background: `linear-gradient(135deg, ${redAlpha(0.45)}, ${redAlpha(0.18)})`,
    border: `1px solid ${redAlpha(0.25)}`,
    transform: "rotate(-10deg)",
  },
  arenaFigGloveR: {
    position: "absolute",
    top: 74,
    right: 12,
    width: 56,
    height: 42,
    borderRadius: "28px 24px 22px 22px",
    background: whiteAlpha(0.03),
    border: `1px solid ${BORDER}`,
    transform: "rotate(8deg)",
  },
  arenaCopy: {
    position: "relative",
    zIndex: 2,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 10,
    textAlign: "center",
    paddingLeft: 28,
    paddingRight: 28,
  },
  arenaKicker: {
    fontSize: 9,
    fontWeight: 900,
    letterSpacing: 3.5,
    textTransform: "uppercase",
    color: RED,
    opacity: 0.72,
  },
  arenaHeadline: {
    margin: 0,
    fontSize: 50,
    fontWeight: 950,
    color: "#fff",
    lineHeight: 0.96,
    textTransform: "uppercase",
    whiteSpace: "pre-line",
    letterSpacing: -0.5,
    textShadow: "0 8px 40px rgba(0,0,0,0.8)",
  },
  arenaDesc: {
    margin: 0,
    fontSize: 13,
    color: whiteAlpha(0.33),
    lineHeight: 1.55,
    maxWidth: 254,
  },
  arenaUploadBtn: {
    marginTop: 8,
    padding: "15px 30px",
    borderRadius: RADIUS.sm,
    border: "none",
    background: `linear-gradient(145deg, ${RED}, ${RED_DARK})`,
    color: "#fff",
    fontSize: 12,
    fontWeight: 900,
    letterSpacing: 1.2,
    cursor: "pointer",
    boxShadow: `0 8px 28px ${redAlpha(0.38)}, inset 0 1px 0 ${whiteAlpha(0.12)}`,
  },
  header: { display: "none" },
  headerTabs: { display: "flex", gap: 24 },
  headerTab: {
    color: whiteAlpha(0.6),
    fontSize: 17,
    fontWeight: 600,
    cursor: "pointer",
  },
  headerTabActive: {
    color: "#fff",
    fontSize: 17,
    fontWeight: 700,
    borderBottom: `2px solid ${RED}`,
    paddingBottom: 4,
  },
  profileBackButton: {
    position: "fixed",
    top: "calc(16px + env(safe-area-inset-top))",
    left: "max(14px, env(safe-area-inset-left))",
    zIndex: 90,
    height: 38,
    paddingTop: 0,
    paddingRight: 13,
    paddingBottom: 0,
    paddingLeft: 10,
    borderRadius: RADIUS.full,
    border: `1px solid ${BORDER_2}`,
    background: blackAlpha(0.5),
    color: "#fff",
    display: "inline-flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12,
    fontWeight: 900,
    letterSpacing: 0.4,
    cursor: "pointer",
    backdropFilter: "blur(16px)",
    WebkitBackdropFilter: "blur(16px)",
  },
  feedTabs: {
    position: "fixed",
    top: "calc(14px + env(safe-area-inset-top))",
    left: "50%",
    transform: "translateX(-50%)",
    zIndex: 110,
    display: "flex",
    alignItems: "center",
    gap: 4,
    paddingTop: 4,
    paddingBottom: 4,
    paddingLeft: 4,
    paddingRight: 4,
    borderRadius: RADIUS.full,
    background: blackAlpha(0.55),
    border: `1px solid ${BORDER_2}`,
    backdropFilter: "blur(28px) saturate(180%)",
    WebkitBackdropFilter: "blur(28px) saturate(180%)",
    boxShadow: `0 4px 24px rgba(0,0,0,0.5), inset 0 1px 0 ${whiteAlpha(0.07)}`,
    maxWidth: "calc(100vw - 24px)",
    overflowX: "auto",
    scrollbarWidth: "none",
  },
  feedTab: {
    border: "none",
    borderRadius: RADIUS.full,
    background: "transparent",
    color: whiteAlpha(0.42),
    minHeight: 32,
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 13,
    paddingRight: 13,
    fontSize: 11,
    fontWeight: 900,
    letterSpacing: 0.5,
    cursor: "pointer",
    WebkitTapHighlightColor: "transparent",
    flexShrink: 0,
    whiteSpace: "nowrap",
  },
  feedTabActive: {
    background: RED,
    color: "#FFFFFF",
    boxShadow: `0 2px 12px ${redAlpha(0.28)}`,
  },
  feed: {
    height: "100dvh",
    overflowY: "scroll",
    scrollSnapType: "y mandatory",
    scrollBehavior: "auto",
    overscrollBehaviorY: "contain",
    WebkitOverflowScrolling: "touch",
  },
  videoContainer: {
    position: "relative",
    width: "100vw",
    height: "100dvh",
    flexShrink: 0,
    overflow: "hidden",
    scrollSnapAlign: "start",
    scrollSnapStop: "always",
    animation: "reelEnter 280ms cubic-bezier(0.16, 1, 0.3, 1) both",
  },
  activeVideo: { zIndex: 1 },
  activeAmbient: {
    position: "absolute",
    top: "10%",
    left: "50%",
    transform: "translateX(-50%)",
    width: "70%",
    height: "40%",
    borderRadius: "50%",
    background: `radial-gradient(circle, ${redAlpha(0.12)} 0%, transparent 70%)`,
    filter: "blur(40px)",
    pointerEvents: "none",
    zIndex: 1,
    animation: "ambientReelPulse 4s ease-in-out infinite",
  },
  nextReelHint: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 3,
    background: `linear-gradient(to right, transparent 0%, ${whiteAlpha(0.12)} 50%, transparent 100%)`,
    pointerEvents: "none",
    zIndex: 25,
    animation: "nextHintPulse 2s ease-in-out infinite",
  },
  followingEmpty: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    paddingLeft: 32,
    paddingRight: 32,
    textAlign: "center",
    background: `radial-gradient(ellipse 55% 35% at 50% 22%, ${redAlpha(0.12)} 0%, transparent 65%), #000`,
  },
  followingEmptyTitle: {
    color: "#fff",
    fontSize: 28,
    fontWeight: 950,
    letterSpacing: -0.3,
    textTransform: "uppercase",
    lineHeight: 1.0,
  },
  followingEmptyText: {
    color: whiteAlpha(0.35),
    fontSize: 13,
    lineHeight: 1.5,
    maxWidth: 280,
  },
  videoLoadingOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    display: "flex",
    flexDirection: "column",
    gap: 12,
    alignItems: "center",
    justifyContent: "center",
    background: `radial-gradient(circle at 50% 42%, ${redAlpha(0.16)}, transparent 34%), linear-gradient(180deg, ${blackAlpha(0.82)}, ${blackAlpha(0.94)})`,
    zIndex: 10,
  },
  videoLoadingText: {
    color: whiteAlpha(0.82),
    fontSize: 13,
    fontWeight: 850,
    textShadow: "0 2px 10px rgba(0,0,0,0.5)",
  },
  video: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    background: "#000",
    filter: "contrast(1.06) saturate(1.06)",
    transformOrigin: "center center",
  },
  vignette: {
    position: "absolute",
    inset: 0,
    pointerEvents: "none",
    background: [
      `radial-gradient(ellipse 110% 110% at 50% 50%, transparent 36%, ${blackAlpha(0.28)} 62%, ${blackAlpha(0.72)} 100%)`,
      `linear-gradient(to bottom, ${blackAlpha(0.38)} 0%, transparent 18%)`,
    ].join(", "),
    zIndex: 2,
  },
  topFade: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: "22%",
    pointerEvents: "none",
    background: `linear-gradient(to bottom, ${blackAlpha(0.62)} 0%, ${blackAlpha(0.18)} 55%, transparent 100%)`,
    zIndex: 3,
  },
  demoReel: {
    position: "absolute",
    inset: 0,
    overflow: "hidden",
    background: `radial-gradient(circle at 52% 34%, ${goldAlpha(0.16)}, transparent 28%), radial-gradient(circle at 46% 62%, ${redAlpha(0.2)}, transparent 30%), #0B0B0C`,
  },
  demoVignette: {
    position: "absolute",
    inset: 0,
    background: `radial-gradient(circle at 50% 38%, ${whiteAlpha(0.08)}, transparent 34%), linear-gradient(to bottom, rgba(0,0,0,0.15), #000)`,
  },
  reelFallback: {
    position: "absolute",
    inset: 0,
    overflow: "hidden",
    background: `radial-gradient(circle at 50% 38%, ${redAlpha(0.22)}, transparent 32%), radial-gradient(circle at 58% 56%, ${goldAlpha(0.12)}, transparent 30%), #0B0B0C`,
  },
  reelFallbackLight: {
    position: "absolute",
    inset: 0,
    background: `linear-gradient(135deg, transparent 0%, ${whiteAlpha(0.08)} 42%, transparent 66%)`,
    opacity: 0.5,
  },
  reelFallbackContent: {
    position: "absolute",
    left: "max(24px, env(safe-area-inset-left))",
    right: 96,
    bottom: "calc(170px + env(safe-area-inset-bottom))",
    display: "grid",
    gap: 10,
    zIndex: 1,
  },
  reelFallbackKicker: {
    color: GOLD,
    fontSize: 11,
    fontWeight: 950,
    letterSpacing: 1.8,
  },
  reelFallbackTitle: {
    color: "#fff",
    fontSize: 28,
    lineHeight: 1.05,
    fontWeight: 1000,
    textShadow: "0 4px 18px rgba(0,0,0,0.6)",
  },
  reelFallbackText: {
    color: whiteAlpha(0.68),
    fontSize: 14,
    lineHeight: 1.45,
    maxWidth: 360,
  },
  demoGrid: { display: "none" },
  demoSpotlight: { display: "none" },
  demoBag: { display: "none" },
  demoFighter: { display: "none" },
  demoHead: {
    position: "absolute",
    left: 76,
    top: 0,
    width: 54,
    height: 54,
    borderRadius: "50%",
    background: GOLD,
  },
  demoTorso: {
    position: "absolute",
    left: 58,
    top: 60,
    width: 92,
    height: 148,
    borderRadius: "42px 42px 24px 24px",
    background: "linear-gradient(160deg, #1c1c1c, #530916)",
    border: `1px solid ${BORDER}`,
  },
  demoGloveLead: {
    position: "absolute",
    right: 0,
    top: 76,
    width: 86,
    height: 58,
    borderRadius: "34px 30px 28px 28px",
    background: RED,
    boxShadow: `0 20px 48px ${blackAlpha(0.36)}`,
  },
  demoGloveRear: {
    position: "absolute",
    left: 8,
    top: 86,
    width: 66,
    height: 54,
    borderRadius: "30px",
    background: GOLD,
  },
  demoHook: {
    position: "absolute",
    left: 18,
    right: 92,
    bottom: 132,
    display: "grid",
    gap: 8,
  },
  demoHookKicker: {
    color: GOLD,
    fontSize: 11,
    fontWeight: 900,
    letterSpacing: 1.8,
    textTransform: "uppercase",
  },
  demoHookTitle: {
    color: "#fff",
    fontSize: 34,
    lineHeight: 1,
    fontWeight: 950,
    letterSpacing: 0,
  },
  demoHookText: {
    color: whiteAlpha(0.72),
    fontSize: 14,
    lineHeight: 1.45,
  },
  demoUploadMessage: {
    marginTop: 8,
    color: "#fff",
    fontSize: 15,
    fontWeight: 900,
    textShadow: "0 2px 8px rgba(0,0,0,0.55)",
  },
  demoUploadButton: {
    width: 128,
    minHeight: 42,
    marginTop: 4,
    border: "none",
    borderRadius: RADIUS.sm,
    background: RED,
    color: "#fff",
    fontSize: 15,
    fontWeight: 900,
    cursor: "pointer",
    boxShadow: `0 14px 32px ${blackAlpha(0.34)}`,
  },
  overlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    paddingTop: 20,
    paddingRight: 18,
    paddingBottom: "calc(80px + env(safe-area-inset-bottom))",
    paddingLeft: 18,
    background: `linear-gradient(to top, ${blackAlpha(0.88)} 0%, ${blackAlpha(0.38)} 46%, transparent 78%)`,
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-end",
  },
  bottomGradient: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    height: "68vh",
    pointerEvents: "none",
    background: `linear-gradient(to top, ${blackAlpha(0.97)} 0%, ${blackAlpha(0.82)} 22%, ${blackAlpha(0.48)} 52%, ${blackAlpha(0.12)} 78%, transparent 100%)`,
    zIndex: 2,
  },
  videoProgressBar: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 3,
    background: whiteAlpha(0.08),
    zIndex: 20,
    overflow: "hidden",
  },
  videoProgressFill: {
    height: "100%",
    background: whiteAlpha(0.78),
    transition: "width 0.2s linear",
    borderRadius: "0 2px 2px 0",
    boxShadow: `0 0 6px ${whiteAlpha(0.45)}`,
  },
};
