import { GOLD, BG, SURFACE_1, SURFACE_2, BORDER, BORDER_2, RADIUS, redAlpha, goldAlpha, whiteAlpha, blackAlpha } from "@/lib/tokens";

export const reelSheetStyles = {
  filterSheetOverlay: {
    position: "fixed",
    inset: 0,
    zIndex: 9999,
    background: blackAlpha(0.55),
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "center",
  },
  filterSheet: {
    width: "100%",
    maxWidth: 600,
    background: `linear-gradient(180deg, ${SURFACE_2}, ${BG})`,
    borderRadius: `${RADIUS.lg}px ${RADIUS.lg}px 0 0`,
    padding: "10px 20px calc(32px + env(safe-area-inset-bottom))",
    border: `1px solid ${goldAlpha(0.12)}`,
    boxShadow: `0 -16px 48px ${blackAlpha(0.7)}`,
    display: "flex",
    flexDirection: "column",
  },
  filterSheetHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    background: whiteAlpha(0.18),
    alignSelf: "center",
    marginBottom: 16,
    flexShrink: 0,
  },
  filterSheetHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  filterSheetTitle: {
    fontSize: 10,
    fontWeight: 900,
    color: whiteAlpha(0.4),
    letterSpacing: 2,
  },
  filterSheetClose: {
    background: whiteAlpha(0.08),
    border: "none",
    borderRadius: "50%",
    width: 28,
    height: 28,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: whiteAlpha(0.6),
    fontSize: 12,
    cursor: "pointer",
    padding: 0,
  },
  filterSheetBody: {
    display: "flex",
    flexDirection: "column",
  },
  filterSheetLabel: {
    margin: "0 0 10px",
    fontSize: 10,
    fontWeight: 900,
    color: GOLD,
    letterSpacing: 1.5,
  },
  filterSheetRow: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
  },
  filterChip: {
    padding: "7px 14px",
    borderRadius: RADIUS.full,
    border: `1px solid ${BORDER_2}`,
    background: whiteAlpha(0.06),
    color: whiteAlpha(0.65),
    fontSize: 12,
    fontWeight: 800,
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  filterChipActive: {
    border: `1px solid ${redAlpha(0.6)}`,
    background: redAlpha(0.2),
    color: "#F87171",
  },
  filterClearBtn: {
    marginTop: 20,
    padding: "10px 20px",
    borderRadius: RADIUS.full,
    border: `1px solid ${BORDER_2}`,
    background: whiteAlpha(0.05),
    color: whiteAlpha(0.5),
    fontSize: 12,
    fontWeight: 800,
    cursor: "pointer",
    alignSelf: "flex-start",
  },
  captionSheetOverlay: {
    position: "fixed",
    inset: 0,
    zIndex: 9999,
    background: blackAlpha(0.55),
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "center",
  },
  captionSheet: {
    width: "100%",
    maxWidth: 600,
    maxHeight: "50vh",
    background: SURFACE_1,
    borderRadius: `${RADIUS.lg}px ${RADIUS.lg}px 0 0`,
    padding: "12px 20px 32px",
    display: "flex",
    flexDirection: "column",
    boxShadow: `0 -4px 32px ${blackAlpha(0.7)}`,
  },
  captionSheetHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    background: whiteAlpha(0.22),
    alignSelf: "center",
    marginBottom: 14,
    flexShrink: 0,
  },
  captionSheetHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
    flexShrink: 0,
  },
  captionSheetTitle: {
    color: whiteAlpha(0.55),
    fontSize: 12,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  captionSheetClose: {
    background: whiteAlpha(0.1),
    border: "none",
    borderRadius: "50%",
    width: 28,
    height: 28,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: whiteAlpha(0.7),
    fontSize: 14,
    cursor: "pointer",
    padding: 0,
  },
  captionSheetBody: {
    overflowY: "auto",
    flex: 1,
  },
  captionSheetText: {
    margin: 0,
    color: "#fff",
    fontSize: 15,
    lineHeight: 1.6,
    fontWeight: 400,
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
  },
  captionMetaChip: {
    display: "inline-flex",
    alignItems: "center",
    padding: "5px 11px",
    borderRadius: RADIUS.full,
    background: whiteAlpha(0.06),
    border: `1px solid ${BORDER}`,
    color: whiteAlpha(0.6),
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: 0.3,
  },
};
