import { RED, RED_DARK, GOLD, redAlpha, goldAlpha, RADIUS, blackAlpha } from "@/lib/tokens";

const d = {
  page: {
    display: "flex",
    height: "100dvh",
    overflow: "hidden",
    background: `
      radial-gradient(ellipse 60% 70% at 38% 42%, ${redAlpha(0.05)} 0%, transparent 62%),
      radial-gradient(ellipse 35% 45% at 82% 18%, rgba(255,255,255,0.025) 0%, transparent 55%),
      radial-gradient(ellipse 30% 40% at 88% 88%, ${redAlpha(0.02)} 0%, transparent 55%),
      #0B0B0C
    `,
    color: "#fff",
  },

  // ── Sidebar ──
  sidebar: {
    width: 260,
    flexShrink: 0,
    display: "flex",
    flexDirection: "column",
    padding: "28px 14px 24px",
    borderRight: "1px solid rgba(255,255,255,0.05)",
    background: `
      radial-gradient(ellipse 100% 40% at 50% 0%, ${redAlpha(0.04)} 0%, transparent 60%),
      rgba(11,11,12,0.96)
    `,
    position: "sticky",
    top: 0,
    height: "100dvh",
    overflowY: "auto",
    scrollbarWidth: "none",
  },
  sidebarLogo: {
    display: "flex",
    flexDirection: "column",
    gap: 1,
    marginBottom: 32,
    padding: "0 10px",
  },
  logoGavana: {
    fontFamily: "var(--font-display, 'Anton', sans-serif)",
    fontSize: 24,
    fontWeight: 400,
    letterSpacing: "0.06em",
    color: "#fff",
    lineHeight: 1,
    textShadow: `0 0 28px ${redAlpha(0.6)}, 0 2px 0 rgba(0,0,0,0.5)`,
  },
  logoBoxing: {
    fontSize: 9,
    fontWeight: 900,
    color: RED,
    letterSpacing: "0.32em",
    textTransform: "uppercase",
  },
  sidebarNav: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    flex: 1,
  },
  navBtn: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "10px 12px",
    borderRadius: 12,
    border: "none",
    background: "transparent",
    color: "rgba(255,255,255,0.38)",
    fontSize: 12,
    fontWeight: 800,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    cursor: "pointer",
    textAlign: "left",
    width: "100%",
    position: "relative",
    transition: "background 150ms ease, color 150ms ease",
  },
  navBtnActive: {
    background: `${redAlpha(0.1)}`,
    color: "#fff",
  },
  navIcon: {
    width: 22,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  navLabel: { flex: 1 },
  navChevron: { fontSize: 12, color: "rgba(255,255,255,0.18)", flexShrink: 0 },
  navActiveBar: {
    position: "absolute",
    left: 0,
    top: "22%",
    bottom: "22%",
    width: 3,
    borderRadius: "0 3px 3px 0",
    background: RED,
    boxShadow: `0 0 8px ${redAlpha(0.7)}`,
  },
  createBtn: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    width: "100%",
    padding: "13px",
    borderRadius: 14,
    border: "none",
    background: `linear-gradient(135deg, ${RED}, ${RED_DARK})`,
    color: "#fff",
    fontSize: 12,
    fontWeight: 900,
    letterSpacing: "0.15em",
    textTransform: "uppercase",
    cursor: "pointer",
    marginTop: 10,
    boxShadow: `0 6px 22px ${redAlpha(0.24)}`,
  },
  sidebarProfile: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px",
    borderRadius: 14,
    border: "1px solid rgba(255,255,255,0.07)",
    background: "rgba(255,255,255,0.03)",
    cursor: "pointer",
    marginTop: 14,
    textAlign: "left",
    width: "100%",
  },
  sidebarProfileAva: {
    width: 36,
    height: 36,
    borderRadius: "50%",
    background: RED,
    border: `2px solid ${goldAlpha(0.4)}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    overflow: "hidden",
  },
  sidebarProfileInfo: { flex: 1, minWidth: 0 },
  sidebarProfileName: {
    fontSize: 12,
    fontWeight: 800,
    letterSpacing: "0.04em",
    color: "#fff",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    textTransform: "uppercase",
  },
  sidebarProfileSub: {
    fontSize: 9,
    color: RED,
    fontWeight: 800,
    letterSpacing: "0.18em",
    textTransform: "uppercase",
    marginTop: 1,
  },

  // ── Center ──
  center: {
    flex: 1,
    overflowY: "auto",
    scrollbarWidth: "none",
    minWidth: 0,
  },
  centerInner: {
    maxWidth: 600,
    margin: "0 auto",
    padding: "16px 24px 40px",
  },
  tabs: {
    position: "sticky",
    top: 0,
    zIndex: 30,
    display: "flex",
    gap: 4,
    padding: "14px 0 12px",
    background: "rgba(11,11,12,0.92)",
    backdropFilter: "blur(24px)",
    WebkitBackdropFilter: "blur(24px)",
    marginBottom: 4,
    borderBottom: "1px solid rgba(255,255,255,0.05)",
  },
  tab: {
    padding: "6px 16px",
    borderRadius: RADIUS.full,
    border: "1px solid rgba(255,255,255,0.06)",
    background: "transparent",
    color: "#9CA3AF",
    fontSize: 12,
    fontWeight: 500,
    cursor: "pointer",
    transition: "all 150ms ease",
  },
  tabActive: {
    background: RED,
    border: `1px solid ${RED}`,
    color: "#fff",
  },

  // ── Quick post ──
  quickPost: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "12px 14px",
    borderRadius: 18,
    background: "rgba(255,255,255,0.025)",
    backdropFilter: "blur(18px)",
    WebkitBackdropFilter: "blur(18px)",
    border: "1px solid rgba(255,255,255,0.07)",
    boxShadow: `0 4px 24px ${blackAlpha(0.25)}`,
    marginBottom: 28,
  },
  quickAva: {
    width: 38,
    height: 38,
    borderRadius: "50%",
    background: RED,
    border: `2px solid ${goldAlpha(0.35)}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    overflow: "hidden",
  },
  quickInput: {
    flex: 1,
    padding: "10px 14px",
    borderRadius: 12,
    border: "1px solid rgba(255,255,255,0.07)",
    background: "rgba(255,255,255,0.04)",
    color: "rgba(255,255,255,0.25)",
    fontSize: 11,
    fontWeight: 800,
    letterSpacing: "0.08em",
    cursor: "text",
    textAlign: "left",
    textTransform: "uppercase",
  },
  quickVideoBtn: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "9px 14px",
    borderRadius: 12,
    border: `1px solid ${redAlpha(0.35)}`,
    background: `${redAlpha(0.08)}`,
    color: "#f87171",
    fontSize: 11,
    fontWeight: 900,
    letterSpacing: "0.1em",
    textTransform: "uppercase",
    cursor: "pointer",
    flexShrink: 0,
    whiteSpace: "nowrap",
  },

  // ── Cards feed ──
  cardsFeed: {
    display: "flex",
    flexDirection: "column",
    gap: 20,
  },
  emptyFeed: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    padding: "80px 24px",
    gap: 10,
    borderRadius: 20,
    background: `radial-gradient(ellipse 60% 50% at 50% 40%, ${redAlpha(0.08)} 0%, transparent 70%)`,
    border: "1px solid rgba(255,255,255,0.04)",
  },

  // ── Reel card ──
  reelCard: {
    background: "#141416",
    border: "1px solid rgba(255,255,255,0.06)",
    borderRadius: 20,
    overflow: "hidden",
    boxShadow: `0 2px 12px ${blackAlpha(0.35)}`,
    transition: "border-color 180ms ease, box-shadow 180ms ease",
  },
  reelRow: {
    display: "flex",
    alignItems: "flex-end",
    gap: 10,
    padding: "14px 14px 0",
  },
  reelVideoWrap: {
    flex: 1,
    position: "relative",
    background: "#000",
    borderRadius: 18,
    overflow: "hidden",
    aspectRatio: "9/16",
    maxHeight: 520,
    cursor: "pointer",
  },
  reelVideo: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    display: "block",
  },
  videoOverlay: {
    position: "absolute",
    inset: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: blackAlpha(0.22),
  },
  playCircle: {
    width: 52,
    height: 52,
    borderRadius: "50%",
    background: blackAlpha(0.5),
    backdropFilter: "blur(10px)",
    WebkitBackdropFilter: "blur(10px)",
    border: "1.5px solid rgba(255,255,255,0.2)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "rgba(255,255,255,0.85)",
    paddingLeft: 2,
  },
  muteBtn: {
    position: "absolute",
    bottom: 10,
    right: 10,
    width: 32,
    height: 32,
    borderRadius: "50%",
    background: blackAlpha(0.55),
    backdropFilter: "blur(8px)",
    WebkitBackdropFilter: "blur(8px)",
    border: "1px solid rgba(255,255,255,0.2)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    color: "rgba(255,255,255,0.85)",
    cursor: "pointer",
    zIndex: 4,
  },
  heartBurstWrap: {
    position: "absolute",
    top: "50%",
    left: "50%",
    transform: "translate(-50%, -50%)",
    pointerEvents: "none",
    zIndex: 5,
  },
  progressBarWrap: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 3,
    background: "rgba(255,255,255,0.1)",
  },
  progressFill: {
    height: "100%",
    background: RED,
    transition: "width 200ms linear",
  },

  // ── Round action buttons ──
  reelActions: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 8,
    paddingBottom: 4,
    flexShrink: 0,
  },
  roundBtn: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 3,
    width: 44,
    height: 44,
    borderRadius: "50%",
    border: "1px solid rgba(255,255,255,0.1)",
    background: "rgba(12,12,14,0.8)",
    backdropFilter: "blur(12px)",
    WebkitBackdropFilter: "blur(12px)",
    cursor: "pointer",
    color: "rgba(255,255,255,0.6)",
    transition: "border-color 150ms ease, box-shadow 150ms ease, transform 100ms ease",
  },
  roundBtnLiked: {
    borderColor: "rgba(248,113,113,0.5)",
    background: "rgba(248,113,113,0.1)",
    boxShadow: "0 0 14px rgba(248,113,113,0.3)",
  },
  roundBtnSaved: {
    borderColor: `${goldAlpha(0.5)}`,
    background: `${goldAlpha(0.1)}`,
  },
  roundBtnCount: {
    fontSize: 9,
    fontWeight: 900,
    color: "rgba(255,255,255,0.5)",
    lineHeight: 1,
    letterSpacing: "0.04em",
  },
  aiRoundBtn: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 3,
    width: 44,
    height: 44,
    borderRadius: "50%",
    border: `1px solid ${redAlpha(0.5)}`,
    background: `${redAlpha(0.12)}`,
    backdropFilter: "blur(12px)",
    WebkitBackdropFilter: "blur(12px)",
    color: RED,
    cursor: "pointer",
    boxShadow: `0 0 12px ${redAlpha(0.14)}`,
    transition: "box-shadow 150ms ease, transform 100ms ease",
  },

  // ── Reel info ──
  reelInfo: {
    padding: "14px 16px 16px",
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  creatorBtn: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: 0,
    textAlign: "left",
  },
  creatorAva: {
    width: 32,
    height: 32,
    borderRadius: "50%",
    background: RED,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    overflow: "hidden",
    border: `1.5px solid ${goldAlpha(0.3)}`,
  },
  creatorName: {
    fontSize: 11,
    fontWeight: 900,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    color: "#fff",
  },
  creatorStat: {
    fontSize: 10,
    color: "rgba(255,255,255,0.32)",
    fontWeight: 700,
    letterSpacing: "0.04em",
  },
  caption: {
    margin: 0,
    fontSize: 13,
    color: "rgba(255,255,255,0.58)",
    lineHeight: 1.55,
  },

  // ── Right panel ──
  rightPanel: {
    width: 320,
    flexShrink: 0,
    display: "flex",
    flexDirection: "column",
    gap: 12,
    padding: "20px 14px 20px",
    borderLeft: "1px solid rgba(255,255,255,0.05)",
    background: `
      radial-gradient(ellipse 100% 35% at 50% 100%, ${redAlpha(0.03)} 0%, transparent 60%),
      rgba(11,11,12,0.98)
    `,
    height: "100dvh",
    overflowY: "auto",
    scrollbarWidth: "none",
  },
  searchBar: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 14px",
    borderRadius: 14,
    background: "rgba(255,255,255,0.04)",
    border: "1px solid rgba(255,255,255,0.07)",
  },
  searchInput: {
    flex: 1,
    background: "none",
    border: "none",
    outline: "none",
    color: "rgba(255,255,255,0.32)",
    fontSize: 11,
    fontWeight: 800,
    letterSpacing: "0.12em",
    textTransform: "uppercase",
    cursor: "pointer",
  },
  rightCard: {
    background: "#141416",
    border: "1px solid rgba(255,255,255,0.06)",
    borderRadius: 14,
    overflow: "clip",
  },
  rightCardHeader: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "10px 14px 8px",
    borderBottom: "1px solid rgba(255,255,255,0.05)",
  },
  liveDot: {
    width: 7,
    height: 7,
    borderRadius: "50%",
    flexShrink: 0,
    background: RED,
    boxShadow: `0 0 8px ${RED}`,
  },
  rightCardTitle: {
    flex: 1,
    fontSize: 9,
    fontWeight: 900,
    color: "rgba(255,255,255,0.35)",
    letterSpacing: "0.22em",
    textTransform: "uppercase",
  },
  liveBadge: {
    fontSize: 9,
    fontWeight: 900,
    color: RED,
    letterSpacing: "0.1em",
    background: `${redAlpha(0.12)}`,
    border: `1px solid ${redAlpha(0.3)}`,
    borderRadius: RADIUS.full,
    padding: "2px 8px",
  },
  rightEmpty: {
    margin: "12px 14px",
    padding: "16px 12px",
    border: "1px dashed rgba(255,255,255,0.1)",
    borderRadius: 12,
    fontSize: 10,
    fontWeight: 700,
    letterSpacing: "0.1em",
    color: "rgba(255,255,255,0.28)",
    textAlign: "center",
    textTransform: "uppercase",
    lineHeight: 1.5,
  },
  lobbyList: {
    display: "flex",
    flexDirection: "column",
  },
  lobbyRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 14px",
    borderBottom: "1px solid rgba(255,255,255,0.04)",
    transition: "background 150ms ease",
    cursor: "pointer",
  },
  lobbyActiveDot: {
    width: 7,
    height: 7,
    borderRadius: "50%",
    background: "#34D399",
    boxShadow: "0 0 7px #34D399",
    flexShrink: 0,
  },
  lobbyName: {
    fontSize: 11,
    fontWeight: 900,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "#ddd",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  lobbyMeta: {
    fontSize: 10,
    color: "rgba(255,255,255,0.3)",
    fontWeight: 700,
    marginTop: 2,
    letterSpacing: "0.04em",
  },
  joinBtn: {
    padding: "5px 10px",
    borderRadius: 9,
    border: `1px solid ${redAlpha(0.4)}`,
    background: `${redAlpha(0.1)}`,
    color: RED,
    fontSize: 9,
    fontWeight: 900,
    letterSpacing: "0.1em",
    textTransform: "uppercase",
    cursor: "pointer",
    flexShrink: 0,
    whiteSpace: "nowrap",
    transition: "background 150ms ease, box-shadow 150ms ease",
  },
  viewAllBtn: {
    display: "block",
    width: "100%",
    padding: "10px 14px",
    background: "none",
    border: "none",
    borderTop: "1px solid rgba(255,255,255,0.05)",
    color: "rgba(255,255,255,0.25)",
    fontSize: 10,
    fontWeight: 900,
    letterSpacing: "0.14em",
    textTransform: "uppercase",
    cursor: "pointer",
    textAlign: "center",
    transition: "color 150ms ease",
  },
  requestRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    padding: "10px 14px",
    borderBottom: "1px solid rgba(255,255,255,0.04)",
  },
  requestTo: {
    fontSize: 11,
    fontWeight: 800,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "#ccc",
    flex: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  statusBadge: {
    fontSize: 9,
    fontWeight: 900,
    letterSpacing: "0.08em",
    textTransform: "uppercase",
    borderRadius: 6,
    padding: "3px 8px",
    flexShrink: 0,
    whiteSpace: "nowrap",
  },

  // ── Horizontal scroll card styles ──
  hScroll: {
    display: "flex", gap: 8, padding: "8px 12px 12px",
    overflowX: "auto", scrollbarWidth: "none",
  },
  hCardWide: {
    width: 220, flexShrink: 0, height: 110, borderRadius: 14,
    border: "1px solid rgba(255,255,255,0.07)", padding: "10px 10px 8px",
    display: "flex", flexDirection: "column", justifyContent: "flex-end",
    cursor: "pointer", position: "relative", overflow: "hidden",
    textAlign: "left", transition: "transform 180ms ease",
  },
  hCardBadge: {
    position: "absolute", top: 8, left: 8, fontSize: 8, fontWeight: 900,
    letterSpacing: "0.14em", textTransform: "uppercase",
    border: "1px solid", borderRadius: 5, padding: "2px 6px",
  },
  hCardStat: { fontSize: 9, fontWeight: 700, marginBottom: 2, letterSpacing: "0.02em" },
  hCardName: {
    fontSize: 12, fontWeight: 900, color: "#fff", letterSpacing: "-0.01em",
    lineHeight: 1.1, textTransform: "uppercase", marginBottom: 2,
  },
  hCardSub: { fontSize: 10, color: "rgba(255,255,255,0.45)", fontWeight: 700 },
  hCardLine: { position: "absolute", bottom: 0, left: 0, right: 0, height: 2 },
  sparringCard: {
    width: 130, flexShrink: 0, height: 130, borderRadius: 14,
    background: "linear-gradient(160deg, rgba(255,59,48,0.12) 0%, #0d0507 100%)",
    border: "1px solid rgba(255,59,48,0.18)", padding: "10px 10px 8px",
    display: "flex", flexDirection: "column", cursor: "pointer",
    position: "relative", overflow: "hidden", transition: "transform 180ms ease",
    textAlign: "left",
  },
  sparringCardDot: {
    width: 7, height: 7, borderRadius: "50%", background: "#34D399",
    boxShadow: "0 0 7px #34D399", marginBottom: 6, flexShrink: 0,
  },
  sparringCardWeight: {
    fontSize: 9, fontWeight: 900, letterSpacing: "0.1em", textTransform: "uppercase", marginBottom: 4,
  },
  sparringCardName: {
    fontSize: 11, fontWeight: 900, color: "#fff", letterSpacing: "-0.01em",
    lineHeight: 1.2, flex: 1,
  },
  sparringCardMeta: { fontSize: 9, color: "rgba(255,255,255,0.3)", fontWeight: 700, marginBottom: 2 },
  sparringCardJoin: {
    alignSelf: "flex-start", padding: "3px 9px", borderRadius: 7,
    border: "1px solid rgba(255,59,48,0.4)", background: "rgba(255,59,48,0.1)",
    color: RED, fontSize: 8, fontWeight: 900, letterSpacing: "0.1em", textTransform: "uppercase",
  },

  // ── Coach rows ──
  coachRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 14px",
    borderBottom: "1px solid rgba(255,255,255,0.04)",
    cursor: "pointer",
  },
  coachAva: {
    width: 34,
    height: 34,
    borderRadius: "50%",
    border: "1.5px solid",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  coachName: {
    fontSize: 11,
    fontWeight: 900,
    letterSpacing: "0.06em",
    color: "#ddd",
    textTransform: "uppercase",
  },
  coachMeta: {
    fontSize: 10,
    color: "rgba(255,255,255,0.32)",
    fontWeight: 700,
    marginTop: 2,
    letterSpacing: "0.02em",
  },

  // ── Featured cards ──
  featuredScroll: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 10,
    padding: "12px",
  },
  featuredCard: {
    width: "100%",
    height: 88,
    borderRadius: 14,
    border: "1px solid rgba(255,255,255,0.07)",
    padding: "10px 10px 8px",
    display: "flex",
    flexDirection: "column",
    justifyContent: "flex-end",
    cursor: "pointer",
    position: "relative",
    overflow: "hidden",
    textAlign: "left",
    transition: "transform 180ms ease, box-shadow 180ms ease",
  },
  featuredTopBadge: {
    position: "absolute",
    top: 8,
    left: 8,
    fontSize: 8,
    fontWeight: 900,
    letterSpacing: "0.14em",
    textTransform: "uppercase",
    border: "1px solid",
    borderRadius: 5,
    padding: "2px 6px",
  },
  featuredName: {
    fontSize: 10,
    fontWeight: 900,
    color: "#fff",
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    lineHeight: 1.2,
    marginBottom: 3,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  featuredSub: {
    fontSize: 9,
    color: "rgba(255,255,255,0.38)",
    fontWeight: 700,
    letterSpacing: "0.02em",
  },
  featuredAccentLine: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 2,
    borderRadius: "0 0 14px 14px",
  },

  // ── Skeleton ──
  skeletonRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 14px",
    borderBottom: "1px solid rgba(255,255,255,0.04)",
  },
  skeletonPulse: {
    background: "rgba(255,255,255,0.07)",
    animation: "skeleton-pulse 1.6s ease-in-out infinite",
  },
};

export default d;
