import { redAlpha, goldAlpha } from "@/lib/tokens";

export const reelInfoStyles = {
  info: {
    position: "absolute",
    left: "max(14px, env(safe-area-inset-left))",
    right: 76,
    bottom: "calc(92px + env(safe-area-inset-bottom))",
    maxWidth: 520,
    animation: "pageEnter 380ms cubic-bezier(0.16, 1, 0.3, 1) both",
    zIndex: 4,
  },
  creatorRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginBottom: 10,
  },
  creatorAvatarButton: {
    width: 44,
    height: 44,
    flex: "0 0 44px",
    borderRadius: "50%",
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: `${goldAlpha(0.64)}`,
    background: `linear-gradient(145deg, ${redAlpha(0.9)}, rgba(7,7,7,0.78))`,
    boxShadow: `0 0 0 3px ${redAlpha(0.2)}, 0 10px 26px rgba(0,0,0,0.55)`,
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    overflow: "hidden",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    WebkitTapHighlightColor: "transparent",
  },
  creatorAvatarImage: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    display: "block",
  },
  creatorAvatarFallback: {
    color: "var(--text-primary)",
    fontSize: 17,
    fontWeight: 1000,
    textShadow: "0 2px 10px rgba(0,0,0,0.72)",
  },
  username: {
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 0,
    paddingRight: 0,
    border: "none",
    background: "transparent",
    color: "var(--text-primary)",
    fontFamily: "inherit",
    fontSize: 15,
    fontWeight: 900,
    margin: 0,
    letterSpacing: 0,
    lineHeight: 1.1,
    textAlign: "left",
    textShadow: "0 5px 28px rgba(0,0,0,0.98), 0 1px 2px rgba(0,0,0,1)",
    WebkitTapHighlightColor: "transparent",
    display: "flex",
    alignItems: "center",
    gap: 6,
  },
  onFireBadge: {
    display: "inline-flex",
    alignItems: "center",
    gap: 3,
    fontSize: 11,
    fontWeight: 900,
    letterSpacing: 0.6,
    color: "#FB923C",
    lineHeight: 1,
    flexShrink: 0,
  },
  viewProof: {
    color: "rgba(255,255,255,0.82)",
    fontSize: 13,
    fontWeight: 800,
    marginBottom: 10,
    textShadow: "0 2px 8px rgba(0,0,0,0.95)",
  },
  descriptionLine: {
    display: "block",
    marginBottom: 8,
    padding: 0,
    border: "none",
    background: "transparent",
    textAlign: "left",
    cursor: "pointer",
    color: "var(--text-primary)",
    fontSize: 13,
    lineHeight: 1.35,
    fontWeight: 500,
    maxWidth: 500,
    width: "100%",
    textShadow: "0 4px 22px rgba(0,0,0,0.96), 0 1px 2px rgba(0,0,0,1)",
    letterSpacing: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  metaLine: {
    display: "flex",
    gap: 14,
    flexWrap: "wrap",
    color: "rgba(170,170,170,0.9)",
    fontSize: 13,
    fontWeight: 800,
    textShadow: "0 4px 18px rgba(0,0,0,0.98)",
  },
  feedbackButton: {
    marginTop: 16,
    width: "fit-content",
    minHeight: 38,
    paddingTop: 0,
    paddingBottom: 0,
    paddingLeft: 16,
    paddingRight: 16,
    borderRadius: 999,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(255,255,255,0.16)",
    background: `${redAlpha(0.82)}`,
    color: "var(--text-primary)",
    fontSize: 13,
    fontWeight: 900,
    letterSpacing: 0,
    cursor: "pointer",
    boxShadow: `0 14px 34px ${redAlpha(0.24)}, inset 0 1px 0 rgba(255,255,255,0.12)`,
    backdropFilter: "blur(16px)",
    WebkitBackdropFilter: "blur(16px)",
    transition: "transform var(--motion-fast), background var(--motion-fast), box-shadow var(--motion-fast)",
    WebkitTapHighlightColor: "transparent",
  },
};
