import { RED, redAlpha, GOLD, goldAlpha } from "@/lib/tokens";

const styles = {
  page: { minHeight: "100dvh", background: "linear-gradient(180deg, #070707 0%, #0A0A0A 100%)", color: "#fff", paddingBottom: "calc(88px + env(safe-area-inset-bottom))" },
  header: {
    position: "sticky", top: 0, zIndex: 10,
    display: "grid", gridTemplateColumns: "64px 1fr 44px", alignItems: "center", gap: 12,
    padding: "calc(18px + env(safe-area-inset-top)) 16px 18px",
    background: "rgba(7,7,7,0.94)", backdropFilter: "blur(14px)", WebkitBackdropFilter: "blur(14px)",
    borderBottom: `1px solid ${goldAlpha(0.18)}`,
  },
  backBtn: { border: `1px solid ${goldAlpha(0.28)}`, background: "transparent", color: "#fff", borderRadius: 10, width: 40, height: 40, display: "flex", alignItems: "center", justifyContent: "center", cursor: "pointer", flexShrink: 0 },
  headerCenter: { textAlign: "center" },
  eyebrow: { margin: 0, color: GOLD, fontSize: 11, fontWeight: 800, letterSpacing: 1.5 },
  title: { margin: "4px 0 0", fontSize: 28, fontWeight: 950, lineHeight: 1.1, fontFamily: "var(--font-display, 'Anton', sans-serif)" },
  trophyBadge: { fontSize: 22, textAlign: "right" },
  tabsWrap: { background: "rgba(7,7,7,0.94)", position: "sticky", top: 90, zIndex: 9, borderBottom: "1px solid rgba(255,255,255,0.07)", padding: "10px 16px 8px" },
  tabsRow: { display: "flex", gap: 8, maxWidth: 640, margin: "0 auto" },
  tabBtn: { flex: 1, padding: "9px 0", borderRadius: 10, border: "1px solid rgba(255,255,255,0.12)", background: "rgba(255,255,255,0.04)", color: "#aaa", fontSize: 13, fontWeight: 700, cursor: "pointer", transition: "all 0.18s" },
  tabBtnActive: { background: `${goldAlpha(0.16)}`, border: `1px solid ${goldAlpha(0.45)}`, color: GOLD },
  tabBtnViews: { background: "rgba(96,165,250,0.16)", border: "1px solid rgba(96,165,250,0.45)", color: "#60A5FA" },
  tabBtnLikes: { background: "rgba(244,114,182,0.16)", border: "1px solid rgba(244,114,182,0.45)", color: "#F472B6" },
  seasonLabel: { margin: "6px auto 0", textAlign: "center", fontSize: 11, color: "#888", maxWidth: 640 },
  content: { maxWidth: 640, margin: "0 auto", padding: "20px 16px" },
  yourRankCard: { padding: "14px 16px", borderRadius: 16, background: `${redAlpha(0.12)}`, border: `1.5px solid ${redAlpha(0.55)}`, boxShadow: `0 0 0 1px ${redAlpha(0.08)}, 0 4px 20px ${redAlpha(0.12)}`, marginBottom: 20 },
  yourRankTop: { display: "flex", alignItems: "center", justifyContent: "space-between", marginBottom: 6 },
  yourRankLabel: { fontSize: 14, fontWeight: 900, color: "#fff" },
  scorePill: { padding: "3px 10px", borderRadius: 999, fontSize: 12, fontWeight: 900, color: "#fff" },
  yourRankSub: { fontSize: 12, color: "#aaa", lineHeight: 1.4 },
  weeklyChampionBanner: { padding: "16px 18px", borderRadius: 16, background: `linear-gradient(135deg, ${goldAlpha(0.18)} 0%, ${goldAlpha(0.06)} 100%)`, border: `1px solid ${goldAlpha(0.4)}`, marginBottom: 20, textAlign: "center" },
  weeklyChampionTop: { display: "flex", alignItems: "center", justifyContent: "center", gap: 6, marginBottom: 4 },
  weeklyChampionCrown: { fontSize: 18 },
  weeklyChampionTitle: { fontSize: 11, fontWeight: 900, letterSpacing: 1.5, color: GOLD, textTransform: "uppercase" },
  weeklyChampionName: { fontSize: 20, fontWeight: 900, color: "#fff", lineHeight: 1.2 },
  weeklyChampionScore: { fontSize: 14, color: GOLD, fontWeight: 800, marginTop: 2 },
  sectionHeader: { marginBottom: 16 },
  sectionKicker: { margin: "0 0 4px", color: GOLD, fontSize: 11, fontWeight: 900, letterSpacing: 1.8 },
  sectionTitle: { margin: 0, fontSize: 22, fontWeight: 900, lineHeight: 1.1, fontFamily: "var(--font-display, 'Anton', sans-serif)" },
  loading: { textAlign: "center", color: "#888", padding: 40, fontSize: 14 },
  emptyWrap: { display: "flex", flexDirection: "column", alignItems: "center", paddingTop: 60, paddingBottom: 40, textAlign: "center" },
  emptyIcon: { fontSize: 48, marginBottom: 16 },
  emptyTitle: { margin: "0 0 8px", fontSize: 18, fontWeight: 800, color: "#fff" },
  emptyText: { margin: 0, fontSize: 14, color: "#888", maxWidth: 260, lineHeight: 1.55 },
  list: { display: "grid", gap: 8 },
  row: { display: "grid", gridTemplateColumns: "44px 48px 1fr auto", alignItems: "center", gap: 12, padding: "14px 14px", borderRadius: 16, background: "rgba(255,255,255,0.03)", border: "1px solid rgba(255,255,255,0.07)" },
  rowHighlight: { background: `${redAlpha(0.1)}`, border: `1px solid ${redAlpha(0.28)}` },
  rowFirst: { background: `linear-gradient(145deg, ${goldAlpha(0.1)}, ${goldAlpha(0.03)})`, border: `1px solid ${goldAlpha(0.28)}`, borderLeft: "3px solid #D4AF37", borderRadius: "3px 16px 16px 3px" },
  rowSecond: { background: "linear-gradient(145deg, rgba(156,163,175,0.08), rgba(156,163,175,0.02))", border: "1px solid rgba(156,163,175,0.2)", borderLeft: "3px solid #9CA3AF", borderRadius: "3px 16px 16px 3px" },
  rowThird: { background: "linear-gradient(145deg, rgba(251,146,60,0.08), rgba(251,146,60,0.02))", border: "1px solid rgba(251,146,60,0.2)", borderLeft: "3px solid #FB923C", borderRadius: "3px 16px 16px 3px" },
  rankWrap: { display: "flex", alignItems: "center", justifyContent: "center" },
  medal: { fontSize: 22, lineHeight: 1 },
  rankNum: { fontSize: 13, fontWeight: 900, color: "#888" },
  avatar: { width: 44, height: 44, borderRadius: "50%", background: `${redAlpha(0.22)}`, overflow: "hidden", display: "flex", alignItems: "center", justifyContent: "center", flexShrink: 0 },
  avatarImg: { width: "100%", height: "100%", objectFit: "cover", display: "block" },
  avatarInitial: { fontSize: 18, fontWeight: 900, color: "#fff" },
  nameBlock: { minWidth: 0 },
  displayName: { fontSize: 14, fontWeight: 800, lineHeight: 1.2, whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" },
  youTag: { fontSize: 9, fontWeight: 900, letterSpacing: 1, color: RED, verticalAlign: "middle" },
  username: { fontSize: 11, color: "#777", marginTop: 1 },
  scoresBlock: { textAlign: "right", flexShrink: 0 },
  bestScore: { fontSize: 18, fontWeight: 900, lineHeight: 1.1 },
  latestScore: { fontSize: 10, color: "#888", marginTop: 2 },
  entryRankRow: { display: "flex", alignItems: "center", gap: 4, marginTop: 3 },
  sessionsBadge: { fontSize: 10, color: "#666" },
  allTimeRankBadge: { fontSize: 10, color: "#60A5FA" },
  filterWrap: { background: "rgba(7,7,7,0.92)", padding: "8px 16px 10px", borderBottom: "1px solid rgba(255,255,255,0.05)", display: "flex", flexDirection: "column", gap: 6 },
  filterRow: { display: "flex", gap: 6, overflowX: "auto", WebkitOverflowScrolling: "touch", scrollbarWidth: "none", msOverflowStyle: "none" },
  filterChip: { flexShrink: 0, padding: "6px 12px", borderRadius: 999, border: "1px solid rgba(255,255,255,0.1)", background: "rgba(255,255,255,0.04)", color: "rgba(255,255,255,0.45)", fontSize: 12, fontWeight: 700, cursor: "pointer", whiteSpace: "nowrap", transition: "all 0.15s ease" },
  filterChipActiveWeight: { background: "rgba(96,165,250,0.15)", border: "1px solid #60A5FA", color: "#60A5FA" },
  archetypeChip: { flexShrink: 0, width: 20, height: 20, borderRadius: 6, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 11 },
  badgeRow: { display: "flex", gap: 4, marginTop: 5, flexWrap: "wrap" },
  badge: { display: "inline-flex", alignItems: "center", gap: 3, padding: "2px 7px", borderRadius: 999, border: "1px solid", fontSize: 10, fontWeight: 800, letterSpacing: 0.2, whiteSpace: "nowrap" },
};

export default styles;
