import { redAlpha, goldAlpha, GOLD } from "@/lib/tokens";

const styles = {
  page: {
    minHeight: "100vh",
    background: `radial-gradient(circle at 50% 0%, ${redAlpha(0.2)}, transparent 34%), linear-gradient(180deg, #080808 0%, #0B0B0B 100%)`,
    color: "#fff",
    padding: "calc(28px + env(safe-area-inset-top)) 16px calc(92px + env(safe-area-inset-bottom))",
    fontFamily: "sans-serif",
  },
  backBtn: {
    width: 40,
    height: 40,
    border: "1px solid rgba(255,255,255,0.12)",
    background: "rgba(255,255,255,0.055)",
    borderRadius: 10,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    padding: 0,
    color: "#fff",
    justifySelf: "start",
  },
  loading: {
    minHeight: "100vh",
    background: "#070707",
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  shell: {
    maxWidth: 760,
    margin: "0 auto",
    display: "grid",
    gap: 14,
  },
  header: { display: "grid", gap: 8 },
  kicker: { margin: 0, color: GOLD, fontSize: 11, fontWeight: 950, letterSpacing: 2 },
  title: { margin: 0, fontSize: 38, lineHeight: 1, fontWeight: 1000, fontFamily: "var(--font-display, 'Anton', sans-serif)" },
  subtitle: { margin: 0, color: "rgba(255,255,255,0.66)", fontSize: 14, lineHeight: 1.45 },
  streakPill: {
    width: "fit-content",
    display: "inline-flex",
    alignItems: "center",
    gap: 8,
    minHeight: 34,
    padding: "0 12px",
    borderRadius: 999,
    background: "rgba(251,146,60,0.13)",
    border: "1px solid rgba(251,146,60,0.3)",
    color: "#FED7AA",
    fontSize: 13,
    fontWeight: 950,
  },
  streakFlame: { fontSize: 16, lineHeight: 1 },
  seasonTabRow: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 6,
    padding: 5,
    borderRadius: 16,
    background: "rgba(0,0,0,0.48)",
    border: "1px solid rgba(255,255,255,0.08)",
    backdropFilter: "blur(14px)",
    WebkitBackdropFilter: "blur(14px)",
    position: "sticky",
    top: "calc(10px + env(safe-area-inset-top))",
    zIndex: 8,
  },
  seasonTab: {
    minHeight: 38,
    border: "1px solid transparent",
    borderRadius: 12,
    background: "transparent",
    color: "rgba(255,255,255,0.4)",
    fontSize: 13,
    fontWeight: 950,
    cursor: "pointer",
  },
  seasonTabActive: {
    background: `linear-gradient(135deg, ${redAlpha(0.9)}, ${goldAlpha(0.18)})`,
    color: "#fff",
    boxShadow: `0 10px 30px ${redAlpha(0.18)}`,
    border: `1px solid ${redAlpha(0.55)}`,
  },
  seasonLabel: {
    textAlign: "center",
    paddingBottom: 2,
  },
  seasonLabelText: {
    fontSize: 11,
    color: "#888",
    fontWeight: 700,
    letterSpacing: 0.4,
  },
  champBanner: {
    padding: "14px 16px",
    borderRadius: 18,
    background: `linear-gradient(135deg, ${goldAlpha(0.16)}, rgba(11,11,11,0.95))`,
    border: `1px solid ${goldAlpha(0.3)}`,
    boxShadow: `0 8px 28px ${goldAlpha(0.1)}`,
    display: "grid",
    gap: 10,
  },
  champBannerTitle: {
    margin: 0,
    color: GOLD,
    fontSize: 11,
    fontWeight: 950,
    letterSpacing: 1.5,
    textTransform: "uppercase",
  },
  champList: { display: "grid", gap: 8 },
  champItem: {
    display: "flex",
    alignItems: "center",
    gap: 10,
  },
  champBadge: { fontSize: 20, flexShrink: 0, lineHeight: 1 },
  champInfo: { display: "grid", gap: 2, flex: 1, minWidth: 0 },
  champName: { fontSize: 13, fontWeight: 900, color: "#fff", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  champChallenge: { fontSize: 10, color: "#888", fontWeight: 700 },
  champScore: { fontSize: 14, fontWeight: 1000, color: GOLD, flexShrink: 0 },
  yourRankBar: {
    position: "sticky",
    top: "calc(62px + env(safe-area-inset-top))",
    zIndex: 7,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    minHeight: 44,
    padding: "0 14px",
    borderRadius: 16,
    background: `linear-gradient(135deg, ${goldAlpha(0.16)}, rgba(10,10,10,0.76))`,
    border: `1px solid ${goldAlpha(0.25)}`,
    backdropFilter: "blur(16px)",
    WebkitBackdropFilter: "blur(16px)",
    boxShadow: "0 14px 36px rgba(0,0,0,0.26)",
  },
  yourRankLabel: { color: "#fff", fontSize: 14, fontWeight: 1000 },
  yourRankChallenge: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: GOLD,
    fontSize: 12,
    fontWeight: 900,
  },
  challengeList: { display: "grid", gap: 20 },
  card: {
    borderRadius: 20,
    padding: 16,
    background: `linear-gradient(145deg, ${redAlpha(0.13)}, rgba(11,11,11,0.98) 48%, ${goldAlpha(0.08)})`,
    border: "1px solid rgba(255,255,255,0.09)",
    boxShadow: "0 18px 50px rgba(0,0,0,0.28)",
  },
  cardTop: { display: "grid", gap: 16 },
  cardTitle: { margin: 0, color: "#fff", fontSize: 20, fontWeight: 950, fontFamily: "var(--font-display, 'Anton', sans-serif)" },
  cardDesc: { margin: "7px 0 0", color: "rgba(255,255,255,0.64)", fontSize: 13, lineHeight: 1.45 },
  startButton: {
    width: "100%",
    minHeight: 58,
    padding: "0 20px",
    border: "1px solid rgba(255,255,255,0.14)",
    borderRadius: 16,
    background: "linear-gradient(135deg, #F02234, #B80F1D 48%, #7d0812)",
    boxShadow: `0 18px 42px ${redAlpha(0.36)}`,
    color: "#fff",
    fontSize: 16,
    fontWeight: 1000,
    whiteSpace: "nowrap",
    cursor: "pointer",
    textTransform: "uppercase",
  },
  leaderboard: { marginTop: 16, display: "grid", gap: 9 },
  leaderboardTitle: {
    margin: 0,
    color: GOLD,
    fontSize: 11,
    fontWeight: 950,
    letterSpacing: 1.4,
    textTransform: "uppercase",
  },
  scoreRows: { display: "grid", gap: 7 },
  scoreRow: {
    minHeight: 62,
    display: "grid",
    gridTemplateColumns: "42px minmax(0, 1fr) auto",
    alignItems: "center",
    gap: 10,
    padding: "9px 11px",
    borderRadius: 14,
    background: "rgba(255,255,255,0.045)",
    border: "1px solid rgba(255,255,255,0.07)",
  },
  scoreRowCurrent: {
    background: `${goldAlpha(0.14)}`,
    borderColor: `${goldAlpha(0.38)}`,
    boxShadow: `0 0 0 1px ${goldAlpha(0.1)}, 0 14px 32px ${goldAlpha(0.12)}`,
  },
  emptyLeaderboard: {
    padding: "14px 12px",
    borderRadius: 12,
    background: "rgba(255,255,255,0.035)",
    border: "1px solid rgba(255,255,255,0.07)",
    color: "rgba(255,255,255,0.58)",
    fontSize: 13,
    fontWeight: 800,
    textAlign: "center",
  },
  rankNum: { color: GOLD, fontSize: 18, fontWeight: 950, textAlign: "center" },
  fighterCell: { minWidth: 0, display: "flex", alignItems: "center", gap: 9 },
  avatar: {
    width: 26,
    height: 26,
    borderRadius: "50%",
    display: "grid",
    placeItems: "center",
    flexShrink: 0,
    overflow: "hidden",
    background: `${redAlpha(0.28)}`,
    border: `1px solid ${goldAlpha(0.24)}`,
    color: "#fff",
    fontSize: 11,
    fontWeight: 950,
  },
  avatarImg: { width: "100%", height: "100%", objectFit: "cover", display: "block" },
  fighterText: { minWidth: 0, display: "grid", gap: 3 },
  fighterName: {
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    color: "rgba(255,255,255,0.76)",
    fontSize: 13,
    fontWeight: 850,
  },
  resultMeta: { color: "rgba(255,255,255,0.52)", fontSize: 11, fontWeight: 850 },
  scoreStack: { display: "grid", justifyItems: "end", gap: 4 },
  scoreValue: { color: "#fff", fontSize: 16, fontWeight: 1000, textShadow: `0 0 18px ${goldAlpha(0.3)}` },
  xpValue: { color: GOLD, fontSize: 11, fontWeight: 950 },
};

export default styles;
