import { RED, GOLD, redAlpha, goldAlpha } from "@/lib/tokens";

const styles = {
  breakdownCard: {
    marginTop: 14,
    padding: "14px 16px",
    borderRadius: 16,
    background: "rgba(255,255,255,0.04)",
    border: "1px solid rgba(255,255,255,0.09)",
  },
  breakdownTitle: {
    margin: "0 0 12px",
    fontSize: 11,
    fontWeight: 900,
    color: "rgba(255,255,255,0.65)",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  breakdownGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "12px 16px",
  },
  breakdownItem: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  breakdownLbl: {
    fontSize: 11,
    color: "rgba(255,255,255,0.5)",
    fontWeight: 700,
  },
  breakdownVal: {
    fontSize: 20,
    fontWeight: 1000,
    lineHeight: 1,
  },
  breakdownTrack: {
    height: 4,
    borderRadius: 999,
    background: "rgba(255,255,255,0.08)",
    overflow: "hidden",
    marginTop: 2,
  },
  breakdownFill: {
    height: "100%",
    borderRadius: 999,
    transition: "width 0.6s ease",
  },
  page: {
    minHeight: "100vh",
    background: `radial-gradient(circle at 50% 0%, ${redAlpha(0.2)}, transparent 34%), linear-gradient(180deg, #080808 0%, #0B0B0B 100%)`,
    color: "#fff",
    padding: "calc(68px + env(safe-area-inset-top)) 16px calc(92px + env(safe-area-inset-bottom))",
    fontFamily: "sans-serif",
  },
  loading: {
    minHeight: "100vh",
    background: "#070707",
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  backButton: {
    position: "fixed",
    top: "calc(14px + env(safe-area-inset-top))",
    left: "max(14px, env(safe-area-inset-left))",
    zIndex: 40,
    width: 40,
    height: 40,
    padding: 0,
    borderRadius: 999,
    border: "1px solid rgba(255,255,255,0.12)",
    background: "rgba(0,0,0,0.44)",
    color: "#fff",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    backdropFilter: "blur(14px)",
    WebkitBackdropFilter: "blur(14px)",
  },
  backIcon: {
    fontSize: 24,
    lineHeight: 1,
    color: GOLD,
  },
  shell: {
    maxWidth: 520,
    margin: "0 auto",
    display: "grid",
    gap: 18,
  },
  header: {
    display: "grid",
    gap: 8,
  },
  kicker: {
    margin: 0,
    color: GOLD,
    fontSize: 11,
    fontWeight: 950,
    letterSpacing: 2,
    textTransform: "uppercase",
  },
  title: {
    margin: 0,
    fontSize: 34,
    lineHeight: 1,
    fontWeight: 1000,
    letterSpacing: 0,
    fontFamily: "var(--font-display, 'Anton', sans-serif)",
  },
  subtitle: {
    margin: 0,
    color: "rgba(255,255,255,0.66)",
    fontSize: 14,
    lineHeight: 1.45,
    maxWidth: 420,
  },
  targetScorePill: {
    width: "fit-content",
    display: "inline-flex",
    alignItems: "center",
    minHeight: 36,
    padding: "0 13px",
    borderRadius: 999,
    background: `${goldAlpha(0.16)}`,
    border: `1px solid ${goldAlpha(0.34)}`,
    boxShadow: `0 12px 32px ${goldAlpha(0.12)}`,
  },
  targetScoreLabel: {
    color: "#FDE68A",
    fontSize: 13,
    fontWeight: 1000,
  },
  pvpBanner: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 14px",
    borderRadius: 14,
    background: "rgba(96,165,250,0.1)",
    border: "1px solid rgba(96,165,250,0.3)",
  },
  pvpBannerVs: {
    fontSize: 20,
    flexShrink: 0,
  },
  pvpBannerText: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
  },
  pvpBannerLabel: {
    color: "#93C5FD",
    fontSize: 13,
    fontWeight: 900,
    lineHeight: 1.2,
  },
  pvpBannerScore: {
    color: GOLD,
    fontSize: 18,
    fontWeight: 1000,
    lineHeight: 1,
  },
  pvpWinBanner: {
    margin: "14px 0 0",
    padding: "14px 16px",
    borderRadius: 14,
    background: "rgba(52,211,153,0.12)",
    border: "1px solid rgba(52,211,153,0.35)",
    textAlign: "center",
  },
  pvpLoseBanner: {
    margin: "14px 0 0",
    padding: "14px 16px",
    borderRadius: 14,
    background: `${redAlpha(0.12)}`,
    border: `1px solid ${redAlpha(0.35)}`,
    textAlign: "center",
  },
  pvpResultBadge: {
    display: "inline-block",
    padding: "3px 14px",
    borderRadius: 999,
    fontSize: 11,
    fontWeight: 1000,
    letterSpacing: 2,
    textTransform: "uppercase",
    background: "rgba(255,255,255,0.1)",
    color: "#fff",
    marginBottom: 8,
  },
  pvpResultHeadline: {
    fontSize: 15,
    fontWeight: 1000,
    color: "#fff",
    marginBottom: 10,
  },
  pvpResultScoreRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    marginBottom: 6,
  },
  pvpResultScoreCell: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 2,
  },
  pvpResultScoreNum: {
    fontSize: 28,
    fontWeight: 1000,
    lineHeight: 1,
    color: "#fff",
  },
  pvpResultScoreLbl: {
    fontSize: 11,
    color: "rgba(255,255,255,0.55)",
    fontWeight: 700,
  },
  pvpResultScoreVs: {
    fontSize: 12,
    color: "rgba(255,255,255,0.62)",
    fontWeight: 700,
  },
  pvpResultDiff: {
    fontSize: 20,
    fontWeight: 1000,
    marginBottom: 6,
  },
  pvpResultSaved: {
    fontSize: 11,
    color: "#34D399",
    fontWeight: 800,
    marginTop: 4,
  },
  stage: {
    position: "relative",
    overflow: "hidden",
    borderRadius: 22,
    minHeight: 460,
    aspectRatio: "9 / 14",
    background: "#050505",
    border: "1px solid rgba(255,255,255,0.1)",
    boxShadow: "0 24px 70px rgba(0,0,0,0.46)",
  },
  preview: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    display: "block",
    transform: "scaleX(-1)",
  },
  fallback: {
    position: "absolute",
    inset: 0,
    display: "grid",
    alignContent: "center",
    justifyItems: "center",
    gap: 12,
    padding: 28,
    textAlign: "center",
    background: `radial-gradient(circle at 50% 38%, ${goldAlpha(0.13)}, transparent 30%), linear-gradient(145deg, #12090a, #050505)`,
  },
  fallbackMark: {
    border: `1px solid ${redAlpha(0.55)}`,
    borderRadius: 999,
    padding: "7px 12px",
    color: "#FF6B6B",
    fontSize: 11,
    fontWeight: 1000,
    letterSpacing: 1.5,
  },
  fallbackTitle: {
    margin: 0,
    fontSize: 22,
    fontWeight: 950,
  },
  fallbackText: {
    margin: 0,
    color: "rgba(255,255,255,0.64)",
    fontSize: 14,
    lineHeight: 1.5,
  },
  stageShade: {
    position: "absolute",
    inset: 0,
    pointerEvents: "none",
    background: "linear-gradient(to top, rgba(0,0,0,0.38), transparent 48%)",
  },
  countdown: {
    position: "absolute",
    inset: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 140,
    fontWeight: 1000,
    fontFamily: "var(--font-display, 'Anton', sans-serif)",
    color: "#fff",
    textShadow: `0 0 80px ${redAlpha(0.7)}, 0 18px 60px rgba(0,0,0,0.9)`,
    zIndex: 10,
    pointerEvents: "none",
  },
  countdownGo: {
    fontSize: 100,
    color: "#34D399",
    textShadow: "0 0 80px rgba(52,211,153,0.65), 0 18px 60px rgba(0,0,0,0.9)",
  },
  flashOverlay: {
    position: "absolute",
    inset: 0,
    background: `${redAlpha(0.38)}`,
    zIndex: 8,
    pointerEvents: "none",
    animation: "flashFade 150ms ease-out forwards",
  },
  hitCounter: {
    position: "absolute",
    top: 64,
    left: "50%",
    transform: "translateX(-50%)",
    display: "flex",
    alignItems: "baseline",
    gap: 4,
    background: "rgba(0,0,0,0.58)",
    backdropFilter: "blur(12px)",
    WebkitBackdropFilter: "blur(12px)",
    borderRadius: 999,
    padding: "5px 16px",
    border: "1px solid rgba(255,255,255,0.16)",
    zIndex: 5,
    whiteSpace: "nowrap",
  },
  hitCountNum: {
    color: "#fff",
    fontSize: 24,
    fontWeight: 1000,
    lineHeight: 1,
    textShadow: `0 0 20px ${goldAlpha(0.5)}`,
  },
  hitCountSep: {
    color: "rgba(255,255,255,0.62)",
    fontSize: 14,
    fontWeight: 700,
    margin: "0 2px",
  },
  hitCountTarget: {
    color: "rgba(255,255,255,0.65)",
    fontSize: 16,
    fontWeight: 800,
  },
  hitCountLabel: {
    color: "rgba(255,255,255,0.65)",
    fontSize: 11,
    fontWeight: 700,
    marginLeft: 3,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  comboCounter: {
    position: "absolute",
    bottom: 70,
    left: "50%",
    transform: "translateX(-50%)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    zIndex: 6,
    pointerEvents: "none",
  },
  comboLabel: {
    color: GOLD,
    fontSize: 10,
    fontWeight: 1000,
    letterSpacing: 2.5,
    textShadow: "0 2px 8px rgba(0,0,0,0.95)",
    textTransform: "uppercase",
  },
  comboNum: {
    color: "#fff",
    fontSize: 64,
    fontWeight: 1000,
    fontFamily: "var(--font-display, 'Anton', sans-serif)",
    lineHeight: 1,
    textShadow: `0 0 40px ${goldAlpha(0.55)}, 0 4px 18px rgba(0,0,0,0.95)`,
  },
  liveFeedbackBox: {
    position: "absolute",
    top: "32%",
    left: "50%",
    transform: "translateX(-50%)",
    background: "rgba(0,0,0,0.72)",
    backdropFilter: "blur(14px)",
    WebkitBackdropFilter: "blur(14px)",
    border: "1px solid rgba(255,255,255,0.22)",
    borderRadius: 999,
    padding: "9px 22px",
    color: "#fff",
    fontSize: 15,
    fontWeight: 900,
    whiteSpace: "nowrap",
    zIndex: 9,
    textShadow: "0 2px 8px rgba(0,0,0,0.9)",
    pointerEvents: "none",
  },
  recordingHud: {
    position: "absolute",
    top: 16,
    left: 16,
    right: 16,
    minHeight: 38,
    display: "flex",
    alignItems: "center",
    gap: 9,
    borderRadius: 999,
    padding: "0 13px",
    background: "rgba(0,0,0,0.54)",
    border: "1px solid rgba(255,255,255,0.12)",
    backdropFilter: "blur(14px)",
    WebkitBackdropFilter: "blur(14px)",
    fontSize: 12,
    fontWeight: 900,
    zIndex: 5,
  },
  recordDot: {
    width: 9,
    height: 9,
    borderRadius: "50%",
    background: RED,
    flexShrink: 0,
    boxShadow: `0 0 0 6px ${redAlpha(0.18)}`,
  },
  liveScoreHud: {
    marginLeft: 8,
    fontSize: 13,
    fontWeight: 1000,
    color: GOLD,
    letterSpacing: 0.5,
  },
  controls: {
    display: "grid",
    gap: 12,
  },
  startButton: {
    minHeight: 58,
    border: `1px solid ${goldAlpha(0.34)}`,
    borderRadius: 16,
    background: "linear-gradient(135deg, #C1121F, #7d0812 58%, #9a6a18)",
    color: "#fff",
    fontSize: 15,
    fontWeight: 1000,
    letterSpacing: 1.2,
    cursor: "pointer",
    boxShadow: `0 18px 44px ${redAlpha(0.26)}`,
  },
  stopButton: {
    minHeight: 54,
    border: "1px solid rgba(255,255,255,0.12)",
    borderRadius: 16,
    background: "rgba(255,255,255,0.08)",
    color: "#fff",
    fontSize: 15,
    fontWeight: 950,
    cursor: "pointer",
  },
  error: {
    padding: 12,
    borderRadius: 12,
    background: `${redAlpha(0.14)}`,
    border: `1px solid ${redAlpha(0.35)}`,
    color: "#ffb4b4",
    fontSize: 13,
  },
  saved: {
    padding: 12,
    borderRadius: 12,
    background: "rgba(52,211,153,0.12)",
    border: "1px solid rgba(52,211,153,0.28)",
    color: "#A7F3D0",
    fontSize: 13,
    fontWeight: 800,
  },
  modalSaved: {
    marginTop: 14,
    padding: 12,
    borderRadius: 12,
    background: "rgba(52,211,153,0.12)",
    border: "1px solid rgba(52,211,153,0.28)",
    color: "#A7F3D0",
    fontSize: 13,
    fontWeight: 900,
  },
  missionCompleteBanner: {
    marginTop: 14,
    padding: "12px 14px",
    borderRadius: 14,
    background: `linear-gradient(135deg, ${goldAlpha(0.15)}, rgba(52,211,153,0.10))`,
    border: `1px solid ${goldAlpha(0.35)}`,
    display: "grid",
    gap: 4,
    textAlign: "center",
  },
  missionCompleteTitle: {
    fontSize: 14,
    fontWeight: 1000,
    color: GOLD,
    letterSpacing: 0.3,
  },
  missionCompleteXP: {
    fontSize: 18,
    fontWeight: 1000,
    color: "#34D399",
  },
  missionStreakBonusText: {
    color: "#FB923C",
    fontSize: 14,
  },
  missionCompleteSub: {
    fontSize: 11,
    color: "#888",
    fontWeight: 700,
  },
  modalWrap: {
    position: "fixed",
    inset: 0,
    zIndex: 200,
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "center",
    padding: "20px 16px calc(92px + env(safe-area-inset-bottom))",
  },
  modalOverlay: {
    position: "absolute",
    inset: 0,
    background: "rgba(0,0,0,0.64)",
    backdropFilter: "blur(8px)",
  },
  modal: {
    position: "relative",
    width: "100%",
    maxWidth: 460,
    borderRadius: 22,
    background: "linear-gradient(180deg, #151111, #080808)",
    border: `1px solid ${goldAlpha(0.2)}`,
    boxShadow: "0 -24px 70px rgba(0,0,0,0.54)",
    textAlign: "center",
    maxHeight: "min(600px, calc(100vh - 120px))",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  modalTop: {
    padding: "18px 20px 14px",
    flexShrink: 0,
  },
  modalMiddle: {
    overflowY: "auto",
    padding: "0 20px",
    flex: 1,
  },
  modalBottom: {
    padding: "12px 20px 16px",
    flexShrink: 0,
    borderTop: "1px solid rgba(255,255,255,0.06)",
  },
  modalKicker: {
    margin: 0,
    color: GOLD,
    fontSize: 11,
    fontWeight: 950,
    letterSpacing: 2,
    textTransform: "uppercase",
  },
  score: {
    marginTop: 8,
    fontSize: 72,
    lineHeight: 0.95,
    fontWeight: 1000,
    fontFamily: "var(--font-display, 'Anton', sans-serif)",
  },
  scoreUnit: {
    color: "rgba(255,255,255,0.52)",
    fontSize: 16,
    fontWeight: 900,
  },
  resultGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 10,
    marginTop: 18,
  },
  resultItem: {
    display: "grid",
    gap: 6,
    padding: 14,
    borderRadius: 14,
    background: "rgba(255,255,255,0.055)",
    border: "1px solid rgba(255,255,255,0.08)",
    color: "rgba(255,255,255,0.62)",
    fontSize: 12,
    fontWeight: 800,
  },
  targetResultItem: {
    gridColumn: "1 / -1",
    background: `${goldAlpha(0.13)}`,
    border: `1px solid ${goldAlpha(0.28)}`,
    color: "rgba(253,230,138,0.78)",
    boxShadow: `0 0 28px ${goldAlpha(0.12)}`,
  },
  progressTrack: {
    height: 8,
    borderRadius: 999,
    marginTop: 16,
    background: "rgba(255,255,255,0.09)",
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    borderRadius: 999,
    background: "linear-gradient(90deg, #C1121F, #D4AF37)",
  },
  shareResultButton: {
    width: "100%",
    minHeight: 46,
    marginTop: 14,
    border: `1px solid ${goldAlpha(0.36)}`,
    borderRadius: 14,
    background: `linear-gradient(135deg, ${goldAlpha(0.18)}, ${redAlpha(0.18)})`,
    color: GOLD,
    fontSize: 14,
    fontWeight: 950,
    cursor: "pointer",
  },
  modalActions: {
    display: "grid",
    gridTemplateColumns: "1fr",
    gap: 10,
    marginTop: 18,
  },
  saveButton: {
    minHeight: 46,
    border: "none",
    borderRadius: 14,
    background: RED,
    color: "#fff",
    fontSize: 14,
    fontWeight: 950,
    cursor: "pointer",
  },
  saveButtonDone: {
    background: "#17664b",
    cursor: "default",
  },
  tryAgainButton: {
    minHeight: 46,
    border: "1px solid rgba(255,255,255,0.14)",
    borderRadius: 14,
    background: "rgba(255,255,255,0.06)",
    color: "#fff",
    fontSize: 14,
    fontWeight: 900,
    cursor: "pointer",
  },
  reelsButton: {
    minHeight: 46,
    border: `1px solid ${goldAlpha(0.32)}`,
    borderRadius: 14,
    background: `${goldAlpha(0.1)}`,
    color: GOLD,
    fontSize: 14,
    fontWeight: 950,
    cursor: "pointer",
  },
  challengeFriendButton: {
    minHeight: 46,
    border: `1px solid ${goldAlpha(0.42)}`,
    borderRadius: 14,
    background: `linear-gradient(135deg, ${redAlpha(0.92)}, ${goldAlpha(0.28)})`,
    color: "#fff",
    fontSize: 14,
    fontWeight: 1000,
    cursor: "pointer",
    boxShadow: `0 14px 34px ${redAlpha(0.22)}`,
  },
  ghostHud: {
    position: "absolute",
    top: 64,
    right: 12,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 3,
    background: "rgba(0,0,0,0.62)",
    backdropFilter: "blur(12px)",
    WebkitBackdropFilter: "blur(12px)",
    borderRadius: 14,
    padding: "8px 14px",
    border: "1px solid rgba(255,255,255,0.14)",
    zIndex: 5,
    minWidth: 60,
  },
  ghostHudRow: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 1,
  },
  ghostHudYouLabel: {
    color: GOLD,
    fontSize: 9,
    fontWeight: 1000,
    letterSpacing: 1.5,
    textTransform: "uppercase",
  },
  ghostHudYouScore: {
    color: GOLD,
    fontSize: 20,
    fontWeight: 1000,
    lineHeight: 1,
  },
  ghostHudSep: {
    color: "rgba(255,255,255,0.58)",
    fontSize: 10,
    fontWeight: 700,
  },
  ghostHudGhostLabel: {
    color: "rgba(255,255,255,0.6)",
    fontSize: 12,
    lineHeight: 1,
  },
  ghostHudGhostScore: {
    color: "rgba(255,255,255,0.85)",
    fontSize: 20,
    fontWeight: 1000,
    lineHeight: 1,
  },
  ghostToggleOn: {
    minHeight: 40,
    border: "1px solid rgba(255,255,255,0.2)",
    borderRadius: 12,
    background: "rgba(255,255,255,0.08)",
    color: "#fff",
    fontSize: 13,
    fontWeight: 900,
    cursor: "pointer",
  },
  ghostToggleOff: {
    minHeight: 40,
    border: "1px solid rgba(255,255,255,0.08)",
    borderRadius: 12,
    background: "transparent",
    color: "rgba(255,255,255,0.58)",
    fontSize: 13,
    fontWeight: 700,
    cursor: "pointer",
  },
  ghostWinBanner: {
    margin: "14px 0 0",
    padding: "12px 16px",
    borderRadius: 14,
    background: "rgba(52,211,153,0.12)",
    border: "1px solid rgba(52,211,153,0.35)",
    textAlign: "center",
    fontSize: 15,
    fontWeight: 1000,
    color: "#34D399",
  },
  ghostLoseBanner: {
    margin: "14px 0 0",
    padding: "12px 16px",
    borderRadius: 14,
    background: "rgba(255,255,255,0.05)",
    border: "1px solid rgba(255,255,255,0.1)",
    textAlign: "center",
    fontSize: 15,
    fontWeight: 1000,
    color: "rgba(255,255,255,0.65)",
  },
  ghostBestScoreRow: {
    marginTop: 4,
    fontSize: 12,
    color: "rgba(255,255,255,0.65)",
    fontWeight: 700,
  },
  ghostHudState: {
    marginTop: 5,
    fontSize: 8,
    fontWeight: 1000,
    letterSpacing: 1.4,
    textTransform: "uppercase",
  },

  // Pre-game context card
  contextCard: {
    padding: "14px 16px",
    borderRadius: 16,
    background: "rgba(255,255,255,0.04)",
    border: "1px solid rgba(255,255,255,0.08)",
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  contextStatsRow: {
    display: "flex",
    gap: 12,
    alignItems: "flex-start",
  },
  contextStat: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    flex: 1,
  },
  contextStatLabel: {
    fontSize: 10,
    fontWeight: 900,
    color: "rgba(255,255,255,0.45)",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  contextStatValue: {
    fontSize: 24,
    fontWeight: 1000,
    color: "#fff",
    lineHeight: 1,
    fontFamily: "var(--font-display, 'Anton', sans-serif)",
  },
  contextStatUnit: {
    fontSize: 13,
    fontWeight: 700,
    color: "rgba(255,255,255,0.5)",
    marginLeft: 2,
  },
  contextEmptyMsg: {
    fontSize: 13,
    color: "rgba(255,255,255,0.5)",
    fontWeight: 700,
    textAlign: "center",
    padding: "4px 0",
  },
  contextGhostNote: {
    fontSize: 11,
    color: "rgba(255,255,255,0.38)",
    fontWeight: 700,
    borderTop: "1px solid rgba(255,255,255,0.07)",
    paddingTop: 8,
  },
  preSessionStrip: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    paddingBottom: 10,
    borderBottom: "1px solid rgba(255,255,255,0.07)",
    marginBottom: 4,
  },
  weeklyRingWrap: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 2,
    flexShrink: 0,
  },
  weeklyRingLabel: {
    fontSize: 9,
    fontWeight: 900,
    color: "rgba(255,255,255,0.4)",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  preSessionStat: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 3,
    flex: 1,
  },
  preSessionStatVal: {
    fontSize: 18,
    fontWeight: 1000,
    color: "#fff",
    lineHeight: 1,
    fontFamily: "var(--font-display, 'Anton', sans-serif)",
  },
  preSessionStatLbl: {
    fontSize: 9,
    fontWeight: 900,
    color: "rgba(255,255,255,0.4)",
    textTransform: "uppercase",
    letterSpacing: 0.8,
    textAlign: "center",
  },
  preSessionSparkWrap: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 3,
    flex: 1,
  },
  preSessionSparkBars: {
    display: "flex",
    alignItems: "flex-end",
    gap: 3,
    height: 36,
  },
  preSessionSparkBar: {
    width: 8,
    borderRadius: "2px 2px 0 0",
    transition: "height 0.5s ease",
  },
  resultSparklineCard: {
    marginTop: 14,
    padding: "12px 14px",
    borderRadius: 14,
    background: "rgba(255,255,255,0.03)",
    border: "1px solid rgba(255,255,255,0.08)",
  },
  resultSparklineTitle: {
    margin: "0 0 10px",
    fontSize: 10,
    fontWeight: 900,
    color: "rgba(255,255,255,0.45)",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  resultSparklineBars: {
    display: "flex",
    alignItems: "flex-end",
    gap: 5,
    height: 56,
  },

  // Result — new best / vs ghost comparison card
  newBestCard: {
    margin: "14px 0 0",
    padding: "14px 16px",
    borderRadius: 16,
    background: "linear-gradient(135deg, rgba(52,211,153,0.14), rgba(11,11,11,0.92))",
    border: "1px solid rgba(52,211,153,0.35)",
    textAlign: "center",
    display: "flex",
    flexDirection: "column",
    gap: 8,
    alignItems: "center",
  },
  vsGhostCard: {
    margin: "14px 0 0",
    padding: "14px 16px",
    borderRadius: 16,
    background: "rgba(255,255,255,0.04)",
    border: "1px solid rgba(255,255,255,0.1)",
    textAlign: "center",
    display: "flex",
    flexDirection: "column",
    gap: 8,
    alignItems: "center",
  },
  newBestBadge: {
    fontSize: 11,
    fontWeight: 1000,
    letterSpacing: 1.6,
    color: "#34D399",
    textTransform: "uppercase",
  },
  vsCompareRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 14,
  },
  vsCompareCell: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 2,
  },
  vsCompareLbl: {
    fontSize: 9,
    fontWeight: 900,
    color: "rgba(255,255,255,0.45)",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  vsCompareScore: {
    fontSize: 30,
    fontWeight: 1000,
    color: "#fff",
    lineHeight: 1,
    fontFamily: "var(--font-display, 'Anton', sans-serif)",
  },
  vsCompareDelta: {
    fontSize: 18,
    fontWeight: 1000,
    minWidth: 44,
    textAlign: "center",
  },
  almostMsg: {
    fontSize: 12,
    color: "rgba(255,255,255,0.55)",
    fontWeight: 700,
  },
};

export default styles;
