import { RED, RED_DARK, GOLD, BG, BORDER, BORDER_2, RADIUS, redAlpha, goldAlpha, whiteAlpha, blackAlpha } from "@/lib/tokens";

const styles = {
  // ── Page shell ────────────────────────────────────────────────────────────
  page: {
    minHeight: "100dvh",
    background: `radial-gradient(ellipse at 50% -5%, ${redAlpha(0.18)} 0%, transparent 48%), ${BG}`,
    color: "#fff",
    padding: "calc(68px + env(safe-area-inset-top)) 16px calc(120px + env(safe-area-inset-bottom))",
  },
  loading: {
    minHeight: "100dvh",
    background: BG,
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },

  // ── Back button ───────────────────────────────────────────────────────────
  backButton: {
    position: "fixed",
    top: "calc(14px + env(safe-area-inset-top))",
    left: "max(14px, env(safe-area-inset-left))",
    zIndex: 40,
    width: 40,
    height: 40,
    padding: 0,
    borderRadius: RADIUS.md,
    border: `1px solid ${whiteAlpha(0.1)}`,
    background: blackAlpha(0.55),
    color: "#fff",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    backdropFilter: "blur(16px)",
    WebkitBackdropFilter: "blur(16px)",
  },
  backIcon: { fontSize: 24, lineHeight: 1, color: GOLD },

  // ── Content shell ─────────────────────────────────────────────────────────
  shell: { maxWidth: 500, margin: "0 auto", display: "flex", flexDirection: "column", gap: 18 },

  // ── Header ───────────────────────────────────────────────────────────────
  header: { display: "grid", gap: 6 },
  kicker: {
    margin: 0,
    color: RED,
    fontSize: 10,
    fontWeight: 900,
    letterSpacing: 3,
    textTransform: "uppercase",
  },
  title: {
    margin: 0,
    fontSize: "clamp(30px, 9vw, 40px)",
    lineHeight: 0.95,
    fontWeight: 1000,
    letterSpacing: "-0.02em",
    fontFamily: "var(--font-display, 'Anton', sans-serif)",
    textTransform: "uppercase",
  },
  subtitle: {
    margin: 0,
    color: whiteAlpha(0.5),
    fontSize: 13,
    lineHeight: 1.45,
    maxWidth: 420,
    fontWeight: 400,
  },

  // ── PvP banner + target ───────────────────────────────────────────────────
  targetScorePill: {
    width: "fit-content",
    display: "inline-flex",
    alignItems: "center",
    minHeight: 34,
    padding: "0 14px",
    borderRadius: RADIUS.full,
    background: goldAlpha(0.12),
    border: `1px solid ${goldAlpha(0.32)}`,
    boxShadow: `0 8px 28px ${goldAlpha(0.1)}`,
  },
  targetScoreLabel: { color: "#FDE68A", fontSize: 13, fontWeight: 1000 },
  pvpBanner: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 14px",
    borderRadius: RADIUS.md,
    background: "rgba(96,165,250,0.08)",
    border: "1px solid rgba(96,165,250,0.25)",
  },
  pvpBannerVs:     { fontSize: 20, flexShrink: 0 },
  pvpBannerText:   { display: "flex", flexDirection: "column", gap: 2 },
  pvpBannerLabel:  { color: "#93C5FD", fontSize: 13, fontWeight: 900, lineHeight: 1.2 },
  pvpBannerScore:  { color: GOLD, fontSize: 18, fontWeight: 1000, lineHeight: 1 },

  pvpWinBanner:    { margin: "14px 0 0", padding: "14px 16px", borderRadius: RADIUS.md, background: "rgba(52,211,153,0.1)", border: "1px solid rgba(52,211,153,0.3)", textAlign: "center" },
  pvpLoseBanner:   { margin: "14px 0 0", padding: "14px 16px", borderRadius: RADIUS.md, background: redAlpha(0.1), border: `1px solid ${redAlpha(0.3)}`, textAlign: "center" },
  pvpResultBadge:  { display: "inline-block", padding: "3px 14px", borderRadius: RADIUS.full, fontSize: 11, fontWeight: 1000, letterSpacing: 2, textTransform: "uppercase", background: whiteAlpha(0.08), color: "#fff", marginBottom: 8 },
  pvpResultHeadline:  { fontSize: 15, fontWeight: 1000, color: "#fff", marginBottom: 10 },
  pvpResultScoreRow:  { display: "flex", alignItems: "center", justifyContent: "center", gap: 12, marginBottom: 6 },
  pvpResultScoreCell: { display: "flex", flexDirection: "column", alignItems: "center", gap: 2 },
  pvpResultScoreNum:  { fontSize: 28, fontWeight: 1000, lineHeight: 1, color: "#fff" },
  pvpResultScoreLbl:  { fontSize: 11, color: whiteAlpha(0.55), fontWeight: 700 },
  pvpResultScoreVs:   { fontSize: 12, color: whiteAlpha(0.62), fontWeight: 700 },
  pvpResultDiff:      { fontSize: 20, fontWeight: 1000, marginBottom: 6 },
  pvpResultSaved:     { fontSize: 11, color: "#34D399", fontWeight: 800, marginTop: 4 },

  // ── Controls ──────────────────────────────────────────────────────────────
  controls: {
    position: "sticky",
    bottom: "calc(12px + env(safe-area-inset-bottom))",
    zIndex: 20,
    display: "grid",
    gap: 10,
    paddingTop: 6,
  },
  startButton: {
    minHeight: 60,
    border: `1px solid ${redAlpha(0.4)}`,
    borderRadius: RADIUS.lg,
    background: `linear-gradient(145deg, ${RED}, ${RED_DARK})`,
    color: "#fff",
    fontSize: 16,
    fontWeight: 900,
    letterSpacing: 2,
    textTransform: "uppercase",
    cursor: "pointer",
    boxShadow: `0 12px 40px ${redAlpha(0.35)}, inset 0 1px 0 ${whiteAlpha(0.14)}`,
    transition: "transform 180ms ease, box-shadow 180ms ease",
  },
  stopButton: {
    minHeight: 52,
    border: `1px solid ${whiteAlpha(0.1)}`,
    borderRadius: RADIUS.md,
    background: whiteAlpha(0.06),
    color: whiteAlpha(0.7),
    fontSize: 14,
    fontWeight: 800,
    letterSpacing: 1,
    textTransform: "uppercase",
    cursor: "pointer",
  },

  // ── Feedback messages ─────────────────────────────────────────────────────
  error: {
    padding: "12px 14px",
    borderRadius: 12,
    background: redAlpha(0.12),
    border: `1px solid ${redAlpha(0.32)}`,
    color: "#ffb4b4",
    fontSize: 13,
  },
  saved: {
    padding: "12px 14px",
    borderRadius: 12,
    background: "rgba(52,211,153,0.1)",
    border: "1px solid rgba(52,211,153,0.26)",
    color: "#A7F3D0",
    fontSize: 13,
    fontWeight: 800,
  },

  // ── Breakdown card (below stage) ──────────────────────────────────────────
  breakdownCard:  { marginTop: 14, padding: "14px 16px", borderRadius: 16, background: whiteAlpha(0.04), border: `1px solid ${BORDER_2}` },
  breakdownTitle: { margin: "0 0 12px", fontSize: 10, fontWeight: 900, color: whiteAlpha(0.4), textTransform: "uppercase", letterSpacing: 1.5 },
  breakdownGrid:  { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "12px 16px" },
  breakdownItem:  { display: "flex", flexDirection: "column", gap: 4 },
  breakdownLbl:   { fontSize: 11, color: whiteAlpha(0.45), fontWeight: 700 },
  breakdownVal:   { fontSize: 20, fontWeight: 1000, lineHeight: 1 },
  breakdownTrack: { height: 3, borderRadius: RADIUS.full, background: BORDER, overflow: "hidden", marginTop: 2 },
  breakdownFill:  { height: "100%", borderRadius: RADIUS.full, transition: "width 0.6s ease" },

  // ── Camera stage ──────────────────────────────────────────────────────────
  stage: {
    position: "relative",
    overflow: "hidden",
    borderRadius: 20,
    width: "100%",
    height: "min(82dvh, 740px)",
    minHeight: 400,
    maxHeight: 740,
    flexShrink: 0,
    flexGrow: 0,
    background: BG,
    border: `1px solid ${whiteAlpha(0.07)}`,
    boxShadow: `0 32px 80px ${blackAlpha(0.55)}, 0 0 0 1px ${whiteAlpha(0.03)}`,
  },
  preview: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    display: "block",
  },

  // ── Fallback (no camera) ──────────────────────────────────────────────────
  fallback: {
    position: "absolute",
    inset: 0,
    display: "grid",
    alignContent: "center",
    justifyItems: "center",
    gap: 12,
    padding: 28,
    textAlign: "center",
    background: `radial-gradient(ellipse at 50% 35%, ${goldAlpha(0.1)}, transparent 55%), linear-gradient(160deg, #0e0608, ${BG})`,
  },
  fallbackMark: {
    border: `1px solid ${redAlpha(0.5)}`,
    borderRadius: 8,
    padding: "6px 14px",
    color: "#FF6B6B",
    fontSize: 10,
    fontWeight: 900,
    letterSpacing: 2,
    textTransform: "uppercase",
  },
  fallbackTitle: { margin: 0, fontSize: 20, fontWeight: 950 },
  fallbackText: { margin: 0, color: whiteAlpha(0.55), fontSize: 13, lineHeight: 1.55 },

  // ── Overlays ──────────────────────────────────────────────────────────────
  stageShade: {
    position: "absolute",
    inset: 0,
    pointerEvents: "none",
    background: `linear-gradient(to top, ${blackAlpha(0.5)} 0%, transparent 45%)`,
  },
  flashOverlay: {
    position: "absolute",
    inset: 0,
    background: redAlpha(0.32),
    zIndex: 8,
    pointerEvents: "none",
    animation: "flashFade 150ms ease-out forwards",
  },

  // ── Countdown ─────────────────────────────────────────────────────────────
  countdown: {
    position: "absolute",
    inset: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 148,
    fontWeight: 1000,
    fontFamily: "var(--font-display, 'Anton', sans-serif)",
    color: "#fff",
    textShadow: `0 0 80px ${redAlpha(0.75)}, 0 20px 60px ${blackAlpha(0.95)}`,
    zIndex: 10,
    pointerEvents: "none",
    letterSpacing: "-0.04em",
  },
  countdownGo: {
    fontSize: 104,
    color: "#34D399",
    textShadow: `0 0 80px rgba(52,211,153,0.7), 0 20px 60px ${blackAlpha(0.95)}`,
    letterSpacing: "0.04em",
  },

  // ── Recording HUD (top bar) ───────────────────────────────────────────────
  recordingHud: {
    position: "absolute",
    top: 14,
    left: 12,
    right: 12,
    height: 40,
    display: "flex",
    alignItems: "center",
    gap: 8,
    borderRadius: 20,
    padding: "0 14px",
    background: blackAlpha(0.6),
    border: `1px solid ${whiteAlpha(0.1)}`,
    backdropFilter: "blur(16px)",
    WebkitBackdropFilter: "blur(16px)",
    fontSize: 12,
    fontWeight: 900,
    zIndex: 5,
    boxShadow: `0 4px 20px ${blackAlpha(0.4)}`,
  },
  recordDot: {
    width: 8,
    height: 8,
    borderRadius: "50%",
    background: RED,
    flexShrink: 0,
    boxShadow: `0 0 0 4px ${redAlpha(0.22)}`,
    animation: "livePulse 1.2s ease-in-out infinite",
  },
  liveScoreHud: {
    marginLeft: 6,
    fontSize: 14,
    fontWeight: 1000,
    color: GOLD,
    letterSpacing: 0.5,
    fontFamily: "var(--font-display, 'Anton', sans-serif)",
  },

  // ── Hit counter (center) ──────────────────────────────────────────────────
  hitCounter: {
    position: "absolute",
    top: 66,
    left: "50%",
    transform: "translateX(-50%)",
    display: "flex",
    alignItems: "baseline",
    gap: 3,
    background: blackAlpha(0.55),
    backdropFilter: "blur(14px)",
    WebkitBackdropFilter: "blur(14px)",
    borderRadius: RADIUS.full,
    padding: "6px 18px",
    border: `1px solid ${whiteAlpha(0.12)}`,
    zIndex: 5,
    whiteSpace: "nowrap",
  },
  hitCountNum: {
    color: "#fff",
    fontSize: 26,
    fontWeight: 1000,
    lineHeight: 1,
    fontFamily: "var(--font-display, 'Anton', sans-serif)",
    textShadow: `0 0 20px ${goldAlpha(0.55)}`,
  },
  hitCountSep:    { color: whiteAlpha(0.5), fontSize: 14, fontWeight: 700, margin: "0 1px" },
  hitCountTarget: { color: whiteAlpha(0.55), fontSize: 16, fontWeight: 800 },
  hitCountLabel:  { color: whiteAlpha(0.45), fontSize: 10, fontWeight: 800, marginLeft: 4, textTransform: "uppercase", letterSpacing: 0.8 },

  // ── Combo counter ─────────────────────────────────────────────────────────
  comboCounter: {
    position: "absolute",
    bottom: 144,
    left: "50%",
    transform: "translateX(-50%)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    zIndex: 21,
    pointerEvents: "none",
  },
  comboLabel: {
    color: GOLD,
    fontSize: 10,
    fontWeight: 1000,
    letterSpacing: 3,
    textShadow: `0 2px 8px ${blackAlpha(0.95)}`,
    textTransform: "uppercase",
  },
  comboNum: {
    color: "#fff",
    fontSize: 72,
    fontWeight: 1000,
    fontFamily: "var(--font-display, 'Anton', sans-serif)",
    lineHeight: 0.95,
    textShadow: `0 0 50px ${goldAlpha(0.65)}, 0 4px 20px ${blackAlpha(0.95)}`,
    letterSpacing: "-0.03em",
  },

  // ── Live feedback toast ────────────────────────────────────────────────────
  liveFeedbackBox: {
    position: "absolute",
    top: "34%",
    left: "50%",
    transform: "translateX(-50%)",
    background: blackAlpha(0.75),
    backdropFilter: "blur(16px)",
    WebkitBackdropFilter: "blur(16px)",
    border: `1px solid ${whiteAlpha(0.18)}`,
    borderRadius: RADIUS.full,
    padding: "10px 24px",
    color: "#fff",
    fontSize: 14,
    fontWeight: 900,
    whiteSpace: "nowrap",
    zIndex: 9,
    textShadow: `0 2px 8px ${blackAlpha(0.9)}`,
    pointerEvents: "none",
    boxShadow: `0 8px 32px ${blackAlpha(0.5)}`,
  },

  // ── Modal ─────────────────────────────────────────────────────────────────
  modalSaved: {
    marginTop: 14,
    padding: 12,
    borderRadius: 12,
    background: "rgba(52,211,153,0.12)",
    border: "1px solid rgba(52,211,153,0.28)",
    color: "#A7F3D0",
    fontSize: 13,
    fontWeight: 900,
  },
  missionCompleteBanner: {
    marginTop: 14,
    padding: "12px 14px",
    borderRadius: RADIUS.md,
    background: `linear-gradient(135deg, ${goldAlpha(0.15)}, rgba(52,211,153,0.10))`,
    border: `1px solid ${goldAlpha(0.35)}`,
    display: "grid",
    gap: 4,
    textAlign: "center",
  },
  missionCompleteTitle: {
    fontSize: 14,
    fontWeight: 1000,
    color: GOLD,
    letterSpacing: 0.3,
  },
  missionCompleteXP: {
    fontSize: 18,
    fontWeight: 1000,
    color: "#34D399",
  },
  missionStreakBonusText: {
    color: "#FB923C",
    fontSize: 14,
  },
  missionCompleteSub: {
    fontSize: 11,
    color: whiteAlpha(0.45),
    fontWeight: 700,
  },
  modalWrap: {
    position: "fixed",
    inset: 0,
    zIndex: 200,
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "center",
    padding: "20px 16px calc(92px + env(safe-area-inset-bottom))",
  },
  modalOverlay: {
    position: "absolute",
    inset: 0,
    background: blackAlpha(0.72),
    backdropFilter: "blur(14px)",
    WebkitBackdropFilter: "blur(14px)",
  },
  modal: {
    position: "relative",
    width: "100%",
    maxWidth: 460,
    borderRadius: 28,
    background: "rgba(16,14,18,0.97)",
    border: `1px solid ${goldAlpha(0.18)}`,
    boxShadow: `0 -32px 80px ${blackAlpha(0.65)}, 0 0 0 1px ${whiteAlpha(0.03)}, 0 0 60px ${redAlpha(0.08)}`,
    backdropFilter: "blur(28px)",
    WebkitBackdropFilter: "blur(28px)",
    textAlign: "center",
    maxHeight: "min(80dvh, calc(100dvh - 80px))",
    display: "flex",
    flexDirection: "column",
    overflowY: "auto",
    WebkitOverflowScrolling: "touch",
  },
  modalTop: {
    padding: "18px 20px 14px",
    flexShrink: 0,
  },
  modalMiddle: {
    overflowY: "auto",
    padding: "0 20px",
    flex: 1,
  },
  modalBottom: {
    padding: "12px 20px 16px",
    flexShrink: 0,
    borderTop: `1px solid ${BORDER}`,
  },
  modalKicker: {
    margin: 0,
    color: GOLD,
    fontSize: 11,
    fontWeight: 900,
    letterSpacing: 3,
    textTransform: "uppercase",
    fontFamily: "var(--font-condensed)",
  },
  score: {
    marginTop: 8,
    fontSize: 72,
    lineHeight: 0.95,
    fontWeight: 1000,
    fontFamily: "var(--font-display, 'Anton', sans-serif)",
  },
  scoreUnit: {
    color: whiteAlpha(0.52),
    fontSize: 16,
    fontWeight: 900,
  },
  resultGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 10,
    marginTop: 18,
  },
  resultItem: {
    display: "grid",
    gap: 6,
    padding: 14,
    borderRadius: RADIUS.md,
    background: whiteAlpha(0.055),
    border: `1px solid ${BORDER_2}`,
    color: whiteAlpha(0.62),
    fontSize: 12,
    fontWeight: 800,
  },
  targetResultItem: {
    gridColumn: "1 / -1",
    background: `${goldAlpha(0.13)}`,
    border: `1px solid ${goldAlpha(0.28)}`,
    color: "rgba(253,230,138,0.78)",
    boxShadow: `0 0 28px ${goldAlpha(0.12)}`,
  },
  progressTrack: {
    height: 8,
    borderRadius: RADIUS.full,
    marginTop: 16,
    background: whiteAlpha(0.09),
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    borderRadius: RADIUS.full,
    background: RED,
  },
  shareResultButton: {
    width: "100%",
    minHeight: 46,
    marginTop: 14,
    border: `1px solid ${goldAlpha(0.36)}`,
    borderRadius: RADIUS.md,
    background: `linear-gradient(135deg, ${goldAlpha(0.18)}, ${redAlpha(0.18)})`,
    color: GOLD,
    fontSize: 14,
    fontWeight: 950,
    cursor: "pointer",
  },
  modalActions: {
    display: "grid",
    gridTemplateColumns: "1fr",
    gap: 10,
    marginTop: 18,
  },
  saveButton: {
    minHeight: 46,
    border: "none",
    borderRadius: RADIUS.md,
    background: `linear-gradient(145deg, ${RED}, ${RED_DARK})`,
    color: "#fff",
    fontSize: 14,
    fontWeight: 950,
    cursor: "pointer",
    boxShadow: `0 8px 24px ${redAlpha(0.28)}, inset 0 1px 0 ${whiteAlpha(0.1)}`,
  },
  saveButtonDone: {
    background: "#17664b",
    cursor: "default",
  },
  tryAgainButton: {
    minHeight: 46,
    border: `1px solid ${whiteAlpha(0.14)}`,
    borderRadius: RADIUS.md,
    background: whiteAlpha(0.06),
    color: "#fff",
    fontSize: 14,
    fontWeight: 900,
    cursor: "pointer",
  },
  reelsButton: {
    minHeight: 46,
    border: `1px solid ${goldAlpha(0.32)}`,
    borderRadius: RADIUS.md,
    background: `${goldAlpha(0.1)}`,
    color: GOLD,
    fontSize: 14,
    fontWeight: 950,
    cursor: "pointer",
  },
  challengeFriendButton: {
    minHeight: 46,
    border: `1px solid ${goldAlpha(0.42)}`,
    borderRadius: RADIUS.md,
    background: `linear-gradient(135deg, ${redAlpha(0.92)}, ${goldAlpha(0.28)})`,
    color: "#fff",
    fontSize: 14,
    fontWeight: 1000,
    cursor: "pointer",
    boxShadow: `0 14px 34px ${redAlpha(0.22)}`,
  },

  // ── Ghost / context HUD ───────────────────────────────────────────────────
  ghostHud: {
    position: "absolute",
    top: 64,
    right: 12,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 3,
    background: blackAlpha(0.62),
    backdropFilter: "blur(12px)",
    WebkitBackdropFilter: "blur(12px)",
    borderRadius: RADIUS.md,
    padding: "8px 14px",
    border: `1px solid ${whiteAlpha(0.14)}`,
    zIndex: 5,
    minWidth: 60,
  },
  ghostHudRow: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 1,
  },
  ghostHudYouLabel: {
    color: GOLD,
    fontSize: 9,
    fontWeight: 1000,
    letterSpacing: 1.5,
    textTransform: "uppercase",
  },
  ghostHudYouScore: {
    color: GOLD,
    fontSize: 20,
    fontWeight: 1000,
    lineHeight: 1,
  },
  ghostHudSep: {
    color: whiteAlpha(0.58),
    fontSize: 10,
    fontWeight: 700,
  },
  ghostHudGhostLabel: {
    color: whiteAlpha(0.6),
    fontSize: 12,
    lineHeight: 1,
  },
  ghostHudGhostScore: {
    color: whiteAlpha(0.85),
    fontSize: 20,
    fontWeight: 1000,
    lineHeight: 1,
  },
  ghostToggleOn: {
    minHeight: 40,
    border: `1px solid ${whiteAlpha(0.2)}`,
    borderRadius: 12,
    background: whiteAlpha(0.08),
    color: "#fff",
    fontSize: 13,
    fontWeight: 900,
    cursor: "pointer",
  },
  ghostToggleOff: {
    minHeight: 40,
    border: `1px solid ${BORDER_2}`,
    borderRadius: 12,
    background: "transparent",
    color: whiteAlpha(0.58),
    fontSize: 13,
    fontWeight: 700,
    cursor: "pointer",
  },
  ghostWinBanner: {
    margin: "14px 0 0",
    padding: "12px 16px",
    borderRadius: RADIUS.md,
    background: "rgba(52,211,153,0.12)",
    border: "1px solid rgba(52,211,153,0.35)",
    textAlign: "center",
    fontSize: 15,
    fontWeight: 1000,
    color: "#34D399",
  },
  ghostLoseBanner: {
    margin: "14px 0 0",
    padding: "12px 16px",
    borderRadius: RADIUS.md,
    background: whiteAlpha(0.05),
    border: `1px solid ${whiteAlpha(0.1)}`,
    textAlign: "center",
    fontSize: 15,
    fontWeight: 1000,
    color: whiteAlpha(0.65),
  },
  ghostBestScoreRow: {
    marginTop: 4,
    fontSize: 12,
    color: whiteAlpha(0.65),
    fontWeight: 700,
  },
  ghostHudState: {
    marginTop: 5,
    fontSize: 8,
    fontWeight: 1000,
    letterSpacing: 1.4,
    textTransform: "uppercase",
  },

  // ── Pre-game context card ─────────────────────────────────────────────────
  contextCard: {
    padding: "14px 16px",
    borderRadius: 16,
    background: whiteAlpha(0.04),
    border: `1px solid ${BORDER_2}`,
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  contextStatsRow: {
    display: "flex",
    gap: 12,
    alignItems: "flex-start",
  },
  contextStat: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    flex: 1,
  },
  contextStatLabel: {
    fontSize: 10,
    fontWeight: 900,
    color: whiteAlpha(0.45),
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  contextStatValue: {
    fontSize: 24,
    fontWeight: 1000,
    color: "#fff",
    lineHeight: 1,
    fontFamily: "var(--font-display, 'Anton', sans-serif)",
  },
  contextStatUnit: {
    fontSize: 13,
    fontWeight: 700,
    color: whiteAlpha(0.5),
    marginLeft: 2,
  },
  contextEmptyMsg: {
    fontSize: 13,
    color: whiteAlpha(0.5),
    fontWeight: 700,
    textAlign: "center",
    padding: "4px 0",
  },
  contextGhostNote: {
    fontSize: 11,
    color: whiteAlpha(0.38),
    fontWeight: 700,
    borderTop: `1px solid ${BORDER}`,
    paddingTop: 8,
  },
  preSessionStrip: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    paddingBottom: 10,
    borderBottom: `1px solid ${BORDER}`,
    marginBottom: 4,
  },
  weeklyRingWrap: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 2,
    flexShrink: 0,
  },
  weeklyRingLabel: {
    fontSize: 9,
    fontWeight: 900,
    color: whiteAlpha(0.4),
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  preSessionStat: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 3,
    flex: 1,
  },
  preSessionStatVal: {
    fontSize: 18,
    fontWeight: 1000,
    color: "#fff",
    lineHeight: 1,
    fontFamily: "var(--font-display, 'Anton', sans-serif)",
  },
  preSessionStatLbl: {
    fontSize: 9,
    fontWeight: 900,
    color: whiteAlpha(0.4),
    textTransform: "uppercase",
    letterSpacing: 0.8,
    textAlign: "center",
  },
  preSessionSparkWrap: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 3,
    flex: 1,
  },
  preSessionSparkBars: {
    display: "flex",
    alignItems: "flex-end",
    gap: 3,
    height: 36,
  },
  preSessionSparkBar: {
    width: 8,
    borderRadius: "2px 2px 0 0",
    transition: "height 0.5s ease",
  },
  resultSparklineCard: {
    marginTop: 14,
    padding: "12px 14px",
    borderRadius: RADIUS.md,
    background: whiteAlpha(0.03),
    border: `1px solid ${BORDER_2}`,
  },
  resultSparklineTitle: {
    margin: "0 0 10px",
    fontSize: 10,
    fontWeight: 900,
    color: whiteAlpha(0.45),
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  resultSparklineBars: {
    display: "flex",
    alignItems: "flex-end",
    gap: 5,
    height: 56,
  },

  // ── Result — new best / vs ghost comparison card ──────────────────────────
  newBestCard: {
    margin: "14px 0 0",
    padding: "14px 16px",
    borderRadius: 16,
    background: "linear-gradient(135deg, rgba(52,211,153,0.14), rgba(11,11,11,0.92))",
    border: "1px solid rgba(52,211,153,0.35)",
    textAlign: "center",
    display: "flex",
    flexDirection: "column",
    gap: 8,
    alignItems: "center",
  },
  vsGhostCard: {
    margin: "14px 0 0",
    padding: "14px 16px",
    borderRadius: 16,
    background: whiteAlpha(0.04),
    border: `1px solid ${whiteAlpha(0.1)}`,
    textAlign: "center",
    display: "flex",
    flexDirection: "column",
    gap: 8,
    alignItems: "center",
  },
  newBestBadge: {
    fontSize: 11,
    fontWeight: 1000,
    letterSpacing: 1.6,
    color: "#34D399",
    textTransform: "uppercase",
  },
  vsCompareRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 14,
  },
  vsCompareCell: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 2,
  },
  vsCompareLbl: {
    fontSize: 9,
    fontWeight: 900,
    color: whiteAlpha(0.45),
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  vsCompareScore: {
    fontSize: 30,
    fontWeight: 1000,
    color: "#fff",
    lineHeight: 1,
    fontFamily: "var(--font-display, 'Anton', sans-serif)",
  },
  vsCompareDelta: {
    fontSize: 18,
    fontWeight: 1000,
    minWidth: 44,
    textAlign: "center",
  },
  almostMsg: {
    fontSize: 12,
    color: whiteAlpha(0.55),
    fontWeight: 700,
  },
};

export default styles;
