import { RED, GOLD, redAlpha, goldAlpha } from "@/lib/tokens";

export const trainStageStyles = {
  stage: {
    position: "relative",
    overflow: "hidden",
    borderRadius: 22,
    minHeight: 460,
    aspectRatio: "9 / 14",
    background: "#050505",
    border: "1px solid rgba(255,255,255,0.1)",
    boxShadow: "0 24px 70px rgba(0,0,0,0.46)",
  },
  preview: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    display: "block",
    transform: "scaleX(-1)",
  },
  fallback: {
    position: "absolute",
    inset: 0,
    display: "grid",
    alignContent: "center",
    justifyItems: "center",
    gap: 12,
    padding: 28,
    textAlign: "center",
    background: `radial-gradient(circle at 50% 38%, ${goldAlpha(0.13)}, transparent 30%), linear-gradient(145deg, #12090a, #050505)`,
  },
  fallbackMark: {
    border: `1px solid ${redAlpha(0.55)}`,
    borderRadius: 999,
    padding: "7px 12px",
    color: "#FF6B6B",
    fontSize: 11,
    fontWeight: 1000,
    letterSpacing: 1.5,
  },
  fallbackTitle: {
    margin: 0,
    fontSize: 22,
    fontWeight: 950,
  },
  fallbackText: {
    margin: 0,
    color: "rgba(255,255,255,0.64)",
    fontSize: 14,
    lineHeight: 1.5,
  },
  stageShade: {
    position: "absolute",
    inset: 0,
    pointerEvents: "none",
    background: "linear-gradient(to top, rgba(0,0,0,0.38), transparent 48%)",
  },
  countdown: {
    position: "absolute",
    inset: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 140,
    fontWeight: 1000,
    fontFamily: "var(--font-display, 'Anton', sans-serif)",
    color: "#fff",
    textShadow: `0 0 80px ${redAlpha(0.7)}, 0 18px 60px rgba(0,0,0,0.9)`,
    zIndex: 10,
    pointerEvents: "none",
  },
  countdownGo: {
    fontSize: 100,
    color: "#34D399",
    textShadow: "0 0 80px rgba(52,211,153,0.65), 0 18px 60px rgba(0,0,0,0.9)",
  },
  flashOverlay: {
    position: "absolute",
    inset: 0,
    background: `${redAlpha(0.38)}`,
    zIndex: 8,
    pointerEvents: "none",
    animation: "flashFade 150ms ease-out forwards",
  },
  hitCounter: {
    position: "absolute",
    top: 64,
    left: "50%",
    transform: "translateX(-50%)",
    display: "flex",
    alignItems: "baseline",
    gap: 4,
    background: "rgba(0,0,0,0.58)",
    backdropFilter: "blur(12px)",
    WebkitBackdropFilter: "blur(12px)",
    borderRadius: 999,
    padding: "5px 16px",
    border: "1px solid rgba(255,255,255,0.16)",
    zIndex: 5,
    whiteSpace: "nowrap",
  },
  hitCountNum: {
    color: "#fff",
    fontSize: 24,
    fontWeight: 1000,
    lineHeight: 1,
    textShadow: `0 0 20px ${goldAlpha(0.5)}`,
  },
  hitCountSep: {
    color: "rgba(255,255,255,0.62)",
    fontSize: 14,
    fontWeight: 700,
    margin: "0 2px",
  },
  hitCountTarget: {
    color: "rgba(255,255,255,0.65)",
    fontSize: 16,
    fontWeight: 800,
  },
  hitCountLabel: {
    color: "rgba(255,255,255,0.65)",
    fontSize: 11,
    fontWeight: 700,
    marginLeft: 3,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  comboCounter: {
    position: "absolute",
    bottom: 70,
    left: "50%",
    transform: "translateX(-50%)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    zIndex: 6,
    pointerEvents: "none",
  },
  comboLabel: {
    color: GOLD,
    fontSize: 10,
    fontWeight: 1000,
    letterSpacing: 2.5,
    textShadow: "0 2px 8px rgba(0,0,0,0.95)",
    textTransform: "uppercase",
  },
  comboNum: {
    color: "#fff",
    fontSize: 64,
    fontWeight: 1000,
    fontFamily: "var(--font-display, 'Anton', sans-serif)",
    lineHeight: 1,
    textShadow: `0 0 40px ${goldAlpha(0.55)}, 0 4px 18px rgba(0,0,0,0.95)`,
  },
  liveFeedbackBox: {
    position: "absolute",
    top: "32%",
    left: "50%",
    transform: "translateX(-50%)",
    background: "rgba(0,0,0,0.72)",
    backdropFilter: "blur(14px)",
    WebkitBackdropFilter: "blur(14px)",
    border: "1px solid rgba(255,255,255,0.22)",
    borderRadius: 999,
    padding: "9px 22px",
    color: "#fff",
    fontSize: 15,
    fontWeight: 900,
    whiteSpace: "nowrap",
    zIndex: 9,
    textShadow: "0 2px 8px rgba(0,0,0,0.9)",
    pointerEvents: "none",
  },
  recordingHud: {
    position: "absolute",
    top: 16,
    left: 16,
    right: 16,
    minHeight: 38,
    display: "flex",
    alignItems: "center",
    gap: 9,
    borderRadius: 999,
    padding: "0 13px",
    background: "rgba(0,0,0,0.54)",
    border: "1px solid rgba(255,255,255,0.12)",
    backdropFilter: "blur(14px)",
    WebkitBackdropFilter: "blur(14px)",
    fontSize: 12,
    fontWeight: 900,
    zIndex: 5,
  },
  recordDot: {
    width: 9,
    height: 9,
    borderRadius: "50%",
    background: RED,
    flexShrink: 0,
    boxShadow: `0 0 0 6px ${redAlpha(0.18)}`,
  },
  liveScoreHud: {
    marginLeft: 8,
    fontSize: 13,
    fontWeight: 1000,
    color: GOLD,
    letterSpacing: 0.5,
  },
  controls: {
    display: "grid",
    gap: 12,
  },
  startButton: {
    minHeight: 58,
    border: `1px solid ${goldAlpha(0.34)}`,
    borderRadius: 16,
    background: RED,
    color: "#fff",
    fontSize: 15,
    fontWeight: 1000,
    letterSpacing: 1.2,
    cursor: "pointer",
    boxShadow: `0 18px 44px ${redAlpha(0.26)}`,
  },
  stopButton: {
    minHeight: 54,
    border: "1px solid rgba(255,255,255,0.12)",
    borderRadius: 16,
    background: "rgba(255,255,255,0.08)",
    color: "#fff",
    fontSize: 15,
    fontWeight: 950,
    cursor: "pointer",
  },
  error: {
    padding: 12,
    borderRadius: 12,
    background: `${redAlpha(0.14)}`,
    border: `1px solid ${redAlpha(0.35)}`,
    color: "#ffb4b4",
    fontSize: 13,
  },
  saved: {
    padding: 12,
    borderRadius: 12,
    background: "rgba(52,211,153,0.12)",
    border: "1px solid rgba(52,211,153,0.28)",
    color: "#A7F3D0",
    fontSize: 13,
    fontWeight: 800,
  },
};
