import { RED, GOLD, BG, RADIUS, redAlpha, goldAlpha, whiteAlpha, blackAlpha } from "@/lib/tokens";

export const trainStageStyles = {
  // ── Camera stage ──────────────────────────────────────────────────────────
  stage: {
    position: "relative",
    overflow: "hidden",
    borderRadius: 28,
    minHeight: 460,
    aspectRatio: "9 / 14",
    background: BG,
    border: `1px solid ${whiteAlpha(0.07)}`,
    boxShadow: `0 32px 80px ${blackAlpha(0.55)}, 0 0 0 1px ${whiteAlpha(0.03)}`,
  },
  preview: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    display: "block",
    transform: "scaleX(-1)",
  },

  // ── Fallback (no camera) ──────────────────────────────────────────────────
  fallback: {
    position: "absolute",
    inset: 0,
    display: "grid",
    alignContent: "center",
    justifyItems: "center",
    gap: 12,
    padding: 28,
    textAlign: "center",
    background: `radial-gradient(ellipse at 50% 35%, ${goldAlpha(0.1)}, transparent 55%), linear-gradient(160deg, #0e0608, ${BG})`,
  },
  fallbackMark: {
    border: `1px solid ${redAlpha(0.5)}`,
    borderRadius: 8,
    padding: "6px 14px",
    color: "#FF6B6B",
    fontSize: 10,
    fontWeight: 900,
    letterSpacing: 2,
    textTransform: "uppercase",
  },
  fallbackTitle: { margin: 0, fontSize: 20, fontWeight: 950 },
  fallbackText: { margin: 0, color: whiteAlpha(0.55), fontSize: 13, lineHeight: 1.55 },

  // ── Overlays ──────────────────────────────────────────────────────────────
  stageShade: {
    position: "absolute",
    inset: 0,
    pointerEvents: "none",
    background: `linear-gradient(to top, ${blackAlpha(0.5)} 0%, transparent 45%)`,
  },
  flashOverlay: {
    position: "absolute",
    inset: 0,
    background: redAlpha(0.32),
    zIndex: 8,
    pointerEvents: "none",
    animation: "flashFade 150ms ease-out forwards",
  },

  // ── Countdown ─────────────────────────────────────────────────────────────
  countdown: {
    position: "absolute",
    inset: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 148,
    fontWeight: 1000,
    fontFamily: "var(--font-display, 'Anton', sans-serif)",
    color: "#fff",
    textShadow: `0 0 80px ${redAlpha(0.75)}, 0 20px 60px ${blackAlpha(0.95)}`,
    zIndex: 10,
    pointerEvents: "none",
    letterSpacing: "-0.04em",
  },
  countdownGo: {
    fontSize: 104,
    color: "#34D399",
    textShadow: `0 0 80px rgba(52,211,153,0.7), 0 20px 60px ${blackAlpha(0.95)}`,
    letterSpacing: "0.04em",
  },

  // ── Recording HUD (top bar) ───────────────────────────────────────────────
  recordingHud: {
    position: "absolute",
    top: 14,
    left: 12,
    right: 12,
    height: 40,
    display: "flex",
    alignItems: "center",
    gap: 8,
    borderRadius: 20,
    padding: "0 14px",
    background: blackAlpha(0.6),
    border: `1px solid ${whiteAlpha(0.1)}`,
    backdropFilter: "blur(16px)",
    WebkitBackdropFilter: "blur(16px)",
    fontSize: 12,
    fontWeight: 900,
    zIndex: 5,
    boxShadow: `0 4px 20px ${blackAlpha(0.4)}`,
  },
  recordDot: {
    width: 8,
    height: 8,
    borderRadius: "50%",
    background: RED,
    flexShrink: 0,
    boxShadow: `0 0 0 4px ${redAlpha(0.22)}`,
    animation: "livePulse 1.2s ease-in-out infinite",
  },
  liveScoreHud: {
    marginLeft: 6,
    fontSize: 14,
    fontWeight: 1000,
    color: GOLD,
    letterSpacing: 0.5,
    fontFamily: "var(--font-display, 'Anton', sans-serif)",
  },

  // ── Hit counter (center) ──────────────────────────────────────────────────
  hitCounter: {
    position: "absolute",
    top: 66,
    left: "50%",
    transform: "translateX(-50%)",
    display: "flex",
    alignItems: "baseline",
    gap: 3,
    background: blackAlpha(0.55),
    backdropFilter: "blur(14px)",
    WebkitBackdropFilter: "blur(14px)",
    borderRadius: RADIUS.full,
    padding: "6px 18px",
    border: `1px solid ${whiteAlpha(0.12)}`,
    zIndex: 5,
    whiteSpace: "nowrap",
  },
  hitCountNum: {
    color: "#fff",
    fontSize: 26,
    fontWeight: 1000,
    lineHeight: 1,
    fontFamily: "var(--font-display, 'Anton', sans-serif)",
    textShadow: `0 0 20px ${goldAlpha(0.55)}`,
  },
  hitCountSep:    { color: whiteAlpha(0.5), fontSize: 14, fontWeight: 700, margin: "0 1px" },
  hitCountTarget: { color: whiteAlpha(0.55), fontSize: 16, fontWeight: 800 },
  hitCountLabel:  { color: whiteAlpha(0.45), fontSize: 10, fontWeight: 800, marginLeft: 4, textTransform: "uppercase", letterSpacing: 0.8 },

  // ── Combo counter ─────────────────────────────────────────────────────────
  comboCounter: {
    position: "absolute",
    bottom: 144,
    left: "50%",
    transform: "translateX(-50%)",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    zIndex: 21,
    pointerEvents: "none",
  },
  comboLabel: {
    color: GOLD,
    fontSize: 10,
    fontWeight: 1000,
    letterSpacing: 3,
    textShadow: `0 2px 8px ${blackAlpha(0.95)}`,
    textTransform: "uppercase",
  },
  comboNum: {
    color: "#fff",
    fontSize: 72,
    fontWeight: 1000,
    fontFamily: "var(--font-display, 'Anton', sans-serif)",
    lineHeight: 0.95,
    textShadow: `0 0 50px ${goldAlpha(0.65)}, 0 4px 20px ${blackAlpha(0.95)}`,
    letterSpacing: "-0.03em",
  },

  // ── Live feedback toast ────────────────────────────────────────────────────
  liveFeedbackBox: {
    position: "absolute",
    top: "34%",
    left: "50%",
    transform: "translateX(-50%)",
    background: blackAlpha(0.75),
    backdropFilter: "blur(16px)",
    WebkitBackdropFilter: "blur(16px)",
    border: `1px solid ${whiteAlpha(0.18)}`,
    borderRadius: RADIUS.full,
    padding: "10px 24px",
    color: "#fff",
    fontSize: 14,
    fontWeight: 900,
    whiteSpace: "nowrap",
    zIndex: 9,
    textShadow: `0 2px 8px ${blackAlpha(0.9)}`,
    pointerEvents: "none",
    boxShadow: `0 8px 32px ${blackAlpha(0.5)}`,
  },
};
