import { RED, GOLD, redAlpha, goldAlpha } from "@/lib/tokens";

export const trainModalStyles = {
  modalSaved: {
    marginTop: 14,
    padding: 12,
    borderRadius: 12,
    background: "rgba(52,211,153,0.12)",
    border: "1px solid rgba(52,211,153,0.28)",
    color: "#A7F3D0",
    fontSize: 13,
    fontWeight: 900,
  },
  missionCompleteBanner: {
    marginTop: 14,
    padding: "12px 14px",
    borderRadius: 14,
    background: `linear-gradient(135deg, ${goldAlpha(0.15)}, rgba(52,211,153,0.10))`,
    border: `1px solid ${goldAlpha(0.35)}`,
    display: "grid",
    gap: 4,
    textAlign: "center",
  },
  missionCompleteTitle: {
    fontSize: 14,
    fontWeight: 1000,
    color: GOLD,
    letterSpacing: 0.3,
  },
  missionCompleteXP: {
    fontSize: 18,
    fontWeight: 1000,
    color: "#34D399",
  },
  missionStreakBonusText: {
    color: "#FB923C",
    fontSize: 14,
  },
  missionCompleteSub: {
    fontSize: 11,
    color: "#888",
    fontWeight: 700,
  },
  modalWrap: {
    position: "fixed",
    inset: 0,
    zIndex: 200,
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "center",
    padding: "20px 16px calc(92px + env(safe-area-inset-bottom))",
  },
  modalOverlay: {
    position: "absolute",
    inset: 0,
    background: "rgba(0,0,0,0.72)",
    backdropFilter: "blur(14px)",
    WebkitBackdropFilter: "blur(14px)",
  },
  modal: {
    position: "relative",
    width: "100%",
    maxWidth: 460,
    borderRadius: 28,
    background: "rgba(16,14,18,0.97)",
    border: `1px solid ${goldAlpha(0.18)}`,
    boxShadow: `0 -32px 80px rgba(0,0,0,0.65), 0 0 0 1px rgba(255,255,255,0.03), 0 0 60px ${redAlpha(0.08)}`,
    backdropFilter: "blur(28px)",
    WebkitBackdropFilter: "blur(28px)",
    textAlign: "center",
    maxHeight: "min(620px, calc(100dvh - 120px))",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  modalTop: {
    padding: "18px 20px 14px",
    flexShrink: 0,
  },
  modalMiddle: {
    overflowY: "auto",
    padding: "0 20px",
    flex: 1,
  },
  modalBottom: {
    padding: "12px 20px 16px",
    flexShrink: 0,
    borderTop: "1px solid rgba(255,255,255,0.06)",
  },
  modalKicker: {
    margin: 0,
    color: GOLD,
    fontSize: 11,
    fontWeight: 900,
    letterSpacing: 3,
    textTransform: "uppercase",
    fontFamily: "var(--font-condensed)",
  },
  score: {
    marginTop: 8,
    fontSize: 72,
    lineHeight: 0.95,
    fontWeight: 1000,
    fontFamily: "var(--font-display, 'Anton', sans-serif)",
  },
  scoreUnit: {
    color: "rgba(255,255,255,0.52)",
    fontSize: 16,
    fontWeight: 900,
  },
  resultGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 10,
    marginTop: 18,
  },
  resultItem: {
    display: "grid",
    gap: 6,
    padding: 14,
    borderRadius: 14,
    background: "rgba(255,255,255,0.055)",
    border: "1px solid rgba(255,255,255,0.08)",
    color: "rgba(255,255,255,0.62)",
    fontSize: 12,
    fontWeight: 800,
  },
  targetResultItem: {
    gridColumn: "1 / -1",
    background: `${goldAlpha(0.13)}`,
    border: `1px solid ${goldAlpha(0.28)}`,
    color: "rgba(253,230,138,0.78)",
    boxShadow: `0 0 28px ${goldAlpha(0.12)}`,
  },
  progressTrack: {
    height: 8,
    borderRadius: 999,
    marginTop: 16,
    background: "rgba(255,255,255,0.09)",
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    borderRadius: 999,
    background: RED,
  },
  shareResultButton: {
    width: "100%",
    minHeight: 46,
    marginTop: 14,
    border: `1px solid ${goldAlpha(0.36)}`,
    borderRadius: 14,
    background: `linear-gradient(135deg, ${goldAlpha(0.18)}, ${redAlpha(0.18)})`,
    color: GOLD,
    fontSize: 14,
    fontWeight: 950,
    cursor: "pointer",
  },
  modalActions: {
    display: "grid",
    gridTemplateColumns: "1fr",
    gap: 10,
    marginTop: 18,
  },
  saveButton: {
    minHeight: 46,
    border: "none",
    borderRadius: 14,
    background: RED,
    color: "#fff",
    fontSize: 14,
    fontWeight: 950,
    cursor: "pointer",
  },
  saveButtonDone: {
    background: "#17664b",
    cursor: "default",
  },
  tryAgainButton: {
    minHeight: 46,
    border: "1px solid rgba(255,255,255,0.14)",
    borderRadius: 14,
    background: "rgba(255,255,255,0.06)",
    color: "#fff",
    fontSize: 14,
    fontWeight: 900,
    cursor: "pointer",
  },
  reelsButton: {
    minHeight: 46,
    border: `1px solid ${goldAlpha(0.32)}`,
    borderRadius: 14,
    background: `${goldAlpha(0.1)}`,
    color: GOLD,
    fontSize: 14,
    fontWeight: 950,
    cursor: "pointer",
  },
  challengeFriendButton: {
    minHeight: 46,
    border: `1px solid ${goldAlpha(0.42)}`,
    borderRadius: 14,
    background: `linear-gradient(135deg, ${redAlpha(0.92)}, ${goldAlpha(0.28)})`,
    color: "#fff",
    fontSize: 14,
    fontWeight: 1000,
    cursor: "pointer",
    boxShadow: `0 14px 34px ${redAlpha(0.22)}`,
  },
};
