import { RED, RED_DARK, GOLD, BG, BORDER, BORDER_2, RADIUS, redAlpha, goldAlpha, whiteAlpha, blackAlpha } from "@/lib/tokens";

export const trainPageStyles = {
  // ── Page shell ────────────────────────────────────────────────────────────
  page: {
    minHeight: "100dvh",
    background: `radial-gradient(ellipse at 50% -5%, ${redAlpha(0.18)} 0%, transparent 48%), ${BG}`,
    color: "#fff",
    padding: "calc(68px + env(safe-area-inset-top)) 16px calc(92px + env(safe-area-inset-bottom))",
  },
  loading: {
    minHeight: "100dvh",
    background: BG,
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },

  // ── Back button ───────────────────────────────────────────────────────────
  backButton: {
    position: "fixed",
    top: "calc(14px + env(safe-area-inset-top))",
    left: "max(14px, env(safe-area-inset-left))",
    zIndex: 40,
    width: 40,
    height: 40,
    padding: 0,
    borderRadius: RADIUS.md,
    border: `1px solid ${whiteAlpha(0.1)}`,
    background: blackAlpha(0.55),
    color: "#fff",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    backdropFilter: "blur(16px)",
    WebkitBackdropFilter: "blur(16px)",
  },
  backIcon: { fontSize: 24, lineHeight: 1, color: GOLD },

  // ── Content shell ─────────────────────────────────────────────────────────
  shell: { maxWidth: 500, margin: "0 auto", display: "grid", gap: 18 },

  // ── Header ───────────────────────────────────────────────────────────────
  header: { display: "grid", gap: 6 },
  kicker: {
    margin: 0,
    color: RED,
    fontSize: 10,
    fontWeight: 900,
    letterSpacing: 3,
    textTransform: "uppercase",
  },
  title: {
    margin: 0,
    fontSize: "clamp(30px, 9vw, 40px)",
    lineHeight: 0.95,
    fontWeight: 1000,
    letterSpacing: "-0.02em",
    fontFamily: "var(--font-display, 'Anton', sans-serif)",
    textTransform: "uppercase",
  },
  subtitle: {
    margin: 0,
    color: whiteAlpha(0.5),
    fontSize: 13,
    lineHeight: 1.45,
    maxWidth: 420,
    fontWeight: 400,
  },

  // ── PvP banner + target ───────────────────────────────────────────────────
  targetScorePill: {
    width: "fit-content",
    display: "inline-flex",
    alignItems: "center",
    minHeight: 34,
    padding: "0 14px",
    borderRadius: RADIUS.full,
    background: goldAlpha(0.12),
    border: `1px solid ${goldAlpha(0.32)}`,
    boxShadow: `0 8px 28px ${goldAlpha(0.1)}`,
  },
  targetScoreLabel: { color: "#FDE68A", fontSize: 13, fontWeight: 1000 },
  pvpBanner: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 14px",
    borderRadius: RADIUS.md,
    background: "rgba(96,165,250,0.08)",
    border: "1px solid rgba(96,165,250,0.25)",
  },
  pvpBannerVs:     { fontSize: 20, flexShrink: 0 },
  pvpBannerText:   { display: "flex", flexDirection: "column", gap: 2 },
  pvpBannerLabel:  { color: "#93C5FD", fontSize: 13, fontWeight: 900, lineHeight: 1.2 },
  pvpBannerScore:  { color: GOLD, fontSize: 18, fontWeight: 1000, lineHeight: 1 },

  pvpWinBanner:    { margin: "14px 0 0", padding: "14px 16px", borderRadius: RADIUS.md, background: "rgba(52,211,153,0.1)", border: "1px solid rgba(52,211,153,0.3)", textAlign: "center" },
  pvpLoseBanner:   { margin: "14px 0 0", padding: "14px 16px", borderRadius: RADIUS.md, background: redAlpha(0.1), border: `1px solid ${redAlpha(0.3)}`, textAlign: "center" },
  pvpResultBadge:  { display: "inline-block", padding: "3px 14px", borderRadius: RADIUS.full, fontSize: 11, fontWeight: 1000, letterSpacing: 2, textTransform: "uppercase", background: whiteAlpha(0.08), color: "#fff", marginBottom: 8 },
  pvpResultHeadline:  { fontSize: 15, fontWeight: 1000, color: "#fff", marginBottom: 10 },
  pvpResultScoreRow:  { display: "flex", alignItems: "center", justifyContent: "center", gap: 12, marginBottom: 6 },
  pvpResultScoreCell: { display: "flex", flexDirection: "column", alignItems: "center", gap: 2 },
  pvpResultScoreNum:  { fontSize: 28, fontWeight: 1000, lineHeight: 1, color: "#fff" },
  pvpResultScoreLbl:  { fontSize: 11, color: whiteAlpha(0.55), fontWeight: 700 },
  pvpResultScoreVs:   { fontSize: 12, color: whiteAlpha(0.62), fontWeight: 700 },
  pvpResultDiff:      { fontSize: 20, fontWeight: 1000, marginBottom: 6 },
  pvpResultSaved:     { fontSize: 11, color: "#34D399", fontWeight: 800, marginTop: 4 },

  // ── Controls ──────────────────────────────────────────────────────────────
  controls: { display: "grid", gap: 10 },
  startButton: {
    minHeight: 60,
    border: `1px solid ${redAlpha(0.4)}`,
    borderRadius: RADIUS.lg,
    background: `linear-gradient(145deg, ${RED}, ${RED_DARK})`,
    color: "#fff",
    fontSize: 16,
    fontWeight: 900,
    letterSpacing: 2,
    textTransform: "uppercase",
    cursor: "pointer",
    boxShadow: `0 12px 40px ${redAlpha(0.35)}, inset 0 1px 0 ${whiteAlpha(0.14)}`,
    transition: "transform 180ms ease, box-shadow 180ms ease",
  },
  stopButton: {
    minHeight: 52,
    border: `1px solid ${whiteAlpha(0.1)}`,
    borderRadius: RADIUS.md,
    background: whiteAlpha(0.06),
    color: whiteAlpha(0.7),
    fontSize: 14,
    fontWeight: 800,
    letterSpacing: 1,
    textTransform: "uppercase",
    cursor: "pointer",
  },

  // ── Feedback messages ─────────────────────────────────────────────────────
  error: {
    padding: "12px 14px",
    borderRadius: 12,
    background: redAlpha(0.12),
    border: `1px solid ${redAlpha(0.32)}`,
    color: "#ffb4b4",
    fontSize: 13,
  },
  saved: {
    padding: "12px 14px",
    borderRadius: 12,
    background: "rgba(52,211,153,0.1)",
    border: "1px solid rgba(52,211,153,0.26)",
    color: "#A7F3D0",
    fontSize: 13,
    fontWeight: 800,
  },

  // ── Breakdown card (below stage) ──────────────────────────────────────────
  breakdownCard:  { marginTop: 14, padding: "14px 16px", borderRadius: 16, background: whiteAlpha(0.04), border: `1px solid ${BORDER_2}` },
  breakdownTitle: { margin: "0 0 12px", fontSize: 10, fontWeight: 900, color: whiteAlpha(0.4), textTransform: "uppercase", letterSpacing: 1.5 },
  breakdownGrid:  { display: "grid", gridTemplateColumns: "1fr 1fr", gap: "12px 16px" },
  breakdownItem:  { display: "flex", flexDirection: "column", gap: 4 },
  breakdownLbl:   { fontSize: 11, color: whiteAlpha(0.45), fontWeight: 700 },
  breakdownVal:   { fontSize: 20, fontWeight: 1000, lineHeight: 1 },
  breakdownTrack: { height: 3, borderRadius: RADIUS.full, background: BORDER, overflow: "hidden", marginTop: 2 },
  breakdownFill:  { height: "100%", borderRadius: RADIUS.full, transition: "width 0.6s ease" },
};
