import { GOLD, redAlpha, goldAlpha } from "@/lib/tokens";

export const trainPageStyles = {
  breakdownCard: {
    marginTop: 14,
    padding: "14px 16px",
    borderRadius: 16,
    background: "rgba(255,255,255,0.04)",
    border: "1px solid rgba(255,255,255,0.09)",
  },
  breakdownTitle: {
    margin: "0 0 12px",
    fontSize: 11,
    fontWeight: 900,
    color: "rgba(255,255,255,0.65)",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  breakdownGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: "12px 16px",
  },
  breakdownItem: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  breakdownLbl: {
    fontSize: 11,
    color: "rgba(255,255,255,0.5)",
    fontWeight: 700,
  },
  breakdownVal: {
    fontSize: 20,
    fontWeight: 1000,
    lineHeight: 1,
  },
  breakdownTrack: {
    height: 4,
    borderRadius: 999,
    background: "rgba(255,255,255,0.08)",
    overflow: "hidden",
    marginTop: 2,
  },
  breakdownFill: {
    height: "100%",
    borderRadius: 999,
    transition: "width 0.6s ease",
  },
  page: {
    minHeight: "100dvh",
    background: `radial-gradient(circle at 50% 0%, ${redAlpha(0.2)}, transparent 34%), linear-gradient(180deg, #080808 0%, #0B0B0B 100%)`,
    color: "#fff",
    padding: "calc(68px + env(safe-area-inset-top)) 16px calc(92px + env(safe-area-inset-bottom))",
  },
  loading: {
    minHeight: "100dvh",
    background: "#070707",
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  backButton: {
    position: "fixed",
    top: "calc(14px + env(safe-area-inset-top))",
    left: "max(14px, env(safe-area-inset-left))",
    zIndex: 40,
    width: 40,
    height: 40,
    padding: 0,
    borderRadius: 999,
    border: "1px solid rgba(255,255,255,0.12)",
    background: "rgba(0,0,0,0.44)",
    color: "#fff",
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    backdropFilter: "blur(14px)",
    WebkitBackdropFilter: "blur(14px)",
  },
  backIcon: {
    fontSize: 24,
    lineHeight: 1,
    color: GOLD,
  },
  shell: {
    maxWidth: 520,
    margin: "0 auto",
    display: "grid",
    gap: 18,
  },
  header: {
    display: "grid",
    gap: 8,
  },
  kicker: {
    margin: 0,
    color: GOLD,
    fontSize: 11,
    fontWeight: 950,
    letterSpacing: 2,
    textTransform: "uppercase",
  },
  title: {
    margin: 0,
    fontSize: 34,
    lineHeight: 1,
    fontWeight: 1000,
    letterSpacing: 0,
    fontFamily: "var(--font-display, 'Anton', sans-serif)",
  },
  subtitle: {
    margin: 0,
    color: "rgba(255,255,255,0.66)",
    fontSize: 14,
    lineHeight: 1.45,
    maxWidth: 420,
  },
  targetScorePill: {
    width: "fit-content",
    display: "inline-flex",
    alignItems: "center",
    minHeight: 36,
    padding: "0 13px",
    borderRadius: 999,
    background: `${goldAlpha(0.16)}`,
    border: `1px solid ${goldAlpha(0.34)}`,
    boxShadow: `0 12px 32px ${goldAlpha(0.12)}`,
  },
  targetScoreLabel: {
    color: "#FDE68A",
    fontSize: 13,
    fontWeight: 1000,
  },
  pvpBanner: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 14px",
    borderRadius: 14,
    background: "rgba(96,165,250,0.1)",
    border: "1px solid rgba(96,165,250,0.3)",
  },
  pvpBannerVs: {
    fontSize: 20,
    flexShrink: 0,
  },
  pvpBannerText: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
  },
  pvpBannerLabel: {
    color: "#93C5FD",
    fontSize: 13,
    fontWeight: 900,
    lineHeight: 1.2,
  },
  pvpBannerScore: {
    color: GOLD,
    fontSize: 18,
    fontWeight: 1000,
    lineHeight: 1,
  },
  pvpWinBanner: {
    margin: "14px 0 0",
    padding: "14px 16px",
    borderRadius: 14,
    background: "rgba(52,211,153,0.12)",
    border: "1px solid rgba(52,211,153,0.35)",
    textAlign: "center",
  },
  pvpLoseBanner: {
    margin: "14px 0 0",
    padding: "14px 16px",
    borderRadius: 14,
    background: `${redAlpha(0.12)}`,
    border: `1px solid ${redAlpha(0.35)}`,
    textAlign: "center",
  },
  pvpResultBadge: {
    display: "inline-block",
    padding: "3px 14px",
    borderRadius: 999,
    fontSize: 11,
    fontWeight: 1000,
    letterSpacing: 2,
    textTransform: "uppercase",
    background: "rgba(255,255,255,0.1)",
    color: "#fff",
    marginBottom: 8,
  },
  pvpResultHeadline: {
    fontSize: 15,
    fontWeight: 1000,
    color: "#fff",
    marginBottom: 10,
  },
  pvpResultScoreRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 12,
    marginBottom: 6,
  },
  pvpResultScoreCell: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 2,
  },
  pvpResultScoreNum: {
    fontSize: 28,
    fontWeight: 1000,
    lineHeight: 1,
    color: "#fff",
  },
  pvpResultScoreLbl: {
    fontSize: 11,
    color: "rgba(255,255,255,0.55)",
    fontWeight: 700,
  },
  pvpResultScoreVs: {
    fontSize: 12,
    color: "rgba(255,255,255,0.62)",
    fontWeight: 700,
  },
  pvpResultDiff: {
    fontSize: 20,
    fontWeight: 1000,
    marginBottom: 6,
  },
  pvpResultSaved: {
    fontSize: 11,
    color: "#34D399",
    fontWeight: 800,
    marginTop: 4,
  },
};
