import { GOLD } from "@/lib/tokens";

export const trainContextStyles = {
  ghostHud: {
    position: "absolute",
    top: 64,
    right: 12,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 3,
    background: "rgba(0,0,0,0.62)",
    backdropFilter: "blur(12px)",
    WebkitBackdropFilter: "blur(12px)",
    borderRadius: 14,
    padding: "8px 14px",
    border: "1px solid rgba(255,255,255,0.14)",
    zIndex: 5,
    minWidth: 60,
  },
  ghostHudRow: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 1,
  },
  ghostHudYouLabel: {
    color: GOLD,
    fontSize: 9,
    fontWeight: 1000,
    letterSpacing: 1.5,
    textTransform: "uppercase",
  },
  ghostHudYouScore: {
    color: GOLD,
    fontSize: 20,
    fontWeight: 1000,
    lineHeight: 1,
  },
  ghostHudSep: {
    color: "rgba(255,255,255,0.58)",
    fontSize: 10,
    fontWeight: 700,
  },
  ghostHudGhostLabel: {
    color: "rgba(255,255,255,0.6)",
    fontSize: 12,
    lineHeight: 1,
  },
  ghostHudGhostScore: {
    color: "rgba(255,255,255,0.85)",
    fontSize: 20,
    fontWeight: 1000,
    lineHeight: 1,
  },
  ghostToggleOn: {
    minHeight: 40,
    border: "1px solid rgba(255,255,255,0.2)",
    borderRadius: 12,
    background: "rgba(255,255,255,0.08)",
    color: "#fff",
    fontSize: 13,
    fontWeight: 900,
    cursor: "pointer",
  },
  ghostToggleOff: {
    minHeight: 40,
    border: "1px solid rgba(255,255,255,0.08)",
    borderRadius: 12,
    background: "transparent",
    color: "rgba(255,255,255,0.58)",
    fontSize: 13,
    fontWeight: 700,
    cursor: "pointer",
  },
  ghostWinBanner: {
    margin: "14px 0 0",
    padding: "12px 16px",
    borderRadius: 14,
    background: "rgba(52,211,153,0.12)",
    border: "1px solid rgba(52,211,153,0.35)",
    textAlign: "center",
    fontSize: 15,
    fontWeight: 1000,
    color: "#34D399",
  },
  ghostLoseBanner: {
    margin: "14px 0 0",
    padding: "12px 16px",
    borderRadius: 14,
    background: "rgba(255,255,255,0.05)",
    border: "1px solid rgba(255,255,255,0.1)",
    textAlign: "center",
    fontSize: 15,
    fontWeight: 1000,
    color: "rgba(255,255,255,0.65)",
  },
  ghostBestScoreRow: {
    marginTop: 4,
    fontSize: 12,
    color: "rgba(255,255,255,0.65)",
    fontWeight: 700,
  },
  ghostHudState: {
    marginTop: 5,
    fontSize: 8,
    fontWeight: 1000,
    letterSpacing: 1.4,
    textTransform: "uppercase",
  },

  // Pre-game context card
  contextCard: {
    padding: "14px 16px",
    borderRadius: 16,
    background: "rgba(255,255,255,0.04)",
    border: "1px solid rgba(255,255,255,0.08)",
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  contextStatsRow: {
    display: "flex",
    gap: 12,
    alignItems: "flex-start",
  },
  contextStat: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
    flex: 1,
  },
  contextStatLabel: {
    fontSize: 10,
    fontWeight: 900,
    color: "rgba(255,255,255,0.45)",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  contextStatValue: {
    fontSize: 24,
    fontWeight: 1000,
    color: "#fff",
    lineHeight: 1,
    fontFamily: "var(--font-display, 'Anton', sans-serif)",
  },
  contextStatUnit: {
    fontSize: 13,
    fontWeight: 700,
    color: "rgba(255,255,255,0.5)",
    marginLeft: 2,
  },
  contextEmptyMsg: {
    fontSize: 13,
    color: "rgba(255,255,255,0.5)",
    fontWeight: 700,
    textAlign: "center",
    padding: "4px 0",
  },
  contextGhostNote: {
    fontSize: 11,
    color: "rgba(255,255,255,0.38)",
    fontWeight: 700,
    borderTop: "1px solid rgba(255,255,255,0.07)",
    paddingTop: 8,
  },
  preSessionStrip: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    paddingBottom: 10,
    borderBottom: "1px solid rgba(255,255,255,0.07)",
    marginBottom: 4,
  },
  weeklyRingWrap: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 2,
    flexShrink: 0,
  },
  weeklyRingLabel: {
    fontSize: 9,
    fontWeight: 900,
    color: "rgba(255,255,255,0.4)",
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  preSessionStat: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 3,
    flex: 1,
  },
  preSessionStatVal: {
    fontSize: 18,
    fontWeight: 1000,
    color: "#fff",
    lineHeight: 1,
    fontFamily: "var(--font-display, 'Anton', sans-serif)",
  },
  preSessionStatLbl: {
    fontSize: 9,
    fontWeight: 900,
    color: "rgba(255,255,255,0.4)",
    textTransform: "uppercase",
    letterSpacing: 0.8,
    textAlign: "center",
  },
  preSessionSparkWrap: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 3,
    flex: 1,
  },
  preSessionSparkBars: {
    display: "flex",
    alignItems: "flex-end",
    gap: 3,
    height: 36,
  },
  preSessionSparkBar: {
    width: 8,
    borderRadius: "2px 2px 0 0",
    transition: "height 0.5s ease",
  },
  resultSparklineCard: {
    marginTop: 14,
    padding: "12px 14px",
    borderRadius: 14,
    background: "rgba(255,255,255,0.03)",
    border: "1px solid rgba(255,255,255,0.08)",
  },
  resultSparklineTitle: {
    margin: "0 0 10px",
    fontSize: 10,
    fontWeight: 900,
    color: "rgba(255,255,255,0.45)",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  resultSparklineBars: {
    display: "flex",
    alignItems: "flex-end",
    gap: 5,
    height: 56,
  },

  // Result — new best / vs ghost comparison card
  newBestCard: {
    margin: "14px 0 0",
    padding: "14px 16px",
    borderRadius: 16,
    background: "linear-gradient(135deg, rgba(52,211,153,0.14), rgba(11,11,11,0.92))",
    border: "1px solid rgba(52,211,153,0.35)",
    textAlign: "center",
    display: "flex",
    flexDirection: "column",
    gap: 8,
    alignItems: "center",
  },
  vsGhostCard: {
    margin: "14px 0 0",
    padding: "14px 16px",
    borderRadius: 16,
    background: "rgba(255,255,255,0.04)",
    border: "1px solid rgba(255,255,255,0.1)",
    textAlign: "center",
    display: "flex",
    flexDirection: "column",
    gap: 8,
    alignItems: "center",
  },
  newBestBadge: {
    fontSize: 11,
    fontWeight: 1000,
    letterSpacing: 1.6,
    color: "#34D399",
    textTransform: "uppercase",
  },
  vsCompareRow: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 14,
  },
  vsCompareCell: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 2,
  },
  vsCompareLbl: {
    fontSize: 9,
    fontWeight: 900,
    color: "rgba(255,255,255,0.45)",
    textTransform: "uppercase",
    letterSpacing: 1,
  },
  vsCompareScore: {
    fontSize: 30,
    fontWeight: 1000,
    color: "#fff",
    lineHeight: 1,
    fontFamily: "var(--font-display, 'Anton', sans-serif)",
  },
  vsCompareDelta: {
    fontSize: 18,
    fontWeight: 1000,
    minWidth: 44,
    textAlign: "center",
  },
  almostMsg: {
    fontSize: 12,
    color: "rgba(255,255,255,0.55)",
    fontWeight: 700,
  },
};
