import { RED, BG, redAlpha, pageBg } from "@/lib/tokens";

const aiCoachStyles = {
  page: {
    minHeight: "100dvh",
    background: pageBg(),
    color: "var(--text-primary)",
  },
  shell: {
    maxWidth: 540,
    margin: "0 auto",
    padding: "var(--space-6)",
  },
  sectionTabRow: {
    display: "flex",
    gap: 6,
    marginBottom: 16,
    background: "rgba(255,255,255,0.03)",
    borderRadius: 12,
    padding: 4,
  },
  sectionTabActive: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    padding: "10px 0",
    borderRadius: 9,
    background: RED,
    border: "none",
    color: "#fff",
    fontSize: 12,
    fontWeight: 900,
    cursor: "pointer",
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    boxShadow: `0 4px 16px ${redAlpha(0.18)}`,
  },
  sectionTabInactive: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    padding: "10px 0",
    borderRadius: 9,
    background: "transparent",
    border: "none",
    color: "rgba(255,255,255,0.32)",
    fontSize: 12,
    fontWeight: 800,
    cursor: "pointer",
    letterSpacing: "0.04em",
    textTransform: "uppercase",
  },
  header: {
    textAlign: "center",
    marginBottom: 32,
    paddingTop: 8,
  },
  kicker: {
    margin: 0,
    color: RED,
    letterSpacing: 3.5,
    fontSize: 9,
    fontWeight: 900,
    textTransform: "uppercase",
  },
  title: {
    margin: "8px 0 0",
    fontSize: 26,
    fontWeight: 900,
    color: "var(--text-primary)",
    letterSpacing: "-0.02em",
  },
  personas: {
    display: "grid",
    gridTemplateColumns: "repeat(3, minmax(0, 1fr))",
    gap: 8,
    marginBottom: 12,
  },
  personaButton: {
    minHeight: 52,
    padding: "10px 10px",
    borderRadius: 12,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(255,255,255,0.06)",
    background: "rgba(255,255,255,0.025)",
    color: "var(--text-primary)",
    cursor: "pointer",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    transition: "transform 180ms ease, border-color 180ms ease, background 180ms ease, box-shadow 180ms ease, opacity 180ms ease",
    opacity: 0.65,
  },
  personaIcon: {
    width: 28,
    height: 28,
    borderRadius: "50%",
    background: "rgba(255,255,255,0.05)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 14,
    fontWeight: 900,
    flexShrink: 0,
  },
  personaText: {
    display: "flex",
    textAlign: "center",
  },
  personaName: {
    color: "var(--text-primary)",
    fontSize: 11,
    fontWeight: 800,
    lineHeight: 1.2,
  },
  personaLabel: {
    display: "none",
  },
  quickActions: {
    display: "flex",
    gap: 8,
    marginBottom: 14,
    justifyContent: "flex-start",
    flexWrap: "wrap",
  },
  quickAction: {
    padding: "8px 12px",
    borderRadius: 999,
    border: "1px solid rgba(255,255,255,0.08)",
    background: "rgba(255,255,255,0.03)",
    color: "rgba(255,255,255,0.55)",
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
    transition: "opacity 150ms ease",
  },
  chatBox: {
    background: "transparent",
    borderRadius: 0,
    padding: "16px 0 14px",
    marginBottom: 20,
    height: 480,
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    borderTop: "1px solid rgba(255,255,255,0.06)",
  },
  messages: {
    flex: 1,
    overflowY: "auto",
    paddingRight: 8,
  },
  userBubble: {
    maxWidth: "74%",
    padding: "11px 15px",
    borderRadius: "18px 18px 4px 18px",
    background: RED,
    color: "#fff",
    fontSize: 14,
    lineHeight: 1.5,
    border: "none",
    boxShadow: `0 8px 24px ${redAlpha(0.12)}`,
  },
  assistantBubble: {
    maxWidth: "78%",
    padding: "11px 15px",
    borderRadius: "18px 18px 18px 4px",
    background: "rgba(18,18,18,0.95)",
    color: "rgba(255,255,255,0.85)",
    fontSize: 14,
    lineHeight: 1.55,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(255,255,255,0.07)",
    borderLeftWidth: 2,
  },
  emptyState: {
    display: "grid",
    alignContent: "center",
    gap: 16,
    height: "100%",
    color: "rgba(247,242,232,0.5)",
    fontSize: 14,
  },
  emptyTitle: {
    textAlign: "center",
    color: "rgba(255,255,255,0.55)",
    fontSize: 15,
    fontWeight: 800,
    letterSpacing: "-0.01em",
  },
  exampleThread: {
    display: "grid",
    gap: 10,
    maxWidth: 520,
    margin: "0 auto",
    width: "100%",
  },
  exampleAssistant: {
    justifySelf: "start",
    maxWidth: "82%",
    padding: "10px 13px",
    borderRadius: 14,
    background: "rgba(255,255,255,0.04)",
    border: "1px solid rgba(255,255,255,0.07)",
    lineHeight: 1.5,
    fontSize: 13,
    color: "rgba(255,255,255,0.5)",
  },
  exampleUser: {
    justifySelf: "end",
    maxWidth: "82%",
    padding: "10px 13px",
    borderRadius: 14,
    background: `${redAlpha(0.7)}`,
    lineHeight: 1.5,
    fontSize: 13,
  },
  inputRow: {
    display: "flex",
    gap: 10,
    alignItems: "center",
    marginTop: 12,
  },
  input: {
    flex: 1,
    padding: "13px 16px",
    borderRadius: 12,
    border: "1px solid rgba(255,255,255,0.08)",
    background: "rgba(255,255,255,0.04)",
    color: "var(--text-primary)",
    fontSize: 14,
    outline: "none",
  },
  sendButton: {
    width: 44,
    height: 44,
    borderRadius: 12,
    border: "none",
    color: "var(--text-primary)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
};

export default aiCoachStyles;
