import { RED, BG, PURPLE, redAlpha, pageBg } from "@/lib/tokens";

const aiCoachStyles = {
  page: {
    minHeight: "100dvh",
    background: pageBg(),
    color: "var(--text-primary)",
  },
  shell: {
    maxWidth: 540,
    margin: "0 auto",
    padding: "var(--space-6)",
  },
  sectionTabRow: {
    display: "flex",
    gap: 6,
    marginBottom: 16,
    background: "rgba(255,255,255,0.03)",
    borderRadius: 12,
    padding: 4,
  },
  sectionTabActive: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    padding: "10px 0",
    borderRadius: 9,
    background: RED,
    border: "none",
    color: "#fff",
    fontSize: 12,
    fontWeight: 900,
    cursor: "pointer",
    letterSpacing: "0.04em",
    textTransform: "uppercase",
    boxShadow: `0 4px 16px ${redAlpha(0.18)}`,
  },
  sectionTabInactive: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    padding: "10px 0",
    borderRadius: 9,
    background: "transparent",
    border: "none",
    color: "rgba(255,255,255,0.32)",
    fontSize: 12,
    fontWeight: 800,
    cursor: "pointer",
    letterSpacing: "0.04em",
    textTransform: "uppercase",
  },
  header: {
    textAlign: "center",
    marginBottom: 24,
    paddingTop: 8,
  },
  kicker: {
    margin: 0,
    color: RED,
    letterSpacing: 3.5,
    fontSize: 9,
    fontWeight: 900,
    textTransform: "uppercase",
  },
  title: {
    margin: "8px 0 0",
    fontSize: 26,
    fontWeight: 900,
    color: "var(--text-primary)",
    letterSpacing: "-0.02em",
  },

  // ── Persona character grid ──
  personaSectionLabel: {
    margin: "0 0 10px",
    fontSize: 9,
    fontWeight: 900,
    letterSpacing: "3.5px",
    textTransform: "uppercase",
    color: "rgba(255,255,255,0.28)",
  },
  personaGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, 1fr)",
    gap: 8,
    marginBottom: 16,
  },
  personaCard: {
    position: "relative",
    padding: "14px 12px",
    borderRadius: 16,
    border: "1px solid rgba(255,255,255,0.07)",
    background: "rgba(255,255,255,0.025)",
    cursor: "pointer",
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    textAlign: "left",
    transition: "transform 180ms ease, border-color 180ms ease, background 180ms ease, box-shadow 180ms ease",
    WebkitTapHighlightColor: "transparent",
    backdropFilter: "blur(12px)",
    WebkitBackdropFilter: "blur(12px)",
    opacity: 0.7,
  },
  personaCardActive: {
    opacity: 1,
    transform: "translateY(-1px)",
  },
  personaAvatar: {
    width: 44,
    height: 44,
    borderRadius: 12,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 22,
    flexShrink: 0,
  },
  personaCardContent: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    gap: 3,
  },
  personaCardName: {
    fontSize: 13,
    fontWeight: 900,
    color: "#fff",
    letterSpacing: "-0.01em",
    lineHeight: 1.1,
  },
  personaCardTagline: {
    fontSize: 11,
    fontWeight: 600,
    color: "rgba(255,255,255,0.42)",
    lineHeight: 1.3,
  },
  personaCardTags: {
    display: "flex",
    gap: 4,
    flexWrap: "wrap",
    marginTop: 2,
  },
  personaCardTag: {
    fontSize: 9,
    fontWeight: 800,
    letterSpacing: "0.5px",
    textTransform: "uppercase",
    padding: "2px 6px",
    borderRadius: 999,
    border: "1px solid",
    lineHeight: 1.4,
  },
  personaCheckBadge: {
    position: "absolute",
    top: 8,
    right: 8,
    width: 18,
    height: 18,
    borderRadius: "50%",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 10,
    fontWeight: 900,
    color: "#fff",
  },

  // ── Active coach banner ──
  personaBanner: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "12px 16px",
    borderRadius: 14,
    marginBottom: 14,
    border: "1px solid rgba(255,255,255,0.07)",
    background: "rgba(255,255,255,0.03)",
  },
  personaBannerEmoji: {
    width: 40,
    height: 40,
    borderRadius: 10,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 20,
    flexShrink: 0,
  },
  personaBannerInfo: {
    flex: 1,
    minWidth: 0,
  },
  personaBannerName: {
    margin: 0,
    fontSize: 14,
    fontWeight: 900,
    color: "#fff",
    letterSpacing: "-0.01em",
  },
  personaBannerSub: {
    margin: 0,
    fontSize: 11,
    color: "rgba(255,255,255,0.38)",
    fontWeight: 700,
    marginTop: 1,
  },
  personaBannerDot: {
    width: 8,
    height: 8,
    borderRadius: "50%",
    background: "#22C55E",
    boxShadow: "0 0 6px rgba(34,197,94,0.8)",
    flexShrink: 0,
  },

  // ── Quick actions ──
  quickActions: {
    display: "flex",
    gap: 8,
    marginBottom: 14,
    overflowX: "auto",
    scrollbarWidth: "none",
    paddingBottom: 2,
  },
  quickAction: {
    flexShrink: 0,
    padding: "8px 13px",
    borderRadius: 999,
    border: "1px solid rgba(255,255,255,0.08)",
    background: "rgba(255,255,255,0.03)",
    color: "rgba(255,255,255,0.55)",
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
    whiteSpace: "nowrap",
    transition: "opacity 150ms ease",
    WebkitTapHighlightColor: "transparent",
  },

  // ── Chat ──
  chatBox: {
    background: "transparent",
    borderRadius: 0,
    padding: "16px 0 14px",
    marginBottom: 20,
    height: 460,
    overflow: "hidden",
    display: "flex",
    flexDirection: "column",
    borderTop: "1px solid rgba(255,255,255,0.06)",
  },
  messages: {
    flex: 1,
    overflowY: "auto",
    paddingRight: 4,
  },
  userBubble: {
    maxWidth: "74%",
    padding: "11px 15px",
    borderRadius: "18px 18px 4px 18px",
    background: RED,
    color: "#fff",
    fontSize: 14,
    lineHeight: 1.5,
    border: "none",
    boxShadow: `0 8px 24px ${redAlpha(0.12)}`,
  },
  assistantBubble: {
    maxWidth: "78%",
    padding: "11px 15px",
    borderRadius: "18px 18px 18px 4px",
    background: "rgba(18,18,18,0.95)",
    color: "rgba(255,255,255,0.85)",
    fontSize: 14,
    lineHeight: 1.55,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(255,255,255,0.07)",
    borderLeftWidth: 2,
  },
  emptyState: {
    display: "grid",
    alignContent: "center",
    gap: 16,
    height: "100%",
    color: "rgba(247,242,232,0.5)",
    fontSize: 14,
  },
  introWrap: {
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  introBubble: {
    alignSelf: "flex-start",
    maxWidth: "84%",
    padding: "12px 15px",
    borderRadius: "18px 18px 18px 4px",
    background: "rgba(18,18,18,0.95)",
    color: "rgba(255,255,255,0.82)",
    fontSize: 14,
    lineHeight: 1.55,
    borderWidth: "1px",
    borderStyle: "solid",
    borderColor: "rgba(255,255,255,0.08)",
    borderLeftWidth: 2,
  },
  introHint: {
    textAlign: "center",
    fontSize: 12,
    fontWeight: 700,
    color: "rgba(255,255,255,0.22)",
    letterSpacing: "0.04em",
  },
  inputRow: {
    display: "flex",
    gap: 10,
    alignItems: "center",
    marginTop: 12,
  },
  input: {
    flex: 1,
    padding: "13px 16px",
    borderRadius: 12,
    border: "1px solid rgba(255,255,255,0.08)",
    background: "rgba(255,255,255,0.04)",
    color: "var(--text-primary)",
    fontSize: 14,
    outline: "none",
  },
  sendButton: {
    width: 44,
    height: 44,
    borderRadius: 12,
    border: "none",
    color: "var(--text-primary)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
};

export default aiCoachStyles;
