export const DNA_DAILY_MISSIONS = {
  pressure: [
    { en: "Volume Pressure",   mn: "Эзлэгч шахалт",       ko: "볼륨 프레셔",
      hint: { en: "3+ punch combos every exchange. Don't stop.", mn: "Дайралт бүрт 3+ цохилт. Зогсохгүй.", ko: "모든 교환에서 3+ 콤보. 멈추지 마세요." } },
    { en: "Body Attack",       mn: "Биед дайралт",         ko: "바디 어택",
      hint: { en: "Head-body-head. Mix your levels.", mn: "Толгой-бие-толгой. Түвшин солих.", ko: "머리-몸통-머리. 레벨 믹스." } },
    { en: "Walk Them Down",    mn: "Урагшлах",              ko: "워크 다운",
      hint: { en: "Control the center. Move forward on every exchange.", mn: "Голыг эзэл. Дайралт бүрт урагш.", ko: "중앙 컨트롤. 모든 교환에서 전진." } },
    { en: "Non-Stop Jab",      mn: "Тасралтгүй жааб",      ko: "논스톱 잽",
      hint: { en: "Set everything up with the jab. Jab your way in.", mn: "Жаабаар бүгдийг бэлд. Жааб дарж ор.", ko: "잽으로 모든 것을 세팅하세요." } },
    { en: "Relentless Pace",   mn: "Өршөөлгүй хурд",       ko: "끊임없는 페이스",
      hint: { en: "70%+ output for the full round. No rest.", mn: "Бүтэн раундад 70%+ гаралт.", ko: "풀 라운드 70%+ 출력. 휴식 없음." } },
    { en: "Inside Fighter",    mn: "Дотоод тулалдаан",      ko: "인사이드 파이터",
      hint: { en: "Get close and work the inside range.", mn: "Ойрхон ор. Дотор зайд ажилла.", ko: "가까이 붙어서 인사이드 레인지 활용." } },
    { en: "Pressure Test",     mn: "Дарамтын шалгалт",      ko: "프레셔 테스트",
      hint: { en: "Don't give them a moment's rest.", mn: "Дайсанд амрах боломж өгөхгүй.", ko: "상대에게 단 한 순간도 쉬지 못하게." } },
  ],
  outboxer: [
    { en: "Lateral Movement",  mn: "Хажуу хөдөлгөөн",      ko: "측면 이동",
      hint: { en: "Work your angles. Don't stand in front.", mn: "Өнцгөө ашигла. Өмнө нь зогсохгүй.", ko: "앵글을 활용하세요. 정면에 서지 마세요." } },
    { en: "Long Jab Control",  mn: "Урт жааб контроль",     ko: "롱 잽 컨트롤",
      hint: { en: "Keep them at the end of your jab. Control the range.", mn: "Тэднийг жаабын үзүүрт барь. Зайг контролло.", ko: "잽 끝에 상대를 유지하세요. 레인지 컨트롤." } },
    { en: "Pivot After Combo", mn: "Комбо дараах эргэлт",   ko: "콤보 후 피벗",
      hint: { en: "Throw and pivot. Never stay in the same spot.", mn: "Цохиж, эрг. Нэг газарт үлдэхгүй.", ko: "콤보 후 피벗. 같은 자리에 있지 마세요." } },
    { en: "Distance Drill",    mn: "Зайн дасгал",            ko: "거리 드릴",
      hint: { en: "Use footwork to reset to your preferred range.", mn: "Хөдөлгөөнөөрөө дуртай зайдаа буц.", ko: "풋워크로 선호 거리를 재설정하세요." } },
    { en: "Catch & Counter",   mn: "Барьж контр хий",       ko: "캐치 앤 카운터",
      hint: { en: "Parry or catch, then fire back immediately.", mn: "Барь эсвэл хааж, шууд эсрэг цох.", ko: "패링 또는 캐치 후 즉시 반격하세요." } },
    { en: "Feint & Exit",      mn: "Хуурамч & Гарах",       ko: "페인트 앤 엑시트",
      hint: { en: "Feint to open gaps. Exit after every exchange.", mn: "Завсар нээхийн тулд хуурамч хий.", ko: "틈을 열기 위해 페인트. 매 교환 후 빠져나오세요." } },
    { en: "Stick & Move",      mn: "Цох & Хөдөл",            ko: "스틱 앤 무브",
      hint: { en: "Hit once or twice and get out. Don't get trapped.", mn: "1-2 удаа цохиод гар. Хавхагдаж болохгүй.", ko: "1-2번 치고 빠지세요. 갇히지 마세요." } },
  ],
  counter: [
    { en: "Slip & Counter",    mn: "Зайлж контр хий",       ko: "슬립 앤 카운터",
      hint: { en: "Slip punches and counter immediately after.", mn: "Цохилтоос зайл, шууд контр хий.", ko: "펀치를 슬립하고 즉시 카운터하세요." } },
    { en: "Defensive Shell",   mn: "Хамгаалалтын бүрхүүл",  ko: "디펜시브 쉘",
      hint: { en: "Tight guard. Make them work, then fire back.", mn: "Нягт хамгаалалт. Тэднийг ядраад контр.", ko: "타이트한 가드. 지치게 만들고 반격하세요." } },
    { en: "Patience Drill",    mn: "Тэвчээрийн дасгал",     ko: "인내 드릴",
      hint: { en: "Wait for openings. Don't rush — time the counter.", mn: "Завсрыг хүлээ. Яарахгүй — цагийг тохируул.", ko: "기회를 기다리세요. 카운터 타이밍을 잡으세요." } },
    { en: "Shoulder Roll",     mn: "Мөрний эргэлт",          ko: "숄더 롤",
      hint: { en: "Roll off the shoulder. Catch, then fire back.", mn: "Мөрөн дээрээс гулгуул. Барьж, дараа цох.", ko: "숄더 롤로 받아내고 반격하세요." } },
    { en: "Bait & Punish",     mn: "Ятгаж шийтгэх",         ko: "베이트 앤 퍼니시",
      hint: { en: "Leave an opening on purpose. Punish what comes.", mn: "Зориудаар завсар үлдээ. Орж ирсэнийг шийтгэ.", ko: "의도적으로 틈을 남기세요. 들어오는 것을 처벌하세요." } },
    { en: "Timing Counter",    mn: "Цагийн контр",            ko: "타이밍 카운터",
      hint: { en: "Meet them as they come in. One perfect shot.", mn: "Орж ирэхэд нь угт. Нэг төгс цохилт.", ko: "들어올 때 맞이하세요. 완벽한 한 방." } },
    { en: "Philly Shell Day",  mn: "Фили Шелл өдөр",         ko: "필리 쉘 데이",
      hint: { en: "Stay in the shell. Practice the defensive system.", mn: "Шелл дотор бай. Хамгаалалтын системийг дадла.", ko: "쉘에 머물러요. 디펜시브 시스템을 연습하세요." } },
  ],
  explosive: [
    { en: "Speed Burst",       mn: "Хурдны дэлбэрэлт",      ko: "스피드 버스트",
      hint: { en: "Explode for 3 seconds, then reset. Max output.", mn: "3 секунд тэсрэн, дараа ре-сет. Дээд гаралт.", ko: "3초 폭발 후 리셋. 최대 출력." } },
    { en: "Power Combo",       mn: "Хүчний комбо",            ko: "파워 콤보",
      hint: { en: "2-3 punch burst with full power on each shot.", mn: "2-3 цохилтын хурдан. Бүтэн хүч.", ko: "2-3 펀치 버스트, 각 샷 풀 파워." } },
    { en: "First Strike",      mn: "Эхний дайралт",           ko: "퍼스트 스트라이크",
      hint: { en: "Initiate first. Be the one who starts the exchange.", mn: "Эхэлж дайрал. Солилцоог та эхлүүлэх.", ko: "먼저 시작하세요. 교환을 주도하세요." } },
    { en: "Animal Combo",      mn: "Зэрлэг комбо",            ko: "애니멀 콤보",
      hint: { en: "6+ punch combo in under 2 seconds. Explode.", mn: "2 секундэд 6+ цохилт. Тэсрэн.", ko: "2초 안에 6+ 콤보. 폭발적으로." } },
    { en: "Knockout Timing",   mn: "Нокаутын цаг",            ko: "녹아웃 타이밍",
      hint: { en: "Look for the one shot that changes everything.", mn: "Бүгдийг өөрчилдэг нэг цохилт хай.", ko: "모든 것을 바꾸는 한 방을 찾으세요." } },
    { en: "Southpaw Angles",   mn: "Зүүнт өнцгүүд",           ko: "사우스포 앵글",
      hint: { en: "Unorthodox angles. Throw from unexpected positions.", mn: "Онцгой өнцгүүд. Гэнэтийн байрлалаас цох.", ko: "비정통 앵글. 예상치 못한 위치에서 던지세요." } },
    { en: "Burst & Breathe",   mn: "Тэсрэлт & Амьсгал",      ko: "버스트 앤 브리드",
      hint: { en: "5s on, 10s off. Train the fast-twitch system.", mn: "5 сек хурдаар, 10 сек амраар. Хурдан булчинг бадра.", ko: "5초 폭발, 10초 휴식. 속근 훈련." } },
  ],
  technician: [
    { en: "Form Focus",        mn: "Хэлбэрт анхаарах",       ko: "폼 포커스",
      hint: { en: "Perfect form over speed. Every punch textbook-clean.", mn: "Хурдаас хэлбэр чухал. Бүр цохилт цэвэр.", ko: "속도보다 폼. 모든 펀치를 교과서처럼 깔끔하게." } },
    { en: "Stance Reset",      mn: "Байрлал сэргээх",         ko: "스탠스 리셋",
      hint: { en: "Reset your stance after every combination.", mn: "Комбо бүрийн дараа байрлалаа буц.", ko: "모든 콤보 후 스탠스를 재설정하세요." } },
    { en: "Systematic Setup",  mn: "Системтэй бэлтгэл",       ko: "시스템적 세팅",
      hint: { en: "Jab-cross-jab. Repeat the system. Build muscle memory.", mn: "Жааб-кросс-жааб. Систем давт. Булчингийн санах ой.", ko: "잽-크로스-잽. 시스템 반복. 근육 기억 구축." } },
    { en: "Guard & Counter",   mn: "Хамгаалалт & Контр",      ko: "가드 앤 카운터",
      hint: { en: "Block precisely, then counter in the opening.", mn: "Нарийн блок, дараа завсарт контр.", ko: "정확하게 블록하고 틈새에서 카운터하세요." } },
    { en: "Slow & Technical",  mn: "Удаан & Техникч",          ko: "슬로우 앤 테크니컬",
      hint: { en: "Half-speed with full technique. Build the pattern.", mn: "Хагас хурдаар бүтэн техник. Хэв маяг буд.", ko: "반 속도로 완전한 기술. 패턴을 구축하세요." } },
    { en: "Patient Buildup",   mn: "Тэвчээртэй хуримтлал",    ko: "인내심 있는 빌드업",
      hint: { en: "Build the attack gradually. Set up your power shot.", mn: "Аажмаар дайрлаа. Хүчний цохилтоо бэлд.", ko: "공격을 점차적으로 구축하세요. 파워 샷을 준비하세요." } },
    { en: "Fundamentals Day",  mn: "Үндсэн дасгалын өдөр",    ko: "펀더멘털 데이",
      hint: { en: "Back to basics. Jab, cross, hook — perfect each one.", mn: "Үндсэнд буц. Жааб, кросс, хук — бүрийг төгс болго.", ko: "기본으로 돌아가세요. 잽, 크로스, 훅 — 각각을 완벽하게." } },
  ],
};

export function getTodaysDNAMission(archetypeKey) {
  const missions = DNA_DAILY_MISSIONS[archetypeKey];
  if (!missions) return null;
  const dayIndex = new Date().getDay(); // 0 = Sunday
  return missions[dayIndex % missions.length];
}
