export const DNA_LABELS = {
  en: {
    dna:       "Fighter DNA",
    style:     "Style Mix",
    weapon:    "Best Weapon",
    weakness:  "Focus Area",
    fighters:  "Train Like",
    evolution: "Next Evolution",
    building:  "Building DNA",
    sessions:  (n) => `Train ${n} more session${n !== 1 ? "s" : ""} to unlock`,
    confidence:"Signal",
    prelim:    "Preliminary Signals",
    confirmed: (n) => `Train ${n} more to confirm archetype`,
    sigAggr:   "Aggression",
    sigRange:  "Range",
    sigCounter:"Counter",
    sigVolume: "Volume",
  },
  mn: {
    dna:       "Тулаанчийн ДНХ",
    style:     "Хэв маягийн холимог",
    weapon:    "Шилдэг зэвсэг",
    weakness:  "Анхаарах чиглэл",
    fighters:  "Дагах тулаанч",
    evolution: "Дараагийн хөгжил",
    building:  "ДНХ бүрдүүлж байна",
    sessions:  (n) => `${n} session дасгал хийж нээ`,
    confidence:"Дохио",
    prelim:    "Анхны дохиолол",
    confirmed: (n) => `${n} session дасгал хийж баталгаажуул`,
    sigAggr:   "Агрессиость",
    sigRange:  "Зай",
    sigCounter:"Контр",
    sigVolume: "Хэмжээ",
  },
  ko: {
    dna:       "파이터 DNA",
    style:     "스타일 믹스",
    weapon:    "주요 무기",
    weakness:  "집중 영역",
    fighters:  "롤모델 파이터",
    evolution: "다음 진화",
    building:  "DNA 구축 중",
    sessions:  (n) => `${n}개 세션 더 훈련 후 공개`,
    confidence:"신호",
    prelim:    "초기 신호",
    confirmed: (n) => `${n}개 세션 더 훈련해서 확인`,
    sigAggr:   "공격성",
    sigRange:  "거리",
    sigCounter:"카운터",
    sigVolume: "볼륨",
  },
};

export const SIGNAL_LABELS = {
  en: { high:"HIGH", medium:"MEDIUM", emerging:"EMERGING", low:"LOW", building:"BUILDING", long:"LONG RANGE", close:"CLOSE RANGE", mid:"MID RANGE" },
  mn: { high:"ӨНДӨР", medium:"ДУНД", emerging:"ГАРЧ БАЙНА", low:"БАГ", building:"БҮРДЭЖ БАЙНА", long:"ХОЛ ЗАЙ", close:"ОЙРХОН", mid:"ДУНД ЗАЙ" },
  ko: { high:"높음", medium:"보통", emerging:"나타나는 중", low:"낮음", building:"형성 중", long:"장거리", close:"근거리", mid:"중거리" },
};

export const PROGRESS_LABELS = {
  en: {
    level:      "Combat Level",
    progress:   "Progress to next level",
    maxLevel:   "Max Level",
    skills:     "Skill Mastery",
    timeline:   "Evolution Timeline",
    building:   "Tracking locked",
    sessions:   (n) => `Train ${n} more session${n !== 1 ? "s" : ""} to unlock progress tracking`,
    xp:         "XP",
    toNext:     "to next level",
    punchTrend: "Punch Pattern Evolution",
    early:      "Early sessions",
    recent:     "Recent sessions",
  },
  mn: {
    level:      "Тулааны түвшин",
    progress:   "Дараагийн түвшин рүү",
    maxLevel:   "Хамгийн өндөр",
    skills:     "Ур чадварын эзэмшил",
    timeline:   "Хөгжлийн цаг хугацаа",
    building:   "Хяналт хаалттай",
    sessions:   (n) => `${n} тренинг хийж нээ`,
    xp:         "XP",
    toNext:     "дараагийн түвшинд",
    punchTrend: "Цохилтын хэв маягийн хөгжил",
    early:      "Эхний тренинг",
    recent:     "Сүүлийн тренинг",
  },
  ko: {
    level:      "전투 레벨",
    progress:   "다음 레벨까지",
    maxLevel:   "최고 레벨",
    skills:     "스킬 마스터리",
    timeline:   "진화 타임라인",
    building:   "추적 잠금됨",
    sessions:   (n) => `${n}개 세션 더 훈련 후 공개`,
    xp:         "XP",
    toNext:     "다음 레벨까지",
    punchTrend: "펀치 패턴 진화",
    early:      "초기 세션",
    recent:     "최근 세션",
  },
};
