"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { computePoseMetrics, poseMetricsScore, lowerBodyVisible } from "@/lib/mediapipePoseMetrics";
import { PunchPhaseDetector } from "@/lib/punchPhaseDetector";
import { generateCoachingMessages, computeVelocityStats, computePunchBreakdown, computeSessionConfidence } from "@/lib/cinematicCoaching";
import { analyzeSession } from "@/lib/boxingIntelligence";

/**
 * MediaPipe files are served from /public/mediapipe/ (local static assets).
 * Generated by `postinstall` / `prebuild` scripts — never committed to git.
 * Serving locally avoids all CDN-403, network, and CORS issues.
 *
 * We use `new Function("url", "return import(url)")` to dynamically import
 * the ESM bundle at runtime. This bypasses webpack's static import analysis —
 * webpack only processes `import()` calls it can statically see.
 */
const LOCAL_BUNDLE = "/mediapipe/vision_bundle.mjs";
const LOCAL_WASM   = "/mediapipe/wasm";
const MODEL_URL    =
  "https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_lite/float16/1/pose_landmarker_lite.task";

const THROTTLE_MS  = 100;  // ~10fps
const SMOOTH_ALPHA = 0.35; // EMA weight for landmark smoothing
// Key joint indices smoothed before metric computation
const SMOOTH_IDX   = new Set([0, 11, 12, 13, 14, 15, 16, 23, 24, 27, 28]);

// Key landmark indices for joint-presence checks in debug overlay
const KEY_JOINTS = {
  L_SHOULDER: 11, R_SHOULDER: 12,
  L_WRIST: 15,    R_WRIST: 16,
  L_HIP: 23,      R_HIP: 24,
  L_ANKLE: 27,    R_ANKLE: 28,
};

// Singleton: only load once across all hook instances
let _loadPromise = null;

async function loadPoseLandmarker() {
  if (_loadPromise) return _loadPromise;

  _loadPromise = (async () => {
    // webpack-bypass dynamic import: new Function hides the import() from static analysis
    const runtimeImport = new Function("url", "return import(url)");
    const { FilesetResolver, PoseLandmarker } = await runtimeImport(LOCAL_BUNDLE);

    const vision = await FilesetResolver.forVisionTasks(LOCAL_WASM);

    // Try GPU delegate first; fall back to CPU (GPU fails on many mobile/WebView browsers)
    let landmarker;
    try {
      landmarker = await PoseLandmarker.createFromOptions(vision, {
        baseOptions: { modelAssetPath: MODEL_URL, delegate: "GPU" },
        runningMode: "VIDEO",
        numPoses: 1,
        minPoseDetectionConfidence: 0.5,
        minPosePresenceConfidence: 0.5,
        minTrackingConfidence: 0.5,
      });
    } catch {
      // GPU unavailable — try CPU
      landmarker = await PoseLandmarker.createFromOptions(vision, {
        baseOptions: { modelAssetPath: MODEL_URL, delegate: "CPU" },
        runningMode: "VIDEO",
        numPoses: 1,
        minPoseDetectionConfidence: 0.5,
        minPosePresenceConfidence: 0.5,
        minTrackingConfidence: 0.5,
      });
    }

    return landmarker;
  })();

  // Don't cache a rejected promise — allow retry next mount
  _loadPromise.catch(() => { _loadPromise = null; });

  return _loadPromise;
}

// "loading" | "ready" | "failed"
export function usePoseDetection({ videoRef, isActive }) {
  const [poseStatus, setPoseStatus] = useState("loading");
  const [poseError, setPoseError] = useState(null);

  const landmarkerRef      = useRef(null);
  const lastRunRef         = useRef(0);
  const rafRef             = useRef(null);
  const frameMetricsRef    = useRef([]);
  const latestLandmarksRef = useRef(null);
  const smoothedLmRef      = useRef(null); // EMA-smoothed landmark array
  const detectorRef        = useRef(new PunchPhaseDetector());
  const currentPhaseRef    = useRef({ leftPhase: "guard", rightPhase: "guard", leftElbow: 0, rightElbow: 0, velocity: 0 });

  // Diagnostic counters (refs — never cause re-renders)
  const frameAttemptRef = useRef(0);
  const detectCountRef  = useRef(0);
  const fpsCountRef     = useRef(0);
  const fpsRef          = useRef(0);
  const lastFpsTickRef  = useRef(0);
  const frameErrorRef   = useRef(null);
  const lowerBodyVisRef = useRef(false);
  const visSamplesRef   = useRef([]);  // per-frame avg arm joint visibility for debug stats

  // ── Load PoseLandmarker ──────────────────────────────────────────────────
  useEffect(() => {
    let cancelled = false;

    loadPoseLandmarker()
      .then((landmarker) => {
        if (!cancelled) {
          landmarkerRef.current = landmarker;
          setPoseStatus("ready");
        }
      })
      .catch((err) => {
        if (!cancelled) {
          setPoseStatus("failed");
          setPoseError(err?.message || String(err));
        }
      });

    return () => { cancelled = true; };
  }, []);

  // ── Detection loop ───────────────────────────────────────────────────────
  useEffect(() => {
    if (!isActive || poseStatus !== "ready") {
      if (rafRef.current) cancelAnimationFrame(rafRef.current);
      return;
    }

    lastFpsTickRef.current = performance.now();
    fpsCountRef.current = 0;

    function loop() {
      rafRef.current = requestAnimationFrame(loop);

      const now = performance.now();
      if (now - lastRunRef.current < THROTTLE_MS) return;
      lastRunRef.current = now;

      // Rolling FPS counter (reset each second)
      fpsCountRef.current++;
      const elapsed = now - lastFpsTickRef.current;
      if (elapsed >= 1000) {
        fpsRef.current = Math.round((fpsCountRef.current / elapsed) * 1000);
        fpsCountRef.current = 0;
        lastFpsTickRef.current = now;
      }

      const video = videoRef.current;
      if (!video || video.readyState < 2 || !landmarkerRef.current) return;

      frameAttemptRef.current++;
      try {
        const res = landmarkerRef.current.detectForVideo(video, now);
        const landmarks = res.landmarks?.[0];
        if (landmarks && landmarks.length >= 29) {
          // ── EMA smoothing on key joint positions ──
          if (!smoothedLmRef.current || smoothedLmRef.current.length !== landmarks.length) {
            smoothedLmRef.current = landmarks.map((lm) => ({ ...lm }));
          } else {
            const s = smoothedLmRef.current;
            for (let i = 0; i < landmarks.length; i++) {
              if (SMOOTH_IDX.has(i)) {
                s[i] = {
                  ...landmarks[i],
                  x: SMOOTH_ALPHA * landmarks[i].x + (1 - SMOOTH_ALPHA) * s[i].x,
                  y: SMOOTH_ALPHA * landmarks[i].y + (1 - SMOOTH_ALPHA) * s[i].y,
                  z: SMOOTH_ALPHA * (landmarks[i].z ?? 0) + (1 - SMOOTH_ALPHA) * (s[i].z ?? 0),
                };
              } else {
                s[i] = landmarks[i];
              }
            }
          }

          const smoothed = smoothedLmRef.current;
          latestLandmarksRef.current = smoothed;
          detectCountRef.current++;
          frameErrorRef.current = null;
          lowerBodyVisRef.current = lowerBodyVisible(smoothed);

          // Track arm visibility for debug session report
          const armVis = [11, 12, 13, 14, 15, 16]
            .reduce((s, i) => s + (landmarks[i]?.visibility ?? 0), 0) / 6;
          visSamplesRef.current.push(armVis);

          // Punch phase detection (uses raw landmarks — detector has own smoothing)
          const phaseInfo = detectorRef.current.update(landmarks);
          if (phaseInfo) currentPhaseRef.current = phaseInfo;

          // Metrics computed from smoothed landmarks — store with timestamp
          const metrics = computePoseMetrics(smoothed);
          if (metrics) frameMetricsRef.current.push({ ...metrics, _ts: Date.now() });
        } else {
          latestLandmarksRef.current = null;
          lowerBodyVisRef.current = false;
        }
      } catch (err) {
        frameErrorRef.current = err?.message || String(err);
      }
    }

    rafRef.current = requestAnimationFrame(loop);
    return () => {
      if (rafRef.current) cancelAnimationFrame(rafRef.current);
    };
  }, [isActive, poseStatus, videoRef]);

  // ── Reset buffers when a new session starts ──────────────────────────────
  useEffect(() => {
    if (isActive) {
      frameMetricsRef.current = [];
      latestLandmarksRef.current = null;
      smoothedLmRef.current = null;
      detectCountRef.current = 0;
      frameAttemptRef.current = 0;
      visSamplesRef.current = [];
      detectorRef.current.reset();
      currentPhaseRef.current = { leftPhase: "guard", rightPhase: "guard", leftElbow: 0, rightElbow: 0, velocity: 0 };
    }
  }, [isActive]);

  // ── Session summary ──────────────────────────────────────────────────────
  const computeSessionSummary = useCallback(() => {
    const frames = frameMetricsRef.current;
    if (frames.length < 5) return null;

    const METRIC_KEYS = [
      { key: "stanceWidth",    valKey: "ratio" },
      { key: "guardHeight",    valKey: "deltaY" },
      { key: "punchExtension", valKey: "angleDeg" },
      { key: "rotation",       valKey: "rotationDeg" },
      { key: "balance",        valKey: "drift" },
    ];

    // Extension and rotation are peak metrics — session value = MAX (not average)
    const PEAK_KEYS = new Set(["punchExtension", "rotation"]);

    const summary = {};
    for (const { key, valKey } of METRIC_KEYS) {
      const valid = frames.filter((f) => f[key] !== null);
      if (!valid.length) { summary[key] = null; continue; }

      const statusCounts = {};
      for (const f of valid) statusCounts[f[key].status] = (statusCounts[f[key].status] || 0) + 1;
      const dominantStatus = Object.entries(statusCounts).sort((a, b) => b[1] - a[1])[0][0];
      const aggVal = PEAK_KEYS.has(key)
        ? Math.max(...valid.map((f) => f[key][valKey]))
        : valid.reduce((s, f) => s + f[key][valKey], 0) / valid.length;

      summary[key] = {
        ...valid[0][key],
        [valKey]: Math.round(aggVal * 100) / 100,
        status: dominantStatus,
      };
    }

    summary.score      = poseMetricsScore(summary);
    summary.frameCount = frames.length;

    // Dominant camera quality across session frames
    const qualityCounts = {};
    for (const f of frames) {
      const q = f._cameraQuality;
      if (q) qualityCounts[q] = (qualityCounts[q] || 0) + 1;
    }
    summary.cameraQuality = Object.entries(qualityCounts).sort((a, b) => b[1] - a[1])[0]?.[0] || "unknown";

    // Track which metrics were null for ALL frames (visibility-gated, not a real reading)
    summary.visibilityGaps = METRIC_KEYS
      .filter(({ key }) => summary[key] === null)
      .map(({ key }) => key);

    // Motion history — guard timeline + punch markers for canvas visualization
    const sessionStart = frames[0]?._ts;
    const sessionEnd   = frames[frames.length - 1]?._ts;
    const durationMs   = sessionStart && sessionEnd ? sessionEnd - sessionStart : 0;

    // Punch events, breakdown by type, velocity stats
    const punchEvents      = detectorRef.current.getPunchEvents();
    summary.punchEvents    = punchEvents;
    summary.punchCount     = punchEvents.length;
    summary.punchBreakdown = computePunchBreakdown(punchEvents);
    summary.velocityStats  = computeVelocityStats(punchEvents);

    // Motion history for timeline chart — with EMA smoothing + status debounce
    if (durationMs > 1000) {
      const TIMELINE_ALPHA = 0.4;
      const DEBOUNCE       = 3;
      const rawGuard = frames.filter((f) => f.guardHeight?.deltaY != null && f._ts != null);
      let smoothDeltaY = null;

      const guardTimeline = rawGuard.map((f, i) => {
        smoothDeltaY = smoothDeltaY === null
          ? f.guardHeight.deltaY
          : TIMELINE_ALPHA * f.guardHeight.deltaY + (1 - TIMELINE_ALPHA) * smoothDeltaY;

        // 3-frame majority vote to suppress status flicker
        const start = Math.max(0, i - DEBOUNCE + 1);
        const counts = {};
        for (const w of rawGuard.slice(start, i + 1)) {
          const s = w.guardHeight.status;
          if (s) counts[s] = (counts[s] || 0) + 1;
        }
        const status = Object.entries(counts).sort((a, b) => b[1] - a[1])[0]?.[0] || f.guardHeight.status;

        return {
          t:      (f._ts - sessionStart) / durationMs,
          deltaY: smoothDeltaY,
          status,
        };
      });

      summary.motionHistory = {
        durationMs,
        guardTimeline,
        punchTimeline: punchEvents
          .map((e) => ({
            t:         (e.ts - sessionStart) / durationMs,
            type:      e.type,
            hand:      e.hand,
            peakAngle: e.peakAngle,
          }))
          .filter((e) => e.t >= 0 && e.t <= 1.05),
      };
    } else {
      summary.motionHistory = null;
    }

    // Session confidence: "high" | "medium" | "low"
    summary.sessionConfidence = computeSessionConfidence(summary, punchEvents);

    // Cinematic coaching messages
    summary.coaching = generateCoachingMessages(summary, punchEvents);

    // Boxing intelligence — style detection, per-type quality, weakness
    summary.boxingIntelligence = analyzeSession(summary, punchEvents);
    if (summary.boxingIntelligence?.coaching?.length) {
      summary.coaching = [...summary.coaching, ...summary.boxingIntelligence.coaching];
    }

    // Debug session stats — only populated when debugEnabled (but computed always so no perf branch)
    const visSamples     = visSamplesRef.current;
    const avgVis         = visSamples.length
      ? visSamples.reduce((s, v) => s + v, 0) / visSamples.length : 0;
    const unstableFrames = visSamples.filter((v) => v < 0.38).length;
    const sessionDurMs   = frames.length >= 2 ? frames[frames.length - 1]._ts - frames[0]._ts : 0;
    const estimatedFps   = sessionDurMs > 0
      ? Math.round((frames.length / sessionDurMs) * 1000 * 10) / 10 : 0;
    const detectorStats  = detectorRef.current.getSessionStats?.() ?? { rejects: {} };
    const jabCount       = punchEvents.filter((e) => e.type === "jab").length;
    const crossCount     = punchEvents.filter((e) => e.type === "cross").length;
    const hookCount      = punchEvents.filter((e) => e.type === "hook").length;
    const avgConf        = punchEvents.length
      ? punchEvents.reduce((s, e) => s + (e.confidence ?? 1), 0) / punchEvents.length : 0;
    const lowConfCount   = punchEvents.filter((e) => (e.confidence ?? 1) < 0.45).length;

    summary.debugStats = {
      rejects:             detectorStats.rejects,
      totalPunches:        punchEvents.length,
      jabCount,
      crossCount,
      hookCount,
      avgConfidencePct:    Math.round(avgConf * 100),
      lowConfCount,
      avgVisPct:           Math.round(avgVis * 100),
      unstablePct:         visSamples.length ? Math.round((unstableFrames / visSamples.length) * 100) : 0,
      cameraQualityBreakdown: qualityCounts,
      frameCount:          frames.length,
      estimatedFps,
    };

    return summary;
  }, []);

  // ── Debug info snapshot ──────────────────────────────────────────────────
  const getDebugInfo = useCallback(() => {
    const lm = latestLandmarksRef.current;
    const hasLm = lm !== null && lm.length >= 29;

    const jointPresence = {};
    if (hasLm) {
      for (const [name, idx] of Object.entries(KEY_JOINTS)) {
        jointPresence[name] = (lm[idx]?.visibility ?? 0) > 0.5;
      }
    }

    const latestMetrics = frameMetricsRef.current.length
      ? frameMetricsRef.current[frameMetricsRef.current.length - 1]
      : null;

    const cameraQuality = latestMetrics?._cameraQuality || "unknown";

    // Per-metric validity: "valid" | "skipped" | "unknown"
    const metricValidity = {
      stanceWidth:    latestMetrics ? (latestMetrics.stanceWidth    !== null ? "valid" : "skipped") : "unknown",
      guardHeight:    latestMetrics ? (latestMetrics.guardHeight    !== null ? "valid" : "skipped") : "unknown",
      punchExtension: latestMetrics ? (latestMetrics.punchExtension !== null ? "valid" : "skipped") : "unknown",
      rotation:       latestMetrics ? (latestMetrics.rotation       !== null ? "valid" : "skipped") : "unknown",
      balance:        latestMetrics ? (latestMetrics.balance        !== null ? "valid" : "skipped") : "unknown",
    };

    const { leftPhase, rightPhase, leftElbow, rightElbow, velocity } = currentPhaseRef.current;

    // Last completed punch — for live debug display
    const allEvents   = detectorRef.current.getPunchEvents();
    const lastPunch   = allEvents.length ? allEvents[allEvents.length - 1] : null;
    const handLiveData = detectorRef.current.getHandLiveData();

    return {
      status:             poseStatus,
      error:              poseError,
      frameError:         frameErrorRef.current,
      fps:                fpsRef.current,
      framesAttempted:    frameAttemptRef.current,
      framesWithBody:     detectCountRef.current,
      totalPoseFrames:    frameMetricsRef.current.length,
      landmarksDetected:  hasLm,
      landmarkCount:      hasLm ? lm.length : 0,
      lowerBodyVisible:   lowerBodyVisRef.current,
      jointPresence,
      metricValidity,
      latestMetrics,
      cameraQuality,
      punchPhase:         detectorRef.current.phase,
      leftPhase,
      rightPhase,
      punchCount:         detectorRef.current.punchCount,
      leftElbow,
      rightElbow,
      velocity,
      lastPunchType:          lastPunch?.type            ?? null,
      lastPunchHand:          lastPunch?.hand            ?? null,
      lastSnapVelocity:       lastPunch?.snapVelocity    ?? null,
      lastRecoilVelocity:     lastPunch?.recoilVelocity  ?? null,
      lastRecoilMs:           lastPunch?.recoilMs        ?? null,
      lastPunchConfidence:      lastPunch?.confidence       ?? null,
      lastPunchConfidenceLabel: lastPunch?.confidenceLabel  ?? null,
      lastPunchLateralPct:      lastPunch?.lateralRatio     ?? null,
      lastPunchReasons:         lastPunch?.classifyReasons  ?? null,
      handLiveData,
      trackingQuality: detectorRef.current.getTrackingQuality?.() ?? "unknown",
    };
  }, [poseStatus, poseError]);

  return {
    poseStatus,
    poseError,
    computeSessionSummary,
    getDebugInfo,
    latestLandmarksRef,
    frameMetricsRef,
  };
}
