"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { computePoseMetrics, poseMetricsScore, lowerBodyVisible } from "@/lib/mediapipePoseMetrics";

/**
 * MediaPipe files are served from /public/mediapipe/ (local static assets).
 * Generated by `postinstall` / `prebuild` scripts — never committed to git.
 * Serving locally avoids all CDN-403, network, and CORS issues.
 *
 * We use `new Function("url", "return import(url)")` to dynamically import
 * the ESM bundle at runtime. This bypasses webpack's static import analysis —
 * webpack only processes `import()` calls it can statically see.
 */
const LOCAL_BUNDLE = "/mediapipe/vision_bundle.mjs";
const LOCAL_WASM   = "/mediapipe/wasm";
const MODEL_URL    =
  "https://storage.googleapis.com/mediapipe-models/pose_landmarker/pose_landmarker_lite/float16/1/pose_landmarker_lite.task";

const THROTTLE_MS = 100; // ~10fps

// Key landmark indices for joint-presence checks in debug overlay
const KEY_JOINTS = {
  L_SHOULDER: 11, R_SHOULDER: 12,
  L_WRIST: 15,    R_WRIST: 16,
  L_HIP: 23,      R_HIP: 24,
  L_ANKLE: 27,    R_ANKLE: 28,
};

// Singleton: only load once across all hook instances
let _loadPromise = null;

async function loadPoseLandmarker() {
  if (_loadPromise) return _loadPromise;

  _loadPromise = (async () => {
    // webpack-bypass dynamic import: new Function hides the import() from static analysis
    const runtimeImport = new Function("url", "return import(url)");
    const { FilesetResolver, PoseLandmarker } = await runtimeImport(LOCAL_BUNDLE);

    const vision = await FilesetResolver.forVisionTasks(LOCAL_WASM);

    // Try GPU delegate first; fall back to CPU (GPU fails on many mobile/WebView browsers)
    let landmarker;
    try {
      landmarker = await PoseLandmarker.createFromOptions(vision, {
        baseOptions: { modelAssetPath: MODEL_URL, delegate: "GPU" },
        runningMode: "VIDEO",
        numPoses: 1,
        minPoseDetectionConfidence: 0.5,
        minPosePresenceConfidence: 0.5,
        minTrackingConfidence: 0.5,
      });
    } catch {
      // GPU unavailable — try CPU
      landmarker = await PoseLandmarker.createFromOptions(vision, {
        baseOptions: { modelAssetPath: MODEL_URL, delegate: "CPU" },
        runningMode: "VIDEO",
        numPoses: 1,
        minPoseDetectionConfidence: 0.5,
        minPosePresenceConfidence: 0.5,
        minTrackingConfidence: 0.5,
      });
    }

    return landmarker;
  })();

  // Don't cache a rejected promise — allow retry next mount
  _loadPromise.catch(() => { _loadPromise = null; });

  return _loadPromise;
}

// "loading" | "ready" | "failed"
export function usePoseDetection({ videoRef, isActive }) {
  const [poseStatus, setPoseStatus] = useState("loading");
  const [poseError, setPoseError] = useState(null);

  const landmarkerRef      = useRef(null);
  const lastRunRef         = useRef(0);
  const rafRef             = useRef(null);
  const frameMetricsRef    = useRef([]);
  const latestLandmarksRef = useRef(null);

  // Diagnostic counters (refs — never cause re-renders)
  const frameAttemptRef    = useRef(0);
  const detectCountRef     = useRef(0);
  const fpsCountRef        = useRef(0);
  const fpsRef             = useRef(0);
  const lastFpsTickRef     = useRef(0);
  const frameErrorRef      = useRef(null);
  const lowerBodyVisRef    = useRef(false); // hips + ankles visible this frame

  // ── Load PoseLandmarker ──────────────────────────────────────────────────
  useEffect(() => {
    let cancelled = false;

    loadPoseLandmarker()
      .then((landmarker) => {
        if (!cancelled) {
          landmarkerRef.current = landmarker;
          setPoseStatus("ready");
        }
      })
      .catch((err) => {
        if (!cancelled) {
          setPoseStatus("failed");
          setPoseError(err?.message || String(err));
        }
      });

    return () => { cancelled = true; };
  }, []);

  // ── Detection loop ───────────────────────────────────────────────────────
  useEffect(() => {
    if (!isActive || poseStatus !== "ready") {
      if (rafRef.current) cancelAnimationFrame(rafRef.current);
      return;
    }

    lastFpsTickRef.current = performance.now();
    fpsCountRef.current = 0;

    function loop() {
      rafRef.current = requestAnimationFrame(loop);

      const now = performance.now();
      if (now - lastRunRef.current < THROTTLE_MS) return;
      lastRunRef.current = now;

      // Rolling FPS counter (reset each second)
      fpsCountRef.current++;
      const elapsed = now - lastFpsTickRef.current;
      if (elapsed >= 1000) {
        fpsRef.current = Math.round((fpsCountRef.current / elapsed) * 1000);
        fpsCountRef.current = 0;
        lastFpsTickRef.current = now;
      }

      const video = videoRef.current;
      if (!video || video.readyState < 2 || !landmarkerRef.current) return;

      frameAttemptRef.current++;
      try {
        const res = landmarkerRef.current.detectForVideo(video, now);
        const landmarks = res.landmarks?.[0];
        if (landmarks && landmarks.length >= 29) {
          latestLandmarksRef.current = landmarks;
          detectCountRef.current++;
          frameErrorRef.current = null;
          lowerBodyVisRef.current = lowerBodyVisible(landmarks);
          const metrics = computePoseMetrics(landmarks);
          if (metrics) frameMetricsRef.current.push(metrics);
        } else {
          latestLandmarksRef.current = null;
          lowerBodyVisRef.current = false;
        }
      } catch (err) {
        frameErrorRef.current = err?.message || String(err);
      }
    }

    rafRef.current = requestAnimationFrame(loop);
    return () => {
      if (rafRef.current) cancelAnimationFrame(rafRef.current);
    };
  }, [isActive, poseStatus, videoRef]);

  // ── Reset buffers when a new session starts ──────────────────────────────
  useEffect(() => {
    if (isActive) {
      frameMetricsRef.current = [];
      latestLandmarksRef.current = null;
      detectCountRef.current = 0;
      frameAttemptRef.current = 0;
    }
  }, [isActive]);

  // ── Session summary ──────────────────────────────────────────────────────
  const computeSessionSummary = useCallback(() => {
    const frames = frameMetricsRef.current;
    if (frames.length < 5) return null;

    const METRIC_KEYS = [
      { key: "stanceWidth",    valKey: "ratio" },
      { key: "guardHeight",    valKey: "deltaY" },
      { key: "punchExtension", valKey: "angleDeg" },
      { key: "rotation",       valKey: "rotationDeg" },
      { key: "balance",        valKey: "drift" },
    ];

    const summary = {};
    for (const { key, valKey } of METRIC_KEYS) {
      const valid = frames.filter((f) => f[key] !== null);
      if (!valid.length) { summary[key] = null; continue; }

      const statusCounts = {};
      for (const f of valid) statusCounts[f[key].status] = (statusCounts[f[key].status] || 0) + 1;
      const dominantStatus = Object.entries(statusCounts).sort((a, b) => b[1] - a[1])[0][0];
      const avgVal = valid.reduce((s, f) => s + f[key][valKey], 0) / valid.length;

      summary[key] = {
        ...valid[0][key],
        [valKey]: Math.round(avgVal * 100) / 100,
        status: dominantStatus,
      };
    }

    summary.score = poseMetricsScore(summary);
    summary.frameCount = frames.length;

    // Track which metrics were null for ALL frames (visibility-gated, not a real reading)
    summary.visibilityGaps = METRIC_KEYS
      .filter(({ key }) => summary[key] === null)
      .map(({ key }) => key);

    return summary;
  }, []);

  // ── Debug info snapshot ──────────────────────────────────────────────────
  const getDebugInfo = useCallback(() => {
    const lm = latestLandmarksRef.current;
    const hasLm = lm !== null && lm.length >= 29;

    const jointPresence = {};
    if (hasLm) {
      for (const [name, idx] of Object.entries(KEY_JOINTS)) {
        jointPresence[name] = (lm[idx]?.visibility ?? 0) > 0.5;
      }
    }

    const latestMetrics = frameMetricsRef.current.length
      ? frameMetricsRef.current[frameMetricsRef.current.length - 1]
      : null;

    // Per-metric validity: "valid" | "skipped" | "unknown"
    const metricValidity = {
      stanceWidth:    latestMetrics ? (latestMetrics.stanceWidth    !== null ? "valid" : "skipped") : "unknown",
      guardHeight:    latestMetrics ? (latestMetrics.guardHeight    !== null ? "valid" : "skipped") : "unknown",
      punchExtension: latestMetrics ? (latestMetrics.punchExtension !== null ? "valid" : "skipped") : "unknown",
      rotation:       latestMetrics ? (latestMetrics.rotation       !== null ? "valid" : "skipped") : "unknown",
      balance:        latestMetrics ? (latestMetrics.balance        !== null ? "valid" : "skipped") : "unknown",
    };

    return {
      status:            poseStatus,
      error:             poseError,
      frameError:        frameErrorRef.current,
      fps:               fpsRef.current,
      framesAttempted:   frameAttemptRef.current,
      framesWithBody:    detectCountRef.current,
      totalPoseFrames:   frameMetricsRef.current.length,
      landmarksDetected: hasLm,
      landmarkCount:     hasLm ? lm.length : 0,
      lowerBodyVisible:  lowerBodyVisRef.current,
      jointPresence,
      metricValidity,
      latestMetrics,
    };
  }, [poseStatus, poseError]);

  return {
    poseStatus,
    poseError,
    computeSessionSummary,
    getDebugInfo,
    latestLandmarksRef,
    frameMetricsRef,
  };
}
