import { goldAlpha, redAlpha, RED, RED_DARK, GOLD, BG, BORDER_2, RADIUS, whiteAlpha, blackAlpha, pageBg } from "@/lib/tokens";

const styles = {
  page: {
    minHeight: "100dvh",
    background: pageBg(),
    color: "#fff",
    fontFamily: "inherit",
    display: "flex",
    flexDirection: "column",
    paddingBottom: "calc(88px + env(safe-area-inset-bottom))",
  },
  header: {
    display: "flex", alignItems: "center", gap: 14,
    padding: "calc(16px + env(safe-area-inset-top)) 16px 16px",
    borderBottom: `1px solid ${BORDER_2}`,
  },
  backBtn: {
    width: 40, height: 40, display: "flex", alignItems: "center", justifyContent: "center",
    background: whiteAlpha(0.055), border: `1px solid ${whiteAlpha(0.12)}`,
    color: "#fff", borderRadius: RADIUS.sm, cursor: "pointer", padding: 0, flexShrink: 0,
  },
  kicker: { margin: 0, fontSize: 10, fontWeight: 900, letterSpacing: 3, textTransform: "uppercase", color: RED },
  sub: { margin: "2px 0 0", fontSize: 13, color: whiteAlpha(0.45) },
  featuredBadge: {
    marginLeft: "auto", padding: "5px 12px", borderRadius: RADIUS.full,
    background: goldAlpha(0.15), border: `1px solid ${goldAlpha(0.4)}`, color: GOLD, fontSize: 12, fontWeight: 900,
  },
  content: { flex: 1, overflowY: "auto", padding: "16px 16px 0", display: "flex", flexDirection: "column", gap: 20 },
  loadingText: { textAlign: "center", color: whiteAlpha(0.35), padding: 40, fontSize: 24 },
  statsGrid: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 10 },
  statCard: {
    background: whiteAlpha(0.04), border: `1px solid ${BORDER_2}`, borderRadius: RADIUS.md,
    padding: "16px 14px", display: "flex", flexDirection: "column", alignItems: "center", gap: 4,
  },
  statIcon: { fontSize: 20, lineHeight: 1 },
  statValue: { fontSize: 26, fontWeight: 900, lineHeight: 1.1 },
  statLabel: { fontSize: 11, color: whiteAlpha(0.45), fontWeight: 700, letterSpacing: 0.3, textAlign: "center" },
  growthRow: { display: "flex", gap: 10, flexWrap: "wrap" },
  growthItem: {
    flex: 1, minWidth: 90, background: whiteAlpha(0.04), border: `1px solid ${BORDER_2}`,
    borderRadius: 12, padding: "12px 10px", display: "flex", flexDirection: "column", alignItems: "center", gap: 4,
  },
  growthNum: { fontSize: 20, fontWeight: 900, color: "#34D399", lineHeight: 1 },
  growthLbl: { fontSize: 10, color: whiteAlpha(0.45), fontWeight: 700, letterSpacing: 0.3, textAlign: "center" },
  section: { display: "flex", flexDirection: "column", gap: 8 },
  sectionTitle: { margin: 0, fontSize: 13, fontWeight: 900, letterSpacing: 0.5, textTransform: "uppercase", color: whiteAlpha(0.45) },
  breakdown: { display: "flex", flexDirection: "column", gap: 8 },
  breakdownRow: { display: "flex", alignItems: "center", gap: 10 },
  breakdownLabel: { width: 110, fontSize: 12, fontWeight: 700, flexShrink: 0 },
  breakdownBar: { flex: 1, height: 6, borderRadius: RADIUS.full, background: whiteAlpha(0.07), overflow: "hidden" },
  breakdownFill: { height: "100%", borderRadius: RADIUS.full, transition: "width 0.4s ease", opacity: 0.85 },
  breakdownCount: { width: 20, textAlign: "right", fontSize: 12, fontWeight: 700, color: whiteAlpha(0.45), flexShrink: 0 },
  tip: {
    display: "flex", alignItems: "flex-start", gap: 10, padding: "14px 16px",
    borderRadius: RADIUS.md, background: goldAlpha(0.07), border: `1px solid ${goldAlpha(0.2)}`,
  },
  tipIcon: { fontSize: 16, flexShrink: 0, marginTop: 1 },
  tipText: { fontSize: 13, color: whiteAlpha(0.75), lineHeight: 1.5 },
  reelList: { display: "flex", flexDirection: "column", gap: 6 },
  reelBar: { height: 3, borderRadius: RADIUS.full, background: whiteAlpha(0.07), overflow: "hidden", margin: "2px 0" },
  reelBarFill: { height: "100%", borderRadius: RADIUS.full, background: RED },
  reelRow: {
    display: "flex", alignItems: "center", gap: 12, padding: "12px 14px",
    background: whiteAlpha(0.04), border: `1px solid ${BORDER_2}`, borderRadius: 12, cursor: "pointer",
  },
  reelRank: { width: 28, textAlign: "center", fontSize: 12, fontWeight: 900, color: whiteAlpha(0.35), flexShrink: 0 },
  reelInfo: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column", gap: 4 },
  reelCaption: { fontSize: 13, fontWeight: 700, color: whiteAlpha(0.9), whiteSpace: "nowrap", overflow: "hidden", textOverflow: "ellipsis" },
  reelMeta: { display: "flex", gap: 12, fontSize: 11, color: whiteAlpha(0.4), fontWeight: 700 },
  uploadBtn: {
    padding: "12px 28px", borderRadius: RADIUS.full,
    background: `linear-gradient(145deg, ${RED}, ${RED_DARK})`, border: "none",
    color: "#fff", fontFamily: "inherit", fontSize: 14, fontWeight: 900, cursor: "pointer",
    boxShadow: `0 8px 24px ${redAlpha(0.28)}, inset 0 1px 0 ${whiteAlpha(0.1)}`,
  },
  reelThumb: { width: 52, height: 72, borderRadius: 8, overflow: "hidden", flexShrink: 0, background: "#111" },
  tabBar: {
    display: "flex", borderBottom: `1px solid ${whiteAlpha(0.07)}`, background: blackAlpha(0.98),
  },
  tabActive: { flex: 1, padding: "12px 0", border: "none", borderBottom: `2px solid ${RED}`, background: "transparent", color: "#fff", fontSize: 13, fontWeight: 900, cursor: "pointer" },
  tabInactive: { flex: 1, padding: "12px 0", border: "none", borderBottom: "2px solid transparent", background: "transparent", color: whiteAlpha(0.4), fontSize: 13, fontWeight: 700, cursor: "pointer" },
};

export default styles;
