import { goldAlpha, RED, GOLD } from "@/lib/tokens";

const styles = {
  page: {
    minHeight: "100dvh",
    background: "#050505",
    color: "#fff",
    fontFamily: "inherit",
    display: "flex",
    flexDirection: "column",
    paddingBottom: "calc(64px + env(safe-area-inset-bottom))",
  },
  header: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    padding: "calc(16px + env(safe-area-inset-top)) 16px 16px",
    borderBottom: "1px solid rgba(255,255,255,0.08)",
  },
  backBtn: {
    width: 40,
    height: 40,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "rgba(255,255,255,0.055)",
    border: "1px solid rgba(255,255,255,0.12)",
    color: "#fff",
    borderRadius: 10,
    cursor: "pointer",
    padding: 0,
    flexShrink: 0,
  },
  kicker: {
    margin: 0,
    fontSize: 11,
    fontWeight: 900,
    letterSpacing: 2,
    textTransform: "uppercase",
    color: GOLD,
  },
  sub: {
    margin: "2px 0 0",
    fontSize: 13,
    color: "#888",
  },
  featuredBadge: {
    marginLeft: "auto",
    padding: "5px 12px",
    borderRadius: 999,
    background: `${goldAlpha(0.15)}`,
    border: `1px solid ${goldAlpha(0.4)}`,
    color: GOLD,
    fontSize: 12,
    fontWeight: 900,
  },
  content: {
    flex: 1,
    overflowY: "auto",
    padding: "16px 16px 0",
    display: "flex",
    flexDirection: "column",
    gap: 20,
  },
  loadingText: {
    textAlign: "center",
    color: "#555",
    padding: 40,
    fontSize: 24,
  },
  statsGrid: {
    display: "grid",
    gridTemplateColumns: "1fr 1fr",
    gap: 10,
  },
  statCard: {
    background: "rgba(255,255,255,0.04)",
    border: "1px solid rgba(255,255,255,0.08)",
    borderRadius: 14,
    padding: "16px 14px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 4,
  },
  statIcon: {
    fontSize: 20,
    lineHeight: 1,
  },
  statValue: {
    fontSize: 26,
    fontWeight: 900,
    lineHeight: 1.1,
  },
  statLabel: {
    fontSize: 11,
    color: "#888",
    fontWeight: 700,
    letterSpacing: 0.3,
    textAlign: "center",
  },
  growthRow: {
    display: "flex",
    gap: 10,
    flexWrap: "wrap",
  },
  growthItem: {
    flex: 1,
    minWidth: 90,
    background: "rgba(255,255,255,0.04)",
    border: "1px solid rgba(255,255,255,0.08)",
    borderRadius: 12,
    padding: "12px 10px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 4,
  },
  growthNum: {
    fontSize: 20,
    fontWeight: 900,
    color: "#34D399",
    lineHeight: 1,
  },
  growthLbl: {
    fontSize: 10,
    color: "#888",
    fontWeight: 700,
    letterSpacing: 0.3,
    textAlign: "center",
  },
  section: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  sectionTitle: {
    margin: 0,
    fontSize: 13,
    fontWeight: 900,
    letterSpacing: 0.5,
    textTransform: "uppercase",
    color: "#888",
  },
  breakdown: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
  },
  breakdownRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
  },
  breakdownLabel: {
    width: 110,
    fontSize: 12,
    fontWeight: 700,
    flexShrink: 0,
  },
  breakdownBar: {
    flex: 1,
    height: 6,
    borderRadius: 999,
    background: "rgba(255,255,255,0.07)",
    overflow: "hidden",
  },
  breakdownFill: {
    height: "100%",
    borderRadius: 999,
    transition: "width 0.4s ease",
    opacity: 0.85,
  },
  breakdownCount: {
    width: 20,
    textAlign: "right",
    fontSize: 12,
    fontWeight: 700,
    color: "#888",
    flexShrink: 0,
  },
  tip: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    padding: "14px 16px",
    borderRadius: 14,
    background: `${goldAlpha(0.07)}`,
    border: `1px solid ${goldAlpha(0.2)}`,
  },
  tipIcon: {
    fontSize: 16,
    flexShrink: 0,
    marginTop: 1,
  },
  tipText: {
    fontSize: 13,
    color: "rgba(255,255,255,0.75)",
    lineHeight: 1.5,
  },
  reelList: {
    display: "flex",
    flexDirection: "column",
    gap: 6,
  },
  reelBar: {
    height: 3,
    borderRadius: 999,
    background: "rgba(255,255,255,0.07)",
    overflow: "hidden",
    margin: "2px 0",
  },
  reelBarFill: {
    height: "100%",
    borderRadius: 999,
    background: "linear-gradient(90deg, #C1121F, #D4AF37)",
  },
  reelRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "12px 14px",
    background: "rgba(255,255,255,0.04)",
    border: "1px solid rgba(255,255,255,0.08)",
    borderRadius: 12,
    cursor: "pointer",
  },
  reelRank: {
    width: 28,
    textAlign: "center",
    fontSize: 12,
    fontWeight: 900,
    color: "#555",
    flexShrink: 0,
  },
  reelInfo: {
    flex: 1,
    minWidth: 0,
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  reelCaption: {
    fontSize: 13,
    fontWeight: 700,
    color: "#eee",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
  },
  reelMeta: {
    display: "flex",
    gap: 12,
    fontSize: 11,
    color: "#666",
    fontWeight: 700,
  },
  uploadBtn: {
    padding: "12px 28px",
    borderRadius: 999,
    background: RED,
    border: "none",
    color: "#fff",
    fontFamily: "inherit",
    fontSize: 14,
    fontWeight: 900,
    cursor: "pointer",
  },
  reelThumb: {
    width: 52,
    height: 72,
    borderRadius: 8,
    overflow: "hidden",
    flexShrink: 0,
    background: "#111",
  },
  tabBar: {
    display: "flex",
    borderBottom: "1px solid rgba(255,255,255,0.07)",
    background: "rgba(5,5,5,0.98)",
  },
  tabActive: {
    flex: 1,
    padding: "12px 0",
    border: "none",
    borderBottom: "2px solid #C1121F",
    background: "transparent",
    color: "#fff",
    fontSize: 13,
    fontWeight: 900,
    cursor: "pointer",
  },
  tabInactive: {
    flex: 1,
    padding: "12px 0",
    border: "none",
    borderBottom: "2px solid transparent",
    background: "transparent",
    color: "rgba(255,255,255,0.4)",
    fontSize: 13,
    fontWeight: 700,
    cursor: "pointer",
  },
};

export default styles;
