import { RED, GOLD, BORDER, BORDER_2, MUTED, SURFACE, BG, RADIUS, redAlpha, goldAlpha, whiteAlpha, blackAlpha, pageBg } from "@/lib/tokens";

const s = {
  page: {
    minHeight: "100dvh",
    background: `
      radial-gradient(ellipse 90% 40% at 50% 0%, ${redAlpha(0.07)} 0%, transparent 52%),
      radial-gradient(ellipse 55% 50% at 8%  80%, ${redAlpha(0.025)} 0%, transparent 60%),
      radial-gradient(ellipse 40% 35% at 92% 65%, ${whiteAlpha(0.009)} 0%, transparent 55%),
      ${BG}
    `,
    color: "#fff",
    display: "flex",
    flexDirection: "column",
  },
  loadWrap: {
    minHeight: "100dvh",
    background: BG,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  spinner: {
    width: 26,
    height: 26,
    border: `2px solid ${RED}`,
    borderTopColor: "transparent",
    borderRadius: "50%",
    animation: "spin 0.8s linear infinite",
  },
  tabBar: {
    display: "flex",
    borderBottom: `1px solid ${BORDER}`,
    background: blackAlpha(0.96),
    backdropFilter: "blur(20px)",
    WebkitBackdropFilter: "blur(20px)",
    position: "sticky",
    top: "calc(52px + env(safe-area-inset-top))",
    zIndex: 19,
  },
  tabBtn: {
    flex: 1,
    padding: "12px 4px",
    border: "none",
    background: "transparent",
    color: whiteAlpha(0.35),
    fontSize: 12,
    fontWeight: 800,
    cursor: "pointer",
    position: "relative",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    borderBottom: "2px solid transparent",
    transition: "all 200ms ease",
  },
  tabBtnActive: {
    color: "#fff",
    borderBottom: `2px solid ${RED}`,
  },
  tabBadge: {
    minWidth: 16,
    height: 16,
    borderRadius: RADIUS.full,
    background: RED,
    color: "#fff",
    fontSize: 9,
    fontWeight: 900,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "0 4px",
  },
  toggleBanner: {
    borderRadius: RADIUS.md,
    border: "1px solid",
    padding: "12px 14px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    transition: "all 300ms ease",
  },
  toggleLeft: { display: "flex", alignItems: "flex-start", gap: 10, flex: 1, minWidth: 0 },
  toggleDot: {
    width: 8,
    height: 8,
    borderRadius: "50%",
    flexShrink: 0,
    marginTop: 4,
    transition: "all 300ms ease",
  },
  toggleTitle: { fontSize: 13, fontWeight: 800, marginBottom: 2, transition: "color 300ms ease" },
  toggleSub: { fontSize: 11, color: whiteAlpha(0.3), lineHeight: 1.45 },
  toggleBtn: {
    flexShrink: 0,
    padding: "8px 14px",
    borderRadius: RADIUS.full,
    fontSize: 12,
    fontWeight: 900,
    cursor: "pointer",
    whiteSpace: "nowrap",
    transition: "all 200ms ease",
  },
  filterSection: { padding: "10px 16px 0", display: "flex", flexDirection: "column", gap: 8 },
  filterRow: { display: "flex", gap: 6, overflowX: "auto", scrollbarWidth: "none" },
  filterChip: {
    flexShrink: 0,
    padding: "6px 12px",
    borderRadius: RADIUS.full,
    border: `1px solid ${BORDER}`,
    background: whiteAlpha(0.03),
    color: whiteAlpha(0.38),
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  weightSelect: {
    width: "100%",
    padding: "9px 12px",
    borderRadius: RADIUS.sm,
    border: `1px solid ${BORDER}`,
    background: whiteAlpha(0.04),
    color: whiteAlpha(0.55),
    fontSize: 12,
    outline: "none",
    appearance: "none",
  },
  // ── Arena live banner ──
  arenaBanner: {
    margin: "14px 16px 0",
    padding: "16px",
    borderRadius: RADIUS.lg,
    border: `1px solid ${redAlpha(0.18)}`,
    background: `linear-gradient(145deg, ${redAlpha(0.07)} 0%, transparent 100%)`,
    backdropFilter: "blur(12px)",
    WebkitBackdropFilter: "blur(12px)",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
  },
  arenaBannerLeft: {
    display: "flex",
    flexDirection: "column",
    gap: 3,
  },
  arenaKicker: {
    margin: 0,
    fontSize: 9,
    fontWeight: 900,
    letterSpacing: "2px",
    textTransform: "uppercase",
    color: RED,
  },
  arenaTitle: {
    margin: "2px 0 0",
    fontSize: 22,
    fontWeight: 900,
    color: "#fff",
    letterSpacing: "-0.02em",
    lineHeight: 1,
    fontFamily: "var(--font-display, 'Anton', sans-serif)",
  },
  arenaLiveRow: {
    display: "flex",
    alignItems: "center",
    gap: 7,
    marginTop: 6,
  },
  arenaLiveDot: {
    width: 8,
    height: 8,
    borderRadius: "50%",
    background: "#22C55E",
    boxShadow: "0 0 7px rgba(34,197,94,0.85)",
    flexShrink: 0,
  },
  arenaLiveCount: {
    fontSize: 13,
    fontWeight: 900,
    color: "#22C55E",
    letterSpacing: "-0.01em",
  },
  arenaLiveSub: {
    fontSize: 12,
    fontWeight: 600,
    color: whiteAlpha(0.35),
  },
  arenaToggleBtn: {
    flexShrink: 0,
    padding: "10px 16px",
    borderRadius: 12,
    border: "none",
    fontSize: 12,
    fontWeight: 900,
    cursor: "pointer",
    letterSpacing: "0.5px",
    WebkitTapHighlightColor: "transparent",
    transition: "opacity 160ms ease",
  },

  countBar: { padding: "12px 16px 4px" },
  countTxt: { fontSize: 10, fontWeight: 700, color: whiteAlpha(0.25), letterSpacing: 0.8, textTransform: "uppercase" },
  list: { flex: 1, display: "flex", flexDirection: "column", padding: "12px 0 0", minHeight: "55dvh" },
  sectionLabel: {
    padding: "20px 16px 6px",
    fontSize: 9,
    fontWeight: 900,
    color: RED,
    letterSpacing: 2,
    textTransform: "uppercase",
  },
  empty: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
    minHeight: "48dvh",
    padding: "48px 32px",
    gap: 12,
  },
  emptyTitle: { margin: 0, fontSize: 17, fontWeight: 900, color: whiteAlpha(0.88), textAlign: "center", letterSpacing: "-0.01em" },
  emptySub: {
    margin: 0,
    fontSize: 13,
    color: whiteAlpha(0.3),
    textAlign: "center",
    lineHeight: 1.6,
    maxWidth: 260,
  },
};

const c = {
  card: {
    background: whiteAlpha(0.04),
    backdropFilter: "blur(16px)",
    WebkitBackdropFilter: "blur(16px)",
    border: `1px solid ${BORDER}`,
    borderRadius: `3px ${RADIUS.lg}px ${RADIUS.lg}px 3px`,
    padding: "16px 14px 14px",
    display: "flex",
    flexDirection: "column",
    gap: 12,
    boxShadow: `0 4px 28px ${blackAlpha(0.4)}`,
    transition: "box-shadow 200ms ease, border-color 200ms ease",
  },
  cardTop: { display: "flex", gap: 12, alignItems: "flex-start" },
  avatarWrap: { position: "relative", flexShrink: 0 },
  avatar: { width: 56, height: 56, borderRadius: "50%", objectFit: "cover", display: "block" },
  avatarFallback: {
    width: 56,
    height: 56,
    borderRadius: "50%",
    border: `1.5px solid ${BORDER_2}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 20,
    fontWeight: 900,
    color: "#fff",
  },
  infoBlock: { flex: 1, minWidth: 0 },
  name: { fontSize: 15, fontWeight: 900, color: "#fff", marginBottom: 6, lineHeight: 1, letterSpacing: "-0.01em" },
  chips: { display: "flex", flexWrap: "wrap", gap: 5, marginBottom: 5 },
  chip: {
    fontSize: 10,
    fontWeight: 800,
    color: MUTED,
    background: whiteAlpha(0.05),
    border: `1px solid ${BORDER}`,
    borderRadius: RADIUS.full,
    padding: "3px 9px",
  },
  location: { fontSize: 11, color: MUTED, marginBottom: 3 },
  bio: { fontSize: 12, color: whiteAlpha(0.38), lineHeight: 1.45 },

  // Stat bars — upgraded
  statBarsRow: { display: "flex", gap: 8, marginTop: 4 },
  statBar: { flex: 1, display: "flex", flexDirection: "column", gap: 4 },
  statLabel: { fontSize: 8, fontWeight: 900, letterSpacing: "0.06em", textAlign: "center" },
  statTrack: { height: 5, borderRadius: 99, background: whiteAlpha(0.07), overflow: "hidden" },
  statFill: { height: "100%", borderRadius: 99 },

  // Request / action buttons
  requestBtn: {
    width: "100%",
    padding: "12px",
    borderRadius: 12,
    border: "none",
    color: "#fff",
    fontSize: 13,
    fontWeight: 900,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    letterSpacing: "0.2px",
    WebkitTapHighlightColor: "transparent",
    transition: "opacity 160ms ease",
  },
  myLabel: {
    fontSize: 11,
    color: whiteAlpha(0.25),
    fontWeight: 700,
    textAlign: "center",
    padding: "4px 0 2px",
    letterSpacing: "0.5px",
  },

  // Incoming request card extras
  incomingKicker: {
    margin: "0 0 8px",
    fontSize: 9,
    fontWeight: 900,
    letterSpacing: "3px",
    textTransform: "uppercase",
    color: GOLD,
    display: "flex",
    alignItems: "center",
    gap: 6,
  },
  incomingKickerDot: {
    width: 6,
    height: 6,
    borderRadius: "50%",
    background: GOLD,
    boxShadow: `0 0 5px ${goldAlpha(0.8)}`,
    flexShrink: 0,
  },
};

export default s;
export { c };
