import { RED, BORDER, MUTED, SURFACE, BG, redAlpha, pageBg } from "@/lib/tokens";

const s = {
  page: {
    minHeight: "100dvh",
    background: `
      radial-gradient(ellipse 90% 40% at 50% 0%, ${redAlpha(0.14)} 0%, transparent 52%),
      radial-gradient(ellipse 55% 50% at 8%  80%, ${redAlpha(0.05)} 0%, transparent 60%),
      radial-gradient(ellipse 40% 35% at 92% 65%, rgba(255,255,255,0.018) 0%, transparent 55%),
      ${BG}
    `,
    color: "#fff",
    display: "flex",
    flexDirection: "column",
  },
  loadWrap: {
    minHeight: "100dvh",
    background: BG,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  spinner: {
    width: 26,
    height: 26,
    border: `2px solid ${RED}`,
    borderTopColor: "transparent",
    borderRadius: "50%",
    animation: "spin 0.8s linear infinite",
  },
  tabBar: {
    display: "flex",
    borderBottom: `1px solid ${BORDER}`,
    background: "rgba(11,11,12,0.96)",
    backdropFilter: "blur(20px)",
    WebkitBackdropFilter: "blur(20px)",
    position: "sticky",
    top: "calc(52px + env(safe-area-inset-top))",
    zIndex: 19,
  },
  tabBtn: {
    flex: 1,
    padding: "12px 4px",
    border: "none",
    background: "transparent",
    color: "rgba(255,255,255,0.35)",
    fontSize: 12,
    fontWeight: 800,
    cursor: "pointer",
    position: "relative",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 5,
    borderBottom: "2px solid transparent",
    transition: "all 200ms ease",
  },
  tabBtnActive: {
    color: "#fff",
    borderBottom: `2px solid ${RED}`,
  },
  tabBadge: {
    minWidth: 16,
    height: 16,
    borderRadius: 999,
    background: RED,
    color: "#fff",
    fontSize: 9,
    fontWeight: 900,
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: "0 4px",
  },
  toggleBanner: {
    borderRadius: 14,
    border: "1px solid",
    padding: "12px 14px",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 12,
    transition: "all 300ms ease",
  },
  toggleLeft: { display: "flex", alignItems: "flex-start", gap: 10, flex: 1, minWidth: 0 },
  toggleDot: {
    width: 8,
    height: 8,
    borderRadius: "50%",
    flexShrink: 0,
    marginTop: 4,
    transition: "all 300ms ease",
  },
  toggleTitle: { fontSize: 13, fontWeight: 800, marginBottom: 2, transition: "color 300ms ease" },
  toggleSub: { fontSize: 11, color: "rgba(255,255,255,0.3)", lineHeight: 1.45 },
  toggleBtn: {
    flexShrink: 0,
    padding: "8px 14px",
    borderRadius: 999,
    fontSize: 12,
    fontWeight: 900,
    cursor: "pointer",
    whiteSpace: "nowrap",
    transition: "all 200ms ease",
  },
  filterSection: { padding: "10px 16px 0", display: "flex", flexDirection: "column", gap: 8 },
  filterRow: { display: "flex", gap: 6, overflowX: "auto", scrollbarWidth: "none" },
  filterChip: {
    flexShrink: 0,
    padding: "6px 12px",
    borderRadius: 999,
    border: `1px solid ${BORDER}`,
    background: "rgba(255,255,255,0.03)",
    color: "rgba(255,255,255,0.38)",
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  weightSelect: {
    width: "100%",
    padding: "9px 12px",
    borderRadius: 10,
    border: `1px solid ${BORDER}`,
    background: "rgba(255,255,255,0.04)",
    color: "rgba(255,255,255,0.55)",
    fontSize: 12,
    outline: "none",
    appearance: "none",
  },
  countBar: { padding: "10px 16px 4px" },
  countTxt: { fontSize: 11, fontWeight: 700, color: "rgba(255,255,255,0.28)", letterSpacing: 0.4 },
  list: { flex: 1, display: "flex", flexDirection: "column", padding: "4px 0 0", minHeight: "55dvh" },
  sectionLabel: {
    padding: "12px 16px 4px",
    fontSize: 9,
    fontWeight: 900,
    color: RED,
    letterSpacing: 2.5,
    textTransform: "uppercase",
  },
  empty: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    flex: 1,
    minHeight: "48dvh",
    padding: "48px 32px",
    gap: 12,
  },
  emptyTitle: { margin: 0, fontSize: 17, fontWeight: 900, color: "rgba(255,255,255,0.88)", textAlign: "center", letterSpacing: "-0.01em" },
  emptySub: {
    margin: 0,
    fontSize: 13,
    color: "rgba(255,255,255,0.3)",
    textAlign: "center",
    lineHeight: 1.6,
    maxWidth: 260,
  },
};

const c = {
  card: {
    background: "rgba(255,255,255,0.03)",
    backdropFilter: "blur(16px)",
    WebkitBackdropFilter: "blur(16px)",
    border: `1px solid rgba(255,255,255,0.07)`,
    borderRadius: "3px 14px 14px 3px",
    padding: "13px 13px 10px",
    display: "flex",
    flexDirection: "column",
    gap: 10,
    boxShadow: "0 4px 20px rgba(0,0,0,0.25)",
  },
  cardTop: { display: "flex", gap: 12, alignItems: "flex-start" },
  avatarWrap: { position: "relative", flexShrink: 0 },
  avatar: { width: 48, height: 48, borderRadius: "50%", objectFit: "cover", display: "block" },
  avatarFallback: {
    width: 48,
    height: 48,
    borderRadius: "50%",
    border: `1px solid ${BORDER}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 18,
    fontWeight: 900,
    color: "#fff",
  },
  infoBlock: { flex: 1, minWidth: 0 },
  name: { fontSize: 15, fontWeight: 900, color: "#fff", marginBottom: 5, lineHeight: 1 },
  chips: { display: "flex", flexWrap: "wrap", gap: 5, marginBottom: 4 },
  chip: {
    fontSize: 10,
    fontWeight: 800,
    color: MUTED,
    background: "rgba(255,255,255,0.05)",
    border: `1px solid ${BORDER}`,
    borderRadius: 999,
    padding: "2px 8px",
  },
  location: { fontSize: 11, color: MUTED, marginBottom: 3 },
  bio: { fontSize: 12, color: "rgba(255,255,255,0.4)", lineHeight: 1.45 },
};

export default s;
export { c };
