import { RED, redAlpha, GOLD, goldAlpha } from "@/lib/tokens";

export const coachPageStyles = {
  page: {
    minHeight: "100dvh",
    background: `radial-gradient(circle at 50% 0%, ${redAlpha(0.18)}, transparent 30%), linear-gradient(180deg, #080808 0%, #0B0B0B 100%)`,
    color: "#fff",
  },
  tabStrip: {
    position: "sticky", top: 0, zIndex: 50,
    display: "flex",
    background: "rgba(8,8,8,0.92)",
    backdropFilter: "blur(14px)", WebkitBackdropFilter: "blur(14px)",
    borderBottom: "1px solid rgba(255,255,255,0.08)",
    padding: "0 4px", paddingTop: "env(safe-area-inset-top)",
  },
  tabActive: { flex: 1, minHeight: 46, border: "none", borderBottom: "2px solid #C1121F", background: "transparent", color: "#fff", fontSize: 13, fontWeight: 1000, letterSpacing: 0.5, cursor: "pointer" },
  tabInactive: { flex: 1, minHeight: 46, border: "none", borderBottom: "2px solid transparent", background: "transparent", color: "rgba(255,255,255,0.65)", fontSize: 13, fontWeight: 700, cursor: "pointer" },
  aiWrap: { minHeight: "calc(100dvh - 46px)" },
  content: { maxWidth: 520, margin: "0 auto", padding: "0 16px calc(104px + env(safe-area-inset-bottom))" },
  pageHeader: { padding: "22px 0 12px", display: "flex", flexDirection: "column", gap: 10 },
  becomeCoachBtn: { alignSelf: "flex-start", background: `${goldAlpha(0.12)}`, border: `1px solid ${goldAlpha(0.4)}`, borderRadius: 20, padding: "7px 16px", color: GOLD, fontSize: 13, fontWeight: 600, cursor: "pointer" },
  kicker: { margin: 0, color: GOLD, fontSize: 11, fontWeight: 950, letterSpacing: 2, textTransform: "uppercase" },
  pageTitle: { margin: "4px 0 0", fontSize: 28, fontWeight: 1000, lineHeight: 1.1, fontFamily: "var(--font-display, 'Anton', sans-serif)" },
  filterBar: { display: "flex", flexDirection: "column", gap: 10, marginBottom: 20 },
  specialtyChipsRow: { display: "flex", gap: 6, overflowX: "auto", paddingBottom: 8, scrollbarWidth: "none", marginBottom: 12, alignItems: "center" },
  specChip: { flexShrink: 0, padding: "7px 14px", borderRadius: 999, border: "1px solid rgba(255,255,255,0.1)", background: "rgba(255,255,255,0.03)", color: "rgba(255,255,255,0.45)", fontSize: 12, fontWeight: 700, cursor: "pointer", whiteSpace: "nowrap", WebkitTapHighlightColor: "transparent" },
  specChipActive: { flexShrink: 0, padding: "7px 14px", borderRadius: 999, border: `1px solid ${redAlpha(0.6)}`, background: `${redAlpha(0.18)}`, color: "#F87171", fontSize: 12, fontWeight: 900, cursor: "pointer", whiteSpace: "nowrap", WebkitTapHighlightColor: "transparent" },
  filterBarCompact: { display: "flex", gap: 6, flexWrap: "nowrap", overflowX: "auto", paddingBottom: 4, scrollbarWidth: "none", marginBottom: 20, alignItems: "center" },
  filterMoreBtn: { flexShrink: 0, padding: "5px 12px", borderRadius: 999, border: `1px solid ${goldAlpha(0.3)}`, background: `${goldAlpha(0.06)}`, color: GOLD, fontSize: 12, fontWeight: 700, cursor: "pointer", whiteSpace: "nowrap" },
  filterSheetSectionLabel: { margin: "0 0 8px", fontSize: 10, fontWeight: 900, color: GOLD, letterSpacing: 1.5 },
  filterSheetDone: { marginTop: 16, width: "100%", minHeight: 46, border: "none", borderRadius: 14, background: "linear-gradient(135deg, #C1121F, #7d0812)", color: "#fff", fontSize: 14, fontWeight: 900, cursor: "pointer", boxShadow: `0 8px 24px ${redAlpha(0.25)}` },
  cardRatingInline: { fontSize: 12, fontWeight: 800, color: GOLD },
  specialtyScroll: { display: "flex", gap: 6, overflowX: "auto", paddingBottom: 4, scrollbarWidth: "none" },
  chip: { flexShrink: 0, padding: "5px 12px", borderRadius: 999, border: "1px solid rgba(255,255,255,0.16)", background: "rgba(255,255,255,0.05)", color: "rgba(255,255,255,0.7)", fontSize: 12, fontWeight: 700, cursor: "pointer", whiteSpace: "nowrap" },
  chipActive: { flexShrink: 0, padding: "5px 12px", borderRadius: 999, border: `1px solid ${redAlpha(0.6)}`, background: `${redAlpha(0.18)}`, color: "#fff", fontSize: 12, fontWeight: 900, cursor: "pointer", whiteSpace: "nowrap" },
  filterRow: { display: "flex", gap: 8 },
  filterInput: { flex: 1, minHeight: 38, padding: "0 12px", borderRadius: 10, border: "1px solid rgba(255,255,255,0.14)", background: "rgba(255,255,255,0.07)", color: "#fff", fontSize: 13, outline: "none" },
  filterSelect: { minHeight: 38, padding: "0 10px", borderRadius: 10, border: "1px solid rgba(255,255,255,0.14)", background: "rgba(255,255,255,0.07)", color: "#fff", fontSize: 12, fontWeight: 700, outline: "none", cursor: "pointer" },
};
