import { RED, RED_DARK, BG, redAlpha, GOLD, goldAlpha, BORDER, BORDER_2, RADIUS, whiteAlpha, blackAlpha, pageBg } from "@/lib/tokens";

const styles = {
  // ── Page ──
  page: {
    minHeight: "100dvh",
    background: pageBg(0.08),
    color: "#fff",
  },
  tabStrip: {
    position: "sticky", top: 0, zIndex: 50,
    display: "flex",
    background: blackAlpha(0.92),
    backdropFilter: "blur(20px)", WebkitBackdropFilter: "blur(20px)",
    borderBottom: `1px solid ${whiteAlpha(0.07)}`,
    padding: "0 4px", paddingTop: "env(safe-area-inset-top)",
  },
  tabActive: { flex: 1, minHeight: 46, border: "none", borderBottom: `2px solid ${RED}`, background: "transparent", color: "#fff", fontSize: 12, fontWeight: 900, letterSpacing: "0.04em", textTransform: "uppercase", cursor: "pointer", transition: "color 180ms ease, border-color 180ms ease", position: "relative" },
  tabInactive: { flex: 1, minHeight: 46, border: "none", borderBottom: "2px solid transparent", background: "transparent", color: whiteAlpha(0.38), fontSize: 12, fontWeight: 800, letterSpacing: "0.04em", textTransform: "uppercase", cursor: "pointer", transition: "color 180ms ease, border-color 180ms ease", position: "relative" },
  aiWrap: { minHeight: "calc(100dvh - 46px)" },
  content: { maxWidth: 520, margin: "0 auto", padding: "0 16px calc(104px + env(safe-area-inset-bottom))" },
  pageHeader: { padding: "22px 0 12px", display: "flex", flexDirection: "column", gap: 10 },
  becomeCoachBtn: { alignSelf: "flex-start", background: goldAlpha(0.12), border: `1px solid ${goldAlpha(0.4)}`, borderRadius: 20, padding: "7px 16px", color: GOLD, fontSize: 13, fontWeight: 600, cursor: "pointer" },
  kicker: { margin: 0, color: RED, fontSize: 9, fontWeight: 900, letterSpacing: 3.5, textTransform: "uppercase" },
  pageTitle: { margin: "4px 0 0", fontSize: 26, fontWeight: 900, lineHeight: 1, letterSpacing: "-0.02em", fontFamily: "var(--font-display, 'Anton', sans-serif)", textTransform: "uppercase" },
  filterBar: { display: "flex", flexDirection: "column", gap: 10, marginBottom: 20 },
  specialtyChipsRow: { display: "flex", gap: 6, overflowX: "auto", paddingBottom: 8, scrollbarWidth: "none", marginBottom: 12, alignItems: "center" },
  specChip: { flexShrink: 0, padding: "7px 14px", borderRadius: RADIUS.full, border: `1px solid ${whiteAlpha(0.09)}`, background: whiteAlpha(0.03), color: whiteAlpha(0.45), fontSize: 12, fontWeight: 700, cursor: "pointer", whiteSpace: "nowrap", WebkitTapHighlightColor: "transparent" },
  specChipActive: { flexShrink: 0, padding: "7px 14px", borderRadius: RADIUS.full, border: `1px solid ${redAlpha(0.6)}`, background: redAlpha(0.18), color: "#F87171", fontSize: 12, fontWeight: 900, cursor: "pointer", whiteSpace: "nowrap", WebkitTapHighlightColor: "transparent", boxShadow: `0 0 12px ${redAlpha(0.15)}` },
  filterBarCompact: { display: "flex", gap: 6, flexWrap: "nowrap", overflowX: "auto", paddingBottom: 4, scrollbarWidth: "none", marginBottom: 20, alignItems: "center" },
  filterMoreBtn: { flexShrink: 0, padding: "5px 12px", borderRadius: RADIUS.full, border: `1px solid ${goldAlpha(0.3)}`, background: goldAlpha(0.06), color: GOLD, fontSize: 12, fontWeight: 700, cursor: "pointer", whiteSpace: "nowrap" },
  filterSheetSectionLabel: { margin: "0 0 8px", fontSize: 9, fontWeight: 900, color: RED, letterSpacing: 3.5, textTransform: "uppercase" },
  filterSheetDone: { marginTop: 16, width: "100%", minHeight: 46, border: "none", borderRadius: RADIUS.md, background: `linear-gradient(145deg, ${RED}, ${RED_DARK})`, color: "#fff", fontSize: 14, fontWeight: 900, cursor: "pointer", boxShadow: `0 8px 24px ${redAlpha(0.32)}, inset 0 1px 0 ${whiteAlpha(0.1)}` },
  cardRatingInline: { fontSize: 12, fontWeight: 800, color: GOLD },
  specialtyScroll: { display: "flex", gap: 6, overflowX: "auto", paddingBottom: 4, scrollbarWidth: "none" },
  chip: { flexShrink: 0, padding: "5px 12px", borderRadius: RADIUS.full, border: `1px solid ${whiteAlpha(0.1)}`, background: whiteAlpha(0.04), color: whiteAlpha(0.6), fontSize: 12, fontWeight: 700, cursor: "pointer", whiteSpace: "nowrap" },
  chipActive: { flexShrink: 0, padding: "5px 12px", borderRadius: RADIUS.full, border: `1px solid ${redAlpha(0.6)}`, background: redAlpha(0.18), color: "#fff", fontSize: 12, fontWeight: 900, cursor: "pointer", whiteSpace: "nowrap" },
  filterRow: { display: "flex", gap: 8 },
  filterInput: { flex: 1, minHeight: 38, padding: "0 12px", borderRadius: RADIUS.sm, border: `1px solid ${whiteAlpha(0.1)}`, background: whiteAlpha(0.05), color: "#fff", fontSize: 13, outline: "none" },
  filterSelect: { minHeight: 38, padding: "0 10px", borderRadius: RADIUS.sm, border: `1px solid ${whiteAlpha(0.1)}`, background: whiteAlpha(0.05), color: "#fff", fontSize: 12, fontWeight: 700, outline: "none", cursor: "pointer" },

  // ── Cards ──
  cardList: { display: "flex", flexDirection: "column", gap: 14 },
  card: {
    borderRadius: 20, padding: "16px",
    background: whiteAlpha(0.03),
    backdropFilter: "blur(20px)", WebkitBackdropFilter: "blur(20px)",
    border: `1px solid ${BORDER_2}`,
    boxShadow: `0 8px 32px ${blackAlpha(0.35)}, inset 0 1px 0 ${whiteAlpha(0.05)}`,
    display: "flex", flexDirection: "column", gap: 10,
  },
  cardTop: { display: "flex", gap: 12, alignItems: "flex-start" },
  avatarWrap: { position: "relative", flexShrink: 0 },
  avatar: { width: 52, height: 52, borderRadius: "50%", objectFit: "cover", border: `2px solid ${goldAlpha(0.4)}` },
  avatarInitials: {
    width: 52, height: 52, borderRadius: "50%",
    background: RED,
    border: `2px solid ${goldAlpha(0.4)}`,
    display: "flex", alignItems: "center", justifyContent: "center",
    fontSize: 18, fontWeight: 1000, color: "#fff",
  },
  verifiedDot: {
    position: "absolute", bottom: 0, right: 0,
    width: 18, height: 18, borderRadius: "50%",
    background: GOLD, color: "#000", fontSize: 10, fontWeight: 1000,
    display: "flex", alignItems: "center", justifyContent: "center",
    border: "2px solid #0b0b0c",
  },
  cardInfo: { flex: 1, display: "flex", flexDirection: "column", gap: 3, minWidth: 0 },
  cardNameRow: { display: "flex", alignItems: "center", gap: 6, flexWrap: "wrap" },
  cardName: { fontSize: 16, fontWeight: 1000, color: "#fff" },
  verifiedBadge: {
    fontSize: 10, fontWeight: 900, color: GOLD,
    background: goldAlpha(0.12), border: `1px solid ${goldAlpha(0.3)}`,
    borderRadius: RADIUS.full, padding: "1px 7px", letterSpacing: 0.5,
  },
  cardLocation: { fontSize: 12, color: whiteAlpha(0.55), fontWeight: 600 },
  cardExp: { fontSize: 12, color: GOLD, fontWeight: 700 },
  specialtyRow: { display: "flex", flexWrap: "wrap", gap: 5 },
  specialtyChip: {
    fontSize: 11, fontWeight: 800, color: whiteAlpha(0.75),
    background: whiteAlpha(0.07), border: `1px solid ${whiteAlpha(0.12)}`,
    borderRadius: RADIUS.full, padding: "3px 9px",
  },
  cardBio: {
    margin: 0, fontSize: 13, color: whiteAlpha(0.62), lineHeight: 1.5,
    display: "-webkit-box", WebkitLineClamp: 2, WebkitBoxOrient: "vertical", overflow: "hidden",
  },
  cardStats: { display: "flex", gap: 16 },
  cardStat: { display: "flex", flexDirection: "column", gap: 1 },
  cardStatNum: { fontSize: 14, fontWeight: 1000, color: "#fff" },
  cardStatLbl: { fontSize: 10, color: whiteAlpha(0.65), fontWeight: 700, textTransform: "uppercase", letterSpacing: 0.5 },
  cardActions: { display: "flex", gap: 8, marginTop: 2 },
  viewProfileBtn: {
    flex: 1, minHeight: 38, border: `1px solid ${whiteAlpha(0.12)}`,
    borderRadius: RADIUS.sm, background: whiteAlpha(0.05),
    color: "#fff", fontSize: 13, fontWeight: 800, cursor: "pointer",
    backdropFilter: "blur(8px)", WebkitBackdropFilter: "blur(8px)",
  },
  requestBtn: {
    flex: 1, minHeight: 38, border: "none", borderRadius: RADIUS.sm,
    background: `linear-gradient(145deg, ${RED}, ${RED_DARK})`,
    color: "#fff", fontSize: 13, fontWeight: 900, cursor: "pointer",
    boxShadow: `0 6px 20px ${redAlpha(0.32)}, inset 0 1px 0 ${whiteAlpha(0.1)}`,
  },
  requestedBtn: {
    flex: 1, minHeight: 38, border: "1px solid rgba(52,211,153,0.3)",
    borderRadius: RADIUS.sm, background: "rgba(52,211,153,0.1)",
    color: "#34D399", fontSize: 13, fontWeight: 900, cursor: "default",
  },
  createPostBtn: {
    width: "100%", minHeight: 48, border: `1px solid ${goldAlpha(0.35)}`,
    borderRadius: RADIUS.md, background: `linear-gradient(135deg, ${redAlpha(0.9)}, ${goldAlpha(0.2)})`,
    color: "#fff", fontSize: 14, fontWeight: 1000, cursor: "pointer",
    marginBottom: 16, boxShadow: `0 12px 30px ${redAlpha(0.22)}`,
  },
  savedBanner: {
    padding: "10px 14px", borderRadius: 12,
    background: "rgba(52,211,153,0.12)", border: "1px solid rgba(52,211,153,0.28)",
    color: "#A7F3D0", fontSize: 13, fontWeight: 800, marginBottom: 12,
  },
  sparringCardHead: { display: "flex", alignItems: "center", gap: 8, flexWrap: "wrap" },
  sparringLevel: {
    fontSize: 13, fontWeight: 1000, color: GOLD,
    background: goldAlpha(0.12), border: `1px solid ${goldAlpha(0.25)}`,
    borderRadius: RADIUS.full, padding: "3px 10px",
  },
  sparringWeight: {
    fontSize: 13, fontWeight: 800, color: "#fff",
    background: whiteAlpha(0.07), border: `1px solid ${whiteAlpha(0.12)}`,
    borderRadius: RADIUS.full, padding: "3px 10px",
  },
  sparringLocation: { fontSize: 12, color: whiteAlpha(0.55), fontWeight: 600 },
  sparringTime: { fontSize: 12, color: whiteAlpha(0.55), fontWeight: 600 },
  loadingText: { textAlign: "center", padding: "40px 0", color: whiteAlpha(0.62), fontSize: 14 },

  // ── Form ──
  fieldLabel: { fontSize: 11, fontWeight: 900, color: GOLD, letterSpacing: 1, textTransform: "uppercase" },
  fieldInput: { width: "100%", minHeight: 42, padding: "0 12px", borderRadius: RADIUS.sm, border: `1px solid ${whiteAlpha(0.1)}`, background: whiteAlpha(0.05), color: "#fff", fontSize: 14, outline: "none", boxSizing: "border-box" },
  fieldSelect: { width: "100%", minHeight: 42, padding: "0 12px", borderRadius: RADIUS.sm, border: `1px solid ${whiteAlpha(0.1)}`, background: whiteAlpha(0.05), color: "#fff", fontSize: 14, outline: "none", cursor: "pointer", boxSizing: "border-box" },
  fieldTextarea: { width: "100%", padding: "10px 12px", borderRadius: RADIUS.sm, border: `1px solid ${whiteAlpha(0.1)}`, background: whiteAlpha(0.05), color: "#fff", fontSize: 14, outline: "none", resize: "none", lineHeight: 1.5, boxSizing: "border-box" },
  modalActions: { display: "flex", gap: 10, marginTop: 6 },
  cancelBtn: { flex: 1, minHeight: 46, border: `1px solid ${whiteAlpha(0.1)}`, borderRadius: 12, background: whiteAlpha(0.04), color: "#fff", fontSize: 14, fontWeight: 800, cursor: "pointer" },
  submitBtn: { flex: 2, minHeight: 46, border: "none", borderRadius: 12, background: `linear-gradient(145deg, ${RED}, ${RED_DARK})`, color: "#fff", fontSize: 14, fontWeight: 1000, cursor: "pointer", boxShadow: `0 10px 28px ${redAlpha(0.32)}, inset 0 1px 0 ${whiteAlpha(0.1)}` },
  vibeChip: { flexShrink: 0, padding: "5px 12px", borderRadius: RADIUS.full, border: `1px solid ${redAlpha(0.25)}`, background: redAlpha(0.08), color: "rgba(255,165,130,0.7)", fontSize: 12, fontWeight: 700, cursor: "pointer", whiteSpace: "nowrap" },
  vibeChipActive: { flexShrink: 0, padding: "5px 12px", borderRadius: RADIUS.full, border: `1px solid ${redAlpha(0.6)}`, background: redAlpha(0.22), color: "#F87171", fontSize: 12, fontWeight: 900, cursor: "pointer", whiteSpace: "nowrap" },
  featuredSection: { marginBottom: 20, padding: "12px 14px 14px", borderRadius: 16, background: goldAlpha(0.05), border: `1px solid ${goldAlpha(0.12)}`, backdropFilter: "blur(12px)", WebkitBackdropFilter: "blur(12px)" },
  featuredLabel: { margin: "0 0 10px", fontSize: 10, fontWeight: 950, color: GOLD, letterSpacing: 2, textTransform: "uppercase" },
  featuredScroll: { display: "flex", gap: 8, overflowX: "auto", paddingBottom: 4, scrollbarWidth: "none" },
  featuredChip: { flexShrink: 0, display: "flex", flexDirection: "column", alignItems: "center", gap: 5, background: whiteAlpha(0.04), border: `1px solid ${goldAlpha(0.25)}`, borderRadius: RADIUS.md, padding: "12px 12px 10px", cursor: "pointer", minWidth: 76, backdropFilter: "blur(8px)", WebkitBackdropFilter: "blur(8px)" },
  featuredAvatar: { width: 44, height: 44, borderRadius: "50%", objectFit: "cover", border: `2px solid ${goldAlpha(0.5)}` },
  featuredAvatarInitials: { width: 44, height: 44, borderRadius: "50%", background: RED, display: "flex", alignItems: "center", justifyContent: "center", fontSize: 15, fontWeight: 900, color: "#fff", border: `2px solid ${goldAlpha(0.4)}` },
  featuredName: { fontSize: 10, fontWeight: 850, color: whiteAlpha(0.85), maxWidth: 68, textAlign: "center", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  featuredVerified: { fontSize: 11, color: GOLD, fontWeight: 900, lineHeight: 1 },
};

export default styles;
