import { RED, redAlpha, GOLD, goldAlpha } from "@/lib/tokens";

const styles = {
  page: {
    minHeight: "100vh",
    background: `radial-gradient(circle at 50% 0%, ${redAlpha(0.18)}, transparent 30%), linear-gradient(180deg, #080808 0%, #0B0B0B 100%)`,
    color: "#fff",
    fontFamily: "sans-serif",
  },
  tabStrip: {
    position: "sticky",
    top: 0,
    zIndex: 50,
    display: "flex",
    background: "rgba(8,8,8,0.92)",
    backdropFilter: "blur(14px)",
    WebkitBackdropFilter: "blur(14px)",
    borderBottom: "1px solid rgba(255,255,255,0.08)",
    padding: "0 4px",
    paddingTop: "env(safe-area-inset-top)",
  },
  tabActive: {
    flex: 1,
    minHeight: 46,
    border: "none",
    borderBottom: "2px solid #C1121F",
    background: "transparent",
    color: "#fff",
    fontSize: 13,
    fontWeight: 1000,
    letterSpacing: 0.5,
    cursor: "pointer",
  },
  tabInactive: {
    flex: 1,
    minHeight: 46,
    border: "none",
    borderBottom: "2px solid transparent",
    background: "transparent",
    color: "rgba(255,255,255,0.65)",
    fontSize: 13,
    fontWeight: 700,
    cursor: "pointer",
  },
  aiWrap: {
    minHeight: "calc(100vh - 46px)",
  },
  content: {
    maxWidth: 520,
    margin: "0 auto",
    padding: "0 16px calc(104px + env(safe-area-inset-bottom))",
  },
  pageHeader: {
    padding: "22px 0 12px",
    display: "flex",
    flexDirection: "column",
    gap: 10,
  },
  becomeCoachBtn: {
    alignSelf: "flex-start",
    background: `${goldAlpha(0.12)}`,
    border: `1px solid ${goldAlpha(0.4)}`,
    borderRadius: 20,
    padding: "7px 16px",
    color: GOLD,
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
  },
  kicker: {
    margin: 0,
    color: GOLD,
    fontSize: 11,
    fontWeight: 950,
    letterSpacing: 2,
    textTransform: "uppercase",
  },
  pageTitle: {
    margin: "4px 0 0",
    fontSize: 28,
    fontWeight: 1000,
    lineHeight: 1.1,
    fontFamily: "var(--font-display, 'Anton', sans-serif)",
  },
  filterBar: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
    marginBottom: 20,
  },
  specialtyChipsRow: {
    display: "flex",
    gap: 6,
    overflowX: "auto",
    paddingBottom: 8,
    scrollbarWidth: "none",
    marginBottom: 12,
    alignItems: "center",
  },
  specChip: {
    flexShrink: 0,
    padding: "7px 14px",
    borderRadius: 999,
    border: "1px solid rgba(255,255,255,0.1)",
    background: "rgba(255,255,255,0.03)",
    color: "rgba(255,255,255,0.45)",
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
    whiteSpace: "nowrap",
    WebkitTapHighlightColor: "transparent",
  },
  specChipActive: {
    flexShrink: 0,
    padding: "7px 14px",
    borderRadius: 999,
    border: `1px solid ${redAlpha(0.6)}`,
    background: `${redAlpha(0.18)}`,
    color: "#F87171",
    fontSize: 12,
    fontWeight: 900,
    cursor: "pointer",
    whiteSpace: "nowrap",
    WebkitTapHighlightColor: "transparent",
  },
  filterBarCompact: {
    display: "flex",
    gap: 6,
    flexWrap: "nowrap",
    overflowX: "auto",
    paddingBottom: 4,
    scrollbarWidth: "none",
    marginBottom: 20,
    alignItems: "center",
  },
  filterMoreBtn: {
    flexShrink: 0,
    padding: "5px 12px",
    borderRadius: 999,
    border: `1px solid ${goldAlpha(0.3)}`,
    background: `${goldAlpha(0.06)}`,
    color: GOLD,
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  filterSheetSectionLabel: {
    margin: "0 0 8px",
    fontSize: 10,
    fontWeight: 900,
    color: GOLD,
    letterSpacing: 1.5,
  },
  filterSheetDone: {
    marginTop: 16,
    width: "100%",
    minHeight: 46,
    border: "none",
    borderRadius: 14,
    background: "linear-gradient(135deg, #C1121F, #7d0812)",
    color: "#fff",
    fontSize: 14,
    fontWeight: 900,
    cursor: "pointer",
    boxShadow: `0 8px 24px ${redAlpha(0.25)}`,
  },
  cardRatingInline: {
    fontSize: 12,
    fontWeight: 800,
    color: GOLD,
  },
  specialtyScroll: {
    display: "flex",
    gap: 6,
    overflowX: "auto",
    paddingBottom: 4,
    scrollbarWidth: "none",
  },
  chip: {
    flexShrink: 0,
    padding: "5px 12px",
    borderRadius: 999,
    border: "1px solid rgba(255,255,255,0.16)",
    background: "rgba(255,255,255,0.05)",
    color: "rgba(255,255,255,0.7)",
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  chipActive: {
    flexShrink: 0,
    padding: "5px 12px",
    borderRadius: 999,
    border: `1px solid ${redAlpha(0.6)}`,
    background: `${redAlpha(0.18)}`,
    color: "#fff",
    fontSize: 12,
    fontWeight: 900,
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  filterRow: {
    display: "flex",
    gap: 8,
  },
  filterInput: {
    flex: 1,
    minHeight: 38,
    padding: "0 12px",
    borderRadius: 10,
    border: "1px solid rgba(255,255,255,0.14)",
    background: "rgba(255,255,255,0.07)",
    color: "#fff",
    fontSize: 13,
    outline: "none",
  },
  filterSelect: {
    minHeight: 38,
    padding: "0 10px",
    borderRadius: 10,
    border: "1px solid rgba(255,255,255,0.14)",
    background: "rgba(255,255,255,0.07)",
    color: "#fff",
    fontSize: 12,
    fontWeight: 700,
    outline: "none",
    cursor: "pointer",
  },
  cardList: {
    display: "flex",
    flexDirection: "column",
    gap: 14,
  },
  card: {
    borderRadius: 18,
    padding: "16px",
    background: "linear-gradient(145deg, #131313, #0a0a0a)",
    border: "1px solid rgba(255,255,255,0.09)",
    boxShadow: "0 8px 32px rgba(0,0,0,0.4)",
    display: "flex",
    flexDirection: "column",
    gap: 10,
  },
  cardTop: {
    display: "flex",
    gap: 12,
    alignItems: "flex-start",
  },
  avatarWrap: {
    position: "relative",
    flexShrink: 0,
  },
  avatar: {
    width: 52,
    height: 52,
    borderRadius: "50%",
    objectFit: "cover",
    border: `2px solid ${goldAlpha(0.4)}`,
  },
  avatarInitials: {
    width: 52,
    height: 52,
    borderRadius: "50%",
    background: "linear-gradient(135deg, #C1121F, #7d0812)",
    border: `2px solid ${goldAlpha(0.4)}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 18,
    fontWeight: 1000,
    color: "#fff",
  },
  verifiedDot: {
    position: "absolute",
    bottom: 0,
    right: 0,
    width: 18,
    height: 18,
    borderRadius: "50%",
    background: GOLD,
    color: "#000",
    fontSize: 10,
    fontWeight: 1000,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    border: "2px solid #0a0a0a",
  },
  cardInfo: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: 3,
    minWidth: 0,
  },
  cardNameRow: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    flexWrap: "wrap",
  },
  cardName: {
    fontSize: 16,
    fontWeight: 1000,
    color: "#fff",
  },
  verifiedBadge: {
    fontSize: 10,
    fontWeight: 900,
    color: GOLD,
    background: `${goldAlpha(0.12)}`,
    border: `1px solid ${goldAlpha(0.3)}`,
    borderRadius: 999,
    padding: "1px 7px",
    letterSpacing: 0.5,
  },
  cardLocation: {
    fontSize: 12,
    color: "rgba(255,255,255,0.55)",
    fontWeight: 600,
  },
  cardExp: {
    fontSize: 12,
    color: GOLD,
    fontWeight: 700,
  },
  specialtyRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: 5,
  },
  specialtyChip: {
    fontSize: 11,
    fontWeight: 800,
    color: "rgba(255,255,255,0.75)",
    background: "rgba(255,255,255,0.07)",
    border: "1px solid rgba(255,255,255,0.13)",
    borderRadius: 999,
    padding: "3px 9px",
  },
  cardBio: {
    margin: 0,
    fontSize: 13,
    color: "rgba(255,255,255,0.62)",
    lineHeight: 1.5,
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
  },
  cardStats: {
    display: "flex",
    gap: 16,
  },
  cardStat: {
    display: "flex",
    flexDirection: "column",
    gap: 1,
  },
  cardStatNum: {
    fontSize: 14,
    fontWeight: 1000,
    color: "#fff",
  },
  cardStatLbl: {
    fontSize: 10,
    color: "rgba(255,255,255,0.65)",
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  cardActions: {
    display: "flex",
    gap: 8,
    marginTop: 2,
  },
  viewProfileBtn: {
    flex: 1,
    minHeight: 38,
    border: "1px solid rgba(255,255,255,0.18)",
    borderRadius: 10,
    background: "rgba(255,255,255,0.07)",
    color: "#fff",
    fontSize: 13,
    fontWeight: 800,
    cursor: "pointer",
  },
  requestBtn: {
    flex: 1,
    minHeight: 38,
    border: "none",
    borderRadius: 10,
    background: "linear-gradient(135deg, #C1121F, #7d0812)",
    color: "#fff",
    fontSize: 13,
    fontWeight: 900,
    cursor: "pointer",
    boxShadow: `0 8px 24px ${redAlpha(0.28)}`,
  },
  requestedBtn: {
    flex: 1,
    minHeight: 38,
    border: "1px solid rgba(52,211,153,0.3)",
    borderRadius: 10,
    background: "rgba(52,211,153,0.1)",
    color: "#34D399",
    fontSize: 13,
    fontWeight: 900,
    cursor: "default",
  },
  createPostBtn: {
    width: "100%",
    minHeight: 48,
    border: `1px solid ${goldAlpha(0.35)}`,
    borderRadius: 14,
    background: `linear-gradient(135deg, ${redAlpha(0.9)}, ${goldAlpha(0.2)})`,
    color: "#fff",
    fontSize: 14,
    fontWeight: 1000,
    cursor: "pointer",
    marginBottom: 16,
    boxShadow: `0 12px 30px ${redAlpha(0.22)}`,
  },
  savedBanner: {
    padding: "10px 14px",
    borderRadius: 12,
    background: "rgba(52,211,153,0.12)",
    border: "1px solid rgba(52,211,153,0.28)",
    color: "#A7F3D0",
    fontSize: 13,
    fontWeight: 800,
    marginBottom: 12,
  },
  sparringCardHead: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flexWrap: "wrap",
  },
  sparringLevel: {
    fontSize: 13,
    fontWeight: 1000,
    color: GOLD,
    background: `${goldAlpha(0.12)}`,
    border: `1px solid ${goldAlpha(0.25)}`,
    borderRadius: 999,
    padding: "3px 10px",
  },
  sparringWeight: {
    fontSize: 13,
    fontWeight: 800,
    color: "#fff",
    background: "rgba(255,255,255,0.07)",
    border: "1px solid rgba(255,255,255,0.12)",
    borderRadius: 999,
    padding: "3px 10px",
  },
  sparringLocation: {
    fontSize: 12,
    color: "rgba(255,255,255,0.55)",
    fontWeight: 600,
  },
  sparringTime: {
    fontSize: 12,
    color: "rgba(255,255,255,0.55)",
    fontWeight: 600,
  },
  loadingText: {
    textAlign: "center",
    padding: "40px 0",
    color: "rgba(255,255,255,0.62)",
    fontSize: 14,
  },
  fieldLabel: {
    fontSize: 11,
    fontWeight: 900,
    color: GOLD,
    letterSpacing: 1,
    textTransform: "uppercase",
  },
  fieldInput: {
    width: "100%",
    minHeight: 42,
    padding: "0 12px",
    borderRadius: 10,
    border: "1px solid rgba(255,255,255,0.14)",
    background: "rgba(255,255,255,0.07)",
    color: "#fff",
    fontSize: 14,
    outline: "none",
    boxSizing: "border-box",
  },
  fieldSelect: {
    width: "100%",
    minHeight: 42,
    padding: "0 12px",
    borderRadius: 10,
    border: "1px solid rgba(255,255,255,0.14)",
    background: "rgba(255,255,255,0.07)",
    color: "#fff",
    fontSize: 14,
    outline: "none",
    cursor: "pointer",
    boxSizing: "border-box",
  },
  fieldTextarea: {
    width: "100%",
    padding: "10px 12px",
    borderRadius: 10,
    border: "1px solid rgba(255,255,255,0.14)",
    background: "rgba(255,255,255,0.07)",
    color: "#fff",
    fontSize: 14,
    outline: "none",
    resize: "vertical",
    fontFamily: "sans-serif",
    lineHeight: 1.5,
    boxSizing: "border-box",
  },
  modalActions: {
    display: "flex",
    gap: 10,
    marginTop: 6,
  },
  cancelBtn: {
    flex: 1,
    minHeight: 46,
    border: "1px solid rgba(255,255,255,0.14)",
    borderRadius: 12,
    background: "rgba(255,255,255,0.06)",
    color: "#fff",
    fontSize: 14,
    fontWeight: 800,
    cursor: "pointer",
  },
  submitBtn: {
    flex: 2,
    minHeight: 46,
    border: "none",
    borderRadius: 12,
    background: "linear-gradient(135deg, #C1121F, #7d0812 60%, #9a6a18)",
    color: "#fff",
    fontSize: 14,
    fontWeight: 1000,
    cursor: "pointer",
    boxShadow: `0 12px 30px ${redAlpha(0.28)}`,
  },
  vibeChip: { flexShrink: 0, padding: "5px 12px", borderRadius: 999, border: `1px solid ${redAlpha(0.25)}`, background: `${redAlpha(0.08)}`, color: "rgba(255,165,130,0.7)", fontSize: 12, fontWeight: 700, cursor: "pointer", whiteSpace: "nowrap" },
  vibeChipActive: { flexShrink: 0, padding: "5px 12px", borderRadius: 999, border: `1px solid ${redAlpha(0.6)}`, background: `${redAlpha(0.22)}`, color: "#F87171", fontSize: 12, fontWeight: 900, cursor: "pointer", whiteSpace: "nowrap" },
  featuredSection: { marginBottom: 16 },
  featuredLabel: { margin: "0 0 8px", fontSize: 11, fontWeight: 900, color: GOLD, letterSpacing: 1.5, textTransform: "uppercase" },
  featuredScroll: { display: "flex", gap: 8, overflowX: "auto", paddingBottom: 4, scrollbarWidth: "none" },
  featuredChip: { flexShrink: 0, display: "flex", flexDirection: "column", alignItems: "center", gap: 4, background: "rgba(255,255,255,0.05)", border: `1px solid ${goldAlpha(0.2)}`, borderRadius: 12, padding: "10px 12px", cursor: "pointer", minWidth: 72 },
  featuredAvatar: { width: 40, height: 40, borderRadius: "50%", objectFit: "cover", border: `2px solid ${goldAlpha(0.4)}` },
  featuredAvatarInitials: { width: 40, height: 40, borderRadius: "50%", background: "linear-gradient(135deg, #C1121F, #7d0812)", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 14, fontWeight: 900, color: "#fff" },
  featuredName: { fontSize: 10, fontWeight: 800, color: "rgba(255,255,255,0.8)", maxWidth: 64, textAlign: "center", overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  featuredVerified: { fontSize: 10, color: GOLD, fontWeight: 900 },
};

export default styles;
