import { redAlpha, RED, BG, BORDER, BORDER_2, RADIUS, whiteAlpha, blackAlpha } from "@/lib/tokens";

const s = {
  page: {
    display: "flex",
    flexDirection: "column",
    height: "100dvh",
    background: BG,
    color: "#fff",
    overflow: "hidden",
  },

  // ── Header ──
  header: {
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "calc(14px + env(safe-area-inset-top)) 16px 12px",
    borderBottom: `1px solid ${BORDER}`,
    background: blackAlpha(0.98),
    backdropFilter: "blur(20px)",
    WebkitBackdropFilter: "blur(20px)",
  },
  backBtn: {
    background: whiteAlpha(0.05),
    border: `1px solid ${whiteAlpha(0.1)}`,
    color: whiteAlpha(0.7),
    cursor: "pointer",
    padding: 6,
    borderRadius: RADIUS.sm,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    WebkitTapHighlightColor: "transparent",
  },
  headerCenter: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    flex: 1,
    justifyContent: "center",
  },
  headerDot: {
    width: 8,
    height: 8,
    borderRadius: "50%",
    flexShrink: 0,
  },
  headerTitle: {
    fontSize: 15,
    fontWeight: 900,
    color: "#fff",
    letterSpacing: 0.1,
  },
  headerAiBadge: {
    fontSize: 9,
    fontWeight: 900,
    letterSpacing: 1.5,
    border: "1px solid",
    borderRadius: 4,
    padding: "1px 5px",
  },
  clearBtn: {
    background: "none",
    border: "none",
    color: whiteAlpha(0.35),
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
    padding: "6px 4px",
    WebkitTapHighlightColor: "transparent",
  },

  // ── Persona row ──
  personaRow: {
    flexShrink: 0,
    display: "flex",
    gap: 8,
    padding: "10px 16px",
    overflowX: "auto",
    scrollbarWidth: "none",
    borderBottom: `1px solid ${whiteAlpha(0.05)}`,
  },
  personaChip: {
    flexShrink: 0,
    padding: "7px 14px",
    borderRadius: RADIUS.full,
    border: `1px solid ${whiteAlpha(0.1)}`,
    background: whiteAlpha(0.03),
    color: whiteAlpha(0.45),
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
    whiteSpace: "nowrap",
    display: "flex",
    alignItems: "center",
    gap: 5,
    WebkitTapHighlightColor: "transparent",
    transition: "background 150ms, border-color 150ms, color 150ms",
  },

  // ── Messages area ──
  messages: {
    flex: 1,
    overflowY: "auto",
    padding: "16px 0",
    WebkitOverflowScrolling: "touch",
  },
  emptyWrap: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    textAlign: "center",
    padding: "32px 24px",
    gap: 16,
  },
  coachAvatar: {
    width: 72,
    height: 72,
    borderRadius: "50%",
    border: "2px solid",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 4,
  },
  greeting: {
    margin: 0,
    fontSize: 22,
    fontWeight: 1000,
    color: "#fff",
    letterSpacing: "-0.02em",
    fontFamily: "var(--font-display, 'Anton', sans-serif)",
    textTransform: "uppercase",
  },
  quickGrid: {
    display: "flex",
    flexDirection: "column",
    gap: 8,
    width: "100%",
    maxWidth: 320,
    marginTop: 8,
  },
  quickChip: {
    width: "100%",
    padding: "12px 16px",
    borderRadius: 12,
    border: `1px solid ${whiteAlpha(0.1)}`,
    background: whiteAlpha(0.04),
    color: whiteAlpha(0.7),
    fontSize: 14,
    fontWeight: 700,
    cursor: "pointer",
    textAlign: "left",
    WebkitTapHighlightColor: "transparent",
  },

  // ── Bubbles ──
  userBubble: {
    maxWidth: "76%",
    padding: "11px 15px",
    borderRadius: "18px 18px 4px 18px",
    background: RED,
    color: "#fff",
    fontSize: 14,
    lineHeight: 1.5,
    boxShadow: `0 8px 24px ${redAlpha(0.22)}`,
    whiteSpace: "pre-wrap",
  },
  aiBubble: {
    maxWidth: "80%",
    padding: "11px 15px",
    borderRadius: "18px 18px 18px 4px",
    background: "rgba(18,18,18,0.96)",
    color: whiteAlpha(0.88),
    fontSize: 14,
    lineHeight: 1.55,
    border: `1px solid ${whiteAlpha(0.07)}`,
    borderLeft: "3px solid",
    whiteSpace: "pre-wrap",
  },

  // ── Input area ──
  inputArea: {
    flexShrink: 0,
    borderTop: `1px solid ${BORDER}`,
    background: blackAlpha(0.98),
    backdropFilter: "blur(20px)",
    WebkitBackdropFilter: "blur(20px)",
    padding: "10px 16px 12px",
  },
  quickRow: {
    display: "flex",
    gap: 6,
    overflowX: "auto",
    scrollbarWidth: "none",
    paddingBottom: 8,
  },
  quickChipSm: {
    flexShrink: 0,
    padding: "6px 12px",
    borderRadius: RADIUS.full,
    border: `1px solid ${BORDER_2}`,
    background: whiteAlpha(0.03),
    color: whiteAlpha(0.5),
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
    whiteSpace: "nowrap",
    WebkitTapHighlightColor: "transparent",
  },
  inputRow: {
    display: "flex",
    gap: 10,
    alignItems: "center",
  },
  input: {
    flex: 1,
    height: 46,
    padding: "0 16px",
    borderRadius: RADIUS.md,
    border: `1px solid ${whiteAlpha(0.1)}`,
    background: whiteAlpha(0.05),
    color: "#fff",
    fontSize: 14,
    outline: "none",
    boxSizing: "border-box",
  },
  sendBtn: {
    width: 46,
    height: 46,
    borderRadius: RADIUS.md,
    border: "none",
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
    transition: "background 150ms, box-shadow 150ms",
  },
};

export default s;
