"use client";

import { useParams, useRouter } from "next/navigation";
import { getLocale } from "@/lib/i18n";
import { GOLD, RED } from "@/lib/tokens";

const T = {
  en: {
    back: "← Back",
    badge: "Legal",
    title: "Terms of Service",
    updated: "Last updated: June 6, 2025",
    intro:
      "These Terms of Service govern your use of the GAVANA Boxing application. By creating an account or using GAVANA, you agree to these terms. Please read them carefully.",

    sections: [
      {
        heading: "1. Acceptance of Terms",
        body: [
          "By downloading, installing, or using GAVANA Boxing, you agree to be bound by these Terms of Service.",
          "If you do not agree to these terms, you may not use GAVANA.",
          "We reserve the right to update these terms at any time. Continued use after changes constitutes acceptance.",
        ],
      },
      {
        heading: "2. Description of Service",
        body: [
          "GAVANA is a boxing training platform that uses movement analysis, AI coaching, and structured training programs to help fighters develop their skills.",
          "Features include: Fighter DNA analysis, technique library, AI coaching, session tracking, leaderboards, and training prescriptions.",
          "Some features require a premium subscription. Free features are provided as-is without guarantees of availability.",
        ],
      },
      {
        heading: "3. User Accounts",
        body: [
          "You must create an account to use GAVANA. You are responsible for maintaining the confidentiality of your account credentials.",
          "You must provide accurate information when creating your account. False information may result in account termination.",
          "You are responsible for all activities that occur under your account.",
          "You must be at least 13 years old to create an account.",
        ],
      },
      {
        heading: "4. Acceptable Use",
        body: [
          "You may use GAVANA for personal, non-commercial boxing training purposes.",
          "You may not: use the app to harass or harm other users; attempt to reverse-engineer or copy proprietary content; use automated tools to access the service; share your account credentials with others.",
          "You may not post, upload, or share content that is abusive, illegal, or infringes on the rights of others.",
          "Violation of these rules may result in immediate account suspension.",
        ],
      },
      {
        heading: "5. Health & Fitness Disclaimer",
        body: [
          "GAVANA provides boxing training guidance for informational and educational purposes only.",
          "GAVANA is NOT a substitute for professional medical advice, diagnosis, or treatment. Consult a qualified healthcare provider before starting any physical training program.",
          "Boxing involves physical risk. You assume full responsibility for your health and safety when following any training guidance provided by GAVANA.",
          "If you experience pain, dizziness, or discomfort during training, stop immediately and consult a medical professional.",
          "GAVANA and its operators are not liable for any injury, health complications, or physical harm resulting from use of the app.",
        ],
      },
      {
        heading: "6. AI Coaching",
        body: [
          "AI coaching responses are generated by artificial intelligence and may not always be accurate, complete, or appropriate for your specific situation.",
          "AI coaching is for informational purposes only and does not replace a qualified human boxing coach.",
          "GAVANA does not guarantee the accuracy or effectiveness of AI-generated coaching advice.",
          "Never disregard professional coaching advice based on AI responses from GAVANA.",
        ],
      },
      {
        heading: "7. Payments & Subscriptions",
        body: [
          "Premium subscriptions are billed on a recurring basis (monthly or annually) through Stripe.",
          "All payments are non-refundable unless required by applicable law.",
          "You may cancel your subscription at any time. Cancellation takes effect at the end of the current billing period.",
          "We reserve the right to change pricing with 30 days' notice to subscribers.",
        ],
      },
      {
        heading: "8. Intellectual Property",
        body: [
          "All content in GAVANA — including technique descriptions, training programs, fighter profiles, UI design, and AI coaching systems — is owned by GAVANA Boxing and protected by intellectual property laws.",
          "You may not reproduce, distribute, or create derivative works from GAVANA content without written permission.",
          "Your personal training data and session records remain your property.",
        ],
      },
      {
        heading: "9. User Content",
        body: [
          "By uploading or sharing content in GAVANA (profile photos, videos, etc.), you grant GAVANA a non-exclusive license to use that content within the platform.",
          "You retain ownership of your content. We will not sell your content to third parties.",
          "You represent that you have the rights to any content you upload.",
        ],
      },
      {
        heading: "10. Limitation of Liability",
        body: [
          "GAVANA is provided 'as is' without warranties of any kind, express or implied.",
          "To the fullest extent permitted by law, GAVANA and its operators shall not be liable for any indirect, incidental, special, or consequential damages.",
          "Our total liability to you for any claim shall not exceed the amount you paid to GAVANA in the 12 months preceding the claim.",
        ],
      },
      {
        heading: "11. Termination",
        body: [
          "You may terminate your account at any time from profile settings.",
          "We may suspend or terminate your account for violation of these terms, illegal activity, or other conduct harmful to GAVANA or its users.",
          "Upon termination, your right to use the service ceases immediately.",
        ],
      },
      {
        heading: "12. Governing Law",
        body: [
          "These Terms of Service are governed by the laws of Mongolia.",
          "Any disputes arising from these terms shall be resolved through good-faith negotiation, and if unsuccessful, through binding arbitration.",
        ],
      },
      {
        heading: "13. Contact",
        body: [
          "Questions about these Terms of Service? Contact us at:",
          "Email: legal@gavana.app",
          "GAVANA Boxing",
        ],
      },
    ],
  },

  mn: {
    back: "← Буцах",
    badge: "Хууль эрх зүй",
    title: "Үйлчилгээний нөхцөл",
    updated: "Сүүлд шинэчилсэн: 2025 оны 6-р сарын 6",
    intro:
      "Энэхүү үйлчилгээний нөхцөл нь GAVANA Boxing програмыг ашиглахад таны харилцааг зохицуулна. Данс үүсгэх эсвэл GAVANA ашиглаж эхлэхэд та эдгээр нөхцлийг хүлээн зөвшөөрсөнд тооцогдоно.",

    sections: [
      {
        heading: "1. Нөхцлийг зөвшөөрөх",
        body: [
          "GAVANA Boxing татаж авах, суулгах, ашиглахаар та энэхүү үйлчилгээний нөхцлийг хүлээн зөвшөөрч байна.",
          "Эдгээр нөхцлийг зөвшөөрөхгүй бол GAVANA-г ашиглаж болохгүй.",
          "Бид нөхцлийг хэдийд ч шинэчлэх эрхтэй. Өөрчлөлтийн дараа үргэлжлүүлэн ашиглах нь зөвшөөрлийг илэрхийлнэ.",
        ],
      },
      {
        heading: "2. Үйлчилгээний тодорхойлолт",
        body: [
          "GAVANA нь хөдөлгөөний шинжилгээ, AI коуч, бүтэцтэй дасгалжуулалтын хөтөлбөрүүдийг ашиглан тулаанчдад ур чадвараа хөгжүүлэхэд туслах боксын дасгалжуулалтын платформ юм.",
          "Функцууд: Тулаанчийн DNA шинжилгээ, техникийн сан, AI коуч, сессийн бүртгэл, тэргүүний самбар, дасгалын жор.",
          "Зарим функц нь үнэт захиалга шаардана. Үнэгүй функцийг байгаагаар нь олгодог.",
        ],
      },
      {
        heading: "3. Хэрэглэгчийн данс",
        body: [
          "GAVANA ашиглахын тулд данс үүсгэх шаардлагатай. Данс нэвтрэх мэдээллийн нууцлалыг хамгаалах хариуцлагыг та өөрөө хүлээнэ.",
          "Данс үүсгэхдээ үнэн мэдээлэл оруулах ёстой. Худал мэдээлэл данс хаагдахад хүргэж болно.",
          "Таны дансан дор үйлдэгдсэн бүх үйлдлийн хариуцлагыг та өөрөө хүлээнэ.",
          "Данс үүсгэхэд 13 нас хүрсэн байх шаардлагатай.",
        ],
      },
      {
        heading: "4. Зөвшөөрөгдсөн хэрэглээ",
        body: [
          "GAVANA-г хувийн, арилжааны бус боксын дасгалжуулалтын зориулалтаар ашиглах боломжтой.",
          "Дараахийг хориглоно: бусад хэрэглэгчдийг дарамтлах; өмчийн контентыг хуулбарлах; автомат хэрэглүүр ашиглах; бүртгэл нэвтрэх мэдээллийг хуваалцах.",
          "Хорлонт, хууль бус, бусдын эрхийг зөрчсөн контент байршуулах, хуваалцахыг хориглоно.",
          "Эдгээр дүрмийг зөрчвөл данс шууд түдгэлзүүлэгдэж болно.",
        ],
      },
      {
        heading: "5. Эрүүл мэнд ба биеийн тамирын анхааруулга",
        body: [
          "GAVANA нь боксын дасгалжуулалтын зааварчилгааг зөвхөн мэдээллийн болон сургалтын зориулалтаар олгоно.",
          "GAVANA нь мэргэжлийн эмнэлгийн зөвлөгөө, оношлогоо, эмчилгээг орлохгүй. Дасгалжуулалтын хөтөлбөр эхлэхийн өмнө мэргэжлийн эмчтэй зөвлөлдөнө үү.",
          "Бокс нь биеийн эрсдэлтэй. GAVANA-ийн зааварчилгааг дагаж дасгал хийхдээ та өөрийн эрүүл мэнд, аюулгүй байдлын хариуцлагыг бүрэн хүлээнэ.",
          "Дасгал хийх явцад өвдөлт, толгой эргэх, тав гамшиг мэдрэгдвэл даруй зогсож мэргэжлийн эмчтэй зөвлөлдөнө.",
          "GAVANA болон оператор нь апп ашигласнаас үүссэн гэмтэл, эрүүл мэндийн хүндрэл, бодгалийн хохирлын хариуцлагыг хүлээхгүй.",
        ],
      },
      {
        heading: "6. AI коуч",
        body: [
          "AI коучийн хариулт нь хиймэл оюун ухаанаар үүсгэгдэх тул таны тодорхой нөхцөл байдалд үргэлж үнэн зөв, бүрэн, тохиромжтой байхгүй байж болно.",
          "AI коуч нь зөвхөн мэдээллийн зориулалттай бөгөөд мэргэжлийн хүний коучийг орлохгүй.",
          "GAVANA нь AI-ийн зөвлөгөөний нарийвчлал, үр нөлөөнд баталгаа өгөхгүй.",
        ],
      },
      {
        heading: "7. Төлбөр ба захиалга",
        body: [
          "Үнэт захиалга нь Stripe-ийн дамжуулан сарын эсвэл жилийн давтамжтайгаар тооцогдоно.",
          "Хэрэглэх хуулиар шаардагдаагүй бол бүх төлбөр буцаалгүй.",
          "Захиалгыг хэдийд ч цуцалж болно. Цуцлалт нь одоогийн тооцооны хугацааны эцэст хүчин төгөлдөр болно.",
          "Захиалагчдад 30 хоногийн урьдчилсан мэдэгдлийн дагуу үнийг өөрчлөх эрхтэй.",
        ],
      },
      {
        heading: "8. Оюуны өмч",
        body: [
          "GAVANA доторх бүх контент — техникийн тайлбар, дасгалын хөтөлбөр, тулаанчийн профайл, UI дизайн, AI коучийн системүүд — GAVANA Boxing-ийн өмч бөгөөд оюуны өмчийн хуулиар хамгаалагдана.",
          "Бичгийн зөвшөөрөлгүйгээр GAVANA-ийн контентыг хувилах, тарааx, дериватив бүтээл гаргахыг хориглоно.",
          "Таны хувийн дасгалын мэдээлэл болон сессийн бичлэг таны өмч хэвээр үлдэнэ.",
        ],
      },
      {
        heading: "9. Хэрэглэгчийн контент",
        body: [
          "GAVANA-д контент байршуулах эсвэл хуваалцахад та тухайн контентыг платформ дотор ашиглах онцгой бус лицензийг GAVANA-д олгоно.",
          "Контентынхоо өмчлөлийг та хадгалж үлдэнэ. Бид таны контентыг гуравдагч талд зарахгүй.",
          "Та байршуулж буй контентад эрх эзэмшдэгээ баталж байна.",
        ],
      },
      {
        heading: "10. Хариуцлагын хязгаарлалт",
        body: [
          "GAVANA нь ямар нэгэн баталгаагүйгээр 'байгаагаар нь' олгогдоно.",
          "Хуулиар зөвшөөрсөн хамгийн өргөн хэмжээнд GAVANA болон оператор нь шууд бус, санамсаргүй, тусгай, үр дагаврын хохирлын хариуцлагыг хүлээхгүй.",
          "Нэхэмжлэл бүрт таны нийт хариуцлага нь нэхэмжлэлийн өмнөх 12 сарын хугацаанд GAVANA-д төлсөн дүнгээс хэтрэхгүй.",
        ],
      },
      {
        heading: "11. Дуусгавар болгох",
        body: [
          "Профайл тохиргооноос дансаа хэдийд ч хаах боломжтой.",
          "Эдгээр нөхцлийг зөрчсөн, хууль бус үйлдэл хийсэн тохиолдолд бид дансыг түдгэлзүүлж эсвэл хаах эрхтэй.",
          "Дуусгавар болсны дараа үйлчилгээ ашиглах таны эрх нэн даруй зогсоно.",
        ],
      },
      {
        heading: "12. Хэрэглэх хууль",
        body: [
          "Энэхүү үйлчилгээний нөхцөл нь Монгол улсын хуулиар зохицуулагдана.",
          "Эдгээр нөхцлөөс үүдэлтэй маргааныг эхлээд сайн санааны хэлэлцүүлгээр, амжилтгүй болвол заавал биелэгдэх арбитраар шийдвэрлэнэ.",
        ],
      },
      {
        heading: "13. Холбоо барих",
        body: [
          "Үйлчилгээний нөхцлийн талаар асуулт байвал:",
          "И-мэйл: legal@gavana.app",
          "GAVANA Boxing",
        ],
      },
    ],
  },

  ko: {
    back: "← 뒤로",
    badge: "법적 고지",
    title: "이용약관",
    updated: "최종 업데이트: 2025년 6월 6일",
    intro:
      "이 이용약관은 GAVANA Boxing 앱 이용을 규정합니다. 계정을 생성하거나 GAVANA를 사용함으로써 이 약관에 동의하는 것으로 간주합니다.",

    sections: [
      {
        heading: "1. 약관 동의",
        body: [
          "GAVANA Boxing을 다운로드, 설치, 또는 사용함으로써 이 이용약관에 동의합니다.",
          "이 약관에 동의하지 않는 경우 GAVANA를 사용할 수 없습니다.",
          "당사는 언제든지 약관을 업데이트할 권리를 보유합니다. 변경 후 계속 사용하면 동의한 것으로 간주합니다.",
        ],
      },
      {
        heading: "2. 서비스 설명",
        body: [
          "GAVANA는 동작 분석, AI 코칭, 구조화된 트레이닝 프로그램을 통해 파이터의 기술 향상을 돕는 복싱 트레이닝 플랫폼입니다.",
          "기능: 파이터 DNA 분석, 기술 라이브러리, AI 코칭, 세션 추적, 리더보드, 트레이닝 처방.",
          "일부 기능은 프리미엄 구독이 필요합니다. 무료 기능은 현 상태로 제공되며 가용성을 보장하지 않습니다.",
        ],
      },
      {
        heading: "3. 사용자 계정",
        body: [
          "GAVANA를 사용하려면 계정을 생성해야 합니다. 계정 자격 증명의 기밀 유지는 귀하의 책임입니다.",
          "계정 생성 시 정확한 정보를 제공해야 합니다. 허위 정보는 계정 해지로 이어질 수 있습니다.",
          "귀하의 계정에서 발생하는 모든 활동에 대한 책임은 귀하에게 있습니다.",
          "계정을 생성하려면 만 13세 이상이어야 합니다.",
        ],
      },
      {
        heading: "4. 허용 사용",
        body: [
          "GAVANA는 개인적, 비상업적 복싱 트레이닝 목적으로 사용할 수 있습니다.",
          "금지 사항: 다른 사용자를 괴롭히거나 해치는 행위; 독점 콘텐츠 역공학 또는 복사; 자동화 도구 사용; 계정 자격 증명 공유.",
          "모욕적, 불법적, 또는 타인의 권리를 침해하는 콘텐츠 게시, 업로드, 공유는 금지됩니다.",
          "이 규칙 위반 시 계정이 즉시 정지될 수 있습니다.",
        ],
      },
      {
        heading: "5. 건강 및 피트니스 면책 조항",
        body: [
          "GAVANA는 복싱 트레이닝 지침을 정보 및 교육 목적으로만 제공합니다.",
          "GAVANA는 전문 의료 조언, 진단 또는 치료를 대체하지 않습니다. 트레이닝 프로그램 시작 전 의료 전문가와 상담하세요.",
          "복싱에는 신체적 위험이 따릅니다. GAVANA의 트레이닝 지침을 따를 때 귀하의 건강과 안전에 대한 책임은 귀하에게 있습니다.",
          "훈련 중 통증, 어지러움, 불편함을 느끼면 즉시 중단하고 의료 전문가에게 상담하세요.",
          "GAVANA와 운영자는 앱 사용으로 인한 부상, 건강 합병증 또는 신체적 피해에 대해 책임지지 않습니다.",
        ],
      },
      {
        heading: "6. AI 코칭",
        body: [
          "AI 코칭 응답은 인공지능으로 생성되며 항상 정확하거나 완전하거나 귀하의 상황에 적합하지 않을 수 있습니다.",
          "AI 코칭은 정보 제공 목적으로만 제공되며 자격을 갖춘 복싱 코치를 대체하지 않습니다.",
          "GAVANA는 AI 생성 코칭 조언의 정확성이나 효과를 보장하지 않습니다.",
        ],
      },
      {
        heading: "7. 결제 및 구독",
        body: [
          "프리미엄 구독은 Stripe를 통해 월별 또는 연간으로 반복 청구됩니다.",
          "관련 법률에서 요구하지 않는 한 모든 결제는 환불되지 않습니다.",
          "언제든지 구독을 취소할 수 있습니다. 취소는 현재 청구 기간 종료 시 적용됩니다.",
          "당사는 구독자에게 30일 전 통보 후 가격을 변경할 권리를 보유합니다.",
        ],
      },
      {
        heading: "8. 지적 재산권",
        body: [
          "GAVANA의 모든 콘텐츠 — 기술 설명, 트레이닝 프로그램, 파이터 프로필, UI 디자인, AI 코칭 시스템 — 는 GAVANA Boxing의 소유이며 지적 재산권법으로 보호됩니다.",
          "서면 허가 없이 GAVANA 콘텐츠를 복제, 배포, 또는 파생 작품을 만드는 것은 금지됩니다.",
          "귀하의 개인 트레이닝 데이터와 세션 기록은 귀하의 소유로 유지됩니다.",
        ],
      },
      {
        heading: "9. 사용자 콘텐츠",
        body: [
          "GAVANA에 콘텐츠를 업로드하거나 공유함으로써 플랫폼 내에서 해당 콘텐츠를 사용할 수 있는 비독점 라이선스를 GAVANA에 부여합니다.",
          "콘텐츠의 소유권은 귀하에게 있습니다. 당사는 귀하의 콘텐츠를 제3자에게 판매하지 않습니다.",
          "업로드하는 콘텐츠에 대한 권리를 보유하고 있음을 확인합니다.",
        ],
      },
      {
        heading: "10. 책임 제한",
        body: [
          "GAVANA는 명시적이든 묵시적이든 어떠한 종류의 보증 없이 '있는 그대로' 제공됩니다.",
          "법률이 허용하는 최대 범위 내에서 GAVANA와 운영자는 간접적, 우발적, 특별 또는 결과적 손해에 대해 책임지지 않습니다.",
          "귀하에 대한 당사의 총 책임은 청구 전 12개월 동안 귀하가 GAVANA에 지불한 금액을 초과하지 않습니다.",
        ],
      },
      {
        heading: "11. 해지",
        body: [
          "프로필 설정에서 언제든지 계정을 해지할 수 있습니다.",
          "당사는 약관 위반, 불법 행위 또는 GAVANA나 사용자에게 해를 끼치는 기타 행위에 대해 계정을 정지 또는 해지할 수 있습니다.",
          "해지 후 서비스 사용 권한이 즉시 소멸됩니다.",
        ],
      },
      {
        heading: "12. 준거법",
        body: [
          "이 이용약관은 몽골의 법률에 따라 규정됩니다.",
          "이 약관에서 발생하는 모든 분쟁은 선의의 협상으로, 실패할 경우 구속력 있는 중재를 통해 해결합니다.",
        ],
      },
      {
        heading: "13. 문의",
        body: [
          "이용약관에 관한 문의:",
          "이메일: legal@gavana.app",
          "GAVANA Boxing",
        ],
      },
    ],
  },
};

export default function TermsPage() {
  const { locale } = useParams();
  const router = useRouter();
  const lang = getLocale(locale);
  const t = T[lang] || T.en;

  return (
    <div style={{
      minHeight: "100dvh",
      background: "#0a0809",
      color: "#fff",
      fontFamily: "var(--font-sans, system-ui, sans-serif)",
    }}>
      {/* Header */}
      <div style={{
        position: "sticky", top: 0, zIndex: 10,
        background: "rgba(10,8,9,0.92)",
        backdropFilter: "blur(12px)",
        borderBottom: "1px solid rgba(255,255,255,0.07)",
        padding: "14px 20px",
        display: "flex", alignItems: "center", gap: 12,
      }}>
        <button
          type="button"
          onClick={() => router.back()}
          style={{
            background: "none", border: "none", color: "rgba(255,255,255,0.5)",
            fontSize: 15, cursor: "pointer", padding: "4px 0",
          }}
        >
          {t.back}
        </button>
        <div style={{ flex: 1 }} />
        <span style={{
          fontSize: 9, fontWeight: 900, letterSpacing: 1.5,
          color: GOLD, background: `${GOLD}15`,
          border: `1px solid ${GOLD}30`,
          borderRadius: 6, padding: "3px 8px", textTransform: "uppercase",
        }}>
          {t.badge}
        </span>
      </div>

      {/* Content */}
      <div style={{ maxWidth: 680, margin: "0 auto", padding: "32px 20px 80px" }}>
        {/* Title */}
        <div style={{ marginBottom: 28 }}>
          <h1 style={{
            fontSize: 28, fontWeight: 1000, color: "#fff", margin: "0 0 8px",
            fontFamily: "var(--font-display, 'Anton', sans-serif)",
            textTransform: "uppercase", letterSpacing: "-0.01em",
          }}>
            {t.title}
          </h1>
          <p style={{ margin: 0, fontSize: 12, color: "rgba(255,255,255,0.35)", letterSpacing: 0.3 }}>
            {t.updated}
          </p>
        </div>

        {/* Intro */}
        <p style={{
          fontSize: 14, color: "rgba(255,255,255,0.65)", lineHeight: 1.7,
          margin: "0 0 32px",
          padding: "16px 18px",
          background: "rgba(255,255,255,0.04)",
          borderRadius: 12,
          border: "1px solid rgba(255,255,255,0.08)",
          borderLeft: `3px solid ${RED}60`,
        }}>
          {t.intro}
        </p>

        {/* Health warning banner */}
        <div style={{
          padding: "14px 16px", borderRadius: 12, marginBottom: 28,
          background: `${RED}10`, border: `1px solid ${RED}35`,
          display: "flex", gap: 12, alignItems: "flex-start",
        }}>
          <span style={{ fontSize: 18, flexShrink: 0 }}>⚠️</span>
          <p style={{ margin: 0, fontSize: 13, color: "#fca5a5", lineHeight: 1.6 }}>
            {lang === "mn"
              ? "GAVANA нь эмнэлгийн зөвлөгөөг орлохгүй. Дасгал хийхийн өмнө эмчтэй зөвлөлд."
              : lang === "ko"
              ? "GAVANA는 의료 조언을 대체하지 않습니다. 훈련 전 의료 전문가와 상담하세요."
              : "GAVANA is not medical advice. Consult a healthcare professional before training."}
          </p>
        </div>

        {/* Sections */}
        <div style={{ display: "flex", flexDirection: "column", gap: 24 }}>
          {t.sections.map((section, i) => (
            <div key={i}>
              <h2 style={{
                fontSize: 13, fontWeight: 900, color: GOLD,
                margin: "0 0 10px", letterSpacing: 0.3,
                textTransform: "uppercase",
              }}>
                {section.heading}
              </h2>
              <ul style={{ margin: 0, padding: 0, listStyle: "none", display: "flex", flexDirection: "column", gap: 7 }}>
                {section.body.map((item, j) => (
                  <li key={j} style={{
                    fontSize: 13.5, color: "rgba(255,255,255,0.62)",
                    lineHeight: 1.65, paddingLeft: 16, position: "relative",
                  }}>
                    <span style={{
                      position: "absolute", left: 0, top: "0.55em",
                      width: 4, height: 4, borderRadius: "50%",
                      background: "rgba(255,255,255,0.2)", display: "block",
                    }} />
                    {item}
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>

        {/* Footer */}
        <div style={{
          marginTop: 40, padding: "16px 18px", borderRadius: 12,
          background: `${RED}08`, border: `1px solid ${RED}20`,
          textAlign: "center",
        }}>
          <p style={{ margin: 0, fontSize: 12, color: "rgba(255,255,255,0.3)", lineHeight: 1.6 }}>
            © 2025 GAVANA Boxing. All rights reserved.
          </p>
        </div>
      </div>
    </div>
  );
}
