import { RED, BG, redAlpha, GOLD, goldAlpha } from "@/lib/tokens";

const styles = {
  page: {
    minHeight: "100dvh",
    background: BG,
    color: "#fff",
    paddingBottom: "calc(88px + env(safe-area-inset-bottom))",
  },
  centered: {
    minHeight: "100dvh",
    background: BG,
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  header: {
    position: "sticky",
    top: 0,
    zIndex: 10,
    display: "grid",
    gridTemplateColumns: "56px 1fr 44px",
    alignItems: "center",
    gap: 12,
    padding: "calc(env(safe-area-inset-top) + 14px) 16px 14px",
    background: "rgba(7,7,7,0.94)",
    backdropFilter: "blur(20px)",
    WebkitBackdropFilter: "blur(20px)",
    borderBottom: "1px solid rgba(255,255,255,0.05)",
  },
  backButton: {
    border: "none",
    background: "rgba(255,255,255,0.07)",
    color: "rgba(255,255,255,0.7)",
    borderRadius: 10,
    width: 40,
    height: 40,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    flexShrink: 0,
  },
  eyebrow: {
    margin: 0,
    color: `${goldAlpha(0.6)}`,
    fontSize: 9,
    fontWeight: 900,
    letterSpacing: 2,
    textAlign: "center",
    textTransform: "uppercase",
  },
  title: {
    margin: "3px 0 0",
    textAlign: "center",
    fontSize: 22,
    fontWeight: 900,
    letterSpacing: "-0.02em",
  },
  unreadPill: {
    justifySelf: "end",
    minWidth: 26,
    height: 26,
    borderRadius: 13,
    background: RED,
    boxShadow: `0 0 12px ${redAlpha(0.5)}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 11,
    fontWeight: 900,
  },
  unreadPillMuted: {
    justifySelf: "end",
    minWidth: 26,
    height: 26,
    borderRadius: 13,
    background: "rgba(255,255,255,0.06)",
    color: "#555",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 11,
    fontWeight: 800,
  },
  list: {
    maxWidth: 540,
    margin: "0 auto",
    padding: "12px 16px",
  },
  group: {
    display: "grid",
    gap: 6,
    marginBottom: 28,
  },
  groupTitle: {
    color: `${goldAlpha(0.55)}`,
    fontSize: 10,
    fontWeight: 900,
    letterSpacing: 2,
    textTransform: "uppercase",
    padding: "6px 2px 8px",
  },
  empty: {
    minHeight: "60vh",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    color: "#888",
    textAlign: "center",
  },
  emptyIcon: {
    width: 72,
    height: 72,
    borderRadius: 36,
    background: `${redAlpha(0.1)}`,
    color: `${goldAlpha(0.85)}`,
    border: `1px solid ${goldAlpha(0.2)}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
    boxShadow: `0 0 40px ${redAlpha(0.15)}`,
  },
  emptyTitle: {
    margin: 0,
    color: "#fff",
    fontSize: 17,
    fontWeight: 800,
  },
  emptyText: {
    margin: "8px 0 0",
    maxWidth: 260,
    lineHeight: 1.55,
    fontSize: 13,
    color: "#555",
  },
  notification: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    gap: 13,
    padding: "13px 14px",
    border: "none",
    borderRadius: 16,
    color: "#fff",
    textAlign: "left",
    cursor: "pointer",
    position: "relative",
    overflow: "hidden",
    transition: "background 200ms ease",
  },
  unreadBar: {
    position: "absolute",
    top: 0,
    left: 0,
    width: 3,
    bottom: 0,
    background: RED,
    borderRadius: "3px 0 0 3px",
  },
  avatarWrap: {
    position: "relative",
    flexShrink: 0,
  },
  avatar: {
    width: 46,
    height: 46,
    borderRadius: "50%",
    background: "#1a1a1a",
    color: "#fff",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontWeight: 800,
    fontSize: 17,
    overflow: "hidden",
    flexShrink: 0,
  },
  avatarImage: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    display: "block",
  },
  typeBadge: {
    position: "absolute",
    bottom: -2,
    right: -4,
    width: 19,
    height: 19,
    borderRadius: "50%",
    background: "#0d0d0d",
    border: "1.5px solid #1a1a1a",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 10,
    lineHeight: 1,
  },
  notificationBody: {
    minWidth: 0,
    flex: 1,
  },
  notificationTopLine: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "baseline",
    marginBottom: 3,
  },
  username: {
    fontSize: 13,
    fontWeight: 800,
    color: "#fff",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    maxWidth: "65%",
  },
  date: {
    color: "#444",
    fontSize: 10,
    whiteSpace: "nowrap",
    flexShrink: 0,
  },
  notificationText: {
    fontSize: 13,
    color: "rgba(255,255,255,0.55)",
    lineHeight: 1.4,
  },
  commentPreview: {
    marginTop: 5,
    color: "#555",
    fontSize: 12,
    lineHeight: 1.4,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    fontStyle: "italic",
  },
  pvpScoreRow: {
    marginTop: 4,
    fontSize: 12,
    fontWeight: 700,
    color: "#aaa",
  },
  filterBar: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "10px 16px 4px",
    maxWidth: 540,
    margin: "0 auto",
  },
  filterChips: {
    display: "flex",
    gap: 6,
    flex: 1,
    overflowX: "auto",
    scrollbarWidth: "none",
    WebkitOverflowScrolling: "touch",
  },
  filterChip: {
    flexShrink: 0,
    padding: "6px 13px",
    borderRadius: 999,
    border: "1px solid rgba(255,255,255,0.1)",
    background: "rgba(255,255,255,0.04)",
    color: "rgba(255,255,255,0.7)",
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
    whiteSpace: "nowrap",
    transition: "all 0.15s ease",
  },
  filterChipActive: {
    background: `${redAlpha(0.18)}`,
    border: `1px solid ${redAlpha(0.55)}`,
    color: "#fff",
    fontWeight: 900,
  },
  clearBtn: {
    flexShrink: 0,
    padding: "6px 12px",
    borderRadius: 999,
    border: "1px solid rgba(248,113,113,0.25)",
    background: "rgba(248,113,113,0.06)",
    color: "#F87171",
    fontSize: 11,
    fontWeight: 800,
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  markReadBtn: {
    flexShrink: 0,
    padding: "6px 12px",
    borderRadius: 999,
    border: `1px solid ${goldAlpha(0.3)}`,
    background: `${goldAlpha(0.07)}`,
    color: GOLD,
    fontSize: 11,
    fontWeight: 800,
    cursor: "pointer",
    whiteSpace: "nowrap",
  },
  dismissBtn: {
    flexShrink: 0,
    width: 26,
    height: 26,
    border: "none",
    background: "transparent",
    color: "rgba(255,255,255,0.22)",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    borderRadius: 8,
    padding: 0,
    marginLeft: 4,
    transition: "color 0.15s, background 0.15s",
  },
  toast: {
    position: "fixed",
    bottom: "calc(72px + env(safe-area-inset-bottom))",
    left: "50%",
    transform: "translateX(-50%)",
    zIndex: 9999,
    background: "rgba(30,10,10,0.97)",
    border: "1px solid rgba(248,113,113,0.35)",
    color: "#F87171",
    padding: "10px 20px",
    borderRadius: 12,
    fontSize: 13,
    fontWeight: 700,
    whiteSpace: "nowrap",
    boxShadow: "0 4px 24px rgba(0,0,0,0.4)",
    pointerEvents: "none",
  },
};



export default styles;
