import { goldAlpha, redAlpha, GOLD, RED, BG, BORDER, BORDER_2, RADIUS, whiteAlpha, blackAlpha } from "@/lib/tokens";

const s = {
  aiBuilderBanner: {
    width: "100%", boxSizing: "border-box", display: "flex", alignItems: "center", gap: 14,
    padding: "14px 16px", borderRadius: `3px ${RADIUS.md}px ${RADIUS.md}px 3px`,
    background: `${goldAlpha(0.08)}`, backdropFilter: "blur(12px)", WebkitBackdropFilter: "blur(12px)",
    border: `1px solid ${goldAlpha(0.22)}`, borderLeft: `2.5px solid ${GOLD}`,
    cursor: "pointer", marginBottom: 20, textAlign: "left",
  },
  page: {
    minHeight: "100dvh",
    background: `radial-gradient(ellipse at 50% 0%, ${goldAlpha(0.1)} 0%, transparent 40%), ${BG}`,
    color: "#fff",
    display: "flex",
    flexDirection: "column",
    paddingBottom: "calc(88px + env(safe-area-inset-bottom))",
  },
  header: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    padding: "calc(16px + env(safe-area-inset-top)) 16px 16px",
    borderBottom: `1px solid ${BORDER}`,
    position: "sticky",
    top: 0,
    background: blackAlpha(0.96),
    backdropFilter: "blur(20px)",
    WebkitBackdropFilter: "blur(20px)",
    zIndex: 10,
  },
  backBtn: {
    width: 40,
    height: 40,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: whiteAlpha(0.05),
    border: `1px solid ${whiteAlpha(0.1)}`,
    color: "#fff",
    borderRadius: 12,
    cursor: "pointer",
    padding: 0,
    flexShrink: 0,
  },
  kicker: {
    margin: 0,
    fontSize: 10,
    fontWeight: 900,
    letterSpacing: 2,
    textTransform: "uppercase",
    color: RED,
  },
  title: {
    margin: "2px 0 0",
    fontSize: "clamp(20px, 6vw, 26px)",
    fontWeight: 1000,
    letterSpacing: "-0.02em",
    textTransform: "uppercase",
    fontFamily: "var(--font-display, 'Anton', sans-serif)",
  },
  content: {
    flex: 1,
    padding: "16px",
    display: "flex",
    flexDirection: "column",
    gap: 24,
    overflowY: "auto",
  },
  section: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
  },
  sectionTitle: {
    margin: 0,
    fontSize: 10,
    fontWeight: 900,
    letterSpacing: 2.5,
    textTransform: "uppercase",
    color: RED,
    paddingBottom: 2,
  },
  enrolledCard: {
    background: whiteAlpha(0.03),
    backdropFilter: "blur(18px)",
    WebkitBackdropFilter: "blur(18px)",
    border: `1px solid ${BORDER_2}`,
    borderRadius: `3px ${RADIUS.lg}px ${RADIUS.lg}px 3px`,
    padding: "14px 16px",
    display: "flex",
    flexDirection: "column",
    gap: 0,
    boxShadow: `0 8px 28px ${blackAlpha(0.3)}`,
  },
  enrolledTitle: {
    margin: "6px 0 0",
    fontSize: 15,
    fontWeight: 900,
    color: "#fff",
  },
  streakBadge: {
    display: "inline-flex",
    alignSelf: "flex-start",
    marginTop: 7,
    padding: "3px 10px",
    borderRadius: RADIUS.full,
    background: "rgba(251,146,60,0.12)",
    border: "1px solid rgba(251,146,60,0.28)",
    color: "#FB923C",
    fontSize: 11,
    fontWeight: 800,
  },
  continueBtn: {
    flex: 1,
    padding: "10px 16px",
    borderRadius: RADIUS.sm,
    border: "none",
    fontSize: 13,
    fontWeight: 900,
    color: "#fff",
    transition: "opacity 0.15s",
  },
  unenrollBtn: {
    padding: "10px 14px",
    borderRadius: RADIUS.sm,
    border: `1px solid ${whiteAlpha(0.1)}`,
    background: whiteAlpha(0.04),
    color: whiteAlpha(0.4),
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
  },
  discoverCard: {
    background: whiteAlpha(0.03),
    backdropFilter: "blur(18px)",
    WebkitBackdropFilter: "blur(18px)",
    border: `1px solid ${BORDER_2}`,
    borderRadius: `3px ${RADIUS.lg}px ${RADIUS.lg}px 3px`,
    padding: "14px 16px",
    display: "flex",
    flexDirection: "column",
    gap: 12,
    boxShadow: `0 8px 28px ${blackAlpha(0.25)}`,
  },
  programEmoji: {
    width: 44,
    height: 44,
    borderRadius: 12,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 22,
    flexShrink: 0,
  },
  metaChip: {
    fontSize: 10,
    fontWeight: 700,
    color: whiteAlpha(0.4),
    background: whiteAlpha(0.05),
    border: `1px solid ${whiteAlpha(0.09)}`,
    borderRadius: RADIUS.full,
    padding: "2px 8px",
  },
  enrollBtn: {
    padding: "10px 0",
    borderRadius: RADIUS.sm,
    border: "none",
    color: "#fff",
    fontSize: 13,
    fontWeight: 900,
    cursor: "pointer",
    width: "100%",
    transition: "opacity 0.15s",
  },
  empty: {
    textAlign: "center",
    padding: "60px 20px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  sheetWrap: {
    position: "fixed",
    inset: 0,
    zIndex: 200,
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "center",
  },
  sheetOverlay: {
    position: "absolute",
    inset: 0,
    background: blackAlpha(0.65),
    backdropFilter: "blur(8px)",
  },
  sheet: {
    position: "relative",
    width: "100%",
    maxWidth: 480,
    background: "rgba(14,14,16,0.98)",
    backdropFilter: "blur(24px)",
    WebkitBackdropFilter: "blur(24px)",
    border: `1px solid ${whiteAlpha(0.09)}`,
    borderRadius: "24px 24px 0 0",
    padding: "20px 20px calc(32px + env(safe-area-inset-bottom))",
  },
  sheetHandle: {
    width: 40,
    height: 4,
    borderRadius: RADIUS.full,
    background: whiteAlpha(0.18),
    margin: "0 auto 16px",
  },
  sheetKicker: {
    margin: 0,
    fontSize: 10,
    fontWeight: 900,
    letterSpacing: 2,
    textTransform: "uppercase",
    color: RED,
  },
  sheetTitle: {
    margin: "3px 0 0",
    fontSize: 16,
    fontWeight: 900,
    color: "#fff",
  },
  closeSheetBtn: {
    background: whiteAlpha(0.07),
    border: `1px solid ${whiteAlpha(0.1)}`,
    color: "#fff",
    width: 32,
    height: 32,
    borderRadius: 8,
    cursor: "pointer",
    fontSize: 14,
    flexShrink: 0,
  },
  sessionRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "12px 14px",
    borderRadius: 12,
    border: "1px solid",
    transition: "background 0.15s, border-color 0.15s",
  },
  completeDayBtn: {
    width: "100%",
    padding: "14px 0",
    borderRadius: RADIUS.md,
    border: "none",
    color: "#fff",
    fontSize: 15,
    fontWeight: 900,
    cursor: "pointer",
    transition: "background 0.3s",
  },
};

export default s;
