import { goldAlpha, GOLD } from "@/lib/tokens";

const s = {
  aiBuilderBanner: { width: "100%", boxSizing: "border-box", display: "flex", alignItems: "center", gap: 14, padding: "14px 16px", borderRadius: "3px 14px 14px 3px", background: "linear-gradient(145deg, #111012, #0a0a0a)", border: `1px solid ${goldAlpha(0.18)}`, borderLeft: "2.5px solid #D4AF37", cursor: "pointer", marginBottom: 20, textAlign: "left" },
  page: {
    minHeight: "100dvh",
    background: "#050505",
    color: "#fff",
    display: "flex",
    flexDirection: "column",
    paddingBottom: "calc(88px + env(safe-area-inset-bottom))",
  },
  header: {
    display: "flex",
    alignItems: "center",
    gap: 14,
    padding: "calc(16px + env(safe-area-inset-top)) 16px 16px",
    borderBottom: "1px solid rgba(255,255,255,0.08)",
    position: "sticky",
    top: 0,
    background: "rgba(5,5,5,0.96)",
    backdropFilter: "blur(16px)",
    zIndex: 10,
  },
  backBtn: {
    width: 40,
    height: 40,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    background: "rgba(255,255,255,0.055)",
    border: "1px solid rgba(255,255,255,0.12)",
    color: "#fff",
    borderRadius: 10,
    cursor: "pointer",
    padding: 0,
    flexShrink: 0,
  },
  kicker: {
    margin: 0,
    fontSize: 9,
    fontWeight: 900,
    letterSpacing: 2,
    textTransform: "uppercase",
    color: GOLD,
  },
  title: {
    margin: "2px 0 0",
    fontSize: 20,
    fontWeight: 900,
  },
  content: {
    flex: 1,
    padding: "16px",
    display: "flex",
    flexDirection: "column",
    gap: 24,
    overflowY: "auto",
  },
  section: {
    display: "flex",
    flexDirection: "column",
    gap: 10,
  },
  sectionTitle: {
    margin: 0,
    fontSize: 11,
    fontWeight: 900,
    letterSpacing: 1.5,
    textTransform: "uppercase",
    color: "#888",
    paddingBottom: 2,
  },
  enrolledCard: {
    background: "linear-gradient(145deg, #111012, #0a0a0a)",
    border: "1px solid rgba(255,255,255,0.07)",
    borderRadius: "3px 14px 14px 3px",
    padding: "14px 16px",
    display: "flex",
    flexDirection: "column",
    gap: 0,
  },
  enrolledTitle: {
    margin: "6px 0 0",
    fontSize: 15,
    fontWeight: 900,
    color: "#fff",
  },
  streakBadge: {
    display: "inline-flex",
    alignSelf: "flex-start",
    marginTop: 7,
    padding: "3px 10px",
    borderRadius: 999,
    background: "rgba(251,146,60,0.12)",
    border: "1px solid rgba(251,146,60,0.28)",
    color: "#FB923C",
    fontSize: 11,
    fontWeight: 800,
  },
  continueBtn: {
    flex: 1,
    padding: "10px 16px",
    borderRadius: 10,
    border: "none",
    fontSize: 13,
    fontWeight: 900,
    color: "#fff",
    transition: "opacity 0.15s",
  },
  unenrollBtn: {
    padding: "10px 14px",
    borderRadius: 10,
    border: "1px solid rgba(255,255,255,0.1)",
    background: "rgba(255,255,255,0.04)",
    color: "rgba(255,255,255,0.4)",
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
  },
  discoverCard: {
    background: "linear-gradient(145deg, #111012, #0a0a0a)",
    border: "1px solid rgba(255,255,255,0.07)",
    borderRadius: "3px 14px 14px 3px",
    padding: "14px 16px",
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },
  programEmoji: {
    width: 44,
    height: 44,
    borderRadius: 12,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 22,
    flexShrink: 0,
  },
  metaChip: {
    fontSize: 10,
    fontWeight: 700,
    color: "#888",
    background: "rgba(255,255,255,0.05)",
    border: "1px solid rgba(255,255,255,0.1)",
    borderRadius: 999,
    padding: "2px 8px",
  },
  enrollBtn: {
    padding: "10px 0",
    borderRadius: 10,
    border: "none",
    color: "#fff",
    fontSize: 13,
    fontWeight: 900,
    cursor: "pointer",
    width: "100%",
    transition: "opacity 0.15s",
  },
  empty: {
    textAlign: "center",
    padding: "60px 20px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  sheetWrap: {
    position: "fixed",
    inset: 0,
    zIndex: 200,
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "center",
  },
  sheetOverlay: {
    position: "absolute",
    inset: 0,
    background: "rgba(0,0,0,0.62)",
    backdropFilter: "blur(8px)",
  },
  sheet: {
    position: "relative",
    width: "100%",
    maxWidth: 480,
    background: "linear-gradient(180deg, #151111, #080808)",
    border: "1px solid rgba(255,255,255,0.1)",
    borderRadius: "24px 24px 0 0",
    padding: "20px 20px calc(32px + env(safe-area-inset-bottom))",
  },
  sheetHandle: {
    width: 40,
    height: 4,
    borderRadius: 999,
    background: "rgba(255,255,255,0.18)",
    margin: "0 auto 16px",
  },
  sheetKicker: {
    margin: 0,
    fontSize: 10,
    fontWeight: 900,
    letterSpacing: 1.5,
    textTransform: "uppercase",
    color: "#888",
  },
  sheetTitle: {
    margin: "3px 0 0",
    fontSize: 16,
    fontWeight: 900,
    color: "#fff",
  },
  closeSheetBtn: {
    background: "rgba(255,255,255,0.07)",
    border: "none",
    color: "#fff",
    width: 32,
    height: 32,
    borderRadius: 8,
    cursor: "pointer",
    fontSize: 14,
    flexShrink: 0,
  },
  sessionRow: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "12px 14px",
    borderRadius: 12,
    border: "1px solid",
    transition: "background 0.15s, border-color 0.15s",
  },
  completeDayBtn: {
    width: "100%",
    padding: "14px 0",
    borderRadius: 14,
    border: "none",
    color: "#fff",
    fontSize: 15,
    fontWeight: 900,
    cursor: "pointer",
    transition: "background 0.3s",
  },
};

export default s;
