import { GOLD, RED, redAlpha } from "@/lib/tokens";

export const discoverFeedStyles = {
  // ── Fighter Study subsection ──
  fighterStudySection: {
    marginBottom: 4,
  },
  fighterStudyHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  fighterStudyLabel: {
    fontSize: 12,
    fontWeight: 800,
    color: GOLD,
    letterSpacing: 0.5,
    textTransform: "uppercase",
  },
  fighterStudySeeAll: {
    background: "none",
    border: "none",
    color: "#888",
    fontSize: 11,
    cursor: "pointer",
    padding: 0,
  },
  fighterStudyScroll: {
    display: "flex",
    gap: 10,
    overflowX: "auto",
    paddingBottom: 4,
    scrollbarWidth: "none",
    msOverflowStyle: "none",
    WebkitOverflowScrolling: "touch",
  },
  learnDivider: {
    height: 1,
    background: "rgba(255,255,255,0.06)",
    margin: "14px 0",
  },

  // ── Feed Tabs ──
  feedTabs: {
    display: "flex",
    gap: 0,
    padding: "0 16px 10px",
    borderBottom: "1px solid rgba(255,255,255,0.06)",
    marginBottom: 2,
  },
  feedTabBtn: {
    flex: 1,
    padding: "10px 0",
    background: "none",
    border: "none",
    borderBottom: "2px solid transparent",
    color: "rgba(255,255,255,0.4)",
    fontSize: 13,
    fontWeight: 700,
    cursor: "pointer",
    WebkitTapHighlightColor: "transparent",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    transition: "color 150ms, border-color 150ms",
  },
  feedTabActive: {
    flex: 1,
    padding: "10px 0",
    background: "none",
    border: "none",
    borderBottom: "2px solid #C1121F",
    color: "#fff",
    fontSize: 13,
    fontWeight: 900,
    cursor: "pointer",
    WebkitTapHighlightColor: "transparent",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },

  // ── Following Feed ──
  skeleton: {
    height: 320,
    borderRadius: 16,
    background: "linear-gradient(90deg, rgba(255,255,255,0.04) 0%, rgba(255,255,255,0.07) 50%, rgba(255,255,255,0.04) 100%)",
    backgroundSize: "200% 100%",
    animation: "shimmer 1.4s ease infinite",
  },
  emptyWrap: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    textAlign: "center",
    padding: "52px 24px",
    gap: 10,
  },
  emptyTitle: {
    margin: 0,
    fontSize: 17,
    fontWeight: 900,
    color: "#fff",
  },
  emptyText: {
    margin: 0,
    fontSize: 13,
    color: "#666",
    lineHeight: 1.5,
    maxWidth: 260,
  },
  emptyBtn: {
    marginTop: 8,
    padding: "11px 22px",
    borderRadius: 12,
    border: "none",
    background: RED,
    color: "#fff",
    fontSize: 14,
    fontWeight: 900,
    cursor: "pointer",
  },
  card: {
    background: "linear-gradient(145deg, #111012, #0a0a0a)",
    border: "1px solid rgba(255,255,255,0.06)",
    borderLeft: "2.5px solid #C1121F",
    borderRadius: "3px 16px 16px 3px",
    overflow: "hidden",
  },
  cardHeader: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "12px 14px 10px",
  },
  avatar: {
    width: 38,
    height: 38,
    borderRadius: "50%",
    background: `${redAlpha(0.2)}`,
    border: `1.5px solid ${redAlpha(0.4)}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    flexShrink: 0,
    cursor: "pointer",
  },
  avatarImg: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  avatarInitial: {
    fontSize: 15,
    fontWeight: 900,
    color: "#fff",
  },
  authorName: {
    margin: 0,
    fontSize: 14,
    fontWeight: 800,
    color: "#fff",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  timeAgo: {
    margin: 0,
    fontSize: 11,
    color: "#555",
    fontWeight: 600,
  },
  typeBadge: {
    fontSize: 18,
    lineHeight: 1,
    flexShrink: 0,
  },
  thumb: {
    position: "relative",
    width: "100%",
    aspectRatio: "16/9",
    background: "#0d0d0d",
    overflow: "hidden",
    cursor: "pointer",
  },
  thumbMedia: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    display: "block",
  },
  thumbGrad: {
    position: "absolute",
    inset: 0,
    background: "linear-gradient(0deg, rgba(0,0,0,0.65) 0%, transparent 50%)",
    pointerEvents: "none",
  },
  thumbCaption: {
    position: "absolute",
    bottom: 10,
    left: 12,
    right: 12,
    margin: 0,
    fontSize: 12,
    fontWeight: 800,
    color: "#fff",
    textShadow: "0 1px 4px rgba(0,0,0,0.9)",
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
  },
  cardFooter: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "10px 14px 12px",
  },
  likes: {
    fontSize: 13,
    color: "rgba(255,255,255,0.5)",
    fontWeight: 600,
  },
  watchBtn: {
    padding: "7px 14px",
    borderRadius: 10,
    border: "none",
    background: RED,
    color: "#fff",
    fontSize: 12,
    fontWeight: 900,
    cursor: "pointer",
  },
};
