import { GOLD, RED, MUTED, redAlpha, goldAlpha } from "@/lib/tokens";

export const discoverFeedStyles = {
  fighterStudySection: { marginBottom: 4 },
  fighterStudyHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 10,
  },
  fighterStudyLabel: {
    fontSize: 10,
    fontWeight: 900,
    color: GOLD,
    letterSpacing: 2.5,
    textTransform: "uppercase",
  },
  fighterStudySeeAll: {
    background: "none",
    border: "none",
    color: MUTED,
    fontSize: 11,
    cursor: "pointer",
    padding: 0,
    fontWeight: 700,
  },
  fighterStudyScroll: {
    display: "flex",
    gap: 10,
    overflowX: "auto",
    paddingBottom: 4,
    scrollbarWidth: "none",
    msOverflowStyle: "none",
    WebkitOverflowScrolling: "touch",
  },
  learnDivider: {
    height: 1,
    background: "rgba(255,255,255,0.06)",
    margin: "14px 0",
  },

  feedTabs: {
    display: "flex",
    gap: 0,
    padding: "0 16px 0",
    borderBottom: "1px solid rgba(255,255,255,0.07)",
    marginBottom: 2,
  },
  feedTabBtn: {
    flex: 1,
    padding: "12px 0",
    background: "none",
    border: "none",
    borderBottom: "2px solid transparent",
    color: "rgba(255,255,255,0.38)",
    fontSize: 13,
    fontWeight: 700,
    cursor: "pointer",
    WebkitTapHighlightColor: "transparent",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    transition: "color 150ms, border-color 150ms",
  },
  feedTabActive: {
    flex: 1,
    padding: "12px 0",
    background: "none",
    border: "none",
    borderBottom: `2px solid ${RED}`,
    color: "#fff",
    fontSize: 13,
    fontWeight: 900,
    cursor: "pointer",
    WebkitTapHighlightColor: "transparent",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },

  skeleton: {
    height: 320,
    borderRadius: 18,
    background: "rgba(255,255,255,0.04)",
  },
  emptyWrap: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    textAlign: "center",
    padding: "52px 24px",
    gap: 10,
  },
  emptyTitle: { margin: 0, fontSize: 17, fontWeight: 900, color: "#fff" },
  emptyText: { margin: 0, fontSize: 13, color: MUTED, lineHeight: 1.5, maxWidth: 260 },
  emptyBtn: {
    marginTop: 8,
    padding: "11px 22px",
    borderRadius: 12,
    border: "none",
    background: `linear-gradient(145deg, ${RED}, #cc2820)`,
    color: "#fff",
    fontSize: 14,
    fontWeight: 800,
    cursor: "pointer",
    boxShadow: `0 8px 24px ${redAlpha(0.32)}, inset 0 1px 0 rgba(255,255,255,0.1)`,
  },

  card: {
    background: "rgba(255,255,255,0.03)",
    border: "1px solid rgba(255,255,255,0.07)",
    borderLeft: `2.5px solid ${RED}`,
    borderRadius: "4px 18px 18px 4px",
    overflow: "hidden",
    backdropFilter: "blur(16px)",
    WebkitBackdropFilter: "blur(16px)",
  },
  cardHeader: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "13px 14px 10px",
  },
  avatar: {
    width: 38,
    height: 38,
    borderRadius: "50%",
    background: redAlpha(0.15),
    border: `1.5px solid ${redAlpha(0.32)}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    flexShrink: 0,
    cursor: "pointer",
  },
  avatarImg: { width: "100%", height: "100%", objectFit: "cover" },
  avatarInitial: { fontSize: 15, fontWeight: 900, color: "#fff" },
  authorName: {
    margin: 0,
    fontSize: 14,
    fontWeight: 800,
    color: "#fff",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  timeAgo: { margin: 0, fontSize: 11, color: MUTED, fontWeight: 600 },
  typeBadge: { fontSize: 18, lineHeight: 1, flexShrink: 0 },
  thumb: {
    position: "relative",
    width: "100%",
    aspectRatio: "16/9",
    background: "#0d0d0d",
    overflow: "hidden",
    cursor: "pointer",
  },
  thumbMedia: { width: "100%", height: "100%", objectFit: "cover", display: "block" },
  thumbGrad: {
    position: "absolute",
    inset: 0,
    background: "linear-gradient(0deg, rgba(0,0,0,0.7) 0%, transparent 55%)",
    pointerEvents: "none",
  },
  thumbCaption: {
    position: "absolute",
    bottom: 10,
    left: 12,
    right: 12,
    margin: 0,
    fontSize: 12,
    fontWeight: 800,
    color: "#fff",
    textShadow: "0 1px 4px rgba(0,0,0,0.9)",
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
  },
  cardFooter: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "10px 14px 12px",
  },
  likes: { fontSize: 13, color: "rgba(255,255,255,0.5)", fontWeight: 600 },
  watchBtn: {
    padding: "7px 16px",
    borderRadius: 10,
    border: "none",
    background: `linear-gradient(135deg, ${RED}, #cc2820)`,
    color: "#fff",
    fontSize: 12,
    fontWeight: 800,
    cursor: "pointer",
    boxShadow: `0 4px 14px ${redAlpha(0.28)}`,
  },
};
