import { GOLD, BORDER, RADIUS, redAlpha, whiteAlpha, blackAlpha } from "@/lib/tokens";

export const discoverSearchStyles = {
  // ── Top coaches ──
  coachStrip: {
    padding: "20px 16px 8px",
  },
  coachStripHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  coachStripLabel: {
    fontSize: 14,
    fontWeight: 900,
    color: "#fff",
  },
  coachScroll: {
    display: "flex",
    gap: 14,
    overflowX: "auto",
    scrollbarWidth: "none",
    paddingBottom: 4,
  },
  coachCard: {
    flexShrink: 0,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 5,
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: 0,
    WebkitTapHighlightColor: "transparent",
    width: 64,
  },
  coachAvatar: {
    width: 52,
    height: 52,
    borderRadius: "50%",
    background: "rgba(96,165,250,0.12)",
    border: "2px solid rgba(96,165,250,0.28)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    fontSize: 18,
    fontWeight: 800,
    color: "#fff",
    boxShadow: `0 4px 16px ${blackAlpha(0.4)}`,
  },
  coachAvatarImg: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  coachName: {
    fontSize: 11,
    fontWeight: 800,
    color: "#fff",
    maxWidth: 64,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    textAlign: "center",
  },
  coachSpec: {
    fontSize: 9,
    fontWeight: 700,
    color: "#60A5FA",
    textAlign: "center",
    maxWidth: 64,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },

  // ── Search results ──
  sectionLabel: {
    margin: "0 0 10px",
    fontSize: 10,
    fontWeight: 900,
    letterSpacing: 2,
    textTransform: "uppercase",
    color: whiteAlpha(0.4),
  },
  listStack: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  listCard: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "11px 14px",
    borderRadius: RADIUS.md,
    border: `1px solid ${BORDER}`,
    background: whiteAlpha(0.035),
    cursor: "pointer",
    color: "#fff",
    textAlign: "left",
    width: "100%",
    boxSizing: "border-box",
    WebkitTapHighlightColor: "transparent",
    backdropFilter: "blur(12px)",
    WebkitBackdropFilter: "blur(12px)",
    transition: "background 150ms",
  },
  listAvatar: {
    width: 40,
    height: 40,
    borderRadius: "50%",
    background: whiteAlpha(0.08),
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 16,
    fontWeight: 800,
    flexShrink: 0,
    overflow: "hidden",
    border: `1px solid ${whiteAlpha(0.1)}`,
  },
  listAvatarImg: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  listCardText: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: 2,
    minWidth: 0,
  },
  listCardName: {
    fontSize: 14,
    fontWeight: 800,
    color: "#fff",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  listCardSub: {
    fontSize: 12,
    color: whiteAlpha(0.4),
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  listArrow: {
    color: whiteAlpha(0.25),
    fontSize: 18,
    flexShrink: 0,
  },
  emptyState: {
    textAlign: "center",
    padding: "48px 20px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
};
