export const discoverReelStyles = {
  // ── Reel scroll ──
  reelScroll: {
    display: "flex",
    gap: 10,
    overflowX: "auto",
    paddingBottom: 6,
    scrollbarWidth: "none",
    WebkitOverflowScrolling: "touch",
  },

  // ── Portrait reel card ──
  reelCard: {
    flexShrink: 0,
    width: 122,
    height: 210,
    borderRadius: 16,
    overflow: "hidden",
    cursor: "pointer",
    background: "none",
    border: "1px solid rgba(255,255,255,0.08)",
    padding: 0,
    display: "block",
    position: "relative",
    WebkitTapHighlightColor: "transparent",
    boxShadow: "0 8px 28px rgba(0,0,0,0.55)",
    transition: "transform 180ms ease, box-shadow 180ms ease",
  },
  reelThumbWrap: {
    width: "100%",
    height: "100%",
    position: "relative",
    background: "linear-gradient(160deg, #1a0808 0%, #0d0d0d 100%)",
    borderRadius: 16,
    overflow: "hidden",
  },
  reelThumbImg: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    display: "block",
    borderRadius: 16,
  },
  reelThumbFallback: {
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    padding: "8px 8px 24px",
    boxSizing: "border-box",
  },
  reelFallbackCaption: {
    margin: 0,
    fontSize: 9,
    color: "rgba(255,255,255,0.55)",
    lineHeight: 1.3,
    textAlign: "center",
    display: "-webkit-box",
    WebkitLineClamp: 3,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
  },
  reelGradTop: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 70,
    background: "linear-gradient(180deg, rgba(0,0,0,0.6) 0%, transparent 100%)",
    pointerEvents: "none",
  },
  reelGradBottom: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 100,
    background: "linear-gradient(0deg, rgba(0,0,0,0.9) 0%, rgba(0,0,0,0.45) 55%, transparent 100%)",
    pointerEvents: "none",
  },
  reelTypeBadge: {
    position: "absolute",
    top: 8,
    left: 9,
    fontSize: 13,
    lineHeight: 1,
    filter: "drop-shadow(0 1px 3px rgba(0,0,0,0.9))",
    zIndex: 2,
  },
  reelViews: {
    position: "absolute",
    top: 9,
    right: 9,
    fontSize: 9,
    fontWeight: 900,
    color: "rgba(255,255,255,0.75)",
    letterSpacing: 0.3,
    zIndex: 2,
    textShadow: "0 1px 4px rgba(0,0,0,0.8)",
  },
  reelCaptionOverlay: {
    position: "absolute",
    bottom: 9,
    left: 9,
    right: 9,
    margin: 0,
    fontSize: 10,
    fontWeight: 800,
    color: "#fff",
    lineHeight: 1.3,
    letterSpacing: 0.1,
    textShadow: "0 1px 6px rgba(0,0,0,0.95)",
    overflow: "hidden",
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    zIndex: 2,
  },
  shimmerCard: {
    flexShrink: 0,
    width: 122,
    height: 210,
    borderRadius: 16,
  },
};
