import { redAlpha } from "@/lib/tokens";

export const discoverPageStyles = {
  page: {
    minHeight: "100vh",
    background: `radial-gradient(ellipse at top center, ${redAlpha(0.07)} 0%, transparent 55%), #080808`,
    color: "#fff",
    paddingBottom: "calc(88px + env(safe-area-inset-bottom))",
  },
  header: {
    padding: "calc(28px + env(safe-area-inset-top)) 20px 14px",
    position: "relative",
  },
  kicker: {
    margin: "0 0 6px",
    color: `${redAlpha(0.9)}`,
    fontSize: 9,
    fontWeight: 900,
    letterSpacing: 3.5,
    textTransform: "uppercase",
  },
  title: {
    margin: "0 0 4px",
    fontSize: "clamp(30px, 9vw, 42px)",
    fontWeight: 900,
    letterSpacing: -0.8,
    lineHeight: 1.0,
    fontFamily: "var(--font-display, 'Anton', sans-serif)",
  },
  subtitle: {
    margin: 0,
    fontSize: 13,
    color: "rgba(255,255,255,0.3)",
    fontWeight: 400,
    lineHeight: 1.5,
  },

  // ── Search ──
  searchRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "0 16px 14px",
    position: "sticky",
    top: 0,
    zIndex: 50,
    background: "rgba(8,8,8,0.95)",
    backdropFilter: "blur(20px)",
    WebkitBackdropFilter: "blur(20px)",
  },
  searchWrap: {
    flex: 1,
    position: "relative",
    display: "flex",
    alignItems: "center",
  },
  searchIconSvg: {
    position: "absolute",
    left: 13,
    width: 16,
    height: 16,
    fill: "none",
    stroke: "#555",
    strokeWidth: 2,
    strokeLinecap: "round",
    pointerEvents: "none",
  },
  searchInput: {
    width: "100%",
    height: 44,
    borderRadius: 999,
    border: "1px solid rgba(255,255,255,0.1)",
    background: "rgba(255,255,255,0.06)",
    color: "#fff",
    padding: "0 34px 0 38px",
    fontSize: 14,
    outline: "none",
    boxSizing: "border-box",
  },
  clearBtn: {
    position: "absolute",
    right: 10,
    background: "none",
    border: "none",
    color: "#666",
    cursor: "pointer",
    padding: 4,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  searchBtn: {
    height: 44,
    boxSizing: "border-box",
    padding: "0 18px",
    borderRadius: 999,
    border: "none",
    background: "linear-gradient(135deg, #C1121F, #8f0d17)",
    color: "#fff",
    fontSize: 14,
    fontWeight: 800,
    cursor: "pointer",
    flexShrink: 0,
    opacity: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },

  // ── Main content ──
  content: {
    padding: "8px 0 0",
  },
};
