export const discoverPageStyles = {
  page: {
    minHeight: "100dvh",
    background: "#0B0B0C",
    color: "#fff",
    paddingBottom: "calc(88px + env(safe-area-inset-bottom))",
  },

  // ── Search ──
  searchRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "12px 16px",
    position: "sticky",
    top: 56,
    zIndex: 40,
    background: "rgba(11,11,12,0.95)",
    backdropFilter: "blur(24px)",
    WebkitBackdropFilter: "blur(24px)",
    borderBottom: "1px solid rgba(255,255,255,0.05)",
  },
  searchWrap: {
    flex: 1,
    position: "relative",
    display: "flex",
    alignItems: "center",
  },
  searchIconSvg: {
    position: "absolute",
    left: 13,
    width: 15,
    height: 15,
    fill: "none",
    stroke: "#4B5563",
    strokeWidth: 2,
    strokeLinecap: "round",
    pointerEvents: "none",
  },
  searchInput: {
    width: "100%",
    height: 40,
    borderRadius: 10,
    border: "1px solid rgba(255,255,255,0.08)",
    background: "#1C1C1E",
    color: "#fff",
    padding: "0 34px 0 38px",
    fontSize: 13,
    outline: "none",
    boxSizing: "border-box",
  },
  clearBtn: {
    position: "absolute",
    right: 10,
    background: "none",
    border: "none",
    color: "#4B5563",
    cursor: "pointer",
    padding: 4,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  searchBtn: {
    height: 40,
    boxSizing: "border-box",
    padding: "0 16px",
    borderRadius: 10,
    border: "none",
    background: "#FF3B30",
    color: "#fff",
    fontSize: 13,
    fontWeight: 600,
    cursor: "pointer",
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },

  // ── Main content ──
  content: {
    padding: "8px 0 0",
  },
};
