import { GOLD, RED, BORDER, MUTED, SURFACE, redAlpha, goldAlpha } from "@/lib/tokens";

export const discoverHubStyles = {
  hubSection: { marginBottom: 32, padding: "0 16px" },
  forYouHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
    paddingTop: 8,
    borderTop: `1px solid ${BORDER}`,
  },
  forYouTitle: { fontSize: 16, fontWeight: 900, color: "#fff", letterSpacing: 0.2 },
  seeAllBtn: {
    background: "none",
    border: "none",
    color: GOLD,
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
    padding: 0,
  },

  styleChips: {
    display: "flex",
    gap: 6,
    overflowX: "auto",
    paddingBottom: 12,
    scrollbarWidth: "none",
  },
  styleChip: {
    flexShrink: 0,
    padding: "7px 13px",
    borderRadius: 999,
    border: `1px solid ${BORDER}`,
    background: "rgba(255,255,255,0.04)",
    color: MUTED,
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
    whiteSpace: "nowrap",
    WebkitTapHighlightColor: "transparent",
    display: "flex",
    alignItems: "center",
    gap: 5,
  },
  styleChipActive: {
    background: redAlpha(0.85),
    borderColor: redAlpha(0.6),
    color: "#fff",
    fontWeight: 900,
  },

  hubWrap: { marginBottom: 4 },
  hubRow: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "16px 20px",
    borderRadius: 0,
    border: "none",
    borderTop: `1px solid ${BORDER}`,
    background: "none",
    cursor: "pointer",
    WebkitTapHighlightColor: "transparent",
    boxSizing: "border-box",
    transition: "background 180ms",
  },
  hubLeft: { display: "flex", alignItems: "center", gap: 12 },
  hubEmoji: {
    width: 34,
    height: 34,
    borderRadius: 9,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 17,
    flexShrink: 0,
  },
  hubTitle: { fontSize: 15, fontWeight: 900, color: "#fff", letterSpacing: 0.1 },
  hubChevron: {
    width: 18,
    height: 18,
    fill: "none",
    stroke: "rgba(255,255,255,0.3)",
    strokeWidth: 2.2,
    strokeLinecap: "round",
    strokeLinejoin: "round",
    transition: "transform 200ms ease",
    flexShrink: 0,
  },
  hubBody: { padding: "4px 16px 20px", display: "flex", flexDirection: "column", gap: 12 },

  learnChips: {
    display: "flex",
    gap: 6,
    overflowX: "auto",
    scrollbarWidth: "none",
    paddingBottom: 4,
  },
  learnChip: {
    flexShrink: 0,
    padding: "6px 12px",
    borderRadius: 999,
    border: `1px solid ${goldAlpha(0.18)}`,
    background: goldAlpha(0.04),
    color: "rgba(255,255,255,0.5)",
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
    whiteSpace: "nowrap",
    display: "flex",
    alignItems: "center",
    gap: 4,
    WebkitTapHighlightColor: "transparent",
  },
  learnChipActive: {
    background: goldAlpha(0.18),
    borderColor: goldAlpha(0.55),
    color: GOLD,
    fontWeight: 900,
  },
  hubEmpty: { padding: "20px 0", textAlign: "center" },
  hubEmptyText: { margin: 0, fontSize: 13, color: MUTED },
  hubFooterBtn: {
    background: "none",
    border: `1px solid ${BORDER}`,
    borderRadius: 12,
    padding: "11px 16px",
    color: GOLD,
    fontSize: 13,
    fontWeight: 700,
    cursor: "pointer",
    width: "100%",
    textAlign: "center",
  },

  challengeGrid: { display: "grid", gridTemplateColumns: "repeat(2, 1fr)", gap: 8 },
  challengeChip: {
    padding: "12px 8px",
    borderRadius: 12,
    border: `1px solid ${redAlpha(0.2)}`,
    background: redAlpha(0.06),
    color: "rgba(255,255,255,0.7)",
    fontSize: 13,
    fontWeight: 800,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    WebkitTapHighlightColor: "transparent",
  },

  exploreSection: { padding: "20px 16px 8px" },
  exploreSectionLabel: {
    margin: "0 0 10px",
    fontSize: 10,
    fontWeight: 900,
    letterSpacing: 2,
    textTransform: "uppercase",
    color: MUTED,
  },
  explorePills: { display: "flex", gap: 8, flexWrap: "wrap" },
  explorePill: {
    padding: "9px 14px",
    borderRadius: 999,
    border: `1px solid ${BORDER}`,
    background: "rgba(255,255,255,0.04)",
    color: "rgba(255,255,255,0.6)",
    fontSize: 13,
    fontWeight: 700,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: 6,
    WebkitTapHighlightColor: "transparent",
  },
};
