import { GOLD, RED, BORDER, MUTED, redAlpha, goldAlpha } from "@/lib/tokens";

export const discoverHubStyles = {
  hubSection: { marginBottom: 28, padding: "0 16px" },
  forYouHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
    paddingTop: 10,
  },
  forYouKicker: {
    margin: "0 0 2px",
    color: RED,
    fontSize: 10,
    fontWeight: 900,
    letterSpacing: 3,
    textTransform: "uppercase",
  },
  forYouTitle: {
    fontSize: 18,
    fontWeight: 1000,
    color: "#fff",
    letterSpacing: "-0.01em",
    fontFamily: "var(--font-display, 'Anton', sans-serif)",
    textTransform: "uppercase",
  },
  seeAllBtn: {
    background: "none",
    border: "none",
    color: GOLD,
    fontSize: 12,
    fontWeight: 800,
    cursor: "pointer",
    padding: "4px 0",
    letterSpacing: 0.3,
  },

  styleChips: {
    display: "flex",
    gap: 6,
    overflowX: "auto",
    paddingBottom: 12,
    scrollbarWidth: "none",
  },
  styleChip: {
    flexShrink: 0,
    padding: "7px 13px",
    borderRadius: 999,
    border: "1px solid rgba(255,255,255,0.09)",
    background: "rgba(255,255,255,0.04)",
    color: "rgba(255,255,255,0.5)",
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
    whiteSpace: "nowrap",
    WebkitTapHighlightColor: "transparent",
    display: "flex",
    alignItems: "center",
    gap: 5,
    transition: "border-color 150ms, background 150ms",
  },
  styleChipActive: {
    background: redAlpha(0.18),
    borderColor: redAlpha(0.6),
    color: "#fff",
    fontWeight: 900,
    boxShadow: `0 0 16px ${redAlpha(0.2)}`,
  },

  // ── Hub cards ──
  hubWrap: {
    margin: "0 16px 8px",
    borderRadius: 20,
    border: "1px solid rgba(255,255,255,0.07)",
    background: "rgba(255,255,255,0.025)",
    backdropFilter: "blur(16px)",
    WebkitBackdropFilter: "blur(16px)",
    overflow: "hidden",
  },
  hubRow: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "16px 18px",
    borderRadius: 0,
    border: "none",
    background: "none",
    cursor: "pointer",
    WebkitTapHighlightColor: "transparent",
    boxSizing: "border-box",
    transition: "background 180ms",
  },
  hubLeft: { display: "flex", alignItems: "center", gap: 12 },
  hubEmoji: {
    width: 36,
    height: 36,
    borderRadius: 10,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 18,
    flexShrink: 0,
  },
  hubTitle: {
    fontSize: 15,
    fontWeight: 900,
    color: "#fff",
    letterSpacing: 0.1,
  },
  hubChevron: {
    width: 18,
    height: 18,
    fill: "none",
    stroke: "rgba(255,255,255,0.3)",
    strokeWidth: 2.2,
    strokeLinecap: "round",
    strokeLinejoin: "round",
    transition: "transform 200ms ease",
    flexShrink: 0,
  },
  hubBody: {
    padding: "4px 16px 18px",
    display: "flex",
    flexDirection: "column",
    gap: 12,
    borderTop: "1px solid rgba(255,255,255,0.06)",
  },

  learnChips: {
    display: "flex",
    gap: 6,
    overflowX: "auto",
    scrollbarWidth: "none",
    paddingBottom: 4,
    paddingTop: 2,
  },
  learnChip: {
    flexShrink: 0,
    padding: "6px 12px",
    borderRadius: 999,
    border: `1px solid ${goldAlpha(0.18)}`,
    background: goldAlpha(0.04),
    color: "rgba(255,255,255,0.5)",
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
    whiteSpace: "nowrap",
    display: "flex",
    alignItems: "center",
    gap: 4,
    WebkitTapHighlightColor: "transparent",
    transition: "border-color 150ms, background 150ms",
  },
  learnChipActive: {
    background: goldAlpha(0.15),
    borderColor: goldAlpha(0.55),
    color: GOLD,
    fontWeight: 900,
    boxShadow: `0 0 14px ${goldAlpha(0.18)}`,
  },
  hubEmpty: { padding: "20px 0", textAlign: "center" },
  hubEmptyText: { margin: 0, fontSize: 13, color: MUTED },
  hubFooterBtn: {
    background: "rgba(255,255,255,0.04)",
    border: "1px solid rgba(255,255,255,0.09)",
    borderRadius: 14,
    padding: "11px 16px",
    color: GOLD,
    fontSize: 13,
    fontWeight: 800,
    cursor: "pointer",
    width: "100%",
    textAlign: "center",
    transition: "background 150ms",
  },

  challengeGrid: { display: "grid", gridTemplateColumns: "repeat(2, 1fr)", gap: 8 },
  challengeChip: {
    padding: "13px 8px",
    borderRadius: 14,
    border: `1px solid ${redAlpha(0.25)}`,
    background: redAlpha(0.07),
    color: "rgba(255,255,255,0.75)",
    fontSize: 13,
    fontWeight: 800,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    WebkitTapHighlightColor: "transparent",
    transition: "background 150ms",
  },

  exploreSection: { padding: "20px 16px 8px" },
  exploreSectionLabel: {
    margin: "0 0 10px",
    fontSize: 10,
    fontWeight: 900,
    letterSpacing: 2,
    textTransform: "uppercase",
    color: MUTED,
  },
  explorePills: { display: "flex", gap: 8, flexWrap: "wrap" },
  explorePill: {
    padding: "10px 16px",
    borderRadius: 999,
    border: "1px solid rgba(255,255,255,0.09)",
    background: "rgba(255,255,255,0.04)",
    color: "rgba(255,255,255,0.65)",
    fontSize: 13,
    fontWeight: 700,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: 6,
    WebkitTapHighlightColor: "transparent",
    transition: "background 150ms",
  },
};
