import { GOLD, redAlpha, goldAlpha } from "@/lib/tokens";

export const discoverCardStyles = {
  // ── Hub Section (For You) ──
  hubSection: {
    marginBottom: 32,
    padding: "0 16px",
  },
  forYouHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 14,
    paddingTop: 8,
    borderTop: "1px solid rgba(255,255,255,0.06)",
  },
  forYouTitle: {
    fontSize: 16,
    fontWeight: 900,
    color: "#fff",
    letterSpacing: 0.2,
  },
  seeAllBtn: {
    background: "none",
    border: "none",
    color: GOLD,
    fontSize: 12,
    fontWeight: 800,
    cursor: "pointer",
    padding: 0,
  },

  // ── Fighter style chips ──
  styleChips: {
    display: "flex",
    gap: 6,
    overflowX: "auto",
    paddingBottom: 12,
    scrollbarWidth: "none",
  },
  styleChip: {
    flexShrink: 0,
    padding: "7px 13px",
    borderRadius: 999,
    border: "1px solid rgba(255,255,255,0.1)",
    background: "rgba(255,255,255,0.04)",
    color: "#888",
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
    whiteSpace: "nowrap",
    WebkitTapHighlightColor: "transparent",
    display: "flex",
    alignItems: "center",
    gap: 5,
  },
  styleChipActive: {
    background: `${redAlpha(0.85)}`,
    borderColor: `${redAlpha(0.6)}`,
    color: "#fff",
    fontWeight: 900,
  },

  // ── Reel scroll ──
  reelScroll: {
    display: "flex",
    gap: 8,
    overflowX: "auto",
    paddingBottom: 4,
    scrollbarWidth: "none",
    WebkitOverflowScrolling: "touch",
  },

  // ── Portrait reel card ──
  reelCard: {
    flexShrink: 0,
    width: 120,
    height: 200,
    borderRadius: 14,
    overflow: "hidden",
    cursor: "pointer",
    background: "none",
    border: "none",
    padding: 0,
    display: "block",
    position: "relative",
    WebkitTapHighlightColor: "transparent",
  },
  reelThumbWrap: {
    width: "100%",
    height: "100%",
    position: "relative",
    background: "linear-gradient(135deg, #1a0a0a 0%, #0d0d0d 100%)",
    borderRadius: 14,
    overflow: "hidden",
  },
  reelThumbImg: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    display: "block",
    borderRadius: 14,
  },
  reelThumbFallback: {
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    padding: "8px 8px 24px",
    boxSizing: "border-box",
  },
  reelFallbackCaption: {
    margin: 0,
    fontSize: 9,
    color: "rgba(255,255,255,0.55)",
    lineHeight: 1.3,
    textAlign: "center",
    display: "-webkit-box",
    WebkitLineClamp: 3,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
  },
  reelGradTop: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 60,
    background: "linear-gradient(180deg, rgba(0,0,0,0.55) 0%, transparent 100%)",
    pointerEvents: "none",
  },
  reelGradBottom: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 90,
    background: "linear-gradient(0deg, rgba(0,0,0,0.88) 0%, rgba(0,0,0,0.4) 50%, transparent 100%)",
    pointerEvents: "none",
  },
  reelTypeBadge: {
    position: "absolute",
    top: 7,
    left: 8,
    fontSize: 13,
    lineHeight: 1,
    filter: "drop-shadow(0 1px 3px rgba(0,0,0,0.9))",
    zIndex: 2,
  },
  reelViews: {
    position: "absolute",
    top: 8,
    right: 8,
    fontSize: 9,
    fontWeight: 900,
    color: "rgba(255,255,255,0.7)",
    letterSpacing: 0.3,
    zIndex: 2,
  },
  reelCaptionOverlay: {
    position: "absolute",
    bottom: 8,
    left: 8,
    right: 8,
    margin: 0,
    fontSize: 10,
    fontWeight: 800,
    color: "#fff",
    lineHeight: 1.3,
    letterSpacing: 0.1,
    textShadow: "0 1px 4px rgba(0,0,0,0.9)",
    overflow: "hidden",
    display: "-webkit-box",
    WebkitLineClamp: 3,
    WebkitBoxOrient: "vertical",
    zIndex: 2,
  },
  shimmerCard: {
    flexShrink: 0,
    width: 120,
    height: 200,
    borderRadius: 14,
  },

  // ── Expandable hub ──
  hubWrap: {
    marginBottom: 4,
  },
  hubRow: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "16px 20px",
    borderRadius: 0,
    border: "none",
    borderTop: "1px solid rgba(255,255,255,0.06)",
    background: "none",
    cursor: "pointer",
    WebkitTapHighlightColor: "transparent",
    boxSizing: "border-box",
    transition: "background 180ms",
  },
  hubLeft: {
    display: "flex",
    alignItems: "center",
    gap: 12,
  },
  hubEmoji: {
    width: 34,
    height: 34,
    borderRadius: 9,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 17,
    flexShrink: 0,
  },
  hubTitle: {
    fontSize: 15,
    fontWeight: 900,
    color: "#fff",
    letterSpacing: 0.1,
  },
  hubChevron: {
    width: 18,
    height: 18,
    fill: "none",
    stroke: "rgba(255,255,255,0.3)",
    strokeWidth: 2.2,
    strokeLinecap: "round",
    strokeLinejoin: "round",
    transition: "transform 200ms ease",
    flexShrink: 0,
  },
  hubBody: {
    padding: "4px 16px 20px",
    display: "flex",
    flexDirection: "column",
    gap: 12,
  },

  // ── Learn sub-cats ──
  learnChips: {
    display: "flex",
    gap: 6,
    overflowX: "auto",
    scrollbarWidth: "none",
    paddingBottom: 4,
  },
  learnChip: {
    flexShrink: 0,
    padding: "6px 12px",
    borderRadius: 999,
    border: `1px solid ${goldAlpha(0.18)}`,
    background: `${goldAlpha(0.04)}`,
    color: "rgba(255,255,255,0.5)",
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
    whiteSpace: "nowrap",
    display: "flex",
    alignItems: "center",
    gap: 4,
    WebkitTapHighlightColor: "transparent",
  },
  learnChipActive: {
    background: `${goldAlpha(0.18)}`,
    borderColor: `${goldAlpha(0.55)}`,
    color: GOLD,
    fontWeight: 900,
  },
  hubEmpty: {
    padding: "20px 0",
    textAlign: "center",
  },
  hubEmptyText: {
    margin: 0,
    fontSize: 13,
    color: "#555",
  },
  hubFooterBtn: {
    background: "none",
    border: "1px solid rgba(255,255,255,0.1)",
    borderRadius: 12,
    padding: "11px 16px",
    color: GOLD,
    fontSize: 13,
    fontWeight: 800,
    cursor: "pointer",
    width: "100%",
    textAlign: "center",
  },

  // ── Challenge grid ──
  challengeGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(2, 1fr)",
    gap: 8,
  },
  challengeChip: {
    padding: "12px 8px",
    borderRadius: 12,
    border: `1px solid ${redAlpha(0.2)}`,
    background: `${redAlpha(0.06)}`,
    color: "rgba(255,255,255,0.7)",
    fontSize: 13,
    fontWeight: 800,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    WebkitTapHighlightColor: "transparent",
  },

  // ── Explore section ──
  exploreSection: {
    padding: "20px 16px 8px",
  },
  exploreSectionLabel: {
    margin: "0 0 10px",
    fontSize: 10,
    fontWeight: 900,
    letterSpacing: 2,
    textTransform: "uppercase",
    color: "#444",
  },
  explorePills: {
    display: "flex",
    gap: 8,
    flexWrap: "wrap",
  },
  explorePill: {
    padding: "9px 14px",
    borderRadius: 999,
    border: "1px solid rgba(255,255,255,0.12)",
    background: "rgba(255,255,255,0.04)",
    color: "rgba(255,255,255,0.6)",
    fontSize: 13,
    fontWeight: 700,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: 6,
    WebkitTapHighlightColor: "transparent",
  },

  // ── Top coaches ──
  coachStrip: {
    padding: "20px 16px 8px",
  },
  coachStripHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  coachStripLabel: {
    fontSize: 14,
    fontWeight: 900,
    color: "#fff",
  },
  coachScroll: {
    display: "flex",
    gap: 12,
    overflowX: "auto",
    scrollbarWidth: "none",
    paddingBottom: 4,
  },
  coachCard: {
    flexShrink: 0,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 5,
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: 0,
    WebkitTapHighlightColor: "transparent",
    width: 64,
  },
  coachAvatar: {
    width: 52,
    height: 52,
    borderRadius: "50%",
    background: "rgba(96,165,250,0.15)",
    border: "2px solid rgba(96,165,250,0.3)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    fontSize: 18,
    fontWeight: 800,
    color: "#fff",
  },
  coachAvatarImg: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  coachName: {
    fontSize: 11,
    fontWeight: 800,
    color: "#fff",
    maxWidth: 64,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    textAlign: "center",
  },
  coachSpec: {
    fontSize: 9,
    fontWeight: 700,
    color: "#60A5FA",
    textAlign: "center",
    maxWidth: 64,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },

  // ── Search results ──
  sectionLabel: {
    margin: "0 0 10px",
    fontSize: 11,
    fontWeight: 900,
    letterSpacing: 1.2,
    textTransform: "uppercase",
    color: "#666",
  },
  listStack: {
    display: "flex",
    flexDirection: "column",
    gap: 2,
  },
  listCard: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "11px 14px",
    borderRadius: 12,
    border: "none",
    background: "rgba(255,255,255,0.03)",
    cursor: "pointer",
    color: "#fff",
    textAlign: "left",
    width: "100%",
    boxSizing: "border-box",
    WebkitTapHighlightColor: "transparent",
  },
  listAvatar: {
    width: 40,
    height: 40,
    borderRadius: "50%",
    background: "rgba(255,255,255,0.08)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 16,
    fontWeight: 800,
    flexShrink: 0,
    overflow: "hidden",
  },
  listAvatarImg: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  listCardText: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: 2,
    minWidth: 0,
  },
  listCardName: {
    fontSize: 14,
    fontWeight: 800,
    color: "#fff",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  listCardSub: {
    fontSize: 12,
    color: "#666",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  listArrow: {
    color: "#444",
    fontSize: 18,
    flexShrink: 0,
  },
  emptyState: {
    textAlign: "center",
    padding: "48px 20px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
};
