import { BG, RED, RED_DARK, GOLD, BORDER, RADIUS, redAlpha, goldAlpha, whiteAlpha, blackAlpha } from "@/lib/tokens";

export const discoverPageStyles = {
  page: {
    minHeight: "100dvh",
    background: `radial-gradient(ellipse at 50% -10%, ${redAlpha(0.07)} 0%, transparent 50%), ${BG}`,
    color: "#fff",
    paddingBottom: "calc(88px + env(safe-area-inset-bottom))",
  },

  // ── Search ──
  searchRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "10px 16px",
    position: "sticky",
    top: 56,
    zIndex: 40,
    background: blackAlpha(0.88),
    backdropFilter: "blur(28px)",
    WebkitBackdropFilter: "blur(28px)",
    borderBottom: `1px solid ${BORDER}`,
  },
  searchWrap: {
    flex: 1,
    position: "relative",
    display: "flex",
    alignItems: "center",
  },
  searchIconSvg: {
    position: "absolute",
    left: 12,
    width: 15,
    height: 15,
    fill: "none",
    stroke: whiteAlpha(0.3),
    strokeWidth: 2,
    strokeLinecap: "round",
    pointerEvents: "none",
  },
  searchInput: {
    width: "100%",
    height: 40,
    borderRadius: RADIUS.md,
    border: `1px solid ${whiteAlpha(0.09)}`,
    background: whiteAlpha(0.06),
    color: "#fff",
    padding: "0 34px 0 38px",
    fontSize: 13,
    outline: "none",
    boxSizing: "border-box",
    backdropFilter: "blur(12px)",
    WebkitBackdropFilter: "blur(12px)",
    transition: "border-color 180ms",
  },
  clearBtn: {
    position: "absolute",
    right: 10,
    background: "none",
    border: "none",
    color: whiteAlpha(0.35),
    cursor: "pointer",
    padding: 4,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  searchBtn: {
    height: 40,
    boxSizing: "border-box",
    padding: "0 16px",
    borderRadius: RADIUS.md,
    border: `1px solid ${redAlpha(0.4)}`,
    background: `linear-gradient(135deg, ${RED}, ${RED_DARK})`,
    color: "#fff",
    fontSize: 13,
    fontWeight: 800,
    cursor: "pointer",
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    letterSpacing: 0.5,
    boxShadow: `0 4px 16px ${redAlpha(0.28)}`,
  },

  // ── Main content ──
  content: {
    padding: "12px 0 0",
  },
};
