import { BG, SURFACE_1, RED, RED_DARK, GOLD, BORDER, BORDER_2, RADIUS, MUTED, SUCCESS, redAlpha, goldAlpha, whiteAlpha, blackAlpha } from "@/lib/tokens";

// ── Feed styles (kept as a named subset) ──
const discoverFeedStyles = {
  fighterStudySection: { marginBottom: 20 },
  fighterStudyHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  fighterStudyLabel: {
    fontSize: 9,
    fontWeight: 900,
    color: GOLD,
    letterSpacing: 3.5,
    textTransform: "uppercase",
  },
  fighterStudySeeAll: {
    background: "none",
    border: "none",
    color: MUTED,
    fontSize: 11,
    cursor: "pointer",
    padding: 0,
    fontWeight: 700,
  },
  fighterStudyScroll: {
    display: "flex",
    gap: 10,
    overflowX: "auto",
    paddingBottom: 4,
    scrollbarWidth: "none",
    msOverflowStyle: "none",
    WebkitOverflowScrolling: "touch",
  },
  learnDivider: {
    height: 1,
    background: whiteAlpha(0.05),
    margin: "24px 0",
  },

  // ── Activity pulse strip ──
  activityStrip: {
    display: "flex",
    gap: 8,
    overflowX: "auto",
    padding: "12px 16px 6px",
    scrollbarWidth: "none",
    msOverflowStyle: "none",
    WebkitOverflowScrolling: "touch",
  },
  activityChip: {
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: "6px 12px",
    borderRadius: RADIUS.full,
    border: `1px solid ${BORDER_2}`,
    background: whiteAlpha(0.04),
    color: whiteAlpha(0.6),
    fontSize: 12,
    fontWeight: 700,
    whiteSpace: "nowrap",
    letterSpacing: 0.1,
  },
  activityChipLive: {
    border: `1px solid ${redAlpha(0.35)}`,
    background: redAlpha(0.07),
    color: "#fff",
  },
  activityLiveDot: {
    width: 6,
    height: 6,
    borderRadius: "50%",
    background: SUCCESS,
    boxShadow: `0 0 5px ${SUCCESS}`,
    flexShrink: 0,
  },

  // ── Sparring lobby banner ──
  lobbyBanner: {
    margin: "4px 16px 20px",
    padding: "13px 16px",
    borderRadius: 16,
    border: "1px solid rgba(34,197,94,0.2)",
    background: "linear-gradient(135deg, rgba(34,197,94,0.08) 0%, rgba(34,197,94,0.02) 100%)",
    display: "flex",
    alignItems: "center",
    gap: 12,
    backdropFilter: "blur(16px)",
    WebkitBackdropFilter: "blur(16px)",
    cursor: "pointer",
    WebkitTapHighlightColor: "transparent",
  },
  lobbyGreenDot: {
    width: 10,
    height: 10,
    borderRadius: "50%",
    background: SUCCESS,
    boxShadow: `0 0 8px ${SUCCESS}, 0 0 0 3px rgba(34,197,94,0.18)`,
    flexShrink: 0,
  },
  lobbyText: {
    flex: 1,
    margin: 0,
    fontSize: 13,
    fontWeight: 800,
    color: "#fff",
    lineHeight: 1.35,
  },
  lobbyCountBadge: {
    color: SUCCESS,
    fontWeight: 900,
  },
  lobbyArrow: {
    fontSize: 18,
    color: "rgba(34,197,94,0.55)",
    flexShrink: 0,
    fontWeight: 900,
  },

  // ── Section header (eyebrow + title) ──
  sectionHeader: {
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  sectionKicker: {
    margin: "0 0 3px",
    fontSize: 9,
    fontWeight: 900,
    letterSpacing: "3.5px",
    textTransform: "uppercase",
  },
  sectionTitle: {
    margin: 0,
    fontSize: 20,
    fontWeight: 900,
    color: "#fff",
    letterSpacing: "-0.02em",
    lineHeight: 1.1,
    fontFamily: "var(--font-display, 'Anton', sans-serif)",
  },
  sectionSeeAll: {
    background: "none",
    border: "none",
    color: GOLD,
    fontSize: 12,
    fontWeight: 800,
    cursor: "pointer",
    padding: "4px 0",
    letterSpacing: 0.3,
    WebkitTapHighlightColor: "transparent",
    alignSelf: "flex-end",
    marginBottom: 2,
  },

  // ── Champion strip ──
  championStrip: {
    display: "flex",
    gap: 14,
    overflowX: "auto",
    paddingBottom: 8,
    scrollbarWidth: "none",
    msOverflowStyle: "none",
    WebkitOverflowScrolling: "touch",
  },
  championCard: {
    flexShrink: 0,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 5,
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: 0,
    WebkitTapHighlightColor: "transparent",
  },
  championAvatarWrap: {
    position: "relative",
  },
  championAvatar: {
    width: 58,
    height: 58,
    borderRadius: "50%",
    background: goldAlpha(0.1),
    border: `2px solid ${goldAlpha(0.28)}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    fontSize: 22,
    fontWeight: 900,
    color: "#fff",
    boxShadow: `0 4px 16px ${blackAlpha(0.4)}, 0 0 0 1px ${goldAlpha(0.12)}`,
  },
  championName: {
    fontSize: 11,
    fontWeight: 800,
    color: "#fff",
    maxWidth: 70,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    textAlign: "center",
  },
  championRole: {
    fontSize: 9,
    fontWeight: 700,
    color: GOLD,
    textAlign: "center",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  championOnlineDot: {
    position: "absolute",
    bottom: 1,
    right: 1,
    width: 12,
    height: 12,
    borderRadius: "50%",
    background: SUCCESS,
    border: `2px solid ${BG}`,
    boxShadow: `0 0 5px rgba(34,197,94,0.7)`,
  },

  feedTabs: {
    display: "flex",
    gap: 0,
    padding: "0 16px 0",
    borderBottom: `1px solid ${BORDER}`,
    marginBottom: 2,
  },
  feedTabBtn: {
    flex: 1,
    padding: "12px 0",
    background: "none",
    border: "none",
    borderBottom: "2px solid transparent",
    color: whiteAlpha(0.38),
    fontSize: 13,
    fontWeight: 700,
    cursor: "pointer",
    WebkitTapHighlightColor: "transparent",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    transition: "color 150ms, border-color 150ms",
  },
  feedTabActive: {
    flex: 1,
    padding: "12px 0",
    background: "none",
    border: "none",
    borderBottom: `2px solid ${RED}`,
    color: "#fff",
    fontSize: 13,
    fontWeight: 900,
    cursor: "pointer",
    WebkitTapHighlightColor: "transparent",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
  },

  skeleton: {
    height: 320,
    borderRadius: RADIUS.lg,
    background: whiteAlpha(0.04),
  },
  emptyWrap: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    textAlign: "center",
    padding: "52px 24px",
    gap: 10,
  },
  emptyTitle: { margin: 0, fontSize: 17, fontWeight: 900, color: "#fff", letterSpacing: "-0.01em" },
  emptyText: { margin: 0, fontSize: 13, color: whiteAlpha(0.35), lineHeight: 1.6, maxWidth: 260 },
  emptyBtn: {
    marginTop: 8,
    padding: "11px 22px",
    borderRadius: RADIUS.md,
    border: "none",
    background: `linear-gradient(145deg, ${RED}, ${RED_DARK})`,
    color: "#fff",
    fontSize: 14,
    fontWeight: 800,
    cursor: "pointer",
    boxShadow: `0 8px 24px ${redAlpha(0.32)}, inset 0 1px 0 ${whiteAlpha(0.1)}`,
  },

  card: {
    background: whiteAlpha(0.03),
    border: `1px solid ${BORDER}`,
    borderLeft: `2.5px solid ${RED}`,
    borderRadius: `4px ${RADIUS.lg}px ${RADIUS.lg}px 4px`,
    overflow: "hidden",
    backdropFilter: "blur(16px)",
    WebkitBackdropFilter: "blur(16px)",
  },
  cardHeader: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "13px 14px 10px",
  },
  avatar: {
    width: 38,
    height: 38,
    borderRadius: "50%",
    background: redAlpha(0.15),
    border: `1.5px solid ${redAlpha(0.32)}`,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    flexShrink: 0,
    cursor: "pointer",
  },
  avatarImg: { width: "100%", height: "100%", objectFit: "cover" },
  avatarInitial: { fontSize: 15, fontWeight: 900, color: "#fff" },
  authorName: {
    margin: 0,
    fontSize: 13,
    fontWeight: 900,
    color: "#fff",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    letterSpacing: "-0.01em",
  },
  timeAgo: { margin: 0, fontSize: 11, color: MUTED, fontWeight: 700 },
  typeBadge: { fontSize: 18, lineHeight: 1, flexShrink: 0 },
  thumb: {
    position: "relative",
    width: "100%",
    aspectRatio: "16/9",
    background: SURFACE_1,
    overflow: "hidden",
    cursor: "pointer",
  },
  thumbMedia: { width: "100%", height: "100%", objectFit: "cover", display: "block" },
  thumbGrad: {
    position: "absolute",
    inset: 0,
    background: `linear-gradient(0deg, ${blackAlpha(0.7)} 0%, transparent 55%)`,
    pointerEvents: "none",
  },
  thumbCaption: {
    position: "absolute",
    bottom: 10,
    left: 12,
    right: 12,
    margin: 0,
    fontSize: 12,
    fontWeight: 800,
    color: "#fff",
    textShadow: `0 1px 4px ${blackAlpha(0.9)}`,
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
  },
  cardFooter: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "10px 14px 12px",
  },
  likes: { fontSize: 13, color: whiteAlpha(0.5), fontWeight: 600 },
  watchBtn: {
    padding: "7px 16px",
    borderRadius: RADIUS.sm,
    border: "none",
    background: `linear-gradient(135deg, ${RED}, ${RED_DARK})`,
    color: "#fff",
    fontSize: 12,
    fontWeight: 800,
    cursor: "pointer",
    boxShadow: `0 4px 14px ${redAlpha(0.28)}`,
  },
};

const styles = {
  // ── Page ──
  page: {
    minHeight: "100dvh",
    background: `radial-gradient(ellipse at 50% -10%, ${redAlpha(0.07)} 0%, transparent 50%), ${BG}`,
    color: "#fff",
    paddingBottom: "calc(88px + env(safe-area-inset-bottom))",
  },

  // ── Search ──
  searchRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "10px 16px",
    position: "sticky",
    top: 56,
    zIndex: 40,
    background: blackAlpha(0.88),
    backdropFilter: "blur(28px)",
    WebkitBackdropFilter: "blur(28px)",
    borderBottom: `1px solid ${BORDER}`,
  },
  searchWrap: {
    flex: 1,
    position: "relative",
    display: "flex",
    alignItems: "center",
  },
  searchIconSvg: {
    position: "absolute",
    left: 12,
    width: 15,
    height: 15,
    fill: "none",
    stroke: whiteAlpha(0.3),
    strokeWidth: 2,
    strokeLinecap: "round",
    pointerEvents: "none",
  },
  searchInput: {
    width: "100%",
    height: 40,
    borderRadius: RADIUS.md,
    border: `1px solid ${whiteAlpha(0.09)}`,
    background: whiteAlpha(0.06),
    color: "#fff",
    padding: "0 34px 0 38px",
    fontSize: 13,
    outline: "none",
    boxSizing: "border-box",
    backdropFilter: "blur(12px)",
    WebkitBackdropFilter: "blur(12px)",
    transition: "border-color 180ms",
  },
  clearBtn: {
    position: "absolute",
    right: 10,
    background: "none",
    border: "none",
    color: whiteAlpha(0.35),
    cursor: "pointer",
    padding: 4,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
  },
  searchBtn: {
    height: 40,
    boxSizing: "border-box",
    padding: "0 16px",
    borderRadius: RADIUS.md,
    border: `1px solid ${redAlpha(0.4)}`,
    background: `linear-gradient(135deg, ${RED}, ${RED_DARK})`,
    color: "#fff",
    fontSize: 13,
    fontWeight: 800,
    cursor: "pointer",
    flexShrink: 0,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    letterSpacing: 0.5,
    boxShadow: `0 4px 16px ${redAlpha(0.28)}`,
  },

  // ── Main content ──
  content: {
    padding: "12px 0 0",
  },

  // ── Hub ──
  hubSection: { marginBottom: 40, padding: "0 16px" },
  forYouHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
    paddingTop: 10,
  },
  forYouKicker: {
    margin: "0 0 2px",
    color: RED,
    fontSize: 9,
    fontWeight: 900,
    letterSpacing: 3.5,
    textTransform: "uppercase",
  },
  forYouTitle: {
    fontSize: 18,
    fontWeight: 900,
    color: "#fff",
    letterSpacing: "-0.01em",
    fontFamily: "var(--font-display, 'Anton', sans-serif)",
  },
  seeAllBtn: {
    background: "none",
    border: "none",
    color: GOLD,
    fontSize: 12,
    fontWeight: 800,
    cursor: "pointer",
    padding: "4px 0",
    letterSpacing: 0.3,
  },

  styleChips: {
    display: "flex",
    gap: 6,
    overflowX: "auto",
    paddingBottom: 12,
    scrollbarWidth: "none",
  },
  styleChip: {
    flexShrink: 0,
    padding: "7px 13px",
    borderRadius: RADIUS.full,
    border: `1px solid ${whiteAlpha(0.09)}`,
    background: whiteAlpha(0.04),
    color: whiteAlpha(0.5),
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
    whiteSpace: "nowrap",
    WebkitTapHighlightColor: "transparent",
    display: "flex",
    alignItems: "center",
    gap: 5,
    transition: "border-color 150ms, background 150ms",
  },
  styleChipActive: {
    background: redAlpha(0.18),
    borderColor: redAlpha(0.6),
    color: "#fff",
    fontWeight: 900,
    boxShadow: `0 0 16px ${redAlpha(0.2)}`,
  },

  // ── Hub cards ──
  hubWrap: {
    margin: "0 16px 8px",
    borderRadius: 20,
    border: `1px solid ${BORDER}`,
    background: whiteAlpha(0.025),
    backdropFilter: "blur(16px)",
    WebkitBackdropFilter: "blur(16px)",
    overflow: "hidden",
  },
  hubRow: {
    width: "100%",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    padding: "16px 18px",
    borderRadius: 0,
    border: "none",
    background: "none",
    cursor: "pointer",
    WebkitTapHighlightColor: "transparent",
    boxSizing: "border-box",
    transition: "background 180ms",
  },
  hubLeft: { display: "flex", alignItems: "center", gap: 12 },
  hubEmoji: {
    width: 36,
    height: 36,
    borderRadius: RADIUS.sm,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 18,
    flexShrink: 0,
  },
  hubTitle: {
    fontSize: 15,
    fontWeight: 900,
    color: "#fff",
    letterSpacing: "-0.01em",
  },
  hubChevron: {
    width: 18,
    height: 18,
    fill: "none",
    stroke: whiteAlpha(0.3),
    strokeWidth: 2.2,
    strokeLinecap: "round",
    strokeLinejoin: "round",
    transition: "transform 200ms ease",
    flexShrink: 0,
  },
  hubBody: {
    padding: "4px 16px 18px",
    display: "flex",
    flexDirection: "column",
    gap: 12,
    borderTop: `1px solid ${BORDER}`,
  },

  learnChips: {
    display: "flex",
    gap: 6,
    overflowX: "auto",
    scrollbarWidth: "none",
    paddingBottom: 4,
    paddingTop: 2,
  },
  learnChip: {
    flexShrink: 0,
    padding: "6px 12px",
    borderRadius: RADIUS.full,
    border: `1px solid ${goldAlpha(0.18)}`,
    background: goldAlpha(0.04),
    color: whiteAlpha(0.5),
    fontSize: 12,
    fontWeight: 700,
    cursor: "pointer",
    whiteSpace: "nowrap",
    display: "flex",
    alignItems: "center",
    gap: 4,
    WebkitTapHighlightColor: "transparent",
    transition: "border-color 150ms, background 150ms",
  },
  learnChipActive: {
    background: goldAlpha(0.15),
    borderColor: goldAlpha(0.55),
    color: GOLD,
    fontWeight: 900,
    boxShadow: `0 0 14px ${goldAlpha(0.18)}`,
  },
  hubEmpty: { padding: "20px 0", textAlign: "center" },
  hubEmptyText: { margin: 0, fontSize: 13, color: MUTED },
  hubFooterBtn: {
    background: whiteAlpha(0.04),
    border: `1px solid ${whiteAlpha(0.09)}`,
    borderRadius: RADIUS.md,
    padding: "11px 16px",
    color: GOLD,
    fontSize: 13,
    fontWeight: 800,
    cursor: "pointer",
    width: "100%",
    textAlign: "center",
    transition: "background 150ms",
  },

  challengeGrid: { display: "grid", gridTemplateColumns: "repeat(2, 1fr)", gap: 8 },
  challengeChip: {
    padding: "13px 8px",
    borderRadius: RADIUS.md,
    border: `1px solid ${redAlpha(0.25)}`,
    background: redAlpha(0.07),
    color: whiteAlpha(0.75),
    fontSize: 13,
    fontWeight: 800,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    gap: 6,
    WebkitTapHighlightColor: "transparent",
    transition: "background 150ms",
  },

  exploreSection: { padding: "28px 16px 12px" },
  exploreSectionLabel: {
    margin: "0 0 10px",
    fontSize: 9,
    fontWeight: 900,
    letterSpacing: 3.5,
    textTransform: "uppercase",
    color: whiteAlpha(0.35),
  },
  explorePills: { display: "flex", gap: 8, flexWrap: "wrap" },
  explorePill: {
    padding: "10px 16px",
    borderRadius: RADIUS.full,
    border: `1px solid ${whiteAlpha(0.09)}`,
    background: whiteAlpha(0.04),
    color: whiteAlpha(0.65),
    fontSize: 13,
    fontWeight: 700,
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: 6,
    WebkitTapHighlightColor: "transparent",
    transition: "background 150ms",
  },

  // ── Reel scroll ──
  reelScroll: {
    display: "flex",
    gap: 10,
    overflowX: "auto",
    paddingBottom: 6,
    scrollbarWidth: "none",
    WebkitOverflowScrolling: "touch",
  },

  // ── Portrait reel card ──
  reelCard: {
    flexShrink: 0,
    width: 122,
    height: 210,
    borderRadius: 16,
    overflow: "hidden",
    cursor: "pointer",
    background: "none",
    border: `1px solid ${BORDER_2}`,
    padding: 0,
    display: "block",
    position: "relative",
    WebkitTapHighlightColor: "transparent",
    boxShadow: `0 8px 28px ${blackAlpha(0.55)}`,
    transition: "transform 180ms ease, box-shadow 180ms ease",
  },
  reelThumbWrap: {
    width: "100%",
    height: "100%",
    position: "relative",
    background: `linear-gradient(160deg, #1a0808 0%, ${SURFACE_1} 100%)`,
    borderRadius: 16,
    overflow: "hidden",
  },
  reelThumbImg: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
    display: "block",
    borderRadius: 16,
  },
  reelThumbFallback: {
    width: "100%",
    height: "100%",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
    padding: "8px 8px 24px",
    boxSizing: "border-box",
  },
  reelFallbackCaption: {
    margin: 0,
    fontSize: 9,
    color: whiteAlpha(0.55),
    lineHeight: 1.3,
    textAlign: "center",
    display: "-webkit-box",
    WebkitLineClamp: 3,
    WebkitBoxOrient: "vertical",
    overflow: "hidden",
  },
  reelGradTop: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 70,
    background: `linear-gradient(180deg, ${blackAlpha(0.6)} 0%, transparent 100%)`,
    pointerEvents: "none",
  },
  reelGradBottom: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 100,
    background: `linear-gradient(0deg, ${blackAlpha(0.9)} 0%, ${blackAlpha(0.45)} 55%, transparent 100%)`,
    pointerEvents: "none",
  },
  reelTypeBadge: {
    position: "absolute",
    top: 8,
    left: 9,
    fontSize: 13,
    lineHeight: 1,
    filter: `drop-shadow(0 1px 3px ${blackAlpha(0.9)})`,
    zIndex: 2,
  },
  reelViews: {
    position: "absolute",
    top: 9,
    right: 9,
    fontSize: 9,
    fontWeight: 900,
    color: whiteAlpha(0.75),
    letterSpacing: 0.3,
    zIndex: 2,
    textShadow: `0 1px 4px ${blackAlpha(0.8)}`,
  },
  reelCaptionOverlay: {
    position: "absolute",
    bottom: 9,
    left: 9,
    right: 9,
    margin: 0,
    fontSize: 10,
    fontWeight: 800,
    color: "#fff",
    lineHeight: 1.3,
    letterSpacing: 0.1,
    textShadow: `0 1px 6px ${blackAlpha(0.95)}`,
    overflow: "hidden",
    display: "-webkit-box",
    WebkitLineClamp: 2,
    WebkitBoxOrient: "vertical",
    zIndex: 2,
  },
  shimmerCard: {
    flexShrink: 0,
    width: 122,
    height: 210,
    borderRadius: 16,
  },

  // ── Top coaches ──
  coachStrip: {
    padding: "20px 16px 8px",
  },
  coachStripHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  coachStripLabel: {
    fontSize: 14,
    fontWeight: 900,
    color: "#fff",
  },
  coachScroll: {
    display: "flex",
    gap: 14,
    overflowX: "auto",
    scrollbarWidth: "none",
    paddingBottom: 4,
  },
  coachCard: {
    flexShrink: 0,
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    gap: 5,
    background: "none",
    border: "none",
    cursor: "pointer",
    padding: 0,
    WebkitTapHighlightColor: "transparent",
    width: 64,
  },
  coachAvatar: {
    width: 52,
    height: 52,
    borderRadius: "50%",
    background: "rgba(96,165,250,0.12)",
    border: "2px solid rgba(96,165,250,0.28)",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    overflow: "hidden",
    fontSize: 18,
    fontWeight: 800,
    color: "#fff",
    boxShadow: `0 4px 16px ${blackAlpha(0.4)}`,
  },
  coachAvatarImg: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  coachName: {
    fontSize: 11,
    fontWeight: 800,
    color: "#fff",
    maxWidth: 64,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    textAlign: "center",
  },
  coachSpec: {
    fontSize: 9,
    fontWeight: 700,
    color: "#60A5FA",
    textAlign: "center",
    maxWidth: 64,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },

  // ── Search results ──
  sectionLabel: {
    margin: "0 0 10px",
    fontSize: 10,
    fontWeight: 900,
    letterSpacing: 2,
    textTransform: "uppercase",
    color: whiteAlpha(0.4),
  },
  listStack: {
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  listCard: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "11px 14px",
    borderRadius: RADIUS.md,
    border: `1px solid ${BORDER}`,
    background: whiteAlpha(0.035),
    cursor: "pointer",
    color: "#fff",
    textAlign: "left",
    width: "100%",
    boxSizing: "border-box",
    WebkitTapHighlightColor: "transparent",
    backdropFilter: "blur(12px)",
    WebkitBackdropFilter: "blur(12px)",
    transition: "background 150ms",
  },
  listAvatar: {
    width: 40,
    height: 40,
    borderRadius: "50%",
    background: whiteAlpha(0.08),
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 16,
    fontWeight: 800,
    flexShrink: 0,
    overflow: "hidden",
    border: `1px solid ${whiteAlpha(0.1)}`,
  },
  listAvatarImg: {
    width: "100%",
    height: "100%",
    objectFit: "cover",
  },
  listCardText: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
    gap: 2,
    minWidth: 0,
  },
  listCardName: {
    fontSize: 14,
    fontWeight: 800,
    color: "#fff",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  listCardSub: {
    fontSize: 12,
    color: whiteAlpha(0.4),
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  listArrow: {
    color: whiteAlpha(0.25),
    fontSize: 18,
    flexShrink: 0,
  },
  emptyState: {
    textAlign: "center",
    padding: "48px 20px",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },

  // ── Feed ──
  ...discoverFeedStyles,
};

export default styles;
export const s = styles;
export const feed = discoverFeedStyles;
